// 이 게임에만 나오는 문구. 도구 이름과 게임 이름은 shared/strings.js에 있다.
//
// **알파라 한국어만 있다**(저장소 규칙). 다른 언어에서는 엔진이 한국어로 내린다.
// 이름 목록은 가나다순이어야 한다 — 판은 번호 순서대로 앉히므로 목록 순서가 곧 판 위의 순서다.
// 단서 문장에서 이름 뒤에 조사를 붙이지 않는다(`의`·`보다`만 쓴다). 이름마다 받침이 달라
// 은/는, 이/가가 갈린다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '단서를 따라 스무 명 가운데 범인을 가려내는 추리 퍼즐',
      'wd.name.0': '가람',
      'wd.name.1': '건우',
      'wd.name.2': '고은',
      'wd.name.3': '나연',
      'wd.name.4': '노아',
      'wd.name.5': '다은',
      'wd.name.6': '도윤',
      'wd.name.7': '라온',
      'wd.name.8': '루다',
      'wd.name.9': '마루',
      'wd.name.10': '민서',
      'wd.name.11': '바다',
      'wd.name.12': '보람',
      'wd.name.13': '서준',
      'wd.name.14': '소율',
      'wd.name.15': '아린',
      'wd.name.16': '예준',
      'wd.name.17': '유나',
      'wd.name.18': '재희',
      'wd.name.19': '주원',
      'wd.name.20': '지호',
      'wd.name.21': '채원',
      'wd.name.22': '태오',
      'wd.name.23': '하늘',
      'wd.name.24': '하준',
      'wd.name.25': '해솔',
      'wd.name.26': '현우',
      'wd.name.27': '혜린',
      'wd.name.28': '호야',
      'wd.name.29': '희수',
      'wd.job.0': '요리사',
      'wd.job.1': '경비원',
      'wd.job.2': '화가',
      'wd.job.3': '의사',
      'wd.job.4': '농부',
      'wd.job.5': '교사',
      'wd.job.6': '상인',
      'wd.job.7': '기자',
      'wd.side.c': '범인',
      'wd.side.i': '무고한 사람',
      'wd.crim': '범인',
      'wd.inno': '무고',
      'wd.place.N': '{name}의 이웃',
      'wd.place.R': '{n}행',
      'wd.place.C': '{n}열',
      'wd.place.A': '{name}보다 위',
      'wd.place.B': '{name}보다 아래',
      'wd.place.L': '{name}의 왼쪽',
      'wd.place.G': '{name}의 오른쪽',
      'wd.place.J': '{job}',
      'wd.place.E': '가장자리',
      'wd.place.K': '네 모서리',
      'wd.clue.count': '{place} 중 {side}은 {n}명이다.',
      'wd.clue.none': '{place} 중 {side}은 없다.',
      'wd.clue.more': '{a}에 {b}보다 {side}이 많다.',
      'wd.clue.same': '{a}과 {b}의 {side} 수가 같다.',
      'wd.clue.odd': '{place}의 {side} 수는 홀수다.',
      'wd.clue.even': '{place}의 {side} 수는 짝수다.',
      'wd.clue.linked': '{place}의 {side}은 모두 이어져 있다.',
      'wd.mistakes': '실수 {n}',
      'wd.ask': '무고일까요, 범인일까요?',
      'wd.pick': '사람을 고르세요.',
      'wd.open': '아직 근거가 부족합니다.',
      'wd.wrong': '틀렸습니다. 단서를 다시 보세요.',
      'wd.noStep': '지금은 더 정할 수 있는 사람이 없습니다.',
      'wd.why.clue': '{from}의 단서로 정해집니다: {who} — {status}',
      'wd.why.trial': '{who}: {assume} 하면 단서끼리 어긋나므로 {status}입니다.',
      'wd.crimIf': '범인이라고',
      'wd.innoIf': '무고라고',
      'wd.why.deep': '단서를 여럿 함께 따지면 정해집니다: {who} — {status}',
      'wd.resultMistakes': '실수 {n}번',
      'wd.rule1': '스무 명은 모두 <b>무고하거나 범인</b>입니다. 정체를 밝히면 그 사람이 <b>단서</b>를 하나 말하고, 단서는 모두 참입니다.',
      'wd.rule2': '사람을 고르고 <b>무고</b>나 <b>범인</b>을 누릅니다. <b>단서로 정해지는 사람만</b> 밝힐 수 있습니다 — 아직 정해지지 않았으면 근거가 부족하다고 하고, 정해졌는데 틀리게 고르면 실수로 셉니다.',
      'wd.rule3': '<b>이웃</b>은 대각선까지 둘레의 여덟 칸입니다. <b>위·아래·왼쪽·오른쪽</b>은 같은 열이나 행에서 그쪽 끝까지입니다. <b>이어져 있다</b>는 그 줄에서 사이에 다른 사람 없이 붙어 있다는 뜻입니다.',
      'wd.rule4': '밝혀진 사람을 누르면 그 단서가 가리키는 사람들이 표시됩니다.',
      'wd.rule5': '<b>모든 판은 찍지 않고 끝까지 풀립니다.</b> 어려움에는 "이 사람이 범인이라면?"을 따져 봐야 하는 자리가 있습니다.',
      'wd.rule6': '<b>힌트</b>는 지금 단서로 정할 수 있는 사람 하나를 까닭과 함께 밝혀 줍니다.'
    }
  });
})();
