// 이 게임에만 나오는 문구. 도구 이름과 게임 이름은 shared/strings.js에 있다.
//
// 이름 목록은 언어마다 그 언어의 사전 순이어야 한다 — 판은 번호 순서대로 앉히므로 목록 순서가
// 곧 판 위의 순서이고, 단서에 나온 이름을 판에서 찾을 때 그 순서를 따라간다.
// 한국어 단서 문장에서 이름 뒤에 조사를 붙이지 않는다(`의`·`보다`만 쓴다). 이름마다 받침이 달라
// 은/는, 이/가가 갈린다. 영어·스페인어는 자리 말(`wd.place.*`)이 전치사까지 들고 있어 문장 틀이
// "There are … {place}" 하나로 모든 자리를 받는다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '단서를 따라 스무 명 가운데 범인을 가려내는 추리 퍼즐',
      'wd.name.0': '가람',
      'wd.name.1': '건우',
      'wd.name.2': '고은',
      'wd.name.3': '나연',
      'wd.name.4': '노아',
      'wd.name.5': '다은',
      'wd.name.6': '도윤',
      'wd.name.7': '라온',
      'wd.name.8': '루다',
      'wd.name.9': '마루',
      'wd.name.10': '민서',
      'wd.name.11': '바다',
      'wd.name.12': '보람',
      'wd.name.13': '서준',
      'wd.name.14': '소율',
      'wd.name.15': '아린',
      'wd.name.16': '예준',
      'wd.name.17': '유나',
      'wd.name.18': '재희',
      'wd.name.19': '주원',
      'wd.name.20': '지호',
      'wd.name.21': '채원',
      'wd.name.22': '태오',
      'wd.name.23': '하늘',
      'wd.name.24': '하준',
      'wd.name.25': '해솔',
      'wd.name.26': '현우',
      'wd.name.27': '혜린',
      'wd.name.28': '호야',
      'wd.name.29': '희수',
      'wd.job.0': '요리사',
      'wd.job.1': '경비원',
      'wd.job.2': '화가',
      'wd.job.3': '의사',
      'wd.job.4': '농부',
      'wd.job.5': '교사',
      'wd.job.6': '상인',
      'wd.job.7': '기자',
      'wd.jobs.0': '요리사',
      'wd.jobs.1': '경비원',
      'wd.jobs.2': '화가',
      'wd.jobs.3': '의사',
      'wd.jobs.4': '농부',
      'wd.jobs.5': '교사',
      'wd.jobs.6': '상인',
      'wd.jobs.7': '기자',
      'wd.side.c': '범인',
      'wd.side1.c': '범인',
      'wd.side1.i': '무고한 사람',
      'wd.side.i': '무고한 사람',
      'wd.crim': '범인',
      'wd.inno': '무고',
      'wd.place.N': '{name}의 이웃',
      'wd.place.R': '{n}행',
      'wd.place.C': '{n}열',
      'wd.place.A': '{name}보다 위',
      'wd.place.B': '{name}보다 아래',
      'wd.place.L': '{name}의 왼쪽',
      'wd.place.G': '{name}의 오른쪽',
      'wd.place.J': '{job}',
      'wd.place.E': '가장자리',
      'wd.place.K': '네 모서리',
      'wd.place.withJob': '{place}에 있는 {job}',
      'wd.clue.count': '{place} 중 {side}은 {n}명이다.',
      'wd.clue.count1': '{place} 중 {side1}은 1명이다.',
      'wd.clue.none': '{place} 중 {side}은 없다.',
      'wd.clue.more': '{a}에 {b}보다 {side}이 많다.',
      'wd.clue.same': '{a}과 {b}의 {side} 수가 같다.',
      'wd.clue.odd': '{place}의 {side} 수는 홀수다.',
      'wd.clue.even': '{place}의 {side} 수는 짝수다.',
      'wd.clue.linked': '{place}의 {side}은 모두 이어져 있다.',
      'wd.clue.outnumber': '{place} 중에는 {side}이 {other}보다 많다.',
      'wd.mistakes': '실수 {n}',
      'wd.ask': '무고일까요, 범인일까요?',
      'wd.pick': '사람을 고르세요.',
      'wd.open': '아직 근거가 부족합니다.',
      'wd.wrong': '틀렸습니다. 단서를 다시 보세요.',
      'wd.noStep': '지금은 더 정할 수 있는 사람이 없습니다.',
      'wd.why.clue': '{from}의 단서로 정해집니다: {who} — {status}',
      'wd.why.trial': '{who}: {assume} 하면 단서끼리 어긋나므로 {status}입니다.',
      'wd.crimIf': '범인이라고',
      'wd.innoIf': '무고라고',
      'wd.why.deep': '단서를 여럿 함께 따지면 정해집니다: {who} — {status}',
      'wd.resultMistakes': '실수 {n}번',
      'wd.used': '다 씀',
      'wd.tag0': '분홍 표시',
      'wd.tag1': '노란 표시',
      'wd.tag2': '파란 표시',
      'wd.tag3': '보라 표시',
      'wd.look.clue': '{from}의 단서를 보세요. 힌트를 한 번 더 누르면 밝혀 줍니다.',
      'wd.look.trial': '{who}: {assume} 해 보세요. 단서끼리 어긋나는 데가 있습니다.',
      'wd.look.deep': '{who}: 단서를 여럿 함께 따져 보세요.',
      'wd.share': '결과 복사',
      'wd.shareHead': '{game} {level} {time}',
      'wd.copied': '결과를 복사했습니다.',
      'wd.rule1': '스무 명은 모두 <b>무고하거나 범인</b>입니다. 정체를 밝히면 그 사람이 <b>단서</b>를 하나 말하고, 단서는 모두 참입니다.',
      'wd.rule2': '사람을 고르고 <b>무고</b>나 <b>범인</b>을 누릅니다. <b>단서로 정해지는 사람만</b> 밝힐 수 있습니다 — 아직 정해지지 않았으면 근거가 부족하다고 하고, 정해졌는데 틀리게 고르면 실수로 셉니다.',
      'wd.rule3': '<b>이웃</b>은 대각선까지 둘레의 여덟 칸입니다. <b>위·아래·왼쪽·오른쪽</b>은 같은 열이나 행에서 그쪽 끝까지입니다. <b>이어져 있다</b>는 그 줄에서 사이에 다른 사람 없이 붙어 있다는 뜻입니다.',
      'wd.rule4': '밝혀진 사람을 누르면 그 단서가 가리키는 사람들이 표시됩니다. 다 쓴 단서는 <b>다 씀</b>으로 흐려 둘 수 있고, 아직 모르는 사람에게는 <b>색 표시</b>를 네 가지까지 달아 메모할 수 있습니다.',
      'wd.rule5': '<b>모든 판은 찍지 않고 끝까지 풀립니다.</b> 어려움에는 "이 사람이 범인이라면?"을 따져 봐야 하는 자리가 있습니다.',
      'wd.rule6': '<b>힌트</b>는 처음에 봐야 할 단서나 사람만 짚어 주고, 한 번 더 누르면 그 사람을 까닭과 함께 밝혀 줍니다. 결과 격자에서 짚어 준 사람은 🟡, 밝혀 준 사람은 🟠, 틀린 적 있는 사람은 🟨로 남습니다.'
    },
    en: {
      'meta.desc': 'Unmask the criminals among twenty suspects by following the clues',
      'wd.name.0': 'Ada',
      'wd.name.1': 'Amy',
      'wd.name.2': 'Ben',
      'wd.name.3': 'Cara',
      'wd.name.4': 'Cole',
      'wd.name.5': 'Dan',
      'wd.name.6': 'Eli',
      'wd.name.7': 'Faye',
      'wd.name.8': 'Gus',
      'wd.name.9': 'Hana',
      'wd.name.10': 'Ivan',
      'wd.name.11': 'Jade',
      'wd.name.12': 'Kai',
      'wd.name.13': 'Lena',
      'wd.name.14': 'Max',
      'wd.name.15': 'Mia',
      'wd.name.16': 'Nina',
      'wd.name.17': 'Omar',
      'wd.name.18': 'Pia',
      'wd.name.19': 'Quinn',
      'wd.name.20': 'Rosa',
      'wd.name.21': 'Sam',
      'wd.name.22': 'Tara',
      'wd.name.23': 'Theo',
      'wd.name.24': 'Uma',
      'wd.name.25': 'Vic',
      'wd.name.26': 'Wade',
      'wd.name.27': 'Xavi',
      'wd.name.28': 'Yara',
      'wd.name.29': 'Zane',
      'wd.job.0': 'Cook',
      'wd.job.1': 'Guard',
      'wd.job.2': 'Painter',
      'wd.job.3': 'Doctor',
      'wd.job.4': 'Farmer',
      'wd.job.5': 'Teacher',
      'wd.job.6': 'Merchant',
      'wd.job.7': 'Reporter',
      'wd.jobs.0': 'cooks',
      'wd.jobs.1': 'guards',
      'wd.jobs.2': 'painters',
      'wd.jobs.3': 'doctors',
      'wd.jobs.4': 'farmers',
      'wd.jobs.5': 'teachers',
      'wd.jobs.6': 'merchants',
      'wd.jobs.7': 'reporters',
      'wd.side.c': 'criminals',
      'wd.side.i': 'innocents',
      'wd.side1.c': 'criminal',
      'wd.side1.i': 'innocent',
      'wd.crim': 'Criminal',
      'wd.inno': 'Innocent',
      'wd.place.N': 'among {name}\'s neighbors',
      'wd.place.R': 'in row {n}',
      'wd.place.C': 'in column {n}',
      'wd.place.A': 'above {name}',
      'wd.place.B': 'below {name}',
      'wd.place.L': 'to the left of {name}',
      'wd.place.G': 'to the right of {name}',
      'wd.place.J': 'among the {jobs}',
      'wd.place.E': 'on the edges',
      'wd.place.K': 'in the corners',
      'wd.place.withJob': '{place} who are {jobs}',
      'wd.clue.count': 'There are exactly {n} {side} {place}.',
      'wd.clue.count1': 'There is exactly one {side1} {place}.',
      'wd.clue.none': 'There are no {side} {place}.',
      'wd.clue.more': 'There are more {side} {a} than {b}.',
      'wd.clue.same': 'There are as many {side} {a} as {b}.',
      'wd.clue.odd': 'There is an odd number of {side} {place}.',
      'wd.clue.even': 'There is an even number of {side} {place}.',
      'wd.clue.linked': 'All {side} {place} are connected.',
      'wd.clue.outnumber': 'There are more {side} than {other} {place}.',
      'wd.mistakes': 'Mistakes {n}',
      'wd.ask': 'Innocent or criminal?',
      'wd.pick': 'Pick a person.',
      'wd.open': 'Not enough evidence yet.',
      'wd.wrong': 'Wrong. Check the clues again.',
      'wd.noStep': 'Nothing else can be settled right now.',
      'wd.why.clue': '{from}\'s clue settles it: {who} — {status}',
      'wd.why.trial': '{who}: {assume}, the clues contradict each other — {status}.',
      'wd.crimIf': 'if criminal',
      'wd.innoIf': 'if innocent',
      'wd.why.deep': 'Weighing several clues together settles it: {who} — {status}',
      'wd.resultMistakes': '{n} mistakes',
      'wd.used': 'Used',
      'wd.tag0': 'Pink mark',
      'wd.tag1': 'Yellow mark',
      'wd.tag2': 'Blue mark',
      'wd.tag3': 'Purple mark',
      'wd.look.clue': 'Look at {from}\'s clue. Press hint again to reveal.',
      'wd.look.trial': 'Try assuming {who} is {assumeWord}. Some clues will clash.',
      'wd.look.deep': '{who}: weigh several clues together.',
      'wd.share': 'Copy result',
      'wd.shareHead': '{game} {level} {time}',
      'wd.copied': 'Result copied.',
      'wd.rule1': 'All twenty are <b>either innocent or a criminal</b>. When someone’s identity is revealed, they give a <b>clue</b> — and every clue is true.',
      'wd.rule2': 'Pick a person and press <b>Innocent</b> or <b>Criminal</b>. <b>You can only reveal people the clues have settled</b> — if they could still be either, you’re told there’s not enough evidence; if you pick wrong on a settled person, it counts as a mistake.',
      'wd.rule3': '<b>Neighbors</b> are the eight surrounding cells, diagonals included. <b>Above, below, left and right</b> run to the end of the same column or row. <b>Connected</b> means side by side in that line with no one else in between.',
      'wd.rule4': 'Tap a revealed person to highlight everyone their clue refers to. Mark a finished clue as <b>Used</b> to dim it, and add up to four <b>color marks</b> to people you haven’t solved yet.',
      'wd.rule5': '<b>Every board can be solved without guessing.</b> Hard boards have spots where you need to ask “what if this person were a criminal?”.',
      'wd.rule6': 'The <b>hint</b> first points to the clue or person to look at; press it again to reveal that person with the reason. In the result grid, people pointed out show 🟡, people revealed show 🟠, and people you got wrong show 🟨.'
    },
    ja: {
      'meta.desc': '手がかりをたどって二十人の中から犯人を見抜く推理パズル',
      'wd.name.0': 'あおい',
      'wd.name.1': 'あかり',
      'wd.name.2': 'いつき',
      'wd.name.3': 'えま',
      'wd.name.4': 'かいと',
      'wd.name.5': 'かえで',
      'wd.name.6': 'けんた',
      'wd.name.7': 'こはる',
      'wd.name.8': 'さくら',
      'wd.name.9': 'しおん',
      'wd.name.10': 'すず',
      'wd.name.11': 'そうた',
      'wd.name.12': 'たける',
      'wd.name.13': 'ちひろ',
      'wd.name.14': 'つばさ',
      'wd.name.15': 'なお',
      'wd.name.16': 'はると',
      'wd.name.17': 'ひかり',
      'wd.name.18': 'ふうか',
      'wd.name.19': 'ほのか',
      'wd.name.20': 'まこと',
      'wd.name.21': 'みお',
      'wd.name.22': 'めい',
      'wd.name.23': 'ゆい',
      'wd.name.24': 'ゆうと',
      'wd.name.25': 'よう',
      'wd.name.26': 'りく',
      'wd.name.27': 'りん',
      'wd.name.28': 'れん',
      'wd.name.29': 'わかな',
      'wd.job.0': '料理人',
      'wd.job.1': '警備員',
      'wd.job.2': '画家',
      'wd.job.3': '医者',
      'wd.job.4': '農家',
      'wd.job.5': '教師',
      'wd.job.6': '商人',
      'wd.job.7': '記者',
      'wd.jobs.0': '料理人',
      'wd.jobs.1': '警備員',
      'wd.jobs.2': '画家',
      'wd.jobs.3': '医者',
      'wd.jobs.4': '農家',
      'wd.jobs.5': '教師',
      'wd.jobs.6': '商人',
      'wd.jobs.7': '記者',
      'wd.side.c': '犯人',
      'wd.side.i': '無実の人',
      'wd.side1.c': '犯人',
      'wd.side1.i': '無実の人',
      'wd.crim': '犯人',
      'wd.inno': '無実',
      'wd.place.N': '{name}の隣',
      'wd.place.R': '{n}行目',
      'wd.place.C': '{n}列',
      'wd.place.A': '{name}より上',
      'wd.place.B': '{name}より下',
      'wd.place.L': '{name}の左',
      'wd.place.G': '{name}の右',
      'wd.place.J': '{job}',
      'wd.place.E': '外周',
      'wd.place.K': '四隅',
      'wd.place.withJob': '{place}にいる{job}',
      'wd.clue.count': '{place}のうち{side}はちょうど{n}人。',
      'wd.clue.count1': '{place}のうち{side1}はちょうど1人。',
      'wd.clue.none': '{place}のうち{side}はいない。',
      'wd.clue.more': '{a}は{b}より{side}が多い。',
      'wd.clue.same': '{a}と{b}の{side}の数は同じ。',
      'wd.clue.odd': '{place}のうち{side}の数は奇数。',
      'wd.clue.even': '{place}のうち{side}の数は偶数。',
      'wd.clue.linked': '{place}の{side}はすべてつながっている。',
      'wd.clue.outnumber': '{place}では{side}が{other}より多い。',
      'wd.mistakes': 'ミス {n}',
      'wd.ask': '無実？それとも犯人？',
      'wd.pick': '人を選んでください。',
      'wd.open': 'まだ根拠が足りません。',
      'wd.wrong': '違います。手がかりを見直してください。',
      'wd.noStep': 'いまはこれ以上決められる人がいません。',
      'wd.why.clue': '{from}の手がかりで決まります：{who} — {status}',
      'wd.why.trial': '{who}：{assume}すると手がかり同士が矛盾するので{status}です。',
      'wd.crimIf': '犯人だと',
      'wd.innoIf': '無実だと',
      'wd.why.deep': '手がかりをいくつか合わせると決まります：{who} — {status}',
      'wd.resultMistakes': 'ミス{n}回',
      'wd.used': '使用済み',
      'wd.tag0': 'ピンクの印',
      'wd.tag1': '黄色の印',
      'wd.tag2': '青の印',
      'wd.tag3': '紫の印',
      'wd.look.clue': '{from}の手がかりを見てください。もう一度ヒントを押すと明かします。',
      'wd.look.trial': '{who}が{assumeWord}だと仮定してみてください。矛盾する手がかりがあります。',
      'wd.look.deep': '{who}：いくつかの手がかりを合わせて考えてください。',
      'wd.share': '結果をコピー',
      'wd.shareHead': '{game} {level} {time}',
      'wd.copied': '結果をコピーしました。',
      'wd.rule1': '二十人は全員<b>無実か犯人</b>です。正体を明かすとその人が<b>手がかり</b>をひとつ話し、手がかりはすべて正しいです。',
      'wd.rule2': '人を選んで<b>無実</b>か<b>犯人</b>を押します。<b>手がかりで決まる人だけ</b>明かせます — まだどちらもありうるときは根拠が足りないと言われ、決まっているのに逆を選ぶとミスになります。',
      'wd.rule3': '<b>隣</b>は斜めを含む周りの八マスです。<b>上・下・左・右</b>は同じ列や行のその端までです。<b>つながっている</b>はその列で間に他の人をはさまず並んでいることです。',
      'wd.rule4': '明かした人を押すと、その手がかりが指す人が示されます。使い終えた手がかりは<b>使用済み</b>で薄くでき、まだわからない人には<b>色の印</b>を四つまで付けてメモできます。',
      'wd.rule5': '<b>どの盤も当てずっぽうなしで最後まで解けます。</b>難しいでは「この人が犯人なら？」と考える必要がある場所があります。',
      'wd.rule6': '<b>ヒント</b>は最初に見るべき手がかりか人だけを示し、もう一度押すとその人を理由と一緒に明かします。結果の格子では示された人が🟡、明かされた人が🟠、間違えた人が🟨になります。'
    },
    'zh-CN': {
      'meta.desc': '根据线索从二十人中找出罪犯的推理谜题',
      'wd.name.0': '安然',
      'wd.name.1': '柏林',
      'wd.name.2': '晨阳',
      'wd.name.3': '丹青',
      'wd.name.4': '东升',
      'wd.name.5': '芳芳',
      'wd.name.6': '光明',
      'wd.name.7': '海涛',
      'wd.name.8': '浩然',
      'wd.name.9': '佳琪',
      'wd.name.10': '嘉欣',
      'wd.name.11': '建华',
      'wd.name.12': '可欣',
      'wd.name.13': '乐乐',
      'wd.name.14': '丽娜',
      'wd.name.15': '美玲',
      'wd.name.16': '明轩',
      'wd.name.17': '宁宁',
      'wd.name.18': '平安',
      'wd.name.19': '琪琪',
      'wd.name.20': '晴雯',
      'wd.name.21': '若曦',
      'wd.name.22': '思远',
      'wd.name.23': '天宇',
      'wd.name.24': '婉清',
      'wd.name.25': '文杰',
      'wd.name.26': '小雨',
      'wd.name.27': '欣怡',
      'wd.name.28': '雅婷',
      'wd.name.29': '子轩',
      'wd.job.0': '厨师',
      'wd.job.1': '保安',
      'wd.job.2': '画家',
      'wd.job.3': '医生',
      'wd.job.4': '农民',
      'wd.job.5': '教师',
      'wd.job.6': '商人',
      'wd.job.7': '记者',
      'wd.jobs.0': '厨师',
      'wd.jobs.1': '保安',
      'wd.jobs.2': '画家',
      'wd.jobs.3': '医生',
      'wd.jobs.4': '农民',
      'wd.jobs.5': '教师',
      'wd.jobs.6': '商人',
      'wd.jobs.7': '记者',
      'wd.side.c': '罪犯',
      'wd.side.i': '无辜者',
      'wd.side1.c': '罪犯',
      'wd.side1.i': '无辜者',
      'wd.crim': '罪犯',
      'wd.inno': '无辜',
      'wd.place.N': '{name}的邻居',
      'wd.place.R': '第{n}行',
      'wd.place.C': '{n}列',
      'wd.place.A': '{name}上方',
      'wd.place.B': '{name}下方',
      'wd.place.L': '{name}左边',
      'wd.place.G': '{name}右边',
      'wd.place.J': '{job}',
      'wd.place.E': '边缘',
      'wd.place.K': '四个角',
      'wd.place.withJob': '{place}的{job}',
      'wd.clue.count': '{place}中恰好有{n}名{side}。',
      'wd.clue.count1': '{place}中恰好有1名{side1}。',
      'wd.clue.none': '{place}中没有{side}。',
      'wd.clue.more': '{a}的{side}比{b}多。',
      'wd.clue.same': '{a}和{b}的{side}一样多。',
      'wd.clue.odd': '{place}中{side}的人数是奇数。',
      'wd.clue.even': '{place}中{side}的人数是偶数。',
      'wd.clue.linked': '{place}中的{side}都连在一起。',
      'wd.clue.outnumber': '{place}中{side}比{other}多。',
      'wd.mistakes': '失误 {n}',
      'wd.ask': '无辜还是罪犯？',
      'wd.pick': '请选择一个人。',
      'wd.open': '证据还不够。',
      'wd.wrong': '错了，请再看看线索。',
      'wd.noStep': '现在没有能确定的人了。',
      'wd.why.clue': '{from}的线索可以确定：{who} — {status}',
      'wd.why.trial': '{who}：如果是{assume}，线索之间会矛盾，所以是{status}。',
      'wd.crimIf': '罪犯',
      'wd.innoIf': '无辜',
      'wd.why.deep': '把几条线索合起来看可以确定：{who} — {status}',
      'wd.resultMistakes': '失误{n}次',
      'wd.used': '已用',
      'wd.tag0': '粉色标记',
      'wd.tag1': '黄色标记',
      'wd.tag2': '蓝色标记',
      'wd.tag3': '紫色标记',
      'wd.look.clue': '看看{from}的线索。再按一次提示就会揭晓。',
      'wd.look.trial': '试着假设{who}是{assumeWord}，有线索会互相矛盾。',
      'wd.look.deep': '{who}：把几条线索合起来想想。',
      'wd.share': '复制结果',
      'wd.shareHead': '{game} {level} {time}',
      'wd.copied': '已复制结果。',
      'wd.rule1': '二十人全部<b>不是无辜就是罪犯</b>。揭晓身份后，这个人会说出一条<b>线索</b>，线索全部为真。',
      'wd.rule2': '选一个人，按<b>无辜</b>或<b>罪犯</b>。<b>只能揭晓线索已经确定的人</b>——如果还两种都有可能，会提示证据不够；已经确定却选反了，算一次失误。',
      'wd.rule3': '<b>邻居</b>是包括斜角在内的周围八格。<b>上方、下方、左边、右边</b>是同一列或同一行直到尽头。<b>连在一起</b>是指在那一行（列）中中间没有隔着别人。',
      'wd.rule4': '点已揭晓的人，会标出这条线索涉及的人。用完的线索可以按<b>已用</b>变淡，还不知道的人可以加最多四种<b>颜色标记</b>做笔记。',
      'wd.rule5': '<b>每个棋盘都不用猜就能解到最后。</b>困难难度中有需要想“如果这个人是罪犯会怎样？”的地方。',
      'wd.rule6': '<b>提示</b>先指出要看的线索或人；再按一次，会连同理由一起揭晓那个人。结果格子里被指出的人是🟡，被揭晓的人是🟠，选错过的人是🟨。'
    },
    'zh-TW': {
      'meta.desc': '根據線索從二十人中找出罪犯的推理謎題',
      'wd.name.0': '柏林',
      'wd.name.1': '平安',
      'wd.name.2': '美玲',
      'wd.name.3': '明軒',
      'wd.name.4': '芳芳',
      'wd.name.5': '丹青',
      'wd.name.6': '東昇',
      'wd.name.7': '天宇',
      'wd.name.8': '寧寧',
      'wd.name.9': '樂樂',
      'wd.name.10': '麗娜',
      'wd.name.11': '光明',
      'wd.name.12': '可欣',
      'wd.name.13': '海濤',
      'wd.name.14': '浩然',
      'wd.name.15': '佳琪',
      'wd.name.16': '嘉欣',
      'wd.name.17': '建華',
      'wd.name.18': '琪琪',
      'wd.name.19': '晴雯',
      'wd.name.20': '小雨',
      'wd.name.21': '欣怡',
      'wd.name.22': '晨陽',
      'wd.name.23': '若曦',
      'wd.name.24': '子軒',
      'wd.name.25': '思遠',
      'wd.name.26': '安然',
      'wd.name.27': '雅婷',
      'wd.name.28': '婉清',
      'wd.name.29': '文傑',
      'wd.job.0': '廚師',
      'wd.job.1': '保全',
      'wd.job.2': '畫家',
      'wd.job.3': '醫生',
      'wd.job.4': '農夫',
      'wd.job.5': '教師',
      'wd.job.6': '商人',
      'wd.job.7': '記者',
      'wd.jobs.0': '廚師',
      'wd.jobs.1': '保全',
      'wd.jobs.2': '畫家',
      'wd.jobs.3': '醫生',
      'wd.jobs.4': '農夫',
      'wd.jobs.5': '教師',
      'wd.jobs.6': '商人',
      'wd.jobs.7': '記者',
      'wd.side.c': '罪犯',
      'wd.side.i': '無辜者',
      'wd.side1.c': '罪犯',
      'wd.side1.i': '無辜者',
      'wd.crim': '罪犯',
      'wd.inno': '無辜',
      'wd.place.N': '{name}的鄰居',
      'wd.place.R': '第{n}列',
      'wd.place.C': '{n}行',
      'wd.place.A': '{name}上方',
      'wd.place.B': '{name}下方',
      'wd.place.L': '{name}左邊',
      'wd.place.G': '{name}右邊',
      'wd.place.J': '{job}',
      'wd.place.E': '邊緣',
      'wd.place.K': '四個角',
      'wd.place.withJob': '{place}的{job}',
      'wd.clue.count': '{place}中恰好有{n}名{side}。',
      'wd.clue.count1': '{place}中恰好有1名{side1}。',
      'wd.clue.none': '{place}中沒有{side}。',
      'wd.clue.more': '{a}的{side}比{b}多。',
      'wd.clue.same': '{a}和{b}的{side}一樣多。',
      'wd.clue.odd': '{place}中{side}的人數是奇數。',
      'wd.clue.even': '{place}中{side}的人數是偶數。',
      'wd.clue.linked': '{place}中的{side}都連在一起。',
      'wd.clue.outnumber': '{place}中{side}比{other}多。',
      'wd.mistakes': '失誤 {n}',
      'wd.ask': '無辜還是罪犯？',
      'wd.pick': '請選擇一個人。',
      'wd.open': '證據還不夠。',
      'wd.wrong': '錯了，請再看看線索。',
      'wd.noStep': '現在沒有能確定的人了。',
      'wd.why.clue': '{from}的線索可以確定：{who} — {status}',
      'wd.why.trial': '{who}：如果是{assume}，線索之間會矛盾，所以是{status}。',
      'wd.crimIf': '罪犯',
      'wd.innoIf': '無辜',
      'wd.why.deep': '把幾條線索合起來看可以確定：{who} — {status}',
      'wd.resultMistakes': '失誤{n}次',
      'wd.used': '已用',
      'wd.tag0': '粉色標記',
      'wd.tag1': '黃色標記',
      'wd.tag2': '藍色標記',
      'wd.tag3': '紫色標記',
      'wd.look.clue': '看看{from}的線索。再按一次提示就會揭曉。',
      'wd.look.trial': '試著假設{who}是{assumeWord}，有線索會互相矛盾。',
      'wd.look.deep': '{who}：把幾條線索合起來想想。',
      'wd.share': '複製結果',
      'wd.shareHead': '{game} {level} {time}',
      'wd.copied': '已複製結果。',
      'wd.rule1': '二十人全部<b>不是無辜就是罪犯</b>。揭曉身分後，這個人會說出一條<b>線索</b>，線索全部為真。',
      'wd.rule2': '選一個人，按<b>無辜</b>或<b>罪犯</b>。<b>只能揭曉線索已經確定的人</b>——如果還兩種都有可能，會提示證據不夠；已經確定卻選反了，算一次失誤。',
      'wd.rule3': '<b>鄰居</b>是包括斜角在內的周圍八格。<b>上方、下方、左邊、右邊</b>是同一行或同一列直到盡頭。<b>連在一起</b>是指在那一列（行）中中間沒有隔著別人。',
      'wd.rule4': '點已揭曉的人，會標出這條線索涉及的人。用完的線索可以按<b>已用</b>變淡，還不知道的人可以加最多四種<b>顏色標記</b>做筆記。',
      'wd.rule5': '<b>每個棋盤都不用猜就能解到最後。</b>困難難度中有需要想「如果這個人是罪犯會怎樣？」的地方。',
      'wd.rule6': '<b>提示</b>先指出要看的線索或人；再按一次，會連同理由一起揭曉那個人。結果格子裡被指出的人是🟡，被揭曉的人是🟠，選錯過的人是🟨。'
    },
    es: {
      'meta.desc': 'Sigue las pistas para descubrir a los culpables entre veinte sospechosos',
      'wd.name.0': 'Abril',
      'wd.name.1': 'Bruno',
      'wd.name.2': 'Carla',
      'wd.name.3': 'Diego',
      'wd.name.4': 'Elena',
      'wd.name.5': 'Fabio',
      'wd.name.6': 'Gael',
      'wd.name.7': 'Hugo',
      'wd.name.8': 'Inés',
      'wd.name.9': 'Javier',
      'wd.name.10': 'Lara',
      'wd.name.11': 'Lucas',
      'wd.name.12': 'Marta',
      'wd.name.13': 'Mateo',
      'wd.name.14': 'Nora',
      'wd.name.15': 'Óscar',
      'wd.name.16': 'Pablo',
      'wd.name.17': 'Paula',
      'wd.name.18': 'Raúl',
      'wd.name.19': 'Rocío',
      'wd.name.20': 'Sara',
      'wd.name.21': 'Sergio',
      'wd.name.22': 'Teresa',
      'wd.name.23': 'Tomás',
      'wd.name.24': 'Úrsula',
      'wd.name.25': 'Valeria',
      'wd.name.26': 'Víctor',
      'wd.name.27': 'Ximena',
      'wd.name.28': 'Yago',
      'wd.name.29': 'Zoe',
      'wd.job.0': 'Cocinero',
      'wd.job.1': 'Guardia',
      'wd.job.2': 'Pintor',
      'wd.job.3': 'Médico',
      'wd.job.4': 'Granjero',
      'wd.job.5': 'Profesor',
      'wd.job.6': 'Comerciante',
      'wd.job.7': 'Periodista',
      'wd.jobs.0': 'cocineros',
      'wd.jobs.1': 'guardias',
      'wd.jobs.2': 'pintores',
      'wd.jobs.3': 'médicos',
      'wd.jobs.4': 'granjeros',
      'wd.jobs.5': 'profesores',
      'wd.jobs.6': 'comerciantes',
      'wd.jobs.7': 'periodistas',
      'wd.side.c': 'culpables',
      'wd.side.i': 'inocentes',
      'wd.side1.c': 'culpable',
      'wd.side1.i': 'inocente',
      'wd.crim': 'Culpable',
      'wd.inno': 'Inocente',
      'wd.place.N': 'entre los vecinos de {name}',
      'wd.place.R': 'en la fila {n}',
      'wd.place.C': 'en la columna {n}',
      'wd.place.A': 'encima de {name}',
      'wd.place.B': 'debajo de {name}',
      'wd.place.L': 'a la izquierda de {name}',
      'wd.place.G': 'a la derecha de {name}',
      'wd.place.J': 'entre los {jobs}',
      'wd.place.E': 'en los bordes',
      'wd.place.K': 'en las esquinas',
      'wd.place.withJob': '{place} que son {jobs}',
      'wd.clue.count': 'Hay exactamente {n} {side} {place}.',
      'wd.clue.count1': 'Hay exactamente un {side1} {place}.',
      'wd.clue.none': 'No hay {side} {place}.',
      'wd.clue.more': 'Hay más {side} {a} que {b}.',
      'wd.clue.same': 'Hay tantos {side} {a} como {b}.',
      'wd.clue.odd': 'Hay un número impar de {side} {place}.',
      'wd.clue.even': 'Hay un número par de {side} {place}.',
      'wd.clue.linked': 'Todos los {side} {place} están juntos.',
      'wd.clue.outnumber': 'Hay más {side} que {other} {place}.',
      'wd.mistakes': 'Errores {n}',
      'wd.ask': '¿Inocente o culpable?',
      'wd.pick': 'Elige a una persona.',
      'wd.open': 'Todavía no hay pruebas suficientes.',
      'wd.wrong': 'Incorrecto. Revisa las pistas.',
      'wd.noStep': 'Ahora mismo no se puede decidir a nadie más.',
      'wd.why.clue': 'La pista de {from} lo decide: {who} — {status}',
      'wd.why.trial': '{who}: {assume}, las pistas se contradicen — {status}.',
      'wd.crimIf': 'si fuera culpable',
      'wd.innoIf': 'si fuera inocente',
      'wd.why.deep': 'Juntando varias pistas se decide: {who} — {status}',
      'wd.resultMistakes': '{n} errores',
      'wd.used': 'Usada',
      'wd.tag0': 'Marca rosa',
      'wd.tag1': 'Marca amarilla',
      'wd.tag2': 'Marca azul',
      'wd.tag3': 'Marca morada',
      'wd.look.clue': 'Mira la pista de {from}. Pulsa la pista otra vez para revelarlo.',
      'wd.look.trial': 'Prueba a suponer que {who} es {assumeWord}. Algunas pistas chocarán.',
      'wd.look.deep': '{who}: junta varias pistas.',
      'wd.share': 'Copiar resultado',
      'wd.shareHead': '{game} {level} {time}',
      'wd.copied': 'Resultado copiado.',
      'wd.rule1': 'Los veinte son <b>inocentes o culpables</b>. Al revelar a alguien, esa persona da una <b>pista</b>, y todas las pistas son ciertas.',
      'wd.rule2': 'Elige a una persona y pulsa <b>Inocente</b> o <b>Culpable</b>. <b>Solo puedes revelar a quien las pistas ya han decidido</b>: si aún puede ser cualquiera de las dos cosas, se te dirá que faltan pruebas; si eliges mal a alguien ya decidido, cuenta como error.',
      'wd.rule3': 'Los <b>vecinos</b> son las ocho casillas de alrededor, diagonales incluidas. <b>Encima, debajo, izquierda y derecha</b> llegan hasta el final de la misma columna o fila. <b>Juntos</b> significa uno al lado del otro en esa línea, sin nadie en medio.',
      'wd.rule4': 'Toca a una persona revelada para resaltar a quienes menciona su pista. Marca una pista terminada como <b>Usada</b> para atenuarla, y pon hasta cuatro <b>marcas de color</b> a quienes aún no has resuelto.',
      'wd.rule5': '<b>Todos los tableros se resuelven sin adivinar.</b> En Difícil hay momentos en que hay que preguntarse «¿y si esta persona fuera culpable?».',
      'wd.rule6': 'La <b>pista</b> primero señala la pista o persona que hay que mirar; púlsala otra vez para revelar a esa persona con el motivo. En la cuadrícula del resultado, las personas señaladas quedan en 🟡, las reveladas en 🟠 y las que fallaste en 🟨.'
    }
  });
})();
