// 이 게임에만 나오는 문구. 로직은 룬·마법·적을 id로만 들고, 이름과 설명은 여기 있다.
//
// 알파라 한국어만 둔다. 사전 엔진이 없는 열쇠를 영어, 한국어 순으로 찾으므로 다른
// 언어에서도 한국어로 보인다 — 규칙과 이름이 바뀌는 중에 여섯 언어를 같이 고치면
// 고칠 것이 여섯 배가 된다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '회귀하며 룬을 조합해 멸망의 밤을 버틴다',

      'rune.fire': '불', 'rune.water': '물', 'rune.wind': '바람', 'rune.earth': '땅',
      'rune.thunder': '번개', 'rune.light': '빛', 'rune.dark': '어둠',
      'rune.chain': '연쇄', 'rune.omni': '전방위', 'rune.echo': '메아리', 'rune.anima': '흡혈',
      'rune.frost': '냉각', 'rune.heat': '과열', 'rune.gravity': '중력', 'rune.gale': '질풍', 'rune.resonance': '공명',
      'rune.erase': '재각인', 'rune.heal': '회복',

      // 원소 룬은 두 줄이다: 마법이 될 때의 형태, 마법에 들지 못하고 남을 때의 효과.
      'form.fire': '날아가 터지는 탄', 'trait.fire': '맞힌 적 둘레로 스플래시 피해',
      'form.water': '꿰뚫는 창', 'trait.water': '이동 속도 감소',
      'form.wind': '몸 둘레를 도는 칼날', 'trait.wind': '넉백',
      'form.earth': '적 무리에 깔리는 지대', 'trait.earth': '확률로 발묶기',
      'form.thunder': '곧바로 치고 곁의 적으로 튀는 번개', 'trait.thunder': '곁의 적에게 감전',
      'form.light': '적 쪽으로 쏘는 광선', 'trait.light': '맞은 적이 받는 피해 증가(취약)',
      'form.dark': '가까운 적 쪽을 크게 베는 그림자 낫', 'trait.dark': '맞은 적이 잠시 달아남(공포)',
      'extra.fire': '스플래시', 'extra.water': '둔화', 'extra.wind': '넉백', 'extra.earth': '발묶기',
      'extra.thunder': '감전', 'extra.light': '취약', 'extra.dark': '공포',
      'desc.chain': '맞힌 자리에서 이 마법이 다음 적에게 번진다',
      'desc.omni': '사방으로 퍼진다',
      'desc.echo': '잠시 뒤 한 번 더 시전한다',
      'desc.anima': '입힌 피해의 일부로 생명력을 되찾는다',
      'desc.frost': '둔화를 강하게 건다<br><b>물</b> 결빙·관통 · <b>불</b> 피해 감소',
      'desc.heat': '화상을 붙인다<br><b>불</b> 화상·폭발 강화 · <b>물</b> 증기로 무효, 피해 감소',
      'desc.gravity': '맞힌 자리로 적을 끌어당긴다<br><b>땅</b> 끌어모아 발묶기 · <b>바람</b> 넉백과 상쇄',
      'desc.gale': '탄과 칼날이 빨라지고 쿨타임이 준다<br><b>바람</b> 칼날 +1 · <b>땅</b> 발묶기 약화',
      'desc.resonance': '한 원소만 새긴 마법진에서 그 룬 수만큼 강해진다<br>원소가 섞이면 효과 없음',
      'desc.erase': '마법진에서 룬 하나를 지운다',
      'desc.heal': '생명력을 40% 되찾는다',
      'desc.primary': '마법', 'desc.added': '남으면', 'desc.stacked': '강화하면',
      'desc.special': '특수 원소',
      'special.light': '어둠과 맞선다. 언데드에게 두 배',
      'special.dark': '빛과 맞선다. 언데드에게 절반, 공포도 통하지 않음',
      'stack.fire': '탄 수·폭발 피해·폭발 범위', 'stack.water': '창 수·관통·피해',
      'stack.wind': '칼날 수·유지·피해', 'stack.earth': '지대 넓이·유지·피해',
      'stack.thunder': '튀는 수·피해', 'stack.light': '광선 유지·피해', 'stack.dark': '베는 횟수·낫 길이·피해',
      'desc.modStack': '이 효과가 커진다',

      'spell.fire': '화염구', 'spell.water': '얼음창', 'spell.wind': '회오리', 'spell.earth': '대지 균열',
      'spell.thunder': '번개', 'spell.light': '빛줄기', 'spell.dark': '그림자 낫',
      'spell.none': '시전 안 됨',
      'spell.fire.2': '폭염탄', 'spell.fire.3': '메테오', 'spell.water.2': '서리창', 'spell.water.3': '해일',
      'spell.wind.2': '폭풍 칼날', 'spell.wind.3': '토네이도', 'spell.earth.2': '충격 균열', 'spell.earth.3': '지진',
      'spell.fire.4': '유성우', 'spell.fire.5': '태양', 'spell.fire.7': '종말의 불꽃',
      'spell.water.4': '빙하', 'spell.water.5': '대해일', 'spell.water.7': '절대영도',
      'spell.wind.4': '회오리 떼', 'spell.wind.5': '태풍의 눈', 'spell.wind.7': '천공의 폭풍',
      'spell.thunder.2': '갈래 번개', 'spell.thunder.3': '낙뢰', 'spell.thunder.4': '뇌우', 'spell.thunder.5': '뇌전 오라', 'spell.thunder.7': '천공의 뇌정',
      'spell.light.2': '쌍광', 'spell.light.3': '성광', 'spell.light.4': '빛의 창', 'spell.light.5': '태양 광륜', 'spell.light.7': '심판',
      'spell.dark.2': '쌍낫', 'spell.dark.3': '어둠의 늪', 'spell.dark.4': '암흑 유성', 'spell.dark.5': '밤의 장막', 'spell.dark.7': '종말',
      'spell.earth.4': '거석 낙하', 'spell.earth.5': '가시 요새', 'spell.earth.7': '대격변',

      // 특수 조합. 원소 수를 정확히 맞추면 이 이름의 마법이 된다(runes.js의 RECIPES).
      // 번개·빛·어둠이 든 쌍은 새 원소가 형태를 정한다(runes.js).
      'recipe.fire1-thunder1': '화염 뇌격', 'recipe.fire2-thunder2': '작열 낙뢰',
      'recipe.water1-thunder1': '빙뢰', 'recipe.water2-thunder2': '빙뢰 낙하',
      'recipe.wind1-thunder1': '폭풍 번개', 'recipe.wind2-thunder2': '폭풍 낙뢰',
      'recipe.earth1-thunder1': '지뢰', 'recipe.earth2-thunder2': '대지 낙뢰',
      'recipe.fire1-light1': '태양 광선', 'recipe.fire2-light2': '작열 성광',
      'recipe.water1-light1': '서리 광선', 'recipe.water2-light2': '빙결 성광',
      'recipe.wind1-light1': '회오리 광선', 'recipe.wind2-light2': '폭풍 성광',
      'recipe.earth1-light1': '수정 광선', 'recipe.earth2-light2': '수정 성광',
      'recipe.thunder1-light1': '뇌광', 'recipe.thunder2-light2': '뇌광 폭발',
      'recipe.fire1-dark1': '지옥불 낫', 'recipe.fire2-dark2': '지옥불 늪',
      'recipe.water1-dark1': '서리 낫', 'recipe.water2-dark2': '검은 빙해',
      'recipe.wind1-dark1': '폭풍 낫', 'recipe.wind2-dark2': '검은 소용돌이',
      'recipe.earth1-dark1': '무덤 낫', 'recipe.earth2-dark2': '무덤 늪',
      'recipe.thunder1-dark1': '흑뢰 낫', 'recipe.thunder2-dark2': '흑뢰의 늪',
      'recipe.light1-dark1': '황혼', 'recipe.light2-dark2': '일식',
      // 궁극기: 일곱 원소를 하나씩.
      'recipe.genesis': '천지개벽',
      'recipe.fire1-water1': '서리불꽃', 'recipe.fire2-water2': '빙염 메테오',
      'recipe.fire3-water3': '빙염 유성우',
      'recipe.fire1-wind1': '화염 칼날', 'recipe.fire2-wind2': '화염 토네이도',
      'recipe.fire3-wind3': '불벼락',
      'recipe.fire1-earth1': '용암 지대', 'recipe.fire2-earth2': '화산 지진',
      'recipe.fire3-earth3': '화산탄',
      'recipe.water1-wind1': '소용돌이 창', 'recipe.water2-wind2': '소용돌이 해일',
      'recipe.water3-wind3': '폭풍 빙하',
      'recipe.water1-earth1': '늪', 'recipe.water2-earth2': '빙결 지진',
      'recipe.water3-earth3': '빙산 낙하',
      'recipe.wind1-earth1': '모래 칼날', 'recipe.wind2-earth2': '모래폭풍',
      'recipe.wind3-earth3': '돌벼락',
      'recipe.fire1-water1-wind1': '뇌운', 'recipe.fire2-water2-wind2': '천둥 폭풍',
      'recipe.fire1-water1-earth1': '화산', 'recipe.fire2-water2-earth2': '화산 폭발',
      'recipe.fire1-wind1-earth1': '불모래 메테오', 'recipe.fire2-wind2-earth2': '운석 폭풍',
      'recipe.water1-wind1-earth1': '폭풍 해일', 'recipe.water2-wind2-earth2': '빙하 폭풍',
      'am.special': '특수',
      'book.all': '전체', 'book.allCircles': '모든 서클', 'book.circle': '{n}서클', 'book.plain': '원소 마법', 'book.recipes': '특수 조합',
      'book.missing': '아직 찾지 못한 마법 {n}개',
      'book.parts': '구성',
      'kind.bolt': '가까운 적에게 날아가 터지는 탄', 'kind.lance': '적을 꿰뚫고 날아가는 창',
      'kind.orbit': '몸 둘레를 도는 칼날', 'kind.zone': '적 무리 아래 깔려 계속 치는 지대',
      'kind.zap': '곧바로 치고 곁의 적으로 튀는 번개', 'kind.beam': '마법사에게서 뻗어 잠시 머무는 광선',
      'kind.reap': '가까운 적 쪽을 부채꼴로 크게 벰', 'kind.meteor': '사거리 안 여러 곳에 한꺼번에 떨어짐',
      'kind.rain': '한동안 사거리 안에 쏟아짐', 'kind.aura': '마법사 둘레를 계속 침',
      'kind.wave': '밀고 나가는 물결', 'kind.tornado': '떠돌며 휩쓰는 회오리',
      'kind.quake': '발밑부터 둘레를 한꺼번에 흔듦', 'kind.harmony': '일곱 원소의 마법을 한꺼번에 씀',
      'kind.screen': '화면 전체',
      'fx.cluster': '터지며 파편이 흩어짐', 'fx.nova': '맞힌 자리에서 냉기 폭발', 'fx.pulse': '칼날 반경이 들고 남',
      'fx.shock': '충격파가 번짐', 'fx.ring': '사방으로', 'fx.pull': '끌어당김', 'fx.vortex': '빨아들임',
      'fx.ignite': '불길이 남음', 'fx.freeze': '얼림', 'fx.shatter': '돌 파편',
      'fx.burn': '화상 {n}/초', 'fx.pierce': '관통 {n}', 'fx.jumps': '튀김 {n}', 'fx.zap': '감전 {n}',
      'fx.vuln': '취약 +{n}%', 'fx.fear': '공포 {n}초',
      'fx.undead-light': '언데드에게 두 배', 'fx.undead-dark': '언데드에게 절반',
      'spell.withMods': '{mods}의 {name}', 'spell.modJoin': '·', 'spell.withExtras': '{name} +{extras}',
      'am.synergy': '상성', 'am.clash': '상극',
      'stat.slow': '둔화 {n}%', 'stat.splash': '스플래시 {n}', 'stat.root': '발묶기 {n}%', 'stat.knock': '넉백 {n}', 'stat.freeze': '결빙 {n}%',
      'spell.unknown': '???',
      'spell.noElement': '원소가 없어 시전되지 않습니다',

      'stat.dmg': '피해', 'stat.size': '범위', 'stat.leech': '흡혈 {n}%', 'stat.cd': '쿨타임', 'stat.dur': '유지', 'stat.count': '개수',
      'stat.sec': '{n}초',

      'am.circle': '{n}서클',
      // 들어가는 밤은 서클 번호 대신 차례로 부른다. 서수는 언어마다 꼴이 달라 통째로 둔다.
      'am.night1': '첫 번째 밤', 'am.night2': '두 번째 밤', 'am.night3': '세 번째 밤',
      'am.night4': '네 번째 밤', 'am.night5': '다섯 번째 밤', 'am.night6': '여섯 번째 밤',
      'am.night7': '일곱 번째 밤', 'am.night8': '여덟 번째 밤', 'am.night9': '아홉 번째 밤',
      'am.nightN': '{n}번째 밤',
      'am.level': 'Lv {n}',
      'am.levelMax': 'Lv {n} 최대',
      'am.boss': '재앙의 사도',
      'am.bossFight': '결전',
      'am.slot': '마법진 {n}',
      'am.locked': 'Lv {n}에 열림',
      'am.empty': '비어 있음',

      'am.levelTitle': '[전생의 기억이 떠오릅니다]',
      'am.levelNote': '룬 하나를 고르십시오',
      'am.pickCircle': '[어느 구멍에 새기시겠습니까?]',
      'am.tapSocket': '빈 구멍은 새기기, 같은 룬이 끼워진 구멍은 강화',
      'am.tapErase': '지울 룬이 끼워진 구멍을 누르십시오',
      'am.erase': '제거', 'am.confirm': '확인',
      'am.pickErase': '[지울 룬을 고르십시오]',
      'am.add': '새기기', 'am.grade': '강화',
      'am.full': '빈 칸 없음',
      'am.back': '다시 고르기',
      'am.new': '새 마법',

      'am.campTitle': '[{n}회차 회귀]',
      'am.campFirst': '[멸망의 밤이 다가옵니다]',
      'am.mana': '마나 {n}',
      'am.break': '{n}서클 돌파',
      'am.breakCost': '마나 {n}',
      'am.bossTag': '보스',
      'am.trainProgress': '마력 수련 {have}/{n}',
      'am.manaLabel': '마나',
      'am.tab.night': '출전', 'am.tab.gear': '장비', 'am.tab.bag': '가방',
      'am.tab.forge': '강화', 'am.tab.shop': '상점', 'am.tab.book': '마도서',
      'am.reportGold': '금화 +{n}',
      'am.reportDrop': '장비 {name}',

      'gear.slot.staff': '지팡이', 'gear.slot.robe': '로브', 'gear.slot.ring': '반지',
      'gear.slot.amulet': '목걸이', 'gear.slot.belt': '허리띠', 'gear.slot.boots': '장화',
      'gear.el.fire': '불의 {name}', 'gear.el.water': '물의 {name}', 'gear.el.wind': '바람의 {name}', 'gear.el.earth': '땅의 {name}',
      'gear.el.thunder': '번개의 {name}', 'gear.el.light': '빛의 {name}', 'gear.el.dark': '어둠의 {name}',
      'gear.rarity.0': '일반', 'gear.rarity.1': '고급', 'gear.rarity.2': '희귀', 'gear.rarity.3': '영웅', 'gear.rarity.4': '전설',
      'gear.stat.dmg': '마법 피해 +{v}%', 'gear.stat.hp': '최대 생명력 +{v}', 'gear.stat.cd': '쿨타임 -{v}%',
      'gear.stat.xp': '경험치 +{v}%', 'gear.stat.regen': '초당 생명력 +{v}', 'gear.stat.speed': '이동 속도 +{v}%',
      'gear.stat.el': '{el} 마법 +{v}%',
      'gear.total': '합계',
      'gear.bagEmpty': '가진 장비가 없습니다. 밤을 넘기거나 상점에서 상자를 여십시오.',
      'gear.bagNote': '장비를 눌러 끼우거나 강화하거나 팝니다. 같은 부위·같은 등급 셋은 강화 탭에서 합성합니다.',
      'gear.level': 'Lv {n}/{max}',
      'gear.next': '다음 레벨: {text}',
      'gear.equipped': '장착 중',
      'gear.equip': '장착', 'gear.unequip': '해제', 'gear.upgrade': '강화', 'gear.maxed': '최대 레벨',
      'gear.sell': '판매 +{n}',
      'gear.gotTitle': '[장비를 얻었습니다]',

      'forge.trainTitle': '마력 수련 · {n}서클',
      'forge.trainNote': '마나로 한 단계씩 수련합니다. 열 단계를 다 채우면 다음 서클로 돌파할 수 있고, 서클이 오를수록 수련이 비싸집니다.',
      'forge.train': '{stat} 수련({v})',
      'forge.trainDone': '이 서클의 수련을 마쳤습니다',
      'forge.needTrain': '수련을 다 채워야 돌파할 수 있습니다 ({have}/{n})',
      'train.dmg': '마력', 'train.hp': '체력', 'train.cd': '집중', 'train.speed': '민첩', 'train.xp': '통찰',
      'train.short.dmg': '력', 'train.short.hp': '체', 'train.short.cd': '집', 'train.short.speed': '민', 'train.short.xp': '통',
      'forge.circleTitle': '서클 돌파',
      'forge.circleNote': '서클이 오르면 마법진마다 룬 구멍이 하나 늘고 최대 레벨이 오릅니다. 수련한 능력은 그대로 남습니다.',
      'forge.mergeTitle': '장비 합성',
      'forge.mergeNote': '같은 부위·같은 등급 장비 셋을 한 등급 위 하나로 합칩니다. 레벨은 가장 높은 것을 잇습니다.',
      'forge.mergeAll': '모두 합성 ({n})',
      'forge.merged': '[{n}번 합성했습니다]',
      'forge.upTitle': '장비 강화',
      'forge.upNote': '가방이나 장비 탭에서 장비를 눌러 금화로 강화합니다.',

      'shop.basic': '기본 상자', 'shop.fine': '고급 상자',
      'shop.note': '금화는 밤에서 적을 쓰러뜨리고 밤을 넘겨 모읍니다. 보스의 밤을 넘기면 장비가 반드시 나옵니다.',
      'am.bossNightInfo': '보스의 밤',
      'am.bossNightAlert': '[강력한 보스가 기다리는 밤입니다]',
      'am.nightOpened': '{night}이 열렸습니다',
      'am.breakNeedMana': '마나가 {n} 모자랍니다',
      'am.breakMax': '최고 서클입니다',
      'am.breakDone': '[{n}서클에 도달했습니다]',
      'am.pickNight': '들어갈 밤',
      'am.nightInfo': '{m}분 · 마법진마다 룬 구멍 {n}개 · 최대 Lv {max}',
      'am.start': '멸망의 밤으로',
      'am.grimoire': '마도서',
      'am.grimoireCount': '{found} / {total}',
      'am.grimoireNone': '아직 기록된 마법이 없습니다',
      'am.best': '최고 {t}',

      'am.lostTitle': '[사망했습니다]',
      'am.lostNote': '회귀합니다…',
      'am.wonTitle': '[{night}을 넘겼습니다]',
      'am.wonNote': '그러나 멸망은 다시 옵니다. 회귀합니다…',
      'am.reportTime': '버틴 시간 {t}',
      'am.reportKills': '처치 {n}',
      'am.reportLevel': '레벨 {n}',
      'am.reportMana': '마나 +{n}',
      'am.reportFound': '새로 기록한 마법 {n}',
      'am.regress': '회귀',

      'am.bossAlert': '[재앙의 사도가 나타났습니다]',
      'am.burstAlert': '[포위됩니다]',
      'am.unlockAlert': '[마법진 {n}이 열렸습니다]',
      'am.newSpell': '[새 마법: {name}]',
      'am.paused': '멈춤',
      'am.resume': '이어 하기',

      'am.help.r1': '<b>끌어서 움직입니다.</b> 화면 어디든 누른 채로 밀면 그쪽으로 걷습니다. PC는 WASD나 방향키.',
      'am.help.r2': '마법은 <b>마법진이 스스로 시전</b>합니다. 마법진마다 쿨타임과 유지 시간이 있습니다.',
      'am.help.r3': '레벨이 오르면 <b>룬 하나를 골라 마법진의 구멍에 새깁니다.</b> 원소 룬은 원, 수식어 룬은 삼각형이라 <b>모양이 맞는 구멍에만</b> 들어가고, 네모난 구멍은 아무것이나 받습니다. 룬을 가장 많이 쓰는 마법이 발동하고(같으면 먼저 새긴 쪽), 남은 원소 룬은 효과를 더합니다. <b>일곱 원소를 모두 모으면 궁극기</b>가 됩니다. 빛과 어둠은 서로 맞서는 특수 원소로, 언데드는 빛에 약하고 어둠에 강합니다.',
      'am.help.r4': '<b>서클</b>은 마법진 한 칸에 새길 수 있는 룬의 수입니다. 로비의 강화 탭에서 마나로 마력 수련을 다 채우면 돌파합니다.',
      'am.help.r5': '한 번 만든 마법은 <b>마도서</b>에 남아, 다음 회차에 룬을 고를 때 무엇이 될지 알려 줍니다.',
      'am.help.r6': '밤은 끝없이 이어집니다. 끝까지 버티면 다음 밤이 열리고, <b>다섯 번째 밤마다</b> 끝에 강력한 보스가 옵니다.',
    },
  });
})();
