// 목록 페이지에만 나오는 문구. 게임 이름은 게임 페이지와 함께 쓰므로 shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'hub.tagline': '브라우저에서 바로 하는 미니 게임 모음',
      'hub.lang': '언어',
      'hub.alpha': '알파',
      'hub.alphaNote': '아직 다듬는 중입니다. 규칙과 균형이 바뀔 수 있어요.',

      'desc.2048': '숫자 합치기',
      'desc.kkodle': '한글 단어 맞히기',
      'desc.sudoku': '1~9 채우기',
      'desc.doppelblock': '숫자 합 맞히기',
      'desc.chess-puzzle': '최선의 한 수 찾기',
      'desc.zip': '한 번에 다 지나기',
      'desc.queens': '행·열·색에 하나씩',
      'desc.patches': '직사각형으로 다 나누기',
      'desc.tango': '해와 달을 반씩 놓기',
      'desc.idioms': '숨은 사자성어 찾기',
      'desc.conquest': '거점 차지하기',
      'desc.hashi': '섬을 하나로 잇기',
      'desc.dicewars': '굴려서 땅 뺏기',
      'desc.yacht': '주사위로 점수 겨루기',
      'desc.nonogram': '숫자대로 칠해 그림 찾기',
      'desc.rushhour': '막힌 길에서 빨간 차 빼내기',
      'desc.healer': '파티 힐러 맡기',
      'desc.defense': '길목에 사람을 세워 적을 막기',
      'desc.metro': '노선을 깔아 도시 키우기',
      'desc.roadworks': '도로를 손봐 차를 흐르게',
      'desc.sokoban': '상자를 밀어 제자리에',

      'daily.title': '오늘의 도전',
      'daily.calendar': '달력',
      'daily.streak': '{count}일 연속',
      'daily.best': '최고 {count}일',
      'daily.prev': '이전 달',
      'daily.next': '다음 달',
      'daily.done': '완료',
      'daily.note': '세 가지를 다 해낸 날이 연속 기록에 들어갑니다. 지난 날은 채울 수 없어요.'
    },
    en: {
      'hub.tagline': 'Mini games you can play right in the browser',
      'hub.lang': 'Language',
      'hub.alpha': 'Alpha',
      'hub.alphaNote': 'Still being polished — rules and balance may change.',

      'desc.2048': 'Merge the numbers',
      'desc.kkodle': 'Guess the Korean word',
      'desc.sudoku': 'Fill in 1 to 9',
      'desc.doppelblock': 'Match the sums',
      'desc.chess-puzzle': 'Find the best move',
      'desc.zip': 'Cover every cell in one line',
      'desc.queens': 'One per row, column and color',
      'desc.patches': 'Split it all into rectangles',
      'desc.tango': 'Half suns, half moons',
      'desc.idioms': 'Find the hidden idioms',
      'desc.conquest': 'Take the strongholds',
      'desc.hashi': 'Connect every island',
      'desc.dicewars': 'Roll to take territory',
      'desc.yacht': 'Score with the dice',
      'desc.nonogram': 'Paint by the numbers',
      'desc.rushhour': 'Get the red car out',
      'desc.healer': 'Play the party healer',
      'desc.defense': 'Post units on the path to stop them',
      'desc.metro': 'Grow a city by laying metro lines',
      'desc.roadworks': 'Keep the traffic moving',
      'desc.sokoban': 'Push every box into place',

      'daily.title': 'Daily challenge',
      'daily.calendar': 'Calendar',
      'daily.streak': '{count}-day streak',
      'daily.best': 'Best {count} days',
      'daily.prev': 'Previous month',
      'daily.next': 'Next month',
      'daily.done': 'Done',
      'daily.note': 'Days where you finish all three count toward your streak. Past days can\'t be filled in.'
    },
    ja: {
      'hub.tagline': 'ブラウザですぐ遊べるミニゲーム集',
      'hub.lang': '言語',
      'hub.alpha': 'アルファ',
      'hub.alphaNote': 'まだ調整中です。ルールやバランスが変わることがあります。',

      'desc.2048': '数字を合わせる',
      'desc.kkodle': 'ハングルの単語を当てる',
      'desc.sudoku': '1〜9を埋める',
      'desc.doppelblock': '数字の和を合わせる',
      'desc.chess-puzzle': '最善手を探す',
      'desc.zip': '一筆で全部を通る',
      'desc.queens': '行・列・色にひとつずつ',
      'desc.patches': '長方形に分け切る',
      'desc.tango': '太陽と月を半分ずつ置く',
      'desc.idioms': '隠れた四字熟語を探す',
      'desc.conquest': '拠点を奪う',
      'desc.hashi': '島をすべてつなぐ',
      'desc.dicewars': 'サイコロで領地を奪う',
      'desc.yacht': 'サイコロで得点を競う',
      'desc.nonogram': '数字どおりに塗って絵を出す',
      'desc.rushhour': '赤い車を外に出す',
      'desc.healer': 'パーティのヒーラーを務める',
      'desc.defense': '通り道に人を置いて敵を止める',
      'desc.metro': '路線を引いて街を育てる',
      'desc.roadworks': '道路を直して車を流す',
      'desc.sokoban': '箱を押して所定の位置へ',

      'daily.title': '今日のチャレンジ',
      'daily.calendar': 'カレンダー',
      'daily.streak': '{count}日連続',
      'daily.best': '最高{count}日',
      'daily.prev': '前の月',
      'daily.next': '次の月',
      'daily.done': '達成',
      'daily.note': '3つすべて達成した日が連続記録に入ります。過ぎた日は埋められません。'
    },
    'zh-CN': {
      'hub.tagline': '打开浏览器就能玩的小游戏',
      'hub.lang': '语言',
      'hub.alpha': '内测',
      'hub.alphaNote': '仍在打磨中，规则和平衡可能会变。',

      'desc.2048': '合并数字',
      'desc.kkodle': '猜韩语单词',
      'desc.sudoku': '填入 1~9',
      'desc.doppelblock': '凑出数字之和',
      'desc.chess-puzzle': '找出最佳一手',
      'desc.zip': '一笔走遍所有格子',
      'desc.queens': '每行每列每色各一个',
      'desc.patches': '全部切成矩形',
      'desc.tango': '太阳和月亮各一半',
      'desc.idioms': '找出藏着的成语',
      'desc.conquest': '夺取据点',
      'desc.hashi': '把小岛连成一片',
      'desc.dicewars': '掷骰子抢地盘',
      'desc.yacht': '用骰子比分数',
      'desc.nonogram': '按数字涂出图案',
      'desc.rushhour': '把红车开出去',
      'desc.healer': '担任队伍的治疗',
      'desc.defense': '在路口布防挡住敌人',
      'desc.metro': '铺地铁线路养大城市',
      'desc.roadworks': '疏通道路，让车流动',
      'desc.sokoban': '把箱子推到位',

      'daily.title': '今日挑战',
      'daily.calendar': '日历',
      'daily.streak': '连续{count}天',
      'daily.best': '最高{count}天',
      'daily.prev': '上个月',
      'daily.next': '下个月',
      'daily.done': '已完成',
      'daily.note': '三项全部完成的日子计入连续记录。过去的日子无法补做。'
    },
    'zh-TW': {
      'hub.tagline': '打開瀏覽器就能玩的小遊戲',
      'hub.lang': '語言',
      'hub.alpha': '內測',
      'hub.alphaNote': '仍在打磨中，規則與平衡可能會變。',

      'desc.2048': '合併數字',
      'desc.kkodle': '猜韓語單字',
      'desc.sudoku': '填入 1~9',
      'desc.doppelblock': '湊出數字之和',
      'desc.chess-puzzle': '找出最佳一手',
      'desc.zip': '一筆走遍所有格子',
      'desc.queens': '每行每列每色各一個',
      'desc.patches': '全部切成矩形',
      'desc.tango': '太陽和月亮各一半',
      'desc.idioms': '找出藏著的成語',
      'desc.conquest': '奪取據點',
      'desc.hashi': '把小島連成一片',
      'desc.dicewars': '擲骰子搶地盤',
      'desc.yacht': '用骰子比分數',
      'desc.nonogram': '按數字塗出圖案',
      'desc.rushhour': '把紅車開出去',
      'desc.healer': '擔任隊伍的治療',
      'desc.defense': '在路口布防擋住敵人',
      'desc.metro': '鋪地鐵線路養大城市',
      'desc.roadworks': '疏通道路，讓車流動',
      'desc.sokoban': '把箱子推到位',

      'daily.title': '今日挑戰',
      'daily.calendar': '日曆',
      'daily.streak': '連續{count}天',
      'daily.best': '最高{count}天',
      'daily.prev': '上個月',
      'daily.next': '下個月',
      'daily.done': '已完成',
      'daily.note': '三項全部完成的日子計入連續紀錄。過去的日子無法補做。'
    },
    es: {
      'hub.tagline': 'Minijuegos para jugar en el navegador',
      'hub.lang': 'Idioma',
      'hub.alpha': 'Alfa',
      'hub.alphaNote': 'Aún en desarrollo: las reglas y el equilibrio pueden cambiar.',

      'desc.2048': 'Combina los números',
      'desc.kkodle': 'Adivina la palabra coreana',
      'desc.sudoku': 'Rellena del 1 al 9',
      'desc.doppelblock': 'Acierta las sumas',
      'desc.chess-puzzle': 'Encuentra la mejor jugada',
      'desc.zip': 'Recórrelo todo de un trazo',
      'desc.queens': 'Uno por fila, columna y color',
      'desc.patches': 'Divídelo todo en rectángulos',
      'desc.tango': 'Mitad soles, mitad lunas',
      'desc.idioms': 'Encuentra los modismos ocultos',
      'desc.conquest': 'Conquista las bases',
      'desc.hashi': 'Conecta todas las islas',
      'desc.dicewars': 'Tira y conquista territorio',
      'desc.yacht': 'Compite con los dados',
      'desc.nonogram': 'Pinta según los números',
      'desc.rushhour': 'Saca el coche rojo',
      'desc.healer': 'Sé el sanador del grupo',
      'desc.defense': 'Coloca unidades en el paso',
      'desc.metro': 'Haz crecer la ciudad con el metro',
      'desc.roadworks': 'Haz que el tráfico fluya',
      'desc.sokoban': 'Empuja las cajas a su sitio',

      'daily.title': 'Reto diario',
      'daily.calendar': 'Calendario',
      'daily.streak': 'Racha de {count} días',
      'daily.best': 'Mejor: {count} días',
      'daily.prev': 'Mes anterior',
      'daily.next': 'Mes siguiente',
      'daily.done': 'Hecho',
      'daily.note': 'Los días en que completas los tres cuentan para tu racha. Los días pasados no se pueden completar.'
    }
  });
})();
