// 이 게임에만 나오는 문구. 난이도와 도구 이름은 shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '막힌 차들을 밀어 빨간 차를 빼내는 퍼즐',
      'rushhour.bestCount': '최소 수로 푼 판 {count}',
      'rushhour.count': '{moves}수 <b>/ 최소 {best}수</b>',
      'rushhour.done': '빠져나갔습니다',
      'rushhour.noteOptimal': '{moves}수 · 최소 수로 풀었습니다',
      'rushhour.note': '{moves}수 · 최소는 {best}수',
      'rushhour.noteHinted': '힌트를 썼습니다',
      'rushhour.hint': '최단 풀이의 다음 한 수입니다',
      'rushhour.rule1': '<b>빨간 차를 오른쪽 끝으로</b> 빼내면 끝납니다.',
      'rushhour.rule2': '차는 <b>제 방향으로만</b> 움직입니다. 가로 차는 좌우로, 세로 차는 위아래로만 가고, 돌리거나 넘어갈 수 없습니다.',
      'rushhour.rule3': '차를 <b>밀어서</b> 옮기세요. 짧게 누르면 그쪽으로 한 칸 갑니다.',
      'rushhour.rule4': '<b>몇 칸을 가든 한 수</b>로 셉니다. 판마다 <b>최소 수</b>가 적혀 있으니 그 수에 맞춰 보세요.',
      'rushhour.rule5': '<b>힌트</b>는 최소 풀이의 다음 한 수를 대신 둬 줍니다. 힌트를 쓴 판은 기록에 넣지 않습니다.',
      'rushhour.rule6': '모든 판은 <b>반드시 풀립니다.</b> 적힌 최소 수도 실제로 풀어 본 값입니다.'
    },
    en: {
      'meta.desc': 'Slide the blocking cars aside and drive the red car out',
      'rushhour.bestCount': 'Solved in the fewest moves: {count}',
      'rushhour.count': '{moves} moves <b>/ best {best}</b>',
      'rushhour.done': 'You made it out',
      'rushhour.noteOptimal': '{moves} moves · the fewest possible',
      'rushhour.note': '{moves} moves · the fewest is {best}',
      'rushhour.noteHinted': 'hint used',
      'rushhour.hint': 'The next move of the shortest solution',
      'rushhour.rule1': 'Get the <b>red car out the right-hand exit</b> and you are done.',
      'rushhour.rule2': 'Cars move <b>only along their own axis</b>. Horizontal cars slide left and right, vertical ones up and down. No turning, no jumping.',
      'rushhour.rule3': '<b>Drag</b> a car to move it. A short tap nudges it one square that way.',
      'rushhour.rule4': '<b>However far a car travels, it counts as one move.</b> Each board shows the <b>fewest moves</b> — try to match it.',
      'rushhour.rule5': 'A <b>Hint</b> plays the next move of the shortest solution for you. Boards solved with hints are not recorded.',
      'rushhour.rule6': 'Every board is <b>guaranteed solvable</b>, and the stated minimum comes from actually solving it.'
    },
    ja: {
      'meta.desc': 'ふさいでいる車を動かして赤い車を出すパズル',
      'rushhour.bestCount': '最小手で解いた盤 {count}',
      'rushhour.count': '{moves}手 <b>/ 最小 {best}手</b>',
      'rushhour.done': '脱出しました',
      'rushhour.noteOptimal': '{moves}手 · 最小手で解きました',
      'rushhour.note': '{moves}手 · 最小は{best}手',
      'rushhour.noteHinted': 'ヒントを使いました',
      'rushhour.hint': '最短手順の次の一手です',
      'rushhour.rule1': '<b>赤い車を右端から</b>出せば終わりです。',
      'rushhour.rule2': '車は<b>自分の向きにだけ</b>動きます。横向きは左右、縦向きは上下だけ。回転も飛び越えもできません。',
      'rushhour.rule3': '車を<b>押して</b>動かします。軽く押すとその方向に一マス進みます。',
      'rushhour.rule4': '<b>何マス動いても一手</b>と数えます。盤ごとに<b>最小手数</b>が書いてあるので、それに合わせてみてください。',
      'rushhour.rule5': '<b>ヒント</b>は最短手順の次の一手を代わりに指します。ヒントを使った盤は記録に入れません。',
      'rushhour.rule6': 'どの盤も<b>必ず解けます。</b>書かれた最小手数も実際に解いて出した値です。'
    },
    'zh-CN': {
      'meta.desc': '挪开挡路的车，把红车开出去',
      'rushhour.bestCount': '用最少步数解开的盘面 {count}',
      'rushhour.count': '{moves} 步 <b>/ 最少 {best} 步</b>',
      'rushhour.done': '开出去了',
      'rushhour.noteOptimal': '{moves} 步 · 正是最少步数',
      'rushhour.note': '{moves} 步 · 最少是 {best} 步',
      'rushhour.noteHinted': '用过提示',
      'rushhour.hint': '这是最短解法的下一步',
      'rushhour.rule1': '把<b>红车从右边开出去</b>就算过关。',
      'rushhour.rule2': '车<b>只能顺着自己的方向</b>走。横着的左右挪，竖着的上下挪，不能转向，也不能越过别的车。',
      'rushhour.rule3': '<b>拖动</b>车来移动。轻点一下就往那个方向挪一格。',
      'rushhour.rule4': '<b>走几格都算一步。</b>每一盘都写着<b>最少步数</b>，可以照着挑战。',
      'rushhour.rule5': '<b>提示</b>会替你走出最短解法的下一步。用过提示的盘面不计入记录。',
      'rushhour.rule6': '所有盘面<b>都一定能解开</b>，写着的最少步数也是实际解出来的。'
    },
    'zh-TW': {
      'meta.desc': '挪開擋路的車，把紅車開出去',
      'rushhour.bestCount': '用最少步數解開的盤面 {count}',
      'rushhour.count': '{moves} 步 <b>/ 最少 {best} 步</b>',
      'rushhour.done': '開出去了',
      'rushhour.noteOptimal': '{moves} 步 · 正是最少步數',
      'rushhour.note': '{moves} 步 · 最少是 {best} 步',
      'rushhour.noteHinted': '用過提示',
      'rushhour.hint': '這是最短解法的下一步',
      'rushhour.rule1': '把<b>紅車從右邊開出去</b>就算過關。',
      'rushhour.rule2': '車<b>只能順著自己的方向</b>走。橫的左右挪，直的上下挪，不能轉向，也不能越過別的車。',
      'rushhour.rule3': '<b>拖曳</b>車來移動。輕點一下就往那個方向挪一格。',
      'rushhour.rule4': '<b>走幾格都算一步。</b>每一盤都寫著<b>最少步數</b>，可以照著挑戰。',
      'rushhour.rule5': '<b>提示</b>會替你走出最短解法的下一步。用過提示的盤面不計入紀錄。',
      'rushhour.rule6': '所有盤面<b>都一定能解開</b>，寫著的最少步數也是實際解出來的。'
    },
    es: {
      'meta.desc': 'Aparta los coches que estorban y saca el coche rojo',
      'rushhour.bestCount': 'Resueltos con el mínimo de movimientos: {count}',
      'rushhour.count': '{moves} movimientos <b>/ mínimo {best}</b>',
      'rushhour.done': 'Has salido',
      'rushhour.noteOptimal': '{moves} movimientos · el mínimo posible',
      'rushhour.note': '{moves} movimientos · el mínimo es {best}',
      'rushhour.noteHinted': 'con pista',
      'rushhour.hint': 'El siguiente movimiento de la solución más corta',
      'rushhour.rule1': 'Saca el <b>coche rojo por la salida de la derecha</b> y habrás terminado.',
      'rushhour.rule2': 'Los coches se mueven <b>solo en su propio eje</b>. Los horizontales, a izquierda y derecha; los verticales, arriba y abajo. Ni giran ni saltan.',
      'rushhour.rule3': '<b>Arrastra</b> un coche para moverlo. Un toque corto lo empuja una casilla en esa dirección.',
      'rushhour.rule4': '<b>Recorra lo que recorra, cuenta como un movimiento.</b> Cada tablero indica el <b>mínimo</b>: intenta igualarlo.',
      'rushhour.rule5': 'Una <b>Pista</b> juega por ti el siguiente movimiento de la solución más corta. Los tableros con pistas no cuentan.',
      'rushhour.rule6': 'Todos los tableros <b>tienen solución garantizada</b>, y el mínimo indicado sale de resolverlos de verdad.'
    }
  });
})();
