// 이 게임에만 나오는 문구. 인원·난이도 같은 공통 문구는 shared/strings.js에 있다.
// 이 파일에서는 사전 함수를 T로 받는다 — main.js가 영토를 t로 쓰고 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '주사위를 굴려 이웃 영토를 뺏고 가장 큰 덩어리로 보급을 받는 턴제 전략 게임',
      'dice.map': '영토 지도',
      'dice.territory': '영토',
      'dice.endTurn': '턴 종료',
      'dice.endTurnGain': '턴 종료 · 주사위 {gain}개 받기',
      'dice.foeTurn': '상대 차례…',
      'dice.myTurn': '내 차례입니다. 칠 영토를 고르세요.',
      'dice.myTurnShort': '내 차례입니다.',
      'dice.won': '이겼습니다',
      'dice.blocked': '막혔습니다',
      'dice.rollScore': '{attack} 대 {defend} · ',
      'dice.describe': '{attack} 대 {defend} · <b>{outcome}</b>',
      'dice.attacking': '{before}개로 {against}개를 칩니다…',
      'dice.attacked': '{before}개로 {against}개를 칩니다 — {result}',
      'dice.gained': '주사위 {gain}개를 받았습니다.',
      'dice.needTwo': '주사위가 하나뿐인 영토로는 칠 수 없습니다.',
      'dice.foeThinking': '<b>{n}번</b>이 두는 중…',
      'dice.foeGained': '<b>{n}번</b>이 주사위 {gain}개를 받았습니다.',
      'dice.foeAttacking': '<b>{n}번</b>이 {dice}개로 {against}개를 칩니다…',
      'dice.foeAttacked': '<b>{n}번</b>의 공격 — {result}',
      'dice.allYours': '다 차지했습니다',
      'dice.lost': '졌습니다',
      'dice.lastStanding': '마지막까지 남았습니다.',
      'dice.foeLastStanding': '{n}번이 마지막까지 남았습니다.',
      'dice.rule1': '내 영토를 고르고 <b>맞닿은 남의 영토</b>를 누르면 칩니다. 주사위가 <b>둘 이상</b>인 영토만 칠 수 있습니다.',
      'dice.rule2': '양쪽 주사위를 <b>모두 굴려 합을 견줍니다.</b> 공격 쪽이 <b>더 커야</b> 이깁니다 — 같으면 지키는 쪽이 이깁니다. 굴린 눈은 판 위에 <b>위가 치는 쪽, 아래가 지키는 쪽</b>으로 뜹니다.',
      'dice.rule3': '이기면 그 영토를 얻고, 친 영토의 주사위를 <b>하나만 남기고</b> 옮깁니다. 지면 친 영토가 <b>하나로</b> 줄어듭니다.',
      'dice.rule4': '고른 영토에서 칠 수 있는 곳에는 <b>이길 확률</b>이 뜹니다. 숫자만 보고 두세요.',
      'dice.rule5': '차례를 끝내면 <b>이어져 있는 내 영토 중 가장 큰 덩어리의 크기만큼</b> 주사위를 받아 내 영토에 무작위로 얹습니다. 넓게 흩어지는 것보다 <b>이어 붙이는 편이 이득</b>입니다. 여덟이 찬 영토는 건너뛰고, 놓을 자리가 없으면 쌓아 뒀다 다음에 받습니다.',
      'dice.rule6': '<b>먼저 치는 쪽이 유리한 놀이</b>라, 뒤 차례일수록 주사위를 조금 더 갖고 시작합니다. 내가 늘 선공이므로 그만큼을 상대가 받습니다 — 2인은 6개, 3인은 3·4개, 4인은 1·2·2개입니다.',
      'dice.rule7': '영토를 모두 잃으면 탈락하고, <b>마지막까지 남으면 이깁니다.</b>',
      'dice.rule8': '<b>난이도</b>는 판을 다시 만들지 않고 언제든 바꿀 수 있습니다.'
    },
    en: {
      'meta.desc': 'Turn-based strategy: roll dice to take neighbouring lands, and get reinforcements from your largest connected block',
      'dice.map': 'Territory map',
      'dice.territory': 'Lands',
      'dice.endTurn': 'End turn',
      'dice.endTurnGain': 'End turn · take {gain} dice',
      'dice.foeTurn': 'Opponent’s turn…',
      'dice.myTurn': 'Your turn. Pick a land to attack from.',
      'dice.myTurnShort': 'Your turn.',
      'dice.won': 'you win',
      'dice.blocked': 'held',
      'dice.rollScore': '{attack} vs {defend} · ',
      'dice.describe': '{attack} vs {defend} · <b>{outcome}</b>',
      'dice.attacking': 'Attacking {against} with {before}…',
      'dice.attacked': 'Attacking {against} with {before} — {result}',
      'dice.gained': 'You received {gain} dice.',
      'dice.needTwo': 'A land with a single die cannot attack.',
      'dice.foeThinking': '<b>Player {n}</b> is thinking…',
      'dice.foeGained': '<b>Player {n}</b> received {gain} dice.',
      'dice.foeAttacking': '<b>Player {n}</b> attacks {against} with {dice}…',
      'dice.foeAttacked': '<b>Player {n}</b> attacks — {result}',
      'dice.allYours': 'The whole map is yours',
      'dice.lost': 'You lost',
      'dice.lastStanding': 'You were the last one standing.',
      'dice.foeLastStanding': 'Player {n} was the last one standing.',
      'dice.rule1': 'Select one of your lands and tap an <b>adjacent enemy land</b> to attack it. Only a land with <b>two or more dice</b> can attack.',
      'dice.rule2': 'Both sides <b>roll every die and compare the totals.</b> The attacker must be <b>strictly higher</b> to win — a tie goes to the defender. The rolls appear on the board with the <b>attacker on top and the defender below</b>.',
      'dice.rule3': 'Win and you take that land, moving your dice over and <b>leaving one behind</b>. Lose and the attacking land drops to <b>a single die</b>.',
      'dice.rule4': 'Every land you can attack from the selected one shows your <b>odds of winning</b>. Play the numbers.',
      'dice.rule5': 'When you end your turn you receive dice equal to the <b>size of your largest connected block of lands</b>, dropped at random on your lands. <b>Keeping your lands joined up beats spreading out.</b> Lands already at eight are skipped, and dice with nowhere to go are saved for next turn.',
      'dice.rule6': 'Because <b>going first is an advantage</b>, later players start with a few extra dice. You always move first, so the opponents get them — 6 in a two-player game, 3 and 4 with three, and 1, 2 and 2 with four.',
      'dice.rule7': 'Lose every land and you are out. <b>The last one standing wins.</b>',
      'dice.rule8': 'You can change the <b>difficulty</b> at any time without starting a new game.'
    },
    ja: {
      'meta.desc': 'サイコロを振って隣の領地を奪い、いちばん大きな塊の分だけ補給を受けるターン制戦略ゲーム',
      'dice.map': '領地マップ',
      'dice.territory': '領地',
      'dice.endTurn': 'ターン終了',
      'dice.endTurnGain': 'ターン終了 · サイコロ{gain}個を受け取る',
      'dice.foeTurn': '相手の番…',
      'dice.myTurn': '自分の番です。攻める領地を選んでください。',
      'dice.myTurnShort': '自分の番です。',
      'dice.won': '勝ちました',
      'dice.blocked': '防がれました',
      'dice.rollScore': '{attack} 対 {defend} · ',
      'dice.describe': '{attack} 対 {defend} · <b>{outcome}</b>',
      'dice.attacking': '{before}個で{against}個を攻めます…',
      'dice.attacked': '{before}個で{against}個を攻めます — {result}',
      'dice.gained': 'サイコロ{gain}個を受け取りました。',
      'dice.needTwo': 'サイコロが一つだけの領地からは攻められません。',
      'dice.foeThinking': '<b>{n}番</b>が考え中…',
      'dice.foeGained': '<b>{n}番</b>がサイコロ{gain}個を受け取りました。',
      'dice.foeAttacking': '<b>{n}番</b>が{dice}個で{against}個を攻めます…',
      'dice.foeAttacked': '<b>{n}番</b>の攻撃 — {result}',
      'dice.allYours': 'すべて取りました',
      'dice.lost': '負けました',
      'dice.lastStanding': '最後まで残りました。',
      'dice.foeLastStanding': '{n}番が最後まで残りました。',
      'dice.rule1': '自分の領地を選び、<b>隣り合う相手の領地</b>を押すと攻めます。サイコロが<b>二つ以上</b>の領地だけが攻められます。',
      'dice.rule2': '双方のサイコロを<b>すべて振って合計を比べます。</b>攻める側が<b>より大きい</b>ときだけ勝ちます — 同じなら守る側の勝ちです。出目は盤の上に<b>上が攻め、下が守り</b>で表示されます。',
      'dice.rule3': '勝てばその領地を得て、攻めた領地のサイコロを<b>一つだけ残して</b>移します。負ければ攻めた領地が<b>一つに</b>減ります。',
      'dice.rule4': '選んだ領地から攻められる先には<b>勝つ確率</b>が出ます。数字を見て決めましょう。',
      'dice.rule5': 'ターンを終えると<b>つながった自分の領地でいちばん大きな塊の大きさだけ</b>サイコロを受け取り、自分の領地に無作為に載せます。広く散らすより<b>つなげる方が得</b>です。八つ埋まった領地は飛ばし、置き場がなければ次に持ち越します。',
      'dice.rule6': '<b>先に攻める側が有利な遊び</b>なので、後の番ほど少し多くサイコロを持って始めます。自分が必ず先攻なので、その分を相手が受け取ります — 2人なら6個、3人なら3・4個、4人なら1・2・2個です。',
      'dice.rule7': '領地をすべて失うと脱落し、<b>最後まで残れば勝ちです。</b>',
      'dice.rule8': '<b>難易度</b>は盤を作り直さずいつでも変えられます。'
    },
    'zh-CN': {
      'meta.desc': '掷骰子抢下相邻地盘，按最大连片地块获得补给的回合制策略游戏',
      'dice.map': '地盘地图',
      'dice.territory': '地盘',
      'dice.endTurn': '结束回合',
      'dice.endTurnGain': '结束回合 · 领 {gain} 颗骰子',
      'dice.foeTurn': '对手的回合…',
      'dice.myTurn': '轮到你了，选一块地出兵。',
      'dice.myTurnShort': '轮到你了。',
      'dice.won': '赢了',
      'dice.blocked': '被挡住',
      'dice.rollScore': '{attack} 对 {defend} · ',
      'dice.describe': '{attack} 对 {defend} · <b>{outcome}</b>',
      'dice.attacking': '用 {before} 颗打 {against} 颗…',
      'dice.attacked': '用 {before} 颗打 {against} 颗 —— {result}',
      'dice.gained': '领到了 {gain} 颗骰子。',
      'dice.needTwo': '只有一颗骰子的地盘不能出兵。',
      'dice.foeThinking': '<b>{n} 号</b>在想…',
      'dice.foeGained': '<b>{n} 号</b>领到了 {gain} 颗骰子。',
      'dice.foeAttacking': '<b>{n} 号</b>用 {dice} 颗打 {against} 颗…',
      'dice.foeAttacked': '<b>{n} 号</b>的进攻 —— {result}',
      'dice.allYours': '全部拿下',
      'dice.lost': '输了',
      'dice.lastStanding': '你撑到了最后。',
      'dice.foeLastStanding': '{n} 号撑到了最后。',
      'dice.rule1': '选中自己的地盘，再点<b>相邻的敌方地盘</b>就开打。只有骰子<b>两颗以上</b>的地盘才能出兵。',
      'dice.rule2': '双方<b>把骰子全部掷出比总和。</b>进攻方<b>必须更大</b>才算赢 —— 打平算守方赢。骰子点数会显示在盘面上，<b>上面是进攻方，下面是防守方</b>。',
      'dice.rule3': '赢了就拿下那块地，并把出兵地的骰子<b>只留一颗</b>其余搬过去。输了，出兵的那块地<b>只剩一颗</b>。',
      'dice.rule4': '从选中的地盘能打的目标上会显示<b>胜率</b>，看着数字下手就行。',
      'dice.rule5': '结束回合时，你会按<b>自己相连地盘中最大一块的大小</b>领到骰子，随机放到自己的地盘上。<b>连成一片比铺得广更划算。</b>已经满八颗的地盘会跳过，放不下的骰子留到下回合。',
      'dice.rule6': '因为<b>先手有利</b>，越靠后的玩家开局骰子越多。你永远先手，所以这些骰子归对手 —— 两人局 6 颗，三人局 3、4 颗，四人局 1、2、2 颗。',
      'dice.rule7': '地盘全丢就出局，<b>撑到最后的人赢。</b>',
      'dice.rule8': '<b>难度</b>随时可以改，不用重开一局。'
    },
    'zh-TW': {
      'meta.desc': '擲骰子搶下相鄰地盤，按最大連片地塊獲得補給的回合制策略遊戲',
      'dice.map': '地盤地圖',
      'dice.territory': '地盤',
      'dice.endTurn': '結束回合',
      'dice.endTurnGain': '結束回合 · 領 {gain} 顆骰子',
      'dice.foeTurn': '對手的回合…',
      'dice.myTurn': '輪到你了，選一塊地出兵。',
      'dice.myTurnShort': '輪到你了。',
      'dice.won': '贏了',
      'dice.blocked': '被擋住',
      'dice.rollScore': '{attack} 對 {defend} · ',
      'dice.describe': '{attack} 對 {defend} · <b>{outcome}</b>',
      'dice.attacking': '用 {before} 顆打 {against} 顆…',
      'dice.attacked': '用 {before} 顆打 {against} 顆 —— {result}',
      'dice.gained': '領到了 {gain} 顆骰子。',
      'dice.needTwo': '只有一顆骰子的地盤不能出兵。',
      'dice.foeThinking': '<b>{n} 號</b>在想…',
      'dice.foeGained': '<b>{n} 號</b>領到了 {gain} 顆骰子。',
      'dice.foeAttacking': '<b>{n} 號</b>用 {dice} 顆打 {against} 顆…',
      'dice.foeAttacked': '<b>{n} 號</b>的進攻 —— {result}',
      'dice.allYours': '全部拿下',
      'dice.lost': '輸了',
      'dice.lastStanding': '你撐到了最後。',
      'dice.foeLastStanding': '{n} 號撐到了最後。',
      'dice.rule1': '選取自己的地盤，再點<b>相鄰的敵方地盤</b>就開打。只有骰子<b>兩顆以上</b>的地盤才能出兵。',
      'dice.rule2': '雙方<b>把骰子全部擲出比總和。</b>進攻方<b>必須更大</b>才算贏 —— 打平算守方贏。骰子點數會顯示在盤面上，<b>上面是進攻方，下面是防守方</b>。',
      'dice.rule3': '贏了就拿下那塊地，並把出兵地的骰子<b>只留一顆</b>其餘搬過去。輸了，出兵的那塊地<b>只剩一顆</b>。',
      'dice.rule4': '從選取的地盤能打的目標上會顯示<b>勝率</b>，看著數字下手就行。',
      'dice.rule5': '結束回合時，你會按<b>自己相連地盤中最大一塊的大小</b>領到骰子，隨機放到自己的地盤上。<b>連成一片比鋪得廣更划算。</b>已經滿八顆的地盤會跳過，放不下的骰子留到下回合。',
      'dice.rule6': '因為<b>先手有利</b>，越靠後的玩家開局骰子越多。你永遠先手，所以這些骰子歸對手 —— 兩人局 6 顆，三人局 3、4 顆，四人局 1、2、2 顆。',
      'dice.rule7': '地盤全丟就出局，<b>撐到最後的人贏。</b>',
      'dice.rule8': '<b>難度</b>隨時可以改，不用重開一局。'
    },
    es: {
      'meta.desc': 'Estrategia por turnos: tira los dados para quitar territorios vecinos y recibe refuerzos según tu mayor bloque conectado',
      'dice.map': 'Mapa de territorios',
      'dice.territory': 'Territorios',
      'dice.endTurn': 'Terminar turno',
      'dice.endTurnGain': 'Terminar turno · recibir {gain} dados',
      'dice.foeTurn': 'Turno del rival…',
      'dice.myTurn': 'Tu turno. Elige desde qué territorio atacar.',
      'dice.myTurnShort': 'Tu turno.',
      'dice.won': 'ganas',
      'dice.blocked': 'aguantan',
      'dice.rollScore': '{attack} contra {defend} · ',
      'dice.describe': '{attack} contra {defend} · <b>{outcome}</b>',
      'dice.attacking': 'Atacas {against} con {before}…',
      'dice.attacked': 'Atacas {against} con {before} — {result}',
      'dice.gained': 'Has recibido {gain} dados.',
      'dice.needTwo': 'Un territorio con un solo dado no puede atacar.',
      'dice.foeThinking': '<b>Jugador {n}</b> está pensando…',
      'dice.foeGained': '<b>Jugador {n}</b> ha recibido {gain} dados.',
      'dice.foeAttacking': '<b>Jugador {n}</b> ataca {against} con {dice}…',
      'dice.foeAttacked': 'Ataque de <b>jugador {n}</b> — {result}',
      'dice.allYours': 'Todo el mapa es tuyo',
      'dice.lost': 'Has perdido',
      'dice.lastStanding': 'Fuiste el último en pie.',
      'dice.foeLastStanding': 'El jugador {n} fue el último en pie.',
      'dice.rule1': 'Selecciona un territorio tuyo y toca un <b>territorio enemigo contiguo</b> para atacarlo. Solo puede atacar un territorio con <b>dos dados o más</b>.',
      'dice.rule2': 'Ambos bandos <b>tiran todos sus dados y comparan la suma.</b> El atacante debe sacar <b>estrictamente más</b> para ganar: el empate es del defensor. Las tiradas salen en el tablero con el <b>atacante arriba y el defensor abajo</b>.',
      'dice.rule3': 'Si ganas te quedas ese territorio y trasladas tus dados <b>dejando uno atrás</b>. Si pierdes, el territorio atacante baja a <b>un solo dado</b>.',
      'dice.rule4': 'Cada objetivo al alcance del territorio elegido muestra tu <b>probabilidad de ganar</b>. Juega con los números.',
      'dice.rule5': 'Al terminar el turno recibes tantos dados como el <b>tamaño de tu mayor bloque de territorios conectados</b>, repartidos al azar entre los tuyos. <b>Mantenerlos unidos rinde más que dispersarse.</b> Los territorios con ocho se saltan, y los dados que no caben se guardan para el turno siguiente.',
      'dice.rule6': 'Como <b>atacar primero es una ventaja</b>, los jugadores posteriores empiezan con algunos dados de más. Tú siempre sales primero, así que esos dados van al rival: 6 a dos jugadores, 3 y 4 a tres, y 1, 2 y 2 a cuatro.',
      'dice.rule7': 'Quien pierde todos sus territorios queda eliminado. <b>Gana el último en pie.</b>',
      'dice.rule8': 'Puedes cambiar la <b>dificultad</b> en cualquier momento sin empezar de nuevo.'
    }
  });
})();
