// 이 게임에만 나오는 문구. 게임 이름과 공통 단추는 shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '곡선과 직선이 섞인 도시의 도로 위로 자동차·택시·버스·트럭·오토바이가 실시간으로 오간다',
      'road.onRoad': '주행',
      'road.avgSpeed': '평균 속도',
      'road.left': '시외로',
      'road.pause': '멈춤',
      'road.play': '시작',
      'road.rate': '빠르기',
      'road.newCity': '새 도시',
      'road.rule1': '지금은 <b>도로 위를 차가 달리는 것</b>까지 만들어져 있습니다. 도로를 놓고 고치는 조작은 아직 없습니다.',
      'road.rule2': '도시의 길은 <b>곧은 길과 굽은 길이 섞여</b> 있고, 길마다 <b>1~4차로</b>입니다. 가운데 노란 선이 마주 오는 방향을 가르고, 흰 점선이 같은 방향의 차로를 가릅니다.',
      'road.rule3': '<b>우측 통행</b>입니다. 차는 제 진행 방향에서 오른쪽 차로를 씁니다.',
      'road.rule4': '맵 가장자리의 점선은 <b>다른 도시로 이어지는 관문</b>입니다. 차는 거기서 들어와 다른 관문으로 빠져나갑니다.',
      'road.rule5': '달리는 것은 <b>자동차·택시·버스·트럭·오토바이</b> 다섯입니다. 길이도 속도도 가속도 저마다 달라서, 트럭 뒤에 승용차가 물리면 줄이 길어집니다.',
      'road.rule6': '앞차와의 거리에 따라 <b>알아서 서고 다시 나갑니다</b>. 신호가 아직 없어 교차로는 <b>먼저 닿은 차가 하나씩</b> 지납니다.'
    },
    en: {
      'meta.desc': 'Cars, taxis, buses, trucks and motorcycles drive in real time across a city of straight and curved roads',
      'road.onRoad': 'Driving',
      'road.avgSpeed': 'Avg speed',
      'road.left': 'Left town',
      'road.pause': 'Pause',
      'road.play': 'Play',
      'road.rate': 'Speed',
      'road.newCity': 'New city',
      'road.rule1': 'So far this is <b>traffic driving on the roads</b>. Building and editing roads is not in yet.',
      'road.rule2': 'The city mixes <b>straight and curved roads</b>, each with <b>one to four lanes</b>. The yellow line splits opposing directions; white dashes split lanes going the same way.',
      'road.rule3': 'Traffic <b>drives on the right</b>. Each vehicle uses the lanes on its own right-hand side.',
      'road.rule4': 'The dashed bars at the edge of the map are <b>gates to other cities</b>. Vehicles enter there and leave by another gate.',
      'road.rule5': 'Five kinds drive here: <b>car, taxi, bus, truck and motorcycle</b>. They differ in length, speed and acceleration, so a car stuck behind a truck makes a queue.',
      'road.rule6': 'They <b>slow down and pull away on their own</b> from the gap ahead. There are no signals yet, so a junction lets <b>one vehicle through at a time</b>.'
    },
    ja: {
      'meta.desc': '直線と曲線が混ざった街の道路を、乗用車・タクシー・バス・トラック・バイクがリアルタイムで走る',
      'road.onRoad': '走行',
      'road.avgSpeed': '平均速度',
      'road.left': '市外へ',
      'road.pause': '停止',
      'road.play': '再生',
      'road.rate': '速さ',
      'road.newCity': '新しい街',
      'road.rule1': '今は<b>道路の上を車が走るところ</b>までです。道路を引いたり直したりする操作はまだありません。',
      'road.rule2': '街の道は<b>直線と曲線が混ざり</b>、道ごとに<b>1〜4車線</b>です。中央の黄色い線が対向方向を分け、白い破線が同じ方向の車線を分けます。',
      'road.rule3': '<b>右側通行</b>です。車は進行方向の右側の車線を使います。',
      'road.rule4': '地図の縁の破線は<b>別の街へつながる出入口</b>です。車はそこから入り、別の出入口から出ていきます。',
      'road.rule5': '走るのは<b>乗用車・タクシー・バス・トラック・バイク</b>の五種です。長さも速度も加速も違うので、トラックの後ろに乗用車がつくと列ができます。',
      'road.rule6': '前の車との距離に応じて<b>自分で止まり、また走り出します</b>。信号はまだないので、交差点は<b>先に着いた車から一台ずつ</b>通ります。'
    },
    'zh-CN': {
      'meta.desc': '轿车、出租车、公交车、卡车和摩托车在直路与弯路交错的城市里实时行驶',
      'road.onRoad': '行驶中',
      'road.avgSpeed': '平均车速',
      'road.left': '驶出城外',
      'road.pause': '暂停',
      'road.play': '播放',
      'road.rate': '速度',
      'road.newCity': '新城市',
      'road.rule1': '目前做到<b>车辆在道路上行驶</b>为止，修路和改路的操作还没有。',
      'road.rule2': '城里的路<b>直路与弯路交错</b>，每条路<b>一到四条车道</b>。中间的黄线分开对向，白色虚线分开同向车道。',
      'road.rule3': '<b>靠右行驶</b>。车辆走自己前进方向右侧的车道。',
      'road.rule4': '地图边缘的虚线是<b>通往其他城市的出入口</b>。车从那里进来，再从别的出入口离开。',
      'road.rule5': '路上跑着<b>轿车、出租车、公交车、卡车和摩托车</b>五种。长度、速度、加速度各不相同，轿车堵在卡车后面就会排起长队。',
      'road.rule6': '它们会按前车的距离<b>自己刹车、自己起步</b>。目前还没有信号灯，路口<b>先到的车一辆一辆</b>通过。'
    },
    'zh-TW': {
      'meta.desc': '轎車、計程車、公車、卡車和機車在直路與彎路交錯的城市裡即時行駛',
      'road.onRoad': '行駛中',
      'road.avgSpeed': '平均車速',
      'road.left': '駛出城外',
      'road.pause': '暫停',
      'road.play': '播放',
      'road.rate': '速度',
      'road.newCity': '新城市',
      'road.rule1': '目前做到<b>車輛在道路上行駛</b>為止，鋪路和改路的操作還沒有。',
      'road.rule2': '城裡的路<b>直路與彎路交錯</b>，每條路<b>一到四條車道</b>。中間的黃線分開對向，白色虛線分開同向車道。',
      'road.rule3': '<b>靠右行駛</b>。車輛走自己前進方向右側的車道。',
      'road.rule4': '地圖邊緣的虛線是<b>通往其他城市的出入口</b>。車從那裡進來，再從別的出入口離開。',
      'road.rule5': '路上跑著<b>轎車、計程車、公車、卡車和機車</b>五種。長度、速度、加速度各不相同，轎車卡在卡車後面就會排起長隊。',
      'road.rule6': '它們會依前車的距離<b>自己煞車、自己起步</b>。目前還沒有號誌，路口<b>先到的車一輛一輛</b>通過。'
    },
    es: {
      'meta.desc': 'Coches, taxis, autobuses, camiones y motos circulan en tiempo real por una ciudad de calles rectas y curvas',
      'road.onRoad': 'Circulando',
      'road.avgSpeed': 'Vel. media',
      'road.left': 'Salieron',
      'road.pause': 'Pausa',
      'road.play': 'Seguir',
      'road.rate': 'Velocidad',
      'road.newCity': 'Nueva ciudad',
      'road.rule1': 'Por ahora hay <b>tráfico circulando por las calles</b>. Construir y editar carreteras todavía no está.',
      'road.rule2': 'La ciudad mezcla <b>calles rectas y curvas</b>, cada una con <b>de uno a cuatro carriles</b>. La línea amarilla separa los sentidos; las rayas blancas separan carriles del mismo sentido.',
      'road.rule3': 'Se <b>circula por la derecha</b>. Cada vehículo usa los carriles de su propia derecha.',
      'road.rule4': 'Las barras discontinuas del borde del mapa son <b>accesos a otras ciudades</b>. Los vehículos entran por ahí y salen por otro acceso.',
      'road.rule5': 'Circulan cinco tipos: <b>coche, taxi, autobús, camión y moto</b>. Cambian en largo, velocidad y aceleración, así que un coche detrás de un camión forma cola.',
      'road.rule6': 'Frenan y arrancan <b>solos</b> según el hueco que tienen delante. Todavía no hay semáforos, así que en un cruce pasa <b>un vehículo cada vez</b>.'
    }
  });
})();
