// 이 게임에만 나오는 문구. 게임 이름과 공통 단추는 shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '실시간으로 오가는 차들의 길을 놓고 다듬어, 시간 안에 배달을 성공시킨다',
      'road.onRoad': '주행',
      'road.avgSpeed': '평균 속도',
      'road.left': '시외로',
      'road.pause': '멈춤',
      'road.play': '시작',
      'road.rate': '빠르기',
      'road.newCity': '새 도시',
      'road.ctrlNone': '신호 없음',
      'road.ctrlSignal': '신호등',
      'road.ctrlCircle': '회전교차로',
      'road.rule1': '<b>교차로를 누르면</b> 아래에서 신호 없음·신호등·회전교차로를 고르고, 신호등은 <b>현시 구성</b>과 <b>횡단보도</b>까지 정합니다. <b>도로를 누르면</b> 차로마다 좌회전·직진·우회전·유턴을 켜고 끄고, <b>방향을 바꾸거나 차로를 늘립니다</b>.',
      'road.rule2': '도시의 길은 <b>곧은 길과 굽은 길이 섞여</b> 있고, 길마다 <b>1~8차로</b>입니다. 가운데 노란 선이 마주 오는 방향을 가르고, 흰 점선이 같은 방향의 차로를 가릅니다. <b>이어진 길은 굽이가 끊기지 않습니다.</b>',
      'road.rule3': '<b>우측 통행</b>입니다. 차는 제 진행 방향에서 오른쪽 차로를 씁니다.',
      'road.rule4': '맵 가장자리의 점선은 <b>다른 도시로 이어지는 관문</b>입니다. 차는 거기서 들어와 다른 관문으로 빠져나가고, <b>길가의 건물에서 나와 다른 건물로 들기도 합니다</b>.',
      'road.rule5': '달리는 것은 <b>자동차·택시·버스·트럭·오토바이</b> 다섯입니다. 길이도 속도도 가속도 저마다 달라서, 트럭 뒤에 승용차가 물리면 줄이 길어집니다.',
      'road.rule6': '앞차와의 거리에 따라 <b>알아서 서고 다시 나갑니다</b>.',
      'road.rule7': '<b>지나는 길이 서로 가로지르는 자리만 교차로입니다</b> — 중앙선을 넘는 이동이 하나도 없으면(이를테면 일방통행 곁길에 마주편 좌회전을 끄면) 교차로가 아니고 아무도 기다리지 않습니다. 아무것도 놓지 않은 교차로는 <b>먼저 닿은 차가 하나씩</b> 지납니다. <b>신호등</b>은 2현시면 마주 보는 두 갈래를 함께 열고(좌회전만 틈을 기다립니다), 갈래 수만큼의 현시면 한 갈래씩 엽니다. 기다리는 차가 없는 갈래는 건너뜁니다. <b>회전교차로</b>는 도는 차가 먼저이고 들어가려는 차가 틈을 기다립니다.',
      'road.junction': '교차로',
      'road.phase2': '2현시',
      'road.phaseN': '{n}현시',
      'road.crosswalk': '횡단보도',
      'road.lanesOf': '{n}차로',
      'road.rule8': '<b>차로 바닥의 화살표</b>가 그 차로에서 갈 수 있는 곳입니다. 좌회전 차로를 없애면 그 길로 가려던 차가 <b>다른 길로 돌아갑니다</b>.',
      'road.rule9': '<b>횡단보도</b>를 놓으면 사람이 건넙니다. 신호가 있으면 빨간 불일 때, 없으면 차가 뜸할 때 건너고, 건너는 사람이 있으면 차가 섭니다.',
      'road.money': '예산',
      'road.flip': '방향 바꾸기',
      'road.addLane': '차로 늘리기',
      'road.rule10': '<b>차로를 늘리는 데는 돈이 듭니다</b>(긴 길일수록 비쌉니다). 돈은 <b>차가 시외로 빠져나갈 때마다</b> 들어오니, 막힌 곳을 풀어야 다음 공사를 할 수 있습니다. 방향을 바꾸는 것은 선만 다시 긋는 일이라 값이 없습니다.',
      'road.newRoad': '새 길',
      'road.build': '놓기',
      'road.cancel': '취소',
      'road.draftHint': '<b>가운데 손잡이를 끌어</b> 굽이를 고칠 수 있습니다. 놓으면 1차로짜리 일방통행으로 생기고, 그 길을 눌러 차로를 늘릴 수 있습니다.',
      'road.toEdge': '<b>도시 밖으로 빠지는 길</b>입니다. 맵 가장자리에 관문이 새로 나고, 차가 그리로 드나듭니다.',
      'road.tooShort': '너무 짧습니다. 손잡이를 끌어 길게 굽히거나 취소하세요.',
      'road.tooDear': '예산이 모자랍니다. 차가 시외로 빠져나가면 채워집니다.',
      'road.laneFull': '이미 {n}차로입니다. 한 길에 둘 수 있는 가장 많은 차로입니다.',
      'road.rule11': '<b>길 위의 아무 데서나 다른 길까지 끌면</b> 새 길이 생깁니다. 끌기를 마치면 값이 나오고, 그때 <b>가운데 손잡이를 끌어 굽이를 고친 뒤</b> 놓거나 취소합니다. 끌기를 시작한 자리와 끝낸 자리, 그리고 <b>지나가며 가로지른 길마다 교차로가 새로 납니다</b>. <b>맵 가장자리까지 끌면 관문이 새로 나서</b> 도시 밖으로 빠지는 길이 됩니다.',
      'road.rule12': '<b>판은 도시의 한 조각만 비춥니다.</b> 빈 땅을 끌면 둘러보고, 손가락 둘을 벌리거나 오므리면(마우스는 휠) 크기를 바꿉니다. 길 위에서 끄는 것은 새 길을 놓는 것이라, 옮겨 볼 때는 길이 없는 곳을 잡거나 손가락 둘을 함께 움직이세요.',
      'road.onBuilding': '건물 위로는 지나갈 수 없습니다. 손잡이를 끌어 비켜 가세요.',
      'road.tunnelBit': '터널 {n}',
      'road.bridgeBit': '다리 {n}',
      'road.join': ' · ',
      'road.rule13': '빈 땅에는 <b>건물·산·강·호수</b>가 있습니다. <b>건물 위로는 길을 낼 수 없고</b>, 산은 <b>터널</b>을, 강과 호수는 <b>다리</b>를 놓고 지나므로 그만큼 값이 더 듭니다.',
      'road.missionOn': '배달 중',
      'road.missionFind': '보기',
      'road.missionDone': '배달 성공',
      'road.missionLost': '배달 취소',
      'road.overTitle': '늦었습니다',
      'road.overNote': '배달 {n}번 성공 · 남은 예산 {money}',
      'road.rule14': '<b>이따금 배달 미션이 붙습니다.</b> 관문 하나에서 다른 관문까지 <b>정해진 시간 안에</b> 그 차를 보내야 하고, 늦으면 <b>거기서 게임이 끝납니다</b>. 닿으면 <b>삯을 더 받습니다</b>. 미션 차는 판 위에 테두리로 표시되고, 화면 밖에 있으면 가장자리의 화살표가 가리킵니다.',
      'road.rule15': '<b>도시는 자랍니다.</b> 처음에는 큰길 하나가 가로, 하나가 세로로 있을 뿐이지만 시간이 지날수록 <b>통행량이 늘고 길가에 건물이 들어섭니다</b>. 길을 놓으면 그 둘레가 도시가 되고, 가만히 두면 언젠가 반드시 막힙니다.',
    },
    en: {
      'meta.desc': 'Cars, taxis, buses, trucks and motorcycles drive in real time across a city of straight and curved roads',
      'road.onRoad': 'Driving',
      'road.avgSpeed': 'Avg speed',
      'road.left': 'Left town',
      'road.pause': 'Pause',
      'road.play': 'Play',
      'road.rate': 'Speed',
      'road.newCity': 'New city',
      'road.ctrlNone': 'No signal',
      'road.ctrlSignal': 'Signal',
      'road.ctrlCircle': 'Roundabout',
      'road.rule1': '<b>Tap a junction</b> to choose below between no signal, a traffic signal or a roundabout; a signal also takes a <b>phase plan</b> and a <b>crosswalk</b>. <b>Tap a road</b> to turn left, through, right and U-turn on or off per lane, to <b>send a lane the other way</b> or to <b>add a lane</b>.',
      'road.rule2': 'The city mixes <b>straight and curved roads</b>, each with <b>one to eight lanes</b>. The yellow line splits opposing directions; white dashes split lanes going the same way. <b>A road that runs on keeps its curve unbroken.</b>',
      'road.rule3': 'Traffic <b>drives on the right</b>. Each vehicle uses the lanes on its own right-hand side.',
      'road.rule4': 'The dashed bars at the edge of the map are <b>gates to other cities</b>. Vehicles come in and out through them, and they also <b>set off from a building on the street and pull up at another</b>.',
      'road.rule5': 'Five kinds drive here: <b>car, taxi, bus, truck and motorcycle</b>. They differ in length, speed and acceleration, so a car stuck behind a truck makes a queue.',
      'road.rule6': 'They <b>slow down and pull away on their own</b> from the gap ahead.',
      'road.rule7': '<b>Only places where paths actually cross are junctions</b> — if nothing has to cross the centre line (say a one-way side road with the opposing left turn switched off), it is not a junction and nobody waits. An uncontrolled junction lets <b>one vehicle through at a time</b>. A <b>signal</b> on two phases opens the two facing approaches together (only left turns wait for a gap); on one phase per approach it opens them one at a time. Either way it skips an approach with nobody waiting. At a <b>roundabout</b> the traffic already circling has priority.',
      'road.junction': 'Junction',
      'road.phase2': '2 phases',
      'road.phaseN': '{n} phases',
      'road.crosswalk': 'Crosswalk',
      'road.lanesOf': '{n} lanes',
      'road.rule8': 'The <b>arrows painted on a lane</b> are where that lane may go. Take away the left-turn lane and the traffic that wanted it <b>goes round another way</b>.',
      'road.rule9': 'Put down a <b>crosswalk</b> and people use it. They cross on red where there is a signal, and in a gap where there is not; vehicles stop for anyone already crossing.',
      'road.money': 'Budget',
      'road.flip': 'Flip way',
      'road.addLane': 'Add lane',
      'road.rule10': '<b>Adding a lane costs money</b> (a longer road costs more). Money comes in <b>every time a vehicle leaves town</b>, so you have to keep things moving to afford the next job. Flipping a lane is only repainting, so it is free.',
      'road.newRoad': 'New road',
      'road.build': 'Build',
      'road.cancel': 'Cancel',
      'road.draftHint': '<b>Drag the handle</b> in the middle to bend it. It goes down as a one-way single lane; select it afterwards to add lanes.',
      'road.toEdge': 'This road <b>runs out of town</b>. A new gate appears at the edge of the map and traffic comes and goes through it.',
      'road.tooShort': 'Too short. Bend it longer with the handle, or cancel.',
      'road.tooDear': 'Not enough budget. It fills up as vehicles leave town.',
      'road.laneFull': 'Already {n} lanes, the most a road can have.',
      'road.rule11': '<b>Drag from anywhere on a road to another road</b> to lay a new one. Let go and the price appears; <b>bend it with the handle in the middle</b>, then build or cancel. <b>New junctions appear</b> where the drag started and ended, and at every road it crosses along the way. <b>Drag all the way to the edge of the map</b> and a new gate opens there, running the road out of town.',
      'road.rule12': '<b>The board shows one corner of the city.</b> Drag empty ground to look around, pinch (or use the wheel) to change the scale. Dragging <em>on</em> a road lays a new one, so grab open ground — or move two fingers together — when you just want to move the view.',
      'road.onBuilding': 'A road cannot run through a building. Bend it aside with the handle.',
      'road.tunnelBit': 'tunnel {n}',
      'road.bridgeBit': 'bridge {n}',
      'road.join': ' · ',
      'road.rule13': 'Open ground holds <b>buildings, hills, rivers and lakes</b>. <b>No road can cross a building</b>; hills are bored as a <b>tunnel</b> and water is spanned by a <b>bridge</b>, and both cost extra.',
      'road.missionOn': 'delivering',
      'road.missionFind': 'Find',
      'road.missionDone': 'delivered',
      'road.missionLost': 'call off',
      'road.overTitle': 'Too late',
      'road.overNote': '{n} deliveries made · {money} left in the budget',
      'road.rule14': '<b>Now and then a delivery comes in.</b> That vehicle has to get from one gate to another <b>within the time given</b>; miss it and <b>the game ends there</b>. Make it and you <b>earn a bonus</b>. The vehicle carries a ring on the board, and an arrow at the edge points to it when it is off screen.',
      'road.rule15': '<b>The city grows.</b> You start with one main road each way, and as time passes <b>traffic climbs and buildings fill in along the streets</b>. Lay a road and the city grows around it; leave it alone and it will jam sooner or later.',
    },
    ja: {
      'meta.desc': '直線と曲線が混ざった街の道路を、乗用車・タクシー・バス・トラック・バイクがリアルタイムで走る',
      'road.onRoad': '走行',
      'road.avgSpeed': '平均速度',
      'road.left': '市外へ',
      'road.pause': '停止',
      'road.play': '再生',
      'road.rate': '速さ',
      'road.newCity': '新しい街',
      'road.ctrlNone': '信号なし',
      'road.ctrlSignal': '信号',
      'road.ctrlCircle': 'ラウンドアバウト',
      'road.rule1': '<b>交差点を押すと</b>下で信号なし・信号・ラウンドアバウトを選べます。信号では<b>現示の組み方</b>と<b>横断歩道</b>も決めます。<b>道路を押すと</b>車線ごとに左折・直進・右折・Uターンを切り替え、<b>向きを変えたり車線を増やしたり</b>できます。',
      'road.rule2': '街の道は<b>直線と曲線が混ざり</b>、道ごとに<b>1〜8車線</b>です。中央の黄色い線が対向方向を分け、白い破線が同じ方向の車線を分けます。<b>つながった道は曲がり具合が途切れません。</b>',
      'road.rule3': '<b>右側通行</b>です。車は進行方向の右側の車線を使います。',
      'road.rule4': '地図の縁の破線は<b>別の街へつながる出入口</b>です。車はそこから出入りするほか、<b>道沿いの建物から出て別の建物に入る</b>車もあります。',
      'road.rule5': '走るのは<b>乗用車・タクシー・バス・トラック・バイク</b>の五種です。長さも速度も加速も違うので、トラックの後ろに乗用車がつくと列ができます。',
      'road.rule6': '前の車との距離に応じて<b>自分で止まり、また走り出します</b>。',
      'road.rule7': '<b>進む道どうしが交わる所だけが交差点です</b> — 中央線を越える動きが一つもなければ（たとえば一方通行の枝道で対向の右折を切れば）交差点ではなく、誰も待ちません。何も置いていない交差点は<b>先に着いた車から一台ずつ</b>通ります。<b>信号</b>は2現示なら向かい合う二つの方向を一緒に開け（左折だけが切れ目を待ちます）、方向の数だけの現示なら一方向ずつ開けます。どちらも待つ車がいない方向は飛ばします。<b>ラウンドアバウト</b>は回っている車が優先です。',
      'road.junction': '交差点',
      'road.phase2': '2現示',
      'road.phaseN': '{n}現示',
      'road.crosswalk': '横断歩道',
      'road.lanesOf': '{n}車線',
      'road.rule8': '<b>車線に描かれた矢印</b>がその車線から行ける先です。左折車線をなくすと、そこを通るはずだった車が<b>別の道へ回ります</b>。',
      'road.rule9': '<b>横断歩道</b>を置くと人が渡ります。信号があれば赤のときに、なければ車の切れ目で渡り、渡っている人がいれば車が止まります。',
      'road.money': '予算',
      'road.flip': '向きを変える',
      'road.addLane': '車線を増やす',
      'road.rule10': '<b>車線を増やすにはお金がかかります</b>（長い道ほど高くなります）。お金は<b>車が市外へ出るたび</b>に入るので、詰まりを解かないと次の工事ができません。向きを変えるのは線を引き直すだけなので無料です。',
      'road.newRoad': '新しい道',
      'road.build': '敷く',
      'road.cancel': '取消',
      'road.draftHint': '<b>真ん中のつまみを引いて</b>曲がりを直せます。敷くと1車線の一方通行になり、その道を押せば車線を増やせます。',
      'road.toEdge': '<b>街の外へ抜ける道</b>です。地図の縁に新しい出入口ができ、車がそこを出入りします。',
      'road.tooShort': '短すぎます。つまみを引いて長く曲げるか、取り消してください。',
      'road.tooDear': '予算が足りません。車が市外へ出れば貯まります。',
      'road.laneFull': 'すでに{n}車線です。1本の道に置ける最大です。',
      'road.rule11': '<b>道の上のどこからでも別の道まで引けば</b>新しい道ができます。引き終えると値段が出るので、<b>真ん中のつまみで曲がりを直してから</b>敷くか取り消します。引き始めた所と終えた所、そして<b>途中で横切った道ごとに新しい交差点ができます</b>。<b>地図の縁まで引くと新しい出入口ができ</b>、街の外へ抜ける道になります。',
      'road.rule12': '<b>盤は街の一部だけを映します。</b>何もない地面をドラッグすると見て回れ、指二本を広げたり狭めたり（マウスはホイール）すると縮尺が変わります。道の上でのドラッグは新しい道を敷く操作なので、動かすだけなら道のない所をつかむか指二本を一緒に動かしてください。',
      'road.onBuilding': '建物の上は通せません。つまみを引いて避けてください。',
      'road.tunnelBit': 'トンネル{n}',
      'road.bridgeBit': '橋{n}',
      'road.join': '・',
      'road.rule13': '空き地には<b>建物・山・川・湖</b>があります。<b>建物の上に道は通せません</b>。山は<b>トンネル</b>、川と湖は<b>橋</b>で越えるので、その分だけ高くつきます。',
      'road.missionOn': '配達中',
      'road.missionFind': '表示',
      'road.missionDone': '配達成功',
      'road.missionLost': '配達取消',
      'road.overTitle': '間に合いませんでした',
      'road.overNote': '配達{n}回成功・残り予算{money}',
      'road.rule14': '<b>ときどき配達の依頼が入ります。</b>その車を関門から関門まで<b>決められた時間内に</b>届けなければならず、遅れると<b>そこでゲームが終わります</b>。届けば<b>報酬が増えます</b>。配達の車は盤上で輪がつき、画面の外にいるときは端の矢印が指します。',
      'road.rule15': '<b>街は育ちます。</b>はじめは大通りが縦横に一本ずつあるだけですが、時間がたつほど<b>交通量が増え、道沿いに建物が建ちます</b>。道を敷けばその周りが街になり、放っておけばいつか必ず詰まります。',
    },
    'zh-CN': {
      'meta.desc': '轿车、出租车、公交车、卡车和摩托车在直路与弯路交错的城市里实时行驶',
      'road.onRoad': '行驶中',
      'road.avgSpeed': '平均车速',
      'road.left': '驶出城外',
      'road.pause': '暂停',
      'road.play': '播放',
      'road.rate': '速度',
      'road.newCity': '新城市',
      'road.ctrlNone': '无信号',
      'road.ctrlSignal': '信号灯',
      'road.ctrlCircle': '环岛',
      'road.rule1': '<b>点路口</b>可以在下面选无信号、信号灯或环岛；信号灯还能选<b>相位方案</b>和<b>人行横道</b>。<b>点道路</b>可以逐条车道开关左转、直行、右转和掉头，还能<b>改变车道方向或增加车道</b>。',
      'road.rule2': '城里的路<b>直路与弯路交错</b>，每条路<b>一到八条车道</b>。中间的黄线分开对向，白色虚线分开同向车道。<b>连起来的路，弯度是连续的。</b>',
      'road.rule3': '<b>靠右行驶</b>。车辆走自己前进方向右侧的车道。',
      'road.rule4': '地图边缘的虚线是<b>通往其他城市的出入口</b>。车从那里进出，也有车<b>从路边的建筑出来、开进另一栋建筑</b>。',
      'road.rule5': '路上跑着<b>轿车、出租车、公交车、卡车和摩托车</b>五种。长度、速度、加速度各不相同，轿车堵在卡车后面就会排起长队。',
      'road.rule6': '它们会按前车的距离<b>自己刹车、自己起步</b>。',
      'road.rule7': '<b>只有行车路线真正交叉的地方才算路口</b>——如果没有任何一个动作需要越过中线（比如单行支路上关掉对向左转），那里就不是路口，谁都不用等。没有控制的路口<b>先到的车一辆一辆</b>通过。<b>信号灯</b>两相位时把相对的两个方向一起放行（只有左转要等空档），按方向数的相位则一个方向一次。两种都会跳过没人等的方向。<b>环岛</b>里正在绕行的车优先。',
      'road.junction': '路口',
      'road.phase2': '两相位',
      'road.phaseN': '{n}相位',
      'road.crosswalk': '人行横道',
      'road.lanesOf': '{n}车道',
      'road.rule8': '<b>画在车道上的箭头</b>就是这条车道能去的方向。取消左转车道，本来要左转的车<b>会绕别的路</b>。',
      'road.rule9': '放下<b>人行横道</b>就会有人过街。有信号时红灯过，没有信号时挑车少的空档过；有人在过，车就停。',
      'road.money': '预算',
      'road.flip': '改变方向',
      'road.addLane': '增加车道',
      'road.rule10': '<b>增加车道要花钱</b>（路越长越贵）。钱在<b>每辆车驶出城外时</b>进账，所以得先把堵点疏通才做得起下一项工程。改变方向只是重划标线，不花钱。',
      'road.newRoad': '新路',
      'road.build': '修建',
      'road.cancel': '取消',
      'road.draftHint': '<b>拖动中间的手柄</b>可以调整弯度。建成后是单车道单行线，点这条路就能加车道。',
      'road.toEdge': '这是<b>通往城外的路</b>。地图边缘会新开一个出入口，车从那里进出。',
      'road.tooShort': '太短了。用手柄拉长弯一点，或者取消。',
      'road.tooDear': '预算不够。车驶出城外就会进账。',
      'road.laneFull': '已经是{n}车道了，一条路最多就这么多。',
      'road.rule11': '<b>从路上任意一点拖到另一条路</b>就能修新路。松手后会显示造价，这时<b>用中间的手柄调整弯度</b>，再决定修建还是取消。起点、终点，以及<b>沿途横穿的每条路上都会新增路口</b>。<b>一直拖到地图边缘</b>就会新开一个出入口，成为通往城外的路。',
      'road.rule12': '<b>画面只显示城市的一角。</b>拖空地可以四处看，双指捏合（鼠标用滚轮）改变缩放。在路上拖是修新路，所以只想移动视野时请拖空地，或者两指一起移动。',
      'road.onBuilding': '路不能从建筑上穿过。拖手柄绕开吧。',
      'road.tunnelBit': '隧道{n}',
      'road.bridgeBit': '桥{n}',
      'road.join': '·',
      'road.rule13': '空地上有<b>建筑、山、河和湖</b>。<b>路不能穿过建筑</b>；过山要打<b>隧道</b>，过水要架<b>桥</b>，都要多花钱。',
      'road.missionOn': '配送中',
      'road.missionFind': '查看',
      'road.missionDone': '配送成功',
      'road.missionLost': '配送取消',
      'road.overTitle': '来不及了',
      'road.overNote': '成功配送{n}次 · 剩余预算{money}',
      'road.rule14': '<b>时不时会来一单配送。</b>那辆车得在<b>规定时间内</b>从一个关口跑到另一个关口，迟到就<b>到此为止</b>。送到则<b>另有奖励</b>。配送车在图上带一圈标记，跑出画面时边缘的箭头会指向它。',
      'road.rule15': '<b>城市会生长。</b>开局只有横竖各一条主干道，随着时间推移<b>车流变多，路边也会盖起建筑</b>。修了路，周围就长成街区；放着不管，迟早会堵死。',
    },
    'zh-TW': {
      'meta.desc': '轎車、計程車、公車、卡車和機車在直路與彎路交錯的城市裡即時行駛',
      'road.onRoad': '行駛中',
      'road.avgSpeed': '平均車速',
      'road.left': '駛出城外',
      'road.pause': '暫停',
      'road.play': '播放',
      'road.rate': '速度',
      'road.newCity': '新城市',
      'road.ctrlNone': '無號誌',
      'road.ctrlSignal': '號誌',
      'road.ctrlCircle': '圓環',
      'road.rule1': '<b>點路口</b>可以在下面選無號誌、號誌或圓環；號誌還能選<b>時相方案</b>和<b>行人穿越道</b>。<b>點道路</b>可以逐條車道開關左轉、直行、右轉和迴轉，還能<b>改變車道方向或增加車道</b>。',
      'road.rule2': '城裡的路<b>直路與彎路交錯</b>，每條路<b>一到八條車道</b>。中間的黃線分開對向，白色虛線分開同向車道。<b>連起來的路，彎度是連續的。</b>',
      'road.rule3': '<b>靠右行駛</b>。車輛走自己前進方向右側的車道。',
      'road.rule4': '地圖邊緣的虛線是<b>通往其他城市的出入口</b>。車從那裡進出，也有車<b>從路邊的建築出來、開進另一棟建築</b>。',
      'road.rule5': '路上跑著<b>轎車、計程車、公車、卡車和機車</b>五種。長度、速度、加速度各不相同，轎車卡在卡車後面就會排起長隊。',
      'road.rule6': '它們會依前車的距離<b>自己煞車、自己起步</b>。',
      'road.rule7': '<b>只有行車路線真正交叉的地方才算路口</b>——如果沒有任何一個動作需要越過中線（比如單行支路上關掉對向左轉），那裡就不是路口，誰都不用等。沒有號誌的路口<b>先到的車一輛一輛</b>通過。<b>號誌</b>兩時相時把相對的兩個方向一起放行（只有左轉要等空檔），依方向數的時相則一個方向一次。兩種都會跳過沒人等的方向。<b>圓環</b>裡正在繞行的車優先。',
      'road.junction': '路口',
      'road.phase2': '兩時相',
      'road.phaseN': '{n}時相',
      'road.crosswalk': '行人穿越道',
      'road.lanesOf': '{n}車道',
      'road.rule8': '<b>畫在車道上的箭頭</b>就是這條車道能去的方向。取消左轉車道，本來要左轉的車<b>會繞別的路</b>。',
      'road.rule9': '放下<b>行人穿越道</b>就會有人過街。有號誌時紅燈過，沒有號誌時挑車少的空檔過；有人在過，車就停。',
      'road.money': '預算',
      'road.flip': '改變方向',
      'road.addLane': '增加車道',
      'road.rule10': '<b>增加車道要花錢</b>（路越長越貴）。錢在<b>每輛車駛出城外時</b>進帳，所以得先把塞車處疏通才做得起下一項工程。改變方向只是重劃標線，不花錢。',
      'road.newRoad': '新路',
      'road.build': '興建',
      'road.cancel': '取消',
      'road.draftHint': '<b>拖曳中間的把手</b>可以調整彎度。建好後是單車道單行道，點這條路就能增加車道。',
      'road.toEdge': '這是<b>通往城外的路</b>。地圖邊緣會新開一個出入口，車從那裡進出。',
      'road.tooShort': '太短了。用把手拉長彎一點，或者取消。',
      'road.tooDear': '預算不足。車駛出城外就會進帳。',
      'road.laneFull': '已經是{n}車道了，一條路最多就這麼多。',
      'road.rule11': '<b>從路上任意一點拖到另一條路</b>就能興建新路。放手後會顯示造價，這時<b>用中間的把手調整彎度</b>，再決定興建還是取消。起點、終點，以及<b>沿途橫越的每條路上都會新增路口</b>。<b>一直拖到地圖邊緣</b>就會新開一個出入口，成為通往城外的路。',
      'road.rule12': '<b>畫面只顯示城市的一角。</b>拖空地可以四處看，雙指捏合（滑鼠用滾輪）改變縮放。在路上拖是興建新路，所以只想移動視野時請拖空地，或者兩指一起移動。',
      'road.onBuilding': '路不能從建築上穿過。拖把手繞開吧。',
      'road.tunnelBit': '隧道{n}',
      'road.bridgeBit': '橋{n}',
      'road.join': '·',
      'road.rule13': '空地上有<b>建築、山、河與湖</b>。<b>路不能穿過建築</b>；過山要開<b>隧道</b>，過水要架<b>橋</b>，都要多花錢。',
      'road.missionOn': '配送中',
      'road.missionFind': '查看',
      'road.missionDone': '配送成功',
      'road.missionLost': '配送取消',
      'road.overTitle': '來不及了',
      'road.overNote': '成功配送{n}次 · 剩餘預算{money}',
      'road.rule14': '<b>不時會來一單配送。</b>那輛車得在<b>規定時間內</b>從一個關口跑到另一個關口，遲到就<b>到此為止</b>。送到則<b>另有獎勵</b>。配送車在圖上帶一圈標記，跑出畫面時邊緣的箭頭會指向它。',
      'road.rule15': '<b>城市會成長。</b>開局只有橫豎各一條主幹道，隨著時間推移<b>車流變多，路邊也會蓋起建築</b>。修了路，周圍就長成街區；放著不管，遲早會塞死。',
    },
    es: {
      'meta.desc': 'Coches, taxis, autobuses, camiones y motos circulan en tiempo real por una ciudad de calles rectas y curvas',
      'road.onRoad': 'Circulando',
      'road.avgSpeed': 'Vel. media',
      'road.left': 'Salieron',
      'road.pause': 'Pausa',
      'road.play': 'Seguir',
      'road.rate': 'Velocidad',
      'road.newCity': 'Nueva ciudad',
      'road.ctrlNone': 'Sin señal',
      'road.ctrlSignal': 'Semáforo',
      'road.ctrlCircle': 'Rotonda',
      'road.rule1': '<b>Toca un cruce</b> y abajo eliges entre sin señal, semáforo o rotonda; el semáforo además lleva <b>plan de fases</b> y <b>paso de peatones</b>. <b>Toca una calle</b> para activar giro a la izquierda, recto, derecha y cambio de sentido en cada carril, <b>invertir el sentido de un carril</b> o <b>añadir uno</b>.',
      'road.rule2': 'La ciudad mezcla <b>calles rectas y curvas</b>, cada una con <b>de uno a ocho carriles</b>. La línea amarilla separa los sentidos; las rayas blancas separan carriles del mismo sentido. <b>Una calle que continúa mantiene su curva sin quiebros.</b>',
      'road.rule3': 'Se <b>circula por la derecha</b>. Cada vehículo usa los carriles de su propia derecha.',
      'road.rule4': 'Las barras discontinuas del borde del mapa son <b>accesos a otras ciudades</b>. Los vehículos entran y salen por ahí, y también <b>arrancan desde un edificio de la calle y aparcan en otro</b>.',
      'road.rule5': 'Circulan cinco tipos: <b>coche, taxi, autobús, camión y moto</b>. Cambian en largo, velocidad y aceleración, así que un coche detrás de un camión forma cola.',
      'road.rule6': 'Frenan y arrancan <b>solos</b> según el hueco que tienen delante.',
      'road.rule7': '<b>Solo son cruces los sitios donde las trayectorias se cortan de verdad</b>: si ningún movimiento tiene que pasar la línea central (por ejemplo, una vía lateral de sentido único con el giro a la izquierda contrario desactivado), no es un cruce y nadie espera. Un cruce sin regular deja pasar <b>un vehículo cada vez</b>. El <b>semáforo</b> con dos fases abre a la vez los dos accesos enfrentados (solo los giros a la izquierda esperan hueco); con una fase por acceso los abre de uno en uno. En ambos casos se salta el acceso sin nadie esperando. En la <b>rotonda</b> manda quien ya está girando.',
      'road.junction': 'Cruce',
      'road.phase2': '2 fases',
      'road.phaseN': '{n} fases',
      'road.crosswalk': 'Paso de peatones',
      'road.lanesOf': '{n} carriles',
      'road.rule8': 'Las <b>flechas pintadas en el carril</b> dicen adónde puede ir. Quita el carril de giro a la izquierda y ese tráfico <b>da la vuelta por otro lado</b>.',
      'road.rule9': 'Pon un <b>paso de peatones</b> y la gente cruza. Con semáforo cruzan en rojo y sin él aprovechan un hueco; los vehículos paran por quien ya está cruzando.',
      'road.money': 'Presupuesto',
      'road.flip': 'Cambiar sentido',
      'road.addLane': 'Añadir carril',
      'road.rule10': '<b>Añadir un carril cuesta dinero</b> (cuanto más larga la calle, más caro). El dinero entra <b>cada vez que un vehículo sale de la ciudad</b>, así que hay que mantener el tráfico fluyendo para pagar la siguiente obra. Invertir un carril es solo repintar: es gratis.',
      'road.newRoad': 'Vía nueva',
      'road.build': 'Construir',
      'road.cancel': 'Cancelar',
      'road.draftHint': '<b>Arrastra el tirador</b> del centro para curvarla. Se construye como un solo carril de sentido único; selecciónala después para añadir carriles.',
      'road.toEdge': 'Esta vía <b>sale de la ciudad</b>. Aparece un acceso nuevo en el borde del mapa y el tráfico entra y sale por ahí.',
      'road.tooShort': 'Demasiado corta. Cúrvala con el tirador o cancela.',
      'road.tooDear': 'No hay presupuesto. Se repone cada vez que un vehículo sale de la ciudad.',
      'road.laneFull': 'Ya tiene {n} carriles, el máximo de una vía.',
      'road.rule11': '<b>Arrastra desde cualquier punto de una vía hasta otra</b> para trazar una nueva. Al soltar aparece el precio; <b>curva el trazado con el tirador del centro</b> y luego construye o cancela. <b>Se crean cruces nuevos</b> donde empieza y termina el arrastre, y en cada vía que cruza por el camino. <b>Arrastra hasta el borde del mapa</b> y se abre un acceso nuevo: la vía sale de la ciudad.',
      'road.rule12': '<b>El tablero muestra solo un trozo de la ciudad.</b> Arrastra sobre terreno vacío para moverte y pellizca (o usa la rueda) para cambiar la escala. Arrastrar <em>sobre</em> una vía traza una nueva, así que agarra terreno libre —o mueve dos dedos a la vez— cuando solo quieras desplazar la vista.',
      'road.onBuilding': 'Una vía no puede atravesar un edificio. Desvíala con el tirador.',
      'road.tunnelBit': 'túnel {n}',
      'road.bridgeBit': 'puente {n}',
      'road.join': ' · ',
      'road.rule13': 'El terreno libre tiene <b>edificios, montes, ríos y lagos</b>. <b>Ninguna vía atraviesa un edificio</b>; los montes se cruzan con un <b>túnel</b> y el agua con un <b>puente</b>, y ambos cuestan más.',
      'road.missionOn': 'en reparto',
      'road.missionFind': 'Ver',
      'road.missionDone': 'entregado',
      'road.missionLost': 'reparto anulado',
      'road.overTitle': 'Llegó tarde',
      'road.overNote': '{n} entregas hechas · quedan {money} de presupuesto',
      'road.rule14': '<b>De vez en cuando llega un reparto.</b> Ese vehículo tiene que ir de una puerta a otra <b>dentro del tiempo dado</b>; si no llega, <b>la partida termina ahí</b>. Si llega, <b>cobras una prima</b>. El vehículo lleva un aro en el tablero, y una flecha en el borde lo señala cuando queda fuera de pantalla.',
      'road.rule15': '<b>La ciudad crece.</b> Empiezas con una vía principal en cada sentido y, con el tiempo, <b>el tráfico sube y los edificios se llenan a lo largo de las calles</b>. Traza una vía y la ciudad crece a su alrededor; déjala estar y acabará atascándose.',
    }
  });
})();
