// 이 게임에만 나오는 문구. 게임 이름과 공통 단추는 shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '이미 있는 도시에서 우회로·차로 확장·신호로 정체를 풀어 민원이 쌓이기 전에 버티는 게임',
      'road.week': '주차',
      'road.budget': '예산',
      'road.complaints': '민원',
      'road.toolRoad': '신설',
      'road.toolWiden': '확장',
      'road.toolSignal': '신호',
      'road.next': '다음 주',
      'road.noComplaints': '아직 들어온 민원이 없습니다',
      'road.cJam': '{spot} 정체',
      'road.cJamNote': '용량의 {pct}%',
      'road.cDelay': '{from}→{to} 통근 지연',
      'road.cDelayNote': '평소의 {ratio}배',
      'road.cWorks': '공사 소음',
      'road.cWorksNote': '한 주에 {n}곳',
      'road.whySpot': '여기엔 놓을 수 없습니다',
      'road.whyLanes': '이미 2차로입니다',
      'road.whyCrossing': '신호는 교차로에만 세웁니다',
      'road.whySignaled': '이미 신호가 있습니다',
      'road.whyNosignal': '신호가 없는 곳입니다',
      'road.whyMoney': '예산이 모자랍니다',
      'road.overTitle': '민원이 넘쳤습니다',
      'road.overNote': '{weeks}주를 버티고 민원 {solved}건을 해결했습니다.',
      'road.rule1': '도로공사 담당자가 되어 <b>막히는 길을 고칩니다</b>. 건물은 부술 수 없으니 <b>빈 땅과 지금 있는 도로</b>로만 풀어야 합니다.',
      'road.rule2': '아래에서 도구를 고르고 판을 누릅니다. <b>신설</b>은 빈 땅에 새 길을, <b>확장</b>은 도로를 2차로로, <b>신호</b>는 교차로에 신호를 세웁니다. 신호가 선 교차로를 다시 누르면 <b>녹색 배분</b>이 바뀝니다.',
      'road.rule3': '도로 색이 그 칸의 혼잡도입니다. <b>빨간 칸</b>은 받을 수 있는 양을 넘긴 곳입니다.',
      'road.rule4': '<b>길을 고치면 운전자가 경로를 바꿉니다.</b> 우회로를 뚫으면 일부가 그리로 옮겨 가고, 그래서 길을 늘려도 나아지지 않는 자리가 있습니다.',
      'road.rule5': '신호는 <b>교차하는 두 흐름</b>을 갈라 줍니다. 대신 녹색을 나누는 만큼 용량이 줄어드니, 한 방향만 지나는 길에 세우면 오히려 느려집니다.',
      'road.rule6': '<b>다음 주</b>를 누르면 통근량이 늘고 예산이 들어옵니다. 도시는 가만히 두면 반드시 막힙니다.',
      'road.rule7': '민원은 <b>원인을 없애면 사라집니다</b>. 한 주에 공사를 너무 많이 하면 공사 민원이 따로 붙습니다.',
      'road.rule8': '민원이 <b>{limit}건</b> 쌓이면 끝납니다.'
    },
    en: {
      'meta.desc': 'Fix an existing city with bypasses, wider roads and signals, and keep the complaints from piling up',
      'road.week': 'Week',
      'road.budget': 'Budget',
      'road.complaints': 'Complaints',
      'road.toolRoad': 'Build',
      'road.toolWiden': 'Widen',
      'road.toolSignal': 'Signal',
      'road.next': 'Next week',
      'road.noComplaints': 'No complaints yet',
      'road.cJam': '{spot} gridlock',
      'road.cJamNote': '{pct}% of capacity',
      'road.cDelay': '{from}→{to} commute delayed',
      'road.cDelayNote': '{ratio}× the usual',
      'road.cWorks': 'Roadworks noise',
      'road.cWorksNote': '{n} sites in one week',
      'road.whySpot': 'Nothing can go here',
      'road.whyLanes': 'Already two lanes',
      'road.whyCrossing': 'Signals go on crossings only',
      'road.whySignaled': 'There is already a signal',
      'road.whyNosignal': 'No signal here',
      'road.whyMoney': 'Not enough budget',
      'road.overTitle': 'The complaints piled up',
      'road.overNote': 'You lasted {weeks} weeks and cleared {solved} complaints.',
      'road.rule1': 'You run the roads department and <b>fix what is jammed</b>. Buildings cannot be torn down, so you work with <b>empty land and the roads already there</b>.',
      'road.rule2': 'Pick a tool below and tap the map. <b>Build</b> lays a road on empty land, <b>Widen</b> makes a road two lanes, <b>Signal</b> puts a signal on a crossing. Tap a signalled crossing again to change its <b>green split</b>.',
      'road.rule3': 'The colour of a road is how crowded it is. A <b>red tile</b> is past what it can carry.',
      'road.rule4': '<b>Fix a road and drivers reroute.</b> Open a bypass and some of them move onto it — which is why more road does not always help.',
      'road.rule5': 'A signal separates <b>two crossing streams</b>. It also splits the capacity, so a signal on a road that carries one direction only makes it slower.',
      'road.rule6': '<b>Next week</b> brings more commuters and a new budget. Left alone, the city always jams.',
      'road.rule7': 'A complaint <b>disappears once its cause is gone</b>. Too much construction in one week adds a complaint of its own.',
      'road.rule8': 'It ends when <b>{limit} complaints</b> are open at once.'
    },
    ja: {
      'meta.desc': '既にある街で、迂回路・車線拡張・信号を使って渋滞を解き、苦情が溜まる前に持ちこたえるゲーム',
      'road.week': '週目',
      'road.budget': '予算',
      'road.complaints': '苦情',
      'road.toolRoad': '新設',
      'road.toolWiden': '拡張',
      'road.toolSignal': '信号',
      'road.next': '次の週',
      'road.noComplaints': 'まだ苦情はありません',
      'road.cJam': '{spot} 渋滞',
      'road.cJamNote': '容量の{pct}%',
      'road.cDelay': '{from}→{to} 通勤の遅れ',
      'road.cDelayNote': '普段の{ratio}倍',
      'road.cWorks': '工事の騒音',
      'road.cWorksNote': '一週間で{n}か所',
      'road.whySpot': 'ここには置けません',
      'road.whyLanes': 'すでに2車線です',
      'road.whyCrossing': '信号は交差点にだけ置けます',
      'road.whySignaled': 'すでに信号があります',
      'road.whyNosignal': '信号がありません',
      'road.whyMoney': '予算が足りません',
      'road.overTitle': '苦情が溢れました',
      'road.overNote': '{weeks}週持ちこたえ、苦情を{solved}件片づけました。',
      'road.rule1': '道路課の担当として<b>詰まった道を直します</b>。建物は壊せないので、<b>空き地と今ある道路</b>だけで解きます。',
      'road.rule2': '下で道具を選び、盤を押します。<b>新設</b>は空き地に新しい道、<b>拡張</b>は道路を2車線に、<b>信号</b>は交差点に信号を置きます。信号のある交差点をもう一度押すと<b>青の配分</b>が変わります。',
      'road.rule3': '道路の色がその区間の混み具合です。<b>赤いマス</b>は捌ける量を超えています。',
      'road.rule4': '<b>道を直すと運転者は経路を変えます。</b>迂回路を通せば一部がそちらへ移り、だから道を増やしても良くならない場所があります。',
      'road.rule5': '信号は<b>交差する二つの流れ</b>を分けます。その代わり青を分けた分だけ容量が減るので、一方向しか通らない道に置くとかえって遅くなります。',
      'road.rule6': '<b>次の週</b>を押すと通勤量が増え、予算が入ります。放っておけば街は必ず詰まります。',
      'road.rule7': '苦情は<b>原因がなくなれば消えます</b>。一週間に工事をしすぎると工事の苦情が別に付きます。',
      'road.rule8': '苦情が<b>{limit}件</b>溜まると終わりです。'
    },
    'zh-CN': {
      'meta.desc': '在已建成的城市里用绕行路、拓宽车道和信号灯疏通拥堵，在投诉堆满之前撑住',
      'road.week': '周',
      'road.budget': '预算',
      'road.complaints': '投诉',
      'road.toolRoad': '新建',
      'road.toolWiden': '拓宽',
      'road.toolSignal': '信号',
      'road.next': '下一周',
      'road.noComplaints': '还没有投诉',
      'road.cJam': '{spot} 拥堵',
      'road.cJamNote': '已占容量{pct}%',
      'road.cDelay': '{from}→{to} 通勤延误',
      'road.cDelayNote': '平时的{ratio}倍',
      'road.cWorks': '施工噪音',
      'road.cWorksNote': '一周{n}处',
      'road.whySpot': '这里放不了',
      'road.whyLanes': '已经是双车道',
      'road.whyCrossing': '信号灯只能装在路口',
      'road.whySignaled': '这里已有信号灯',
      'road.whyNosignal': '这里没有信号灯',
      'road.whyMoney': '预算不够',
      'road.overTitle': '投诉堆满了',
      'road.overNote': '你撑了{weeks}周，解决了{solved}件投诉。',
      'road.rule1': '你是道路科的负责人，要<b>疏通堵住的路</b>。建筑不能拆，只能用<b>空地和现有的道路</b>解决。',
      'road.rule2': '在下面选工具再点地图。<b>新建</b>在空地上修路，<b>拓宽</b>把道路改成双车道，<b>信号</b>在路口装信号灯。再点一次已装灯的路口可以改<b>绿灯配时</b>。',
      'road.rule3': '道路的颜色就是这一格的拥挤程度，<b>红色</b>表示已经超出它能承受的量。',
      'road.rule4': '<b>路一改，司机就换路线。</b>开了绕行路，一部分车会转过去——所以修更多路未必更好。',
      'road.rule5': '信号灯把<b>交叉的两股车流</b>分开，代价是绿灯一分，容量就少一半。只有单向车流的路上装灯反而更慢。',
      'road.rule6': '点<b>下一周</b>，通勤量增加，预算入账。放着不管，城市一定会堵死。',
      'road.rule7': '投诉<b>只要原因消失就会撤销</b>。一周里施工太多，还会多一条施工投诉。',
      'road.rule8': '同时积压<b>{limit}件</b>投诉就结束。'
    },
    'zh-TW': {
      'meta.desc': '在已建成的城市裡用繞行道路、拓寬車道和號誌疏通壅塞，在陳情堆滿之前撐住',
      'road.week': '週',
      'road.budget': '預算',
      'road.complaints': '陳情',
      'road.toolRoad': '新建',
      'road.toolWiden': '拓寬',
      'road.toolSignal': '號誌',
      'road.next': '下一週',
      'road.noComplaints': '還沒有陳情',
      'road.cJam': '{spot} 壅塞',
      'road.cJamNote': '已佔容量{pct}%',
      'road.cDelay': '{from}→{to} 通勤延誤',
      'road.cDelayNote': '平時的{ratio}倍',
      'road.cWorks': '施工噪音',
      'road.cWorksNote': '一週{n}處',
      'road.whySpot': '這裡放不了',
      'road.whyLanes': '已經是雙車道',
      'road.whyCrossing': '號誌只能設在路口',
      'road.whySignaled': '這裡已有號誌',
      'road.whyNosignal': '這裡沒有號誌',
      'road.whyMoney': '預算不夠',
      'road.overTitle': '陳情堆滿了',
      'road.overNote': '你撐了{weeks}週，解決了{solved}件陳情。',
      'road.rule1': '你是道路科的負責人，要<b>疏通堵住的路</b>。建築不能拆，只能用<b>空地和現有的道路</b>解決。',
      'road.rule2': '在下面選工具再點地圖。<b>新建</b>在空地上修路，<b>拓寬</b>把道路改成雙車道，<b>號誌</b>在路口設號誌。再點一次已設號誌的路口可以改<b>綠燈時比</b>。',
      'road.rule3': '道路的顏色就是這一格的擁擠程度，<b>紅色</b>表示已經超出它能承受的量。',
      'road.rule4': '<b>路一改，駕駛就換路線。</b>開了繞行道路，一部分車會轉過去——所以修更多路未必更好。',
      'road.rule5': '號誌把<b>交叉的兩股車流</b>分開，代價是綠燈一分，容量就少一半。只有單向車流的路上設號誌反而更慢。',
      'road.rule6': '按<b>下一週</b>，通勤量增加，預算入帳。放著不管，城市一定會塞死。',
      'road.rule7': '陳情<b>只要原因消失就會撤銷</b>。一週裡施工太多，還會多一件施工陳情。',
      'road.rule8': '同時累積<b>{limit}件</b>陳情就結束。'
    },
    es: {
      'meta.desc': 'Arregla una ciudad ya construida con desvíos, carriles nuevos y semáforos, y aguanta antes de que se acumulen las quejas',
      'road.week': 'Semana',
      'road.budget': 'Presupuesto',
      'road.complaints': 'Quejas',
      'road.toolRoad': 'Construir',
      'road.toolWiden': 'Ampliar',
      'road.toolSignal': 'Semáforo',
      'road.next': 'Siguiente semana',
      'road.noComplaints': 'Todavía no hay quejas',
      'road.cJam': 'Atasco en {spot}',
      'road.cJamNote': '{pct}% de la capacidad',
      'road.cDelay': 'Trayecto lento {from}→{to}',
      'road.cDelayNote': '{ratio}× lo habitual',
      'road.cWorks': 'Ruido de obras',
      'road.cWorksNote': '{n} obras en una semana',
      'road.whySpot': 'Aquí no cabe nada',
      'road.whyLanes': 'Ya tiene dos carriles',
      'road.whyCrossing': 'Los semáforos solo van en cruces',
      'road.whySignaled': 'Ya hay un semáforo',
      'road.whyNosignal': 'Aquí no hay semáforo',
      'road.whyMoney': 'No hay presupuesto',
      'road.overTitle': 'Las quejas se desbordaron',
      'road.overNote': 'Aguantaste {weeks} semanas y resolviste {solved} quejas.',
      'road.rule1': 'Diriges el departamento de carreteras y <b>arreglas lo que se atasca</b>. Los edificios no se derriban, así que trabajas con <b>los solares vacíos y las calles que ya existen</b>.',
      'road.rule2': 'Elige una herramienta abajo y toca el mapa. <b>Construir</b> traza una calle en un solar, <b>Ampliar</b> la deja de dos carriles, <b>Semáforo</b> lo instala en un cruce. Toca otra vez un cruce con semáforo para cambiar su <b>reparto de verde</b>.',
      'road.rule3': 'El color de una calle es lo cargada que está. Una <b>casilla roja</b> supera lo que puede absorber.',
      'road.rule4': '<b>Si cambias una calle, los conductores cambian de ruta.</b> Abre un desvío y parte del tráfico se mueve allí: por eso más asfalto no siempre mejora nada.',
      'road.rule5': 'El semáforo separa <b>dos flujos que se cruzan</b>, pero reparte la capacidad. En una calle con un solo sentido de paso, ponerlo la vuelve más lenta.',
      'road.rule6': '<b>Siguiente semana</b> trae más tráfico y presupuesto nuevo. Si no haces nada, la ciudad acaba colapsando.',
      'road.rule7': 'Una queja <b>desaparece cuando desaparece su causa</b>. Demasiada obra en una semana añade su propia queja.',
      'road.rule8': 'Termina cuando hay <b>{limit} quejas</b> abiertas a la vez.'
    }
  });
})();
