// 이 게임에만 나오는 문구. 판 크기·난이도 같은 공통 문구는 shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '거점에 생산탑을 세워 병력을 불리고 이웃 거점을 점령해 가는 실시간 전략 게임',
      'conquest.map': '거점 지도',
      'conquest.pickHint': '내 거점을 누르면 고릅니다.',
      'conquest.factory': '생산탑 {cost}',
      'conquest.turret': '방어탑 {cost}',
      'conquest.rally': '집결지',
      'conquest.rallyOff': '집결 해제',
      'conquest.rallyPick': '이어 둘 거점을 누르세요',
      'conquest.rallyOn': '병력이 {keep}만 남기고 흘러갑니다',
      'conquest.sendAmount': '보낼 양',
      'conquest.half': '절반',
      'conquest.all': '전부',
      'conquest.energy': '점령력',
      'conquest.strength': '공격력',
      'conquest.speed': '이동속도',
      'conquest.tally': '거점 <b>{mine}</b>:<i>{theirs}</i> · 병력 <b>{myUnits}</b>:<i>{theirUnits}</i>',
      'conquest.won': '모두 점령했습니다',
      'conquest.lost': '모두 빼앗겼습니다',
      'conquest.wonNote': '{seconds}초 만에 상대를 몰아냈습니다.',
      'conquest.lostNote': '상대가 먼저 모든 거점을 차지했습니다.',
      'conquest.rule1': '거점마다 <b>병력</b>이 머무릅니다. 병력은 싸우는 힘이자 건설 비용입니다.',
      'conquest.rule2': '<b>생산탑</b>은 병력을 뽑아내고, <b>방어탑</b>은 다가온 적 병력을 공격합니다. 하나 세우는 데 병력 <b>10</b>이 들고, 거점이 클수록 더 세울 수 있습니다.',
      'conquest.rule3': '병력은 <b>사거리 안의 거점</b>으로만 보냅니다. 고른 거점에서 갈 수 있는 곳은 선으로 이어집니다.',
      'conquest.rule4': '전투는 저절로 벌어집니다. 남의 거점은 <b>지키는 병력 → 시설 → 코어</b> 순서로 무너뜨려야 넘어옵니다. 코어를 깎다 말고 물러나면 도로 차오릅니다.',
      'conquest.rule5': '<b>지키는 쪽이 유리합니다.</b> 같은 수로 부딪히면 지키는 쪽이 남으니, 칠 때는 넉넉히 모아서 한 번에 가세요. 빈 거점에서는 양쪽 다 손님이라 이점이 없습니다.',
      'conquest.rule6': '병력의 <b>점령력·공격력·이동속도</b>는 생산된 거점에서 물려받습니다. 점령력은 코어를 깎는 속도, 공격력은 전투, 이동속도는 이동입니다. 좋은 거점에서 뽑은 병력을 약한 부대에 섞으면 평균이 내려갑니다.',
      'conquest.rule7': '거점에 모을 수 있는 병력에는 <b>한도</b>가 있습니다. 넘긴 만큼은 조금씩 줄어드니 쌓아 두기보다 쓰는 편이 낫습니다.',
      'conquest.rule8': '내 거점을 누르고 이웃을 누르면 병력이 갑니다. <b>절반·전부</b>로 보낼 양을 고릅니다. 빈 곳을 누르면 선택이 풀립니다.',
      'conquest.rule9': '거점이 늘면 <b>집결지</b>를 걸어 두세요. 거점을 고르고 <b>집결지</b>를 누른 뒤 이웃을 누르면, 그 거점에서 생산되는 병력이 <b>10</b>만 남기고 알아서 그리로 흘러갑니다. 같은 단추로 풀 수 있고, 거점을 빼앗기면 저절로 풀립니다.',
      'conquest.rule10': '상대의 거점과 병력을 <b>모두 없애면 이깁니다.</b>',
      'conquest.rule11': '<b>난이도</b>는 판을 다시 만들지 않고 언제든 바꿀 수 있습니다. <b>쉬움</b>에서는 상대가 한동안 시설만 세우고, 병력도 천천히 불어나며, 방어탑을 세우지 않습니다. <b>어려움</b>은 자주 움직이고 여러 곳에서 한꺼번에 밀어붙입니다.'
    },
    en: {
      'meta.desc': 'A real-time strategy game: build factories on your bases, grow your forces and take the neighbours',
      'conquest.map': 'Base map',
      'conquest.pickHint': 'Tap one of your bases to select it.',
      'conquest.factory': 'Factory {cost}',
      'conquest.turret': 'Turret {cost}',
      'conquest.rally': 'Rally point',
      'conquest.rallyOff': 'Clear rally',
      'conquest.rallyPick': 'Tap the base to link it to',
      'conquest.rallyOn': 'Units flow out, leaving {keep} behind',
      'conquest.sendAmount': 'How much to send',
      'conquest.half': 'Half',
      'conquest.all': 'All',
      'conquest.energy': 'Capture',
      'conquest.strength': 'Attack',
      'conquest.speed': 'Speed',
      'conquest.tally': 'Bases <b>{mine}</b>:<i>{theirs}</i> · Units <b>{myUnits}</b>:<i>{theirUnits}</i>',
      'conquest.won': 'You took everything',
      'conquest.lost': 'You lost everything',
      'conquest.wonNote': 'You drove them out in {seconds} seconds.',
      'conquest.lostNote': 'They took every base first.',
      'conquest.rule1': 'Every base holds <b>units</b>. Units are both your fighting strength and your building cost.',
      'conquest.rule2': 'A <b>factory</b> produces units and a <b>turret</b> shoots at approaching enemies. Each costs <b>10</b> units, and a bigger base holds more of them.',
      'conquest.rule3': 'Units can only be sent to a <b>base within range</b>. Lines show where the selected base can reach.',
      'conquest.rule4': 'Fighting happens on its own. To take an enemy base you have to break through <b>defending units → buildings → core</b>, in that order. Back off mid-core and it fills back up.',
      'conquest.rule5': '<b>The defender has the edge.</b> Equal numbers leave the defender standing, so gather enough and strike in one go. On an empty base neither side is at home, so nobody has the edge.',
      'conquest.rule6': 'A unit inherits its <b>capture, attack and speed</b> from the base that produced it. Capture is how fast it eats a core, attack is combat, speed is travel. Mixing units from a strong base into a weak stack pulls the average down.',
      'conquest.rule7': 'Each base has a <b>cap</b> on the units it can hold. Anything over it drains away slowly, so spend rather than hoard.',
      'conquest.rule8': 'Tap your base, then a neighbour, and the units go. Choose <b>half or all</b> for how much to send. Tapping empty space clears the selection.',
      'conquest.rule9': 'As you take more bases, set a <b>rally point</b>. Select a base, press <b>Rally point</b>, then tap a neighbour: everything that base produces flows there, leaving <b>10</b> behind. The same button clears it, and losing the base clears it too.',
      'conquest.rule10': '<b>Wipe out every enemy base and unit to win.</b>',
      'conquest.rule11': 'You can change the <b>difficulty</b> at any time without starting over. On <b>easy</b> the opponent only builds for a while, grows slowly and never builds turrets. On <b>hard</b> it moves often and pushes from several places at once.'
    },
    ja: {
      'meta.desc': '拠点に生産塔を建てて兵力を増やし、隣の拠点を奪っていくリアルタイム戦略ゲーム',
      'conquest.map': '拠点マップ',
      'conquest.pickHint': '自分の拠点を押すと選べます。',
      'conquest.factory': '生産塔 {cost}',
      'conquest.turret': '防御塔 {cost}',
      'conquest.rally': '集結地',
      'conquest.rallyOff': '集結解除',
      'conquest.rallyPick': 'つなぐ拠点を押してください',
      'conquest.rallyOn': '兵力が{keep}だけ残して流れていきます',
      'conquest.sendAmount': '送る量',
      'conquest.half': '半分',
      'conquest.all': '全部',
      'conquest.energy': '占領力',
      'conquest.strength': '攻撃力',
      'conquest.speed': '移動速度',
      'conquest.tally': '拠点 <b>{mine}</b>:<i>{theirs}</i> · 兵力 <b>{myUnits}</b>:<i>{theirUnits}</i>',
      'conquest.won': 'すべて占領しました',
      'conquest.lost': 'すべて奪われました',
      'conquest.wonNote': '{seconds}秒で相手を追い出しました。',
      'conquest.lostNote': '相手が先にすべての拠点を取りました。',
      'conquest.rule1': '拠点ごとに<b>兵力</b>がとどまります。兵力は戦う力であり、建設の費用でもあります。',
      'conquest.rule2': '<b>生産塔</b>は兵力を生み、<b>防御塔</b>は近づく敵兵を攻撃します。ひとつ建てるのに兵力<b>10</b>がかかり、大きな拠点ほど多く建てられます。',
      'conquest.rule3': '兵力は<b>射程内の拠点</b>にだけ送れます。選んだ拠点から行ける先は線でつながって見えます。',
      'conquest.rule4': '戦闘は自動で起きます。敵の拠点は<b>守る兵力 → 施設 → コア</b>の順に崩さないと落ちません。コアを削る途中で退くと元に戻ります。',
      'conquest.rule5': '<b>守る側が有利です。</b>同数でぶつかれば守る側が残るので、攻めるときは十分ためて一度に行きましょう。空の拠点では双方とも客なので有利不利はありません。',
      'conquest.rule6': '兵力の<b>占領力・攻撃力・移動速度</b>は生産された拠点から受け継ぎます。占領力はコアを削る速さ、攻撃力は戦闘、移動速度は移動です。良い拠点の兵を弱い部隊に混ぜると平均が下がります。',
      'conquest.rule7': '拠点に集められる兵力には<b>上限</b>があります。超えた分は少しずつ減るので、ためるより使う方が得です。',
      'conquest.rule8': '自分の拠点を押してから隣を押すと兵力が動きます。<b>半分・全部</b>で送る量を選びます。空いた所を押すと選択が解けます。',
      'conquest.rule9': '拠点が増えたら<b>集結地</b>を設定しましょう。拠点を選んで<b>集結地</b>を押し、隣を押すと、その拠点で生産された兵力が<b>10</b>だけ残して自動でそちらへ流れます。同じボタンで解除でき、拠点を奪われると自動で解けます。',
      'conquest.rule10': '相手の拠点と兵力を<b>すべて無くせば勝ちです。</b>',
      'conquest.rule11': '<b>難易度</b>は盤を作り直さずいつでも変えられます。<b>やさしい</b>では相手がしばらく施設だけ建て、兵力もゆっくり増え、防御塔を建てません。<b>むずかしい</b>はよく動き、何か所からも一度に押してきます。'
    },
    'zh-CN': {
      'meta.desc': '在据点上建生产塔扩充兵力、一步步占领邻近据点的即时战略游戏',
      'conquest.map': '据点地图',
      'conquest.pickHint': '点自己的据点就能选中。',
      'conquest.factory': '生产塔 {cost}',
      'conquest.turret': '防御塔 {cost}',
      'conquest.rally': '集结点',
      'conquest.rallyOff': '取消集结',
      'conquest.rallyPick': '点一个要连过去的据点',
      'conquest.rallyOn': '兵力只留 {keep}，其余自动流过去',
      'conquest.sendAmount': '派兵数量',
      'conquest.half': '一半',
      'conquest.all': '全部',
      'conquest.energy': '占领力',
      'conquest.strength': '攻击力',
      'conquest.speed': '移动速度',
      'conquest.tally': '据点 <b>{mine}</b>:<i>{theirs}</i> · 兵力 <b>{myUnits}</b>:<i>{theirUnits}</i>',
      'conquest.won': '全部占领',
      'conquest.lost': '全部失守',
      'conquest.wonNote': '{seconds} 秒就把对手赶了出去。',
      'conquest.lostNote': '对手先拿下了所有据点。',
      'conquest.rule1': '每个据点都驻有<b>兵力</b>。兵力既是战斗力，也是建造的花费。',
      'conquest.rule2': '<b>生产塔</b>产兵，<b>防御塔</b>攻击靠近的敌兵。建一座要 <b>10</b> 兵力，据点越大能建的越多。',
      'conquest.rule3': '兵力只能派往<b>射程内的据点</b>。选中据点后，能去的地方会用线连起来。',
      'conquest.rule4': '战斗会自动发生。要拿下敌方据点，得按<b>守军 → 设施 → 核心</b>的顺序打穿。核心削到一半退兵，它会回满。',
      'conquest.rule5': '<b>防守方占优。</b>同样兵力相撞，留下来的是守方，所以进攻要攒够一次打。空据点上双方都是客，没有优势可言。',
      'conquest.rule6': '兵的<b>占领力、攻击力、移动速度</b>继承自产它的据点。占领力决定削核心的快慢，攻击力用于战斗，移动速度用于赶路。把好据点的兵混进弱队伍，平均值会被拉低。',
      'conquest.rule7': '据点能屯的兵力有<b>上限</b>，超出的部分会慢慢流失，与其囤着不如花掉。',
      'conquest.rule8': '点自己的据点再点邻居，兵就过去了。用<b>一半／全部</b>选派兵量。点空白处取消选中。',
      'conquest.rule9': '据点变多后就设<b>集结点</b>。选中据点，按<b>集结点</b>，再点邻居，那个据点产出的兵就只留 <b>10</b>，其余自动流过去。同一个按钮可以取消，据点被夺走也会自动取消。',
      'conquest.rule10': '<b>把对手的据点和兵力全部消灭就赢了。</b>',
      'conquest.rule11': '<b>难度</b>随时可以改，不用重开一局。<b>简单</b>时对手会有一阵子只建设施，兵力增长慢，也不建防御塔。<b>困难</b>则频繁行动，还会多路同时压上来。'
    },
    'zh-TW': {
      'meta.desc': '在據點上建生產塔擴充兵力、一步步佔領鄰近據點的即時戰略遊戲',
      'conquest.map': '據點地圖',
      'conquest.pickHint': '點自己的據點就能選取。',
      'conquest.factory': '生產塔 {cost}',
      'conquest.turret': '防禦塔 {cost}',
      'conquest.rally': '集結點',
      'conquest.rallyOff': '取消集結',
      'conquest.rallyPick': '點一個要連過去的據點',
      'conquest.rallyOn': '兵力只留 {keep}，其餘自動流過去',
      'conquest.sendAmount': '派兵數量',
      'conquest.half': '一半',
      'conquest.all': '全部',
      'conquest.energy': '佔領力',
      'conquest.strength': '攻擊力',
      'conquest.speed': '移動速度',
      'conquest.tally': '據點 <b>{mine}</b>:<i>{theirs}</i> · 兵力 <b>{myUnits}</b>:<i>{theirUnits}</i>',
      'conquest.won': '全部佔領',
      'conquest.lost': '全部失守',
      'conquest.wonNote': '{seconds} 秒就把對手趕了出去。',
      'conquest.lostNote': '對手先拿下了所有據點。',
      'conquest.rule1': '每個據點都駐有<b>兵力</b>。兵力既是戰鬥力，也是建造的花費。',
      'conquest.rule2': '<b>生產塔</b>產兵，<b>防禦塔</b>攻擊靠近的敵兵。建一座要 <b>10</b> 兵力，據點越大能建的越多。',
      'conquest.rule3': '兵力只能派往<b>射程內的據點</b>。選取據點後，能去的地方會用線連起來。',
      'conquest.rule4': '戰鬥會自動發生。要拿下敵方據點，得按<b>守軍 → 設施 → 核心</b>的順序打穿。核心削到一半退兵，它會回滿。',
      'conquest.rule5': '<b>防守方占優。</b>同樣兵力相撞，留下來的是守方，所以進攻要攢夠一次打。空據點上雙方都是客，沒有優勢可言。',
      'conquest.rule6': '兵的<b>佔領力、攻擊力、移動速度</b>繼承自產它的據點。佔領力決定削核心的快慢，攻擊力用於戰鬥，移動速度用於趕路。把好據點的兵混進弱隊伍，平均值會被拉低。',
      'conquest.rule7': '據點能屯的兵力有<b>上限</b>，超出的部分會慢慢流失，與其囤著不如花掉。',
      'conquest.rule8': '點自己的據點再點鄰居，兵就過去了。用<b>一半／全部</b>選派兵量。點空白處取消選取。',
      'conquest.rule9': '據點變多後就設<b>集結點</b>。選取據點，按<b>集結點</b>，再點鄰居，那個據點產出的兵就只留 <b>10</b>，其餘自動流過去。同一個按鈕可以取消，據點被奪走也會自動取消。',
      'conquest.rule10': '<b>把對手的據點和兵力全部消滅就贏了。</b>',
      'conquest.rule11': '<b>難度</b>隨時可以改，不用重開一局。<b>簡單</b>時對手會有一陣子只建設施，兵力增長慢，也不建防禦塔。<b>困難</b>則頻繁行動，還會多路同時壓上來。'
    },
    es: {
      'meta.desc': 'Estrategia en tiempo real: levanta fábricas en tus bases, haz crecer tus tropas y toma las bases vecinas',
      'conquest.map': 'Mapa de bases',
      'conquest.pickHint': 'Toca una base tuya para seleccionarla.',
      'conquest.factory': 'Fábrica {cost}',
      'conquest.turret': 'Torreta {cost}',
      'conquest.rally': 'Punto de reunión',
      'conquest.rallyOff': 'Quitar reunión',
      'conquest.rallyPick': 'Toca la base a la que enlazarla',
      'conquest.rallyOn': 'Las tropas salen dejando {keep} atrás',
      'conquest.sendAmount': 'Cuánto enviar',
      'conquest.half': 'Mitad',
      'conquest.all': 'Todo',
      'conquest.energy': 'Captura',
      'conquest.strength': 'Ataque',
      'conquest.speed': 'Velocidad',
      'conquest.tally': 'Bases <b>{mine}</b>:<i>{theirs}</i> · Tropas <b>{myUnits}</b>:<i>{theirUnits}</i>',
      'conquest.won': 'Lo has conquistado todo',
      'conquest.lost': 'Lo has perdido todo',
      'conquest.wonNote': 'Los echaste en {seconds} segundos.',
      'conquest.lostNote': 'El rival se quedó antes con todas las bases.',
      'conquest.rule1': 'En cada base se acumulan <b>tropas</b>. Las tropas son a la vez tu fuerza y el coste de construir.',
      'conquest.rule2': 'La <b>fábrica</b> produce tropas y la <b>torreta</b> dispara a los enemigos que se acercan. Cada una cuesta <b>10</b> tropas, y cuanto mayor es la base, más caben.',
      'conquest.rule3': 'Solo puedes enviar tropas a una <b>base dentro del alcance</b>. Las líneas muestran adónde llega la base seleccionada.',
      'conquest.rule4': 'Los combates ocurren solos. Para tomar una base enemiga hay que romper <b>tropas defensoras → edificios → núcleo</b>, en ese orden. Si te retiras a medio núcleo, se rellena.',
      'conquest.rule5': '<b>El defensor tiene ventaja.</b> Con números iguales sobrevive quien defiende, así que ataca con margen y de una vez. En una base vacía nadie juega en casa, así que no hay ventaja.',
      'conquest.rule6': 'Cada tropa hereda <b>captura, ataque y velocidad</b> de la base que la produjo. La captura es lo rápido que come el núcleo, el ataque es el combate y la velocidad el desplazamiento. Mezclar tropas de una base buena con un grupo flojo baja la media.',
      'conquest.rule7': 'Cada base tiene un <b>tope</b> de tropas. Lo que pase de ahí se pierde poco a poco: mejor gastar que acumular.',
      'conquest.rule8': 'Toca tu base y luego una vecina y las tropas salen. Elige <b>mitad o todo</b> para decidir cuántas. Tocar el vacío quita la selección.',
      'conquest.rule9': 'Cuando tengas muchas bases, pon un <b>punto de reunión</b>. Selecciona la base, pulsa <b>Punto de reunión</b> y toca una vecina: todo lo que produzca esa base fluirá hacia allí dejando <b>10</b>. El mismo botón lo quita, y perder la base también.',
      'conquest.rule10': '<b>Gana quien elimina todas las bases y tropas del rival.</b>',
      'conquest.rule11': 'Puedes cambiar la <b>dificultad</b> cuando quieras sin empezar de nuevo. En <b>fácil</b> el rival solo construye durante un rato, crece despacio y no levanta torretas. En <b>difícil</b> se mueve a menudo y presiona desde varios sitios a la vez.'
    }
  });
})();
