// 이 게임에만 나오는 문구. 도구 이름과 게임 이름은 shared/strings.js에 있다.
//
// **알파라 한국어만 있다**(저장소 규칙). 다른 언어에서는 엔진이 한국어로 내린다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '한 줄 길 위에서 적의 수를 읽고 패를 쌓아 출두하는 암행어사 로그라이트',

      'ah.tile.sword': '환도',
      'ah.tile.spear': '창',
      'ah.tile.bow': '각궁',
      'ah.tile.flail': '편곤',
      'ah.tile.twin': '쌍검',
      'ah.tile.kick': '택견',
      'ah.tile.charm': '부적',
      'ah.tile.dash': '축지법',
      'ah.tile.mapae': '마패',
      'ah.tileDesc.sword': '바로 앞 한 칸을 벤다.',
      'ah.tileDesc.spear': '앞 두 칸을 함께 찌른다.',
      'ah.tileDesc.bow': '앞쪽으로 처음 만나는 적을 쏜다.',
      'ah.tileDesc.flail': '양옆 한 칸씩을 후려친다.',
      'ah.tileDesc.twin': '바로 앞을 두 번 벤다.',
      'ah.tileDesc.kick': '바로 앞 적을 한 칸 밀어낸다. 막히면 둘 다 1 피해.',
      'ah.tileDesc.charm': '앞쪽으로 처음 만나는 적을 2차례 묶는다.',
      'ah.tileDesc.dash': '바로 앞 적을 뛰어넘어 그 뒤에서 돌아선다. 적이 없으면 두 칸 나아간다.',
      'ah.tileDesc.mapae': '"암행어사 출두요!" 모든 적이 한 차례 얼어붙는다.',

      'ah.foe.bandit': '산적',
      'ah.foe.spearman': '창 산적',
      'ah.foe.archer': '산적 궁수',
      'ah.foe.assassin': '자객',
      'ah.foe.guard': '사병',
      'ah.foe.dokkaebi': '도깨비',
      'ah.foe.gumiho': '구미호',
      'ah.foe.mulgwisin': '물귀신',
      'ah.foe.chief': '산적 두목',
      'ah.foe.magistrate': '탐관오리',
      'ah.foe.imugi': '이무기',
      'ah.foeDesc.bandit': '바로 앞을 벤다.',
      'ah.foeDesc.spearman': '앞 두 칸을 찌른다.',
      'ah.foeDesc.archer': '앞쪽으로 처음 만나는 것을 쏜다. 붙으면 물러선다.',
      'ah.foeDesc.assassin': '바로 앞을 빠르게 벤다.',
      'ah.foeDesc.guard': '방패를 든 쪽에서 오는 피해를 1 줄인다.',
      'ah.foeDesc.dokkaebi': '방망이로 양옆을 후려친다.',
      'ah.foeDesc.gumiho': '닿지 않으면 어사의 등 뒤로 옮겨 간다.',
      'ah.foeDesc.mulgwisin': '앞쪽으로 처음 만나는 것을 끌어당긴다.',
      'ah.foeDesc.chief': '앞 두 칸을 내리치고, 졸개를 부른다.',
      'ah.foeDesc.magistrate': '방패 든 사병을 부르고, 앞에서 오는 피해를 줄인다.',
      'ah.foeDesc.imugi': '앞 세 칸에 불을 뿜고, 뒤는 꼬리로 친다.',

      'ah.region.pass': '고갯길',
      'ah.region.town': '고을',
      'ah.region.mountain': '깊은 산',
      'ah.node.fight': '싸움',
      'ah.node.boss': '우두머리',
      'ah.node.inn': '주막',
      'ah.node.shrine': '서낭당',

      'ah.blessing.pouch': '복주머니',
      'ah.blessing.robe': '두루마기',
      'ah.blessing.water': '정화수',
      'ah.blessing.sash': '허리띠',
      'ah.blessingDesc.pouch': '모든 패를 한 차례 빨리 다시 쓸 수 있다.',
      'ah.blessingDesc.robe': '싸움마다 처음 받는 공격 하나를 막는다.',
      'ah.blessingDesc.water': '싸움이 끝날 때마다 체력 1을 되찾는다.',
      'ah.blessingDesc.sash': '패를 하나 더 쌓아 둘 수 있다.',

      'ah.move': '이동',
      'ah.turn': '돌기',
      'ah.wait': '기다림',
      'ah.unleash': '출두',
      'ah.queue': '쌓은 패',
      'ah.hp': '체력',
      'ah.coins': '엽전',
      'ah.depart': '길을 나선다',
      'ah.newRun': '새 여정',
      'ah.continue': '이어서',
      'ah.next': '다음으로',
      'ah.leave': '떠난다',
      'ah.skip': '받지 않는다',
      'ah.where': '{region} · {n}번째 자리',
      'ah.mapTitle': '{region}',
      'ah.rewardTitle': '패 하나를 고르세요',
      'ah.shrineTitle': '서낭당에 빌어 복 하나를 받습니다',
      'ah.innTitle': '주막',
      'ah.inn.soup': '국밥 (체력 +{heal})',
      'ah.inn.tonic': '보약 (최대 체력 +1)',
      'ah.inn.forge': '대장간: 패 하나 벼리기',
      'ah.inn.tile': '새 패',
      'ah.forgeLv': '+{lv}',
      'ah.cost': '{n}냥',
      'ah.handFull': '패는 {n}개까지 지닐 수 있습니다.',
      'ah.fightWon': '이겼습니다. 엽전 {coins}냥을 받았습니다.',
      'ah.overTitle': '쓰러졌습니다',
      'ah.overNote': '{region}에서 싸움 {fights}번을 이겼습니다.',
      'ah.wonTitle': '이무기를 물리쳤습니다',
      'ah.wonNote': '모든 고을을 지나 여정을 마쳤습니다. 싸움 {fights}번.',
      'ah.best': '가장 멀리 간 곳: {where}',
      'ah.cantMove': '그쪽으로는 갈 수 없습니다.',
      'ah.cantQueue': '지금은 쌓을 수 없습니다.',
      'ah.emptyQueue': '쌓은 패가 없습니다.',
      'ah.blocked': '막았다',
      'ah.ward': '두루마기가 막았다',
      'ah.intent': '{n}차례 뒤 공격',
      'ah.stunned': '묶임 {n}',

      'ah.rule1': '한 줄 길 위에서 싸웁니다. <b>어사가 한 가지를 하면 적이 모두 한 번씩 움직입니다</b> — 움직이기, 돌아서기, 기다리기, 패 쌓기, 출두가 모두 한 가지입니다.',
      'ah.rule2': '적의 머리 위 숫자는 <b>공격까지 남은 차례</b>이고, 칠 칸은 붉게 칠해집니다. 0이 되는 순간 그 칸에 없으면 헛칩니다. 적의 공격은 <b>제 편도 맞힙니다</b>.',
      'ah.rule3': '패를 누르면 <b>쌓이고</b>, <b>출두</b>를 누르면 쌓은 차례대로 한꺼번에 나갑니다. 쌓는 데도 차례가 들어 적이 움직이므로, 칠 칸이 노랗게 미리 보입니다. 쓴 패는 숫자만큼 차례가 지나야 다시 쓸 수 있습니다.',
      'ah.rule4': '어사는 <b>바라보는 쪽</b>으로만 칩니다. 움직여도 방향은 그대로이고, 돌아서는 데 한 차례가 듭니다. 축지법은 적을 넘어가며 돌아서고, 사병의 방패는 앞에서 오는 피해만 줄입니다.',
      'ah.rule5': '고을마다 싸움 몇 번과 우두머리가 기다립니다. 싸움에서 번 엽전은 <b>주막</b>에서 국밥·보약·새 패·벼리기에 쓰고, <b>서낭당</b>에서는 복 하나를 받습니다. 쓰러지면 여정을 처음부터 다시 합니다.',
      'ah.rule6': '키보드: 방향키 이동, <b>T</b> 돌기, <b>스페이스</b> 기다림, <b>1~6</b> 패 쌓기, <b>엔터</b> 출두.'
    }
  });
})();
