// 이 게임에만 나오는 문구. 난이도와 공통 단추 이름은 shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '주사위 다섯 개를 세 번 굴려 열두 칸을 채우는 점수 놀이',
      'yacht.players': '인원',
      'yacht.playerCount': '{n}인',
      'yacht.me': '나',
      'yacht.other': '{n}번',
      'yacht.face': '{face}의 눈',
      'yacht.bonus': '보너스 ({at})',
      'yacht.total': '합계',
      'yacht.round': '{round} / {total}판',
      'yacht.end': '끝',
      'yacht.myTurn': '<b class="p1">내 차례</b>',
      'yacht.otherTurn': '<b class="p{n}">{n}번</b> 차례',
      'yacht.over': '판이 끝났습니다',
      'yacht.waiting': '{n}번 차례…',
      'yacht.roll': '굴리기',
      'yacht.pickCell': '적을 칸을 고르세요',
      'yacht.reroll': '다시 굴리기 · {left}번 남음',
      'yacht.lastRoll': '마지막 굴림입니다. 적을 칸을 고르세요.',
      'yacht.holdHint': '남길 주사위를 눌러 잡아 두세요.',
      'yacht.zeroConfirm': '<b>{name}</b>에 0점을 적습니다. 한 번 더 누르면 확정됩니다.',
      'yacht.wrote': '<b>{name}</b>에 {score}점',
      'yacht.bonusGot': '위 칸 {at}점을 넘겨 <b>보너스 {bonus}점</b>',
      'yacht.otherWrote': '<b class="p{n}">{n}번</b>이 {name}에 {score}점',
      'yacht.win': '이겼습니다 · {score}점',
      'yacht.rank': '{rank}등 · {score}점',
      'yacht.lineMe': '나 {total}',
      'yacht.lineOther': '{n}번 {total}',
      'yacht.bestNote': '내 최고 기록입니다',
      'yacht.rollFirst': '먼저 주사위를 굴리세요.',
      'yacht.cat.choice': '초이스',
      'yacht.cat.four': '4다이스',
      'yacht.cat.full': '풀하우스',
      'yacht.cat.small': 'S.스트레이트',
      'yacht.cat.large': 'L.스트레이트',
      'yacht.cat.yacht': '야추',
      'yacht.rule1': '주사위 다섯 개를 <b>한 판에 세 번까지</b> 굴립니다. 남기고 싶은 주사위를 눌러 <b>잡아 두고</b> 나머지만 다시 굴립니다.',
      'yacht.rule2': '굴린 뒤 <b>점수판의 빈 칸</b>을 누르면 그 칸에 적히고 다음 판으로 넘어갑니다. 빈 칸에는 지금 주사위로 받을 점수가 <b>흐리게</b> 미리 보입니다.',
      'yacht.rule3': '차례는 <b>돌아가며</b> 옵니다. 모두가 열두 칸을 채우면 끝나고, <b>합계가 가장 높은 자리가 이깁니다.</b> <b>0점으로 버리는 칸</b>을 언제 쓸지가 이 놀이의 전부입니다.',
      'yacht.rule4': '판 위의 점수판은 <b>지금 차례인 자리의 것</b>입니다. 상대 차례에는 상대가 무엇을 적는지 그대로 보입니다.',
      'yacht.rule5': '<b>위 여섯 칸</b>은 그 눈의 개수만큼 받습니다(3이 셋이면 9점). 위 칸 합이 <b>63점을 넘기면 보너스 35점</b>이 붙습니다 — 눈마다 셋씩 채우면 딱 63점입니다.',
      'yacht.rule6': '<b>초이스</b>는 다섯 눈의 합, <b>4다이스</b>는 같은 눈이 넷 이상일 때 다섯 눈의 합, <b>풀하우스</b>는 셋 + 둘일 때 다섯 눈의 합입니다.',
      'yacht.rule7': '<b>S.스트레이트</b>는 넉 줄로 이어지면 15점, <b>L.스트레이트</b>는 닷 줄이면 30점, <b>야추</b>는 다섯이 모두 같으면 50점입니다.',
      'yacht.rule8': '<b>0점을 적을 때만</b> 한 번 더 눌러 확인합니다. 값비싼 칸을 손이 미끄러져 버리는 일을 막으려는 것입니다.',
      'yacht.rule9': '<b>난이도</b>는 판을 다시 만들지 않고 언제든 바꿀 수 있습니다.'
    },
    en: {
      'meta.desc': 'Roll five dice up to three times and fill twelve scoring boxes',
      'yacht.players': 'Players',
      'yacht.playerCount': '{n} players',
      'yacht.me': 'You',
      'yacht.other': 'P{n}',
      'yacht.face': '{face}s',
      'yacht.bonus': 'Bonus ({at})',
      'yacht.total': 'Total',
      'yacht.round': 'Round {round} / {total}',
      'yacht.end': 'End',
      'yacht.myTurn': '<b class="p1">Your turn</b>',
      'yacht.otherTurn': '<b class="p{n}">Player {n}</b>’s turn',
      'yacht.over': 'The game is over',
      'yacht.waiting': 'Player {n}’s turn…',
      'yacht.roll': 'Roll',
      'yacht.pickCell': 'Pick a box to score',
      'yacht.reroll': 'Roll again · {left} left',
      'yacht.lastRoll': 'That was the last roll. Pick a box to score.',
      'yacht.holdHint': 'Tap the dice you want to keep.',
      'yacht.zeroConfirm': 'Scoring <b>{name}</b> as 0. Tap again to confirm.',
      'yacht.wrote': '{score} in <b>{name}</b>',
      'yacht.bonusGot': 'Upper section past {at} — <b>bonus {bonus}</b>',
      'yacht.otherWrote': '<b class="p{n}">Player {n}</b> scored {score} in {name}',
      'yacht.win': 'You win · {score}',
      'yacht.rank': 'Place {rank} · {score}',
      'yacht.lineMe': 'You {total}',
      'yacht.lineOther': 'P{n} {total}',
      'yacht.bestNote': 'your best score yet',
      'yacht.rollFirst': 'Roll the dice first.',
      'yacht.cat.choice': 'Chance',
      'yacht.cat.four': 'Four of a kind',
      'yacht.cat.full': 'Full house',
      'yacht.cat.small': 'Small straight',
      'yacht.cat.large': 'Large straight',
      'yacht.cat.yacht': 'Yacht',
      'yacht.rule1': 'Roll five dice <b>up to three times a turn</b>. Tap the dice you want to <b>hold</b> and reroll the rest.',
      'yacht.rule2': 'After a roll, tap an <b>empty box on the scoresheet</b> to write the score there and pass the turn. Empty boxes show what your current dice would score, <b>greyed out</b>.',
      'yacht.rule3': 'Turns go <b>round the table</b>. The game ends when everyone has filled twelve boxes, and the <b>highest total wins</b>. Knowing when to <b>sacrifice a box for zero</b> is the whole game.',
      'yacht.rule4': 'The scoresheet on screen belongs to <b>whoever is up right now</b>. On someone else’s turn you watch what they write.',
      'yacht.rule5': 'The <b>upper six boxes</b> score the pips of that face (three 3s is 9). If the upper section passes <b>63, you get a 35-point bonus</b> — three of each face is exactly 63.',
      'yacht.rule6': '<b>Chance</b> is the sum of all five dice, <b>four of a kind</b> is the sum when four or more match, and a <b>full house</b> is the sum on three plus two.',
      'yacht.rule7': 'A <b>small straight</b> is four in a row for 15, a <b>large straight</b> is five in a row for 30, and a <b>yacht</b> is all five alike for 50.',
      'yacht.rule8': '<b>Only a zero</b> asks you to tap again to confirm. It keeps a slipped finger from throwing away an expensive box.',
      'yacht.rule9': 'You can change the <b>difficulty</b> at any time without starting a new game.'
    },
    ja: {
      'meta.desc': 'サイコロ五つを三回まで振って十二のマスを埋める得点遊び',
      'yacht.players': '人数',
      'yacht.playerCount': '{n}人',
      'yacht.me': '自分',
      'yacht.other': '{n}番',
      'yacht.face': '{face}の目',
      'yacht.bonus': 'ボーナス ({at})',
      'yacht.total': '合計',
      'yacht.round': '{round} / {total}回',
      'yacht.end': '終了',
      'yacht.myTurn': '<b class="p1">自分の番</b>',
      'yacht.otherTurn': '<b class="p{n}">{n}番</b>の番',
      'yacht.over': 'ゲームが終わりました',
      'yacht.waiting': '{n}番の番…',
      'yacht.roll': '振る',
      'yacht.pickCell': '書くマスを選んでください',
      'yacht.reroll': 'もう一度振る · 残り{left}回',
      'yacht.lastRoll': '最後の振りです。書くマスを選んでください。',
      'yacht.holdHint': '残したいサイコロを押して押さえてください。',
      'yacht.zeroConfirm': '<b>{name}</b>に0点を書きます。もう一度押すと確定します。',
      'yacht.wrote': '<b>{name}</b>に{score}点',
      'yacht.bonusGot': '上段が{at}点を超えて<b>ボーナス{bonus}点</b>',
      'yacht.otherWrote': '<b class="p{n}">{n}番</b>が{name}に{score}点',
      'yacht.win': '勝ちました · {score}点',
      'yacht.rank': '{rank}位 · {score}点',
      'yacht.lineMe': '自分 {total}',
      'yacht.lineOther': '{n}番 {total}',
      'yacht.bestNote': '自己ベストです',
      'yacht.rollFirst': 'まずサイコロを振ってください。',
      'yacht.cat.choice': 'チョイス',
      'yacht.cat.four': 'フォーダイス',
      'yacht.cat.full': 'フルハウス',
      'yacht.cat.small': 'S.ストレート',
      'yacht.cat.large': 'L.ストレート',
      'yacht.cat.yacht': 'ヨット',
      'yacht.rule1': 'サイコロ五つを<b>一回の手番に三回まで</b>振ります。残したいサイコロを押して<b>押さえ</b>、残りだけ振り直します。',
      'yacht.rule2': '振ったあと<b>得点表の空きマス</b>を押すと、そこに書かれて次の手番に移ります。空きマスには今の出目で入る点が<b>薄く</b>先に見えます。',
      'yacht.rule3': '手番は<b>順に回ります</b>。全員が十二マスを埋めると終わり、<b>合計がいちばん高い人の勝ち</b>です。<b>0点で捨てるマス</b>をいつ使うかがこの遊びのすべてです。',
      'yacht.rule4': '画面の得点表は<b>いまの手番の人のもの</b>です。相手の番には相手が何を書くかそのまま見えます。',
      'yacht.rule5': '<b>上の六マス</b>はその目の数だけもらえます（3が三つで9点）。上段の合計が<b>63点を超えるとボーナス35点</b>が付きます — 各目を三つずつ埋めるとちょうど63点です。',
      'yacht.rule6': '<b>チョイス</b>は五つの目の合計、<b>フォーダイス</b>は同じ目が四つ以上あるときの合計、<b>フルハウス</b>は三つ＋二つのときの合計です。',
      'yacht.rule7': '<b>S.ストレート</b>は四つ続けば15点、<b>L.ストレート</b>は五つ続けば30点、<b>ヨット</b>は五つとも同じで50点です。',
      'yacht.rule8': '<b>0点を書くときだけ</b>もう一度押して確認します。高いマスを指が滑って捨ててしまうのを防ぐためです。',
      'yacht.rule9': '<b>難易度</b>は盤を作り直さずいつでも変えられます。'
    },
    'zh-CN': {
      'meta.desc': '五颗骰子最多掷三次，填满十二个计分格的点数游戏',
      'yacht.players': '人数',
      'yacht.playerCount': '{n} 人',
      'yacht.me': '我',
      'yacht.other': '{n} 号',
      'yacht.face': '{face} 点',
      'yacht.bonus': '奖励 ({at})',
      'yacht.total': '合计',
      'yacht.round': '第 {round} / {total} 轮',
      'yacht.end': '结束',
      'yacht.myTurn': '<b class="p1">轮到我</b>',
      'yacht.otherTurn': '轮到 <b class="p{n}">{n} 号</b>',
      'yacht.over': '这一局结束了',
      'yacht.waiting': '轮到 {n} 号…',
      'yacht.roll': '掷骰',
      'yacht.pickCell': '选一个格子记分',
      'yacht.reroll': '再掷一次 · 还剩 {left} 次',
      'yacht.lastRoll': '这是最后一次掷骰，选个格子记分吧。',
      'yacht.holdHint': '点一下想留下的骰子把它按住。',
      'yacht.zeroConfirm': '要在<b>{name}</b>记 0 分。再点一次确认。',
      'yacht.wrote': '<b>{name}</b> 记 {score} 分',
      'yacht.bonusGot': '上区超过 {at} 分，<b>奖励 {bonus} 分</b>',
      'yacht.otherWrote': '<b class="p{n}">{n} 号</b>在 {name} 记了 {score} 分',
      'yacht.win': '赢了 · {score} 分',
      'yacht.rank': '第 {rank} 名 · {score} 分',
      'yacht.lineMe': '我 {total}',
      'yacht.lineOther': '{n} 号 {total}',
      'yacht.bestNote': '这是我的最好成绩',
      'yacht.rollFirst': '先掷骰子。',
      'yacht.cat.choice': '全选',
      'yacht.cat.four': '四条',
      'yacht.cat.full': '葫芦',
      'yacht.cat.small': '小顺',
      'yacht.cat.large': '大顺',
      'yacht.cat.yacht': '快艇',
      'yacht.rule1': '五颗骰子<b>每轮最多掷三次</b>。点一下想留的骰子把它<b>按住</b>，只重掷其余的。',
      'yacht.rule2': '掷完后点<b>计分表上的空格</b>，分数就记在那里并轮到下一位。空格里会<b>淡淡地</b>先显示当前骰子能得的分。',
      'yacht.rule3': '大家<b>轮流</b>来。所有人填满十二格就结束，<b>总分最高的赢</b>。什么时候<b>把一格舍成 0 分</b>，就是这个游戏的全部。',
      'yacht.rule4': '屏幕上的计分表是<b>当前轮到那一位的</b>。轮到别人时，你能看到他写了什么。',
      'yacht.rule5': '<b>上面六格</b>按那个点数的个数算分（三个 3 就是 9 分）。上区合计<b>超过 63 分有 35 分奖励</b> —— 每种点数各三个正好 63。',
      'yacht.rule6': '<b>全选</b>是五颗之和，<b>四条</b>是有四颗以上相同时的五颗之和，<b>葫芦</b>是三加二时的五颗之和。',
      'yacht.rule7': '<b>小顺</b>是连着四颗得 15 分，<b>大顺</b>是连着五颗得 30 分，<b>快艇</b>是五颗全同得 50 分。',
      'yacht.rule8': '<b>只有记 0 分时</b>才需要再点一次确认，免得手滑舍掉值钱的格子。',
      'yacht.rule9': '<b>难度</b>随时可以改，不用重开一局。'
    },
    'zh-TW': {
      'meta.desc': '五顆骰子最多擲三次，填滿十二個計分格的點數遊戲',
      'yacht.players': '人數',
      'yacht.playerCount': '{n} 人',
      'yacht.me': '我',
      'yacht.other': '{n} 號',
      'yacht.face': '{face} 點',
      'yacht.bonus': '獎勵 ({at})',
      'yacht.total': '合計',
      'yacht.round': '第 {round} / {total} 輪',
      'yacht.end': '結束',
      'yacht.myTurn': '<b class="p1">輪到我</b>',
      'yacht.otherTurn': '輪到 <b class="p{n}">{n} 號</b>',
      'yacht.over': '這一局結束了',
      'yacht.waiting': '輪到 {n} 號…',
      'yacht.roll': '擲骰',
      'yacht.pickCell': '選一個格子記分',
      'yacht.reroll': '再擲一次 · 還剩 {left} 次',
      'yacht.lastRoll': '這是最後一次擲骰，選個格子記分吧。',
      'yacht.holdHint': '點一下想留下的骰子把它按住。',
      'yacht.zeroConfirm': '要在<b>{name}</b>記 0 分。再點一次確認。',
      'yacht.wrote': '<b>{name}</b> 記 {score} 分',
      'yacht.bonusGot': '上區超過 {at} 分，<b>獎勵 {bonus} 分</b>',
      'yacht.otherWrote': '<b class="p{n}">{n} 號</b>在 {name} 記了 {score} 分',
      'yacht.win': '贏了 · {score} 分',
      'yacht.rank': '第 {rank} 名 · {score} 分',
      'yacht.lineMe': '我 {total}',
      'yacht.lineOther': '{n} 號 {total}',
      'yacht.bestNote': '這是我的最佳成績',
      'yacht.rollFirst': '先擲骰子。',
      'yacht.cat.choice': '全選',
      'yacht.cat.four': '四條',
      'yacht.cat.full': '葫蘆',
      'yacht.cat.small': '小順',
      'yacht.cat.large': '大順',
      'yacht.cat.yacht': '快艇',
      'yacht.rule1': '五顆骰子<b>每輪最多擲三次</b>。點一下想留的骰子把它<b>按住</b>，只重擲其餘的。',
      'yacht.rule2': '擲完後點<b>計分表上的空格</b>，分數就記在那裡並輪到下一位。空格裡會<b>淡淡地</b>先顯示目前骰子能得的分。',
      'yacht.rule3': '大家<b>輪流</b>來。所有人填滿十二格就結束，<b>總分最高的贏</b>。什麼時候<b>把一格捨成 0 分</b>，就是這個遊戲的全部。',
      'yacht.rule4': '螢幕上的計分表是<b>目前輪到那一位的</b>。輪到別人時，你能看到他寫了什麼。',
      'yacht.rule5': '<b>上面六格</b>按那個點數的個數算分（三個 3 就是 9 分）。上區合計<b>超過 63 分有 35 分獎勵</b> —— 每種點數各三個正好 63。',
      'yacht.rule6': '<b>全選</b>是五顆之和，<b>四條</b>是有四顆以上相同時的五顆之和，<b>葫蘆</b>是三加二時的五顆之和。',
      'yacht.rule7': '<b>小順</b>是連著四顆得 15 分，<b>大順</b>是連著五顆得 30 分，<b>快艇</b>是五顆全同得 50 分。',
      'yacht.rule8': '<b>只有記 0 分時</b>才需要再點一次確認，免得手滑捨掉值錢的格子。',
      'yacht.rule9': '<b>難度</b>隨時可以改，不用重開一局。'
    },
    es: {
      'meta.desc': 'Tira cinco dados hasta tres veces y rellena doce casillas de puntuación',
      'yacht.players': 'Jugadores',
      'yacht.playerCount': '{n} jugadores',
      'yacht.me': 'Yo',
      'yacht.other': 'J{n}',
      'yacht.face': 'Cara {face}',
      'yacht.bonus': 'Bonus ({at})',
      'yacht.total': 'Total',
      'yacht.round': 'Ronda {round} / {total}',
      'yacht.end': 'Fin',
      'yacht.myTurn': '<b class="p1">Tu turno</b>',
      'yacht.otherTurn': 'Turno de <b class="p{n}">jugador {n}</b>',
      'yacht.over': 'La partida ha terminado',
      'yacht.waiting': 'Turno del jugador {n}…',
      'yacht.roll': 'Tirar',
      'yacht.pickCell': 'Elige una casilla para anotar',
      'yacht.reroll': 'Tirar otra vez · quedan {left}',
      'yacht.lastRoll': 'Era la última tirada. Elige una casilla para anotar.',
      'yacht.holdHint': 'Toca los dados que quieras conservar.',
      'yacht.zeroConfirm': 'Vas a anotar 0 en <b>{name}</b>. Toca otra vez para confirmar.',
      'yacht.wrote': '{score} en <b>{name}</b>',
      'yacht.bonusGot': 'La sección alta pasa de {at}: <b>bonus de {bonus}</b>',
      'yacht.otherWrote': '<b class="p{n}">Jugador {n}</b> anotó {score} en {name}',
      'yacht.win': '¡Has ganado! · {score}',
      'yacht.rank': 'Puesto {rank} · {score}',
      'yacht.lineMe': 'Yo {total}',
      'yacht.lineOther': 'J{n} {total}',
      'yacht.bestNote': 'tu mejor marca hasta ahora',
      'yacht.rollFirst': 'Tira los dados primero.',
      'yacht.cat.choice': 'Chance',
      'yacht.cat.four': 'Póker',
      'yacht.cat.full': 'Full',
      'yacht.cat.small': 'Escalera corta',
      'yacht.cat.large': 'Escalera larga',
      'yacht.cat.yacht': 'Yacht',
      'yacht.rule1': 'Tira cinco dados <b>hasta tres veces por turno</b>. Toca los que quieras <b>conservar</b> y vuelve a tirar el resto.',
      'yacht.rule2': 'Tras la tirada, toca una <b>casilla vacía de la hoja</b> para anotar ahí y pasar el turno. Las casillas vacías muestran <b>en gris</b> lo que puntuarían con los dados actuales.',
      'yacht.rule3': 'Los turnos van <b>por orden</b>. La partida acaba cuando todos llenan doce casillas y <b>gana el total más alto</b>. Saber cuándo <b>sacrificar una casilla con un cero</b> es todo el juego.',
      'yacht.rule4': 'La hoja en pantalla es la de <b>quien tiene el turno ahora</b>. En el turno ajeno ves lo que anota el rival.',
      'yacht.rule5': 'Las <b>seis casillas de arriba</b> suman los puntos de esa cara (tres treses son 9). Si la sección alta pasa de <b>63, hay un bonus de 35</b>: tres de cada cara son exactamente 63.',
      'yacht.rule6': '<b>Chance</b> es la suma de los cinco dados, el <b>póker</b> es la suma con cuatro o más iguales, y el <b>full</b> es la suma con tres más dos.',
      'yacht.rule7': 'La <b>escalera corta</b> son cuatro seguidos y vale 15, la <b>larga</b> son cinco seguidos y vale 30, y el <b>yacht</b> son cinco iguales y vale 50.',
      'yacht.rule8': '<b>Solo al anotar un cero</b> se pide confirmar con un segundo toque. Así un resbalón no tira una casilla cara.',
      'yacht.rule9': 'Puedes cambiar la <b>dificultad</b> en cualquier momento sin empezar de nuevo.'
    }
  });
})();
