// 이 게임에만 나오는 문구. 문제 자료는 주제·제목·힌트를 열쇠로만 들고 있고,
// 실제 문장은 여기 있다 — 구워 둔 자료가 한 언어에 묶이지 않게 하기 위해서다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '한 수로 판을 뒤집는 전술을 찾는 체스 퍼즐',
      'cp.board': '체스판',
      'cp.promotionTitle': '무엇으로 승격할까요?',
      'cp.replay': '이어지는 수순 보기',
      'cp.replayAgain': '다시 보기',
      'cp.replaying': '두는 중…',
      'cp.next': '다음 문제',
      'cp.source': '퍼즐 출처: Lichess Puzzle Database · CC0',
      'cp.count': '문제 {index} / {total}',
      'cp.rating': '레이팅 {rating}',
      'cp.sideWhite': '내가 백',
      'cp.sideBlack': '내가 흑',
      'cp.loading': '문제를 불러오는 중…',
      'cp.loadFailed': '문제를 불러오지 못했습니다. 연결을 확인하고 다시 눌러 보세요.',
      'cp.turnWhite': '백 차례입니다. 가장 강한 수를 찾아보세요.',
      'cp.turnBlack': '흑 차례입니다. 가장 강한 수를 찾아보세요.',
      'cp.illegal': '그 수는 체스 규칙에 맞지 않습니다.',
      'cp.notBest': '규칙에는 맞지만 가장 강한 수가 아닙니다. 다시 보세요.',
      'cp.reply': '상대가 최선으로 응수합니다…',
      'cp.keepGoing': '계속해서 가장 강한 수를 두세요.',
      'cp.solvedMate': '체크메이트! 문제를 풀었습니다.',
      'cp.solved': '정답입니다! 문제를 풀었습니다.',
      'cp.hintShown': '{hint} 움직일 말을 표시했습니다.',
      'cp.emptySquare': '{square} 빈 칸',
      'cp.pieceAt': '{square} {color} {piece}',
      'cp.white': '백',
      'cp.black': '흑',
      'cp.rule1': '각 문제는 실제로 둔 대국에서 나온 자리입니다. <b>상대가 방금 실수를 두었고, 그 자리에서 가장 강한 수를 찾는 것</b>이 목표입니다.',
      'cp.rule2': '<b>난이도는 세 단계이고, 레이팅으로 나뉩니다.</b> 레이팅은 그 문제를 푼 수많은 사람들의 성적으로 매겨진 값입니다 — 쉬움은 1200 아래, 보통은 1400~1900, 어려움은 2000 위입니다. 난이도를 고르면 그 난이도의 문제만 나옵니다.',
      'cp.rule3': '<b>판은 항상 내 쪽이 아래입니다.</b> 내가 흑이면 판이 뒤집혀 보입니다. 지금 어느 쪽인지는 위에 적혀 있습니다.',
      'cp.rule4': '말을 누르면 <b>갈 수 있는 칸이 점으로 표시</b>됩니다. 체스 규칙에 어긋나는 수는 애초에 둘 수 없습니다.',
      'cp.rule5': '규칙에 맞아도 <b>가장 강한 수가 아니면 정답이 아닙니다.</b> 다만 <b>메이트가 여럿인 자리에서는 어느 메이트든 정답</b>으로 봅니다.',
      'cp.rule6': '정답을 두면 <b>상대가 최선으로 응수</b>하고, 수순이 끝날 때까지 이어집니다.',
      'cp.rule7': '<b>다 풀고 나면 왜 그 수가 이겼는지</b>를 알려 줍니다. 수순을 끝까지 둔 자리에서 말을 얼마나 벌었는지, 메이트로 이어지는지를 세어 적은 것입니다 — 특히 손해처럼 보이는 수를 두는 문제에서, 두고 나도 무엇을 얻었는지 안 보일 때를 위한 것입니다.',
      'cp.rule8': '<b>힌트</b>는 어떤 말을 움직여야 하는지까지만 알려 줍니다. <b>다시</b>는 지금 문제를 처음부터 놓습니다.',
      'cp.rule9': '노란 테두리는 <b>직전에 움직인 수</b>, 붉은 테두리는 <b>체크를 받고 있는 킹</b>입니다.',
      'cp.rule10': '<b>문제는 무작위 순서로 나옵니다.</b> 다만 그 순서는 한 번 정해지면 그대로라, 창을 닫았다 열어도 풀던 자리에서 이어집니다.',
      'cp.theme.smotheredMate': '질식 메이트',
      'cp.theme.backRankMate': '백 랭크 메이트',
      'cp.theme.doubleCheck': '더블 체크',
      'cp.theme.discoveredCheck': '발견 체크',
      'cp.theme.discoveredAttack': '발견 공격',
      'cp.theme.skewer': '스큐어',
      'cp.theme.pin': '핀',
      'cp.theme.fork': '포크',
      'cp.theme.deflection': '수비 이탈',
      'cp.theme.attraction': '유인',
      'cp.theme.clearance': '길 비우기',
      'cp.theme.interference': '차단',
      'cp.theme.intermezzo': '중간 수',
      'cp.theme.capturingDefender': '수비 말 잡기',
      'cp.theme.xRayAttack': '엑스레이 공격',
      'cp.theme.trappedPiece': '갇힌 말',
      'cp.theme.zugzwang': '추크츠방',
      'cp.theme.enPassant': '앙파상',
      'cp.theme.castling': '캐슬링',
      'cp.theme.underPromotion': '낮은 승격',
      'cp.theme.promotion': '승격',
      'cp.theme.advancedPawn': '전진한 폰',
      'cp.theme.sacrifice': '희생',
      'cp.theme.mateIn1': '한 수 메이트',
      'cp.theme.mateIn2': '두 수 메이트',
      'cp.theme.mateIn3': '세 수 메이트',
      'cp.theme.mateIn4': '긴 메이트',
      'cp.theme.mate': '메이트',
      'cp.theme.quietMove': '조용한 수',
      'cp.theme.defensiveMove': '수비수',
      'cp.theme.hangingPiece': '지켜지지 않은 말',
      'cp.theme.attackingF2F7': '약한 칸 공격',
      'cp.theme.exposedKing': '드러난 킹',
      'cp.theme.kingsideAttack': '킹사이드 공격',
      'cp.theme.queensideAttack': '퀸사이드 공격',
      'cp.theme.pawnEndgame': '폰 종반',
      'cp.theme.rookEndgame': '룩 종반',
      'cp.theme.bishopEndgame': '비숍 종반',
      'cp.theme.knightEndgame': '나이트 종반',
      'cp.theme.queenEndgame': '퀸 종반',
      'cp.theme.opening': '오프닝',
      'cp.theme.middlegame': '중반',
      'cp.theme.endgame': '종반',
      'cp.theme.tactic': '전술',
      'cp.title.smotheredMate': '빠져나갈 곳이 없다',
      'cp.title.backRankMate': '맨 끝 줄',
      'cp.title.doubleCheck': '두 곳에서 동시에',
      'cp.title.discoveredCheck': '비켜서면 체크',
      'cp.title.discoveredAttack': '열린 길',
      'cp.title.skewer': '앞의 말을 밀어낸다',
      'cp.title.pin': '묶인 말',
      'cp.title.deflection': '수비를 떼어낸다',
      'cp.title.attraction': '불러들인다',
      'cp.title.clearance': '길을 비운다',
      'cp.title.interference': '사이를 끊는다',
      'cp.title.intermezzo': '그전에 한 수',
      'cp.title.capturingDefender': '지키는 말을 잡는다',
      'cp.title.xRayAttack': '말을 꿰뚫어',
      'cp.title.trappedPiece': '갈 곳이 없다',
      'cp.title.zugzwang': '둘 수가 없다',
      'cp.title.enPassant': '지나쳐 잡는다',
      'cp.title.underPromotion': '퀸이 아니다',
      'cp.title.advancedPawn': '끝줄이 가깝다',
      'cp.title.quietMove': '조용한 한 수',
      'cp.title.defensiveMove': '먼저 막는다',
      'cp.title.hangingPiece': '그냥 놓여 있다',
      'cp.title.mateLine': '메이트로 가는 길',
      'cp.title.promotionTitle': '끝까지 간 폰',
      'cp.title.mateIn1': '{piece} 끝낸다',
      'cp.title.sacrifice': '{piece} 내준다',
      'cp.title.fork': '{piece} 둘을 노린다',
      'cp.title.hanging': '{piece} 놓여 있다',
      'cp.title.undefended': '{piece} 지켜지지 않았다',
      'cp.title.press': '{piece} 몰아붙인다',
      'cp.hint.smotheredMate': '킹의 도망 칸을 자기 말이 막고 있습니다.',
      'cp.hint.backRankMate': '킹이 폰 뒤에 갇혀 있습니다.',
      'cp.hint.doubleCheck': '두 말이 함께 체크를 겁니다. 막을 수 없습니다.',
      'cp.hint.discoveredCheck': '한 말이 비켜서면 뒤의 말이 체크를 겁니다.',
      'cp.hint.discoveredAttack': '한 말이 비켜서면 뒤의 말이 노리는 것이 드러납니다.',
      'cp.hint.skewer': '값진 말을 먼저 겨누면 뒤의 말이 남습니다.',
      'cp.hint.pin': '움직이면 뒤가 드러나는 말이 있습니다.',
      'cp.hint.deflection': '무언가를 지키고 있는 말을 다른 곳으로 부르세요.',
      'cp.hint.attraction': '상대 말을 원하는 칸으로 끌어내 보세요.',
      'cp.hint.clearance': '내 말이 내 길을 막고 있습니다.',
      'cp.hint.interference': '지키는 말과 지켜지는 말 사이를 막아 보세요.',
      'cp.hint.intermezzo': '되잡기 전에 먼저 끼워 넣을 수가 있습니다.',
      'cp.hint.capturingDefender': '무언가를 지키고 있는 말부터 없애 보세요.',
      'cp.hint.xRayAttack': '내 말 너머까지 이어지는 줄을 보세요.',
      'cp.hint.trappedPiece': '도망갈 칸이 없는 말이 있습니다.',
      'cp.hint.zugzwang': '상대는 무엇을 두든 나빠집니다.',
      'cp.hint.enPassant': '방금 두 칸 나온 폰을 앙파상으로 잡을 수 있습니다.',
      'cp.hint.underPromotion': '퀸 말고 다른 말로 승격해 보세요.',
      'cp.hint.advancedPawn': '깊이 들어간 폰을 보세요.',
      'cp.hint.quietMove': '잡지도 체크하지도 않는 수입니다.',
      'cp.hint.defensiveMove': '공격보다 지키는 수가 필요한 자리입니다.',
      'cp.hint.hangingPiece': '아무도 지키지 않는 말이 있습니다.',
      'cp.hint.mateIn1': '한 번에 끝낼 수 있습니다.',
      'cp.hint.mateLine': '피할 곳을 좁혀 가면 메이트가 보입니다.',
      'cp.hint.sacrifice': '손해처럼 보이는 수를 한 번 따져 보세요.',
      'cp.hint.fork': '한 수로 두 개를 동시에 노릴 수 있습니다.',
      'cp.hint.promotionHint': '폰이 끝 줄에 닿습니다.',
      'cp.hint.capture': '지켜지지 않은 말이 있습니다.',
      'cp.hint.check': '체크를 걸어 상대를 몰아 보세요.',
      'cp.why.mateNow': '체크메이트입니다.',
      'cp.why.mateLine': '수순을 다 두면 체크메이트입니다.',
      'cp.why.bigGain': '수순을 다 두면 말을 크게 벌어 둡니다(폰 {gain}개 값).',
      'cp.why.gain': '수순을 다 두면 폰 {gain}개 값만큼 앞섭니다.',
      'cp.why.gaveCrushing': '말을 내주고도 판이 결정적으로 기웁니다.',
      'cp.why.gaveBetter': '말을 내주고도 자리가 좋아집니다.',
      'cp.why.crushing': '잡은 것은 없어도 자리가 결정적으로 좋아집니다.',
      'cp.why.advantage': '잡은 것은 없어도 뚜렷하게 유리해집니다.',
      'cp.why.equality': '불리하던 판을 다시 팽팽하게 돌려놓습니다.',
      'cp.why.better': '잡은 것은 없어도 자리가 좋아집니다.',
      'cp.piece.k': '킹',
      'cp.piece.q': '퀸',
      'cp.piece.r': '룩',
      'cp.piece.b': '비숍',
      'cp.piece.n': '나이트',
      'cp.piece.p': '폰'
    },
    en: {
      'meta.desc': 'Chess puzzles: find the move that turns the game around',
      'cp.board': 'Chess board',
      'cp.promotionTitle': 'Promote to what?',
      'cp.replay': 'See the rest of the line',
      'cp.replayAgain': 'Watch again',
      'cp.replaying': 'Playing…',
      'cp.next': 'Next puzzle',
      'cp.source': 'Puzzles from the Lichess Puzzle Database · CC0',
      'cp.count': 'Puzzle {index} / {total}',
      'cp.rating': 'Rating {rating}',
      'cp.sideWhite': 'You are White',
      'cp.sideBlack': 'You are Black',
      'cp.loading': 'Loading puzzles…',
      'cp.loadFailed': 'Could not load the puzzles. Check your connection and tap again.',
      'cp.turnWhite': 'White to move. Find the strongest move.',
      'cp.turnBlack': 'Black to move. Find the strongest move.',
      'cp.illegal': 'That move is not legal.',
      'cp.notBest': 'Legal, but not the strongest move. Look again.',
      'cp.reply': 'The opponent answers with the best reply…',
      'cp.keepGoing': 'Keep playing the strongest move.',
      'cp.solvedMate': 'Checkmate! Puzzle solved.',
      'cp.solved': 'That is it! Puzzle solved.',
      'cp.hintShown': '{hint} The piece to move is highlighted.',
      'cp.emptySquare': '{square} empty',
      'cp.pieceAt': '{square} {color} {piece}',
      'cp.white': 'white',
      'cp.black': 'black',
      'cp.rule1': 'Every puzzle comes from a real game. <b>The opponent has just blundered, and your job is to find the strongest move in that position.</b>',
      'cp.rule2': '<b>There are three difficulties, split by rating.</b> The rating comes from how thousands of solvers actually did — easy is under 1200, medium 1400–1900, hard above 2000. Pick a difficulty and you only get puzzles from it.',
      'cp.rule3': '<b>Your side is always at the bottom.</b> If you have Black, the board is flipped. Which side you have is shown above.',
      'cp.rule4': 'Tap a piece and <b>its legal squares appear as dots</b>. An illegal move cannot be played at all.',
      'cp.rule5': 'Legal is not enough: <b>only the strongest move counts.</b> The exception is a position with several mates — <b>there any mate is accepted.</b>',
      'cp.rule6': 'Play the right move and <b>the opponent answers with the best reply</b>, and so on until the line ends.',
      'cp.rule7': '<b>Once solved, it tells you why that move won.</b> It counts the material you end up ahead by after the whole line, and whether it ends in mate — meant for the puzzles where the move looks like a loss and you still cannot see what you gained.',
      'cp.rule8': 'A <b>Hint</b> only tells you which piece to move. <b>Restart</b> sets the current puzzle back to the beginning.',
      'cp.rule9': 'A yellow outline marks <b>the move just played</b>, a red one <b>a king in check</b>.',
      'cp.rule10': '<b>Puzzles come in a random order.</b> That order is fixed once drawn, so closing the tab and coming back picks up where you left off.',
      'cp.theme.smotheredMate': 'Smothered mate',
      'cp.theme.backRankMate': 'Back-rank mate',
      'cp.theme.doubleCheck': 'Double check',
      'cp.theme.discoveredCheck': 'Discovered check',
      'cp.theme.discoveredAttack': 'Discovered attack',
      'cp.theme.skewer': 'Skewer',
      'cp.theme.pin': 'Pin',
      'cp.theme.fork': 'Fork',
      'cp.theme.deflection': 'Deflection',
      'cp.theme.attraction': 'Attraction',
      'cp.theme.clearance': 'Clearance',
      'cp.theme.interference': 'Interference',
      'cp.theme.intermezzo': 'Zwischenzug',
      'cp.theme.capturingDefender': 'Capturing the defender',
      'cp.theme.xRayAttack': 'X-ray attack',
      'cp.theme.trappedPiece': 'Trapped piece',
      'cp.theme.zugzwang': 'Zugzwang',
      'cp.theme.enPassant': 'En passant',
      'cp.theme.castling': 'Castling',
      'cp.theme.underPromotion': 'Underpromotion',
      'cp.theme.promotion': 'Promotion',
      'cp.theme.advancedPawn': 'Advanced pawn',
      'cp.theme.sacrifice': 'Sacrifice',
      'cp.theme.mateIn1': 'Mate in 1',
      'cp.theme.mateIn2': 'Mate in 2',
      'cp.theme.mateIn3': 'Mate in 3',
      'cp.theme.mateIn4': 'Long mate',
      'cp.theme.mate': 'Mate',
      'cp.theme.quietMove': 'Quiet move',
      'cp.theme.defensiveMove': 'Defensive move',
      'cp.theme.hangingPiece': 'Hanging piece',
      'cp.theme.attackingF2F7': 'Weak-square attack',
      'cp.theme.exposedKing': 'Exposed king',
      'cp.theme.kingsideAttack': 'Kingside attack',
      'cp.theme.queensideAttack': 'Queenside attack',
      'cp.theme.pawnEndgame': 'Pawn endgame',
      'cp.theme.rookEndgame': 'Rook endgame',
      'cp.theme.bishopEndgame': 'Bishop endgame',
      'cp.theme.knightEndgame': 'Knight endgame',
      'cp.theme.queenEndgame': 'Queen endgame',
      'cp.theme.opening': 'Opening',
      'cp.theme.middlegame': 'Middlegame',
      'cp.theme.endgame': 'Endgame',
      'cp.theme.tactic': 'Tactics',
      'cp.title.smotheredMate': 'Nowhere to run',
      'cp.title.backRankMate': 'The last rank',
      'cp.title.doubleCheck': 'From two sides at once',
      'cp.title.discoveredCheck': 'Step aside for check',
      'cp.title.discoveredAttack': 'The line opens',
      'cp.title.skewer': 'Push the front piece off',
      'cp.title.pin': 'A pinned piece',
      'cp.title.deflection': 'Pull the defender away',
      'cp.title.attraction': 'Lure it in',
      'cp.title.clearance': 'Clear the way',
      'cp.title.interference': 'Cut in between',
      'cp.title.intermezzo': 'One move first',
      'cp.title.capturingDefender': 'Take the defender',
      'cp.title.xRayAttack': 'Straight through',
      'cp.title.trappedPiece': 'Nowhere to go',
      'cp.title.zugzwang': 'No good move left',
      'cp.title.enPassant': 'Take it in passing',
      'cp.title.underPromotion': 'Not a queen',
      'cp.title.advancedPawn': 'The last rank is close',
      'cp.title.quietMove': 'A quiet move',
      'cp.title.defensiveMove': 'Block it first',
      'cp.title.hangingPiece': 'Just sitting there',
      'cp.title.mateLine': 'The road to mate',
      'cp.title.promotionTitle': 'A pawn all the way',
      'cp.title.mateIn1': 'The {piece} finishes it',
      'cp.title.sacrifice': 'Give up the {piece}',
      'cp.title.fork': 'The {piece} hits two',
      'cp.title.hanging': 'The {piece} is just sitting there',
      'cp.title.undefended': 'The {piece} was left unguarded',
      'cp.title.press': 'The {piece} presses',
      'cp.hint.smotheredMate': 'The king’s escape squares are blocked by its own pieces.',
      'cp.hint.backRankMate': 'The king is shut in behind its pawns.',
      'cp.hint.doubleCheck': 'Two pieces give check at once. It cannot be blocked.',
      'cp.hint.discoveredCheck': 'Move one piece aside and the one behind gives check.',
      'cp.hint.discoveredAttack': 'Move one piece aside and what the piece behind attacks comes into view.',
      'cp.hint.skewer': 'Aim at the valuable piece first and the one behind it is left over.',
      'cp.hint.pin': 'There is a piece that cannot move without exposing what is behind it.',
      'cp.hint.deflection': 'Call the defending piece somewhere else.',
      'cp.hint.attraction': 'Try to lure an enemy piece onto the square you want.',
      'cp.hint.clearance': 'One of your own pieces is in the way.',
      'cp.hint.interference': 'Try blocking the line between the defender and what it defends.',
      'cp.hint.intermezzo': 'There is a move to slip in before recapturing.',
      'cp.hint.capturingDefender': 'Start by removing the piece that is defending.',
      'cp.hint.xRayAttack': 'Look at the line that runs on past your own piece.',
      'cp.hint.trappedPiece': 'There is a piece with no square to run to.',
      'cp.hint.zugzwang': 'Whatever the opponent plays makes things worse.',
      'cp.hint.enPassant': 'The pawn that just went two squares can be taken en passant.',
      'cp.hint.underPromotion': 'Try promoting to something other than a queen.',
      'cp.hint.advancedPawn': 'Look at the pawn that has pushed deep.',
      'cp.hint.quietMove': 'It is a move that neither captures nor checks.',
      'cp.hint.defensiveMove': 'This position calls for defence rather than attack.',
      'cp.hint.hangingPiece': 'There is a piece nobody is defending.',
      'cp.hint.mateIn1': 'You can finish it in one.',
      'cp.hint.mateLine': 'Narrow the escape squares and the mate appears.',
      'cp.hint.sacrifice': 'Give the move that looks like a loss a second thought.',
      'cp.hint.fork': 'One move can hit two things at once.',
      'cp.hint.promotionHint': 'A pawn reaches the last rank.',
      'cp.hint.capture': 'There is an undefended piece.',
      'cp.hint.check': 'Give check and drive the opponent back.',
      'cp.why.mateNow': 'That is checkmate.',
      'cp.why.mateLine': 'Play out the line and it is checkmate.',
      'cp.why.bigGain': 'Play out the line and you come out well ahead in material ({gain} pawns’ worth).',
      'cp.why.gain': 'Play out the line and you are ahead by {gain} pawns’ worth.',
      'cp.why.gaveCrushing': 'You give up material and the position still swings decisively your way.',
      'cp.why.gaveBetter': 'You give up material and still come out better placed.',
      'cp.why.crushing': 'Nothing is captured, but the position becomes decisively better.',
      'cp.why.advantage': 'Nothing is captured, but you come out clearly better.',
      'cp.why.equality': 'It pulls a worse position back to level.',
      'cp.why.better': 'Nothing is captured, but the position improves.',
      'cp.piece.k': 'king',
      'cp.piece.q': 'queen',
      'cp.piece.r': 'rook',
      'cp.piece.b': 'bishop',
      'cp.piece.n': 'knight',
      'cp.piece.p': 'pawn'
    },
    ja: {
      'meta.desc': '一手で局面をひっくり返す戦術を探すチェスパズル',
      'cp.board': 'チェス盤',
      'cp.promotionTitle': '何に昇格しますか？',
      'cp.replay': '続きの手順を見る',
      'cp.replayAgain': 'もう一度見る',
      'cp.replaying': '指しています…',
      'cp.next': '次の問題',
      'cp.source': '出典: Lichess Puzzle Database · CC0',
      'cp.count': '問題 {index} / {total}',
      'cp.rating': 'レーティング {rating}',
      'cp.sideWhite': '自分は白',
      'cp.sideBlack': '自分は黒',
      'cp.loading': '問題を読み込み中…',
      'cp.loadFailed': '問題を読み込めませんでした。接続を確かめてもう一度押してください。',
      'cp.turnWhite': '白の手番です。最善手を探してください。',
      'cp.turnBlack': '黒の手番です。最善手を探してください。',
      'cp.illegal': 'その手はチェスのルールに反します。',
      'cp.notBest': 'ルール上は指せますが最善手ではありません。もう一度見てください。',
      'cp.reply': '相手が最善で応じます…',
      'cp.keepGoing': '続けて最善手を指してください。',
      'cp.solvedMate': 'チェックメイト！問題を解きました。',
      'cp.solved': '正解です！問題を解きました。',
      'cp.hintShown': '{hint}動かす駒を示しました。',
      'cp.emptySquare': '{square} 空きマス',
      'cp.pieceAt': '{square} {color}{piece}',
      'cp.white': '白',
      'cp.black': '黒',
      'cp.rule1': 'どの問題も実際の対局から出た局面です。<b>相手が今ミスをしたところで、その局面の最善手を見つけるのが目標</b>です。',
      'cp.rule2': '<b>難易度は三段階で、レーティングで分かれます。</b>レーティングはその問題を解いた大勢の成績から付いた値です — やさしいは1200未満、ふつうは1400〜1900、むずかしいは2000超です。難易度を選ぶと、その難易度の問題だけが出ます。',
      'cp.rule3': '<b>盤は常に自分の側が下です。</b>自分が黒なら盤が反転して見えます。今どちらかは上に書いてあります。',
      'cp.rule4': '駒を押すと<b>行けるマスが点で表示</b>されます。ルールに反する手はそもそも指せません。',
      'cp.rule5': 'ルールに合っていても<b>最善手でなければ正解ではありません。</b>ただし<b>メイトが複数ある局面では、どのメイトでも正解</b>とします。',
      'cp.rule6': '正解を指すと<b>相手が最善で応じ</b>、手順が終わるまで続きます。',
      'cp.rule7': '<b>解き終えると、なぜその手が勝ちなのか</b>を教えます。手順を最後まで指した局面で駒をどれだけ得したか、メイトにつながるかを数えたものです — 特に損に見える手を指す問題で、指した後も何を得たのか見えないときのためです。',
      'cp.rule8': '<b>ヒント</b>はどの駒を動かすかまでしか教えません。<b>やり直す</b>は今の問題を最初から並べ直します。',
      'cp.rule9': '黄色い枠は<b>直前に指した手</b>、赤い枠は<b>王手を受けているキング</b>です。',
      'cp.rule10': '<b>問題は無作為な順で出ます。</b>ただしその順は一度決まればそのままなので、閉じて開き直しても続きから始まります。',
      'cp.theme.smotheredMate': '窒息メイト',
      'cp.theme.backRankMate': 'バックランクメイト',
      'cp.theme.doubleCheck': 'ダブルチェック',
      'cp.theme.discoveredCheck': '開き王手',
      'cp.theme.discoveredAttack': '開き攻撃',
      'cp.theme.skewer': '串刺し',
      'cp.theme.pin': 'ピン',
      'cp.theme.fork': 'フォーク',
      'cp.theme.deflection': '引き離し',
      'cp.theme.attraction': 'おびき寄せ',
      'cp.theme.clearance': '道空け',
      'cp.theme.interference': '遮断',
      'cp.theme.intermezzo': '中間手',
      'cp.theme.capturingDefender': '守り駒を取る',
      'cp.theme.xRayAttack': 'X線攻撃',
      'cp.theme.trappedPiece': '閉じ込められた駒',
      'cp.theme.zugzwang': 'ツークツワンク',
      'cp.theme.enPassant': 'アンパッサン',
      'cp.theme.castling': 'キャスリング',
      'cp.theme.underPromotion': '成り下げ',
      'cp.theme.promotion': '昇格',
      'cp.theme.advancedPawn': '進んだポーン',
      'cp.theme.sacrifice': '犠牲',
      'cp.theme.mateIn1': '1手メイト',
      'cp.theme.mateIn2': '2手メイト',
      'cp.theme.mateIn3': '3手メイト',
      'cp.theme.mateIn4': '長手数メイト',
      'cp.theme.mate': 'メイト',
      'cp.theme.quietMove': '静かな手',
      'cp.theme.defensiveMove': '守りの手',
      'cp.theme.hangingPiece': '浮き駒',
      'cp.theme.attackingF2F7': '弱点攻撃',
      'cp.theme.exposedKing': '露出した王',
      'cp.theme.kingsideAttack': 'キングサイド攻撃',
      'cp.theme.queensideAttack': 'クイーンサイド攻撃',
      'cp.theme.pawnEndgame': 'ポーンエンドゲーム',
      'cp.theme.rookEndgame': 'ルークエンドゲーム',
      'cp.theme.bishopEndgame': 'ビショップエンドゲーム',
      'cp.theme.knightEndgame': 'ナイトエンドゲーム',
      'cp.theme.queenEndgame': 'クイーンエンドゲーム',
      'cp.theme.opening': 'オープニング',
      'cp.theme.middlegame': '中盤',
      'cp.theme.endgame': '終盤',
      'cp.theme.tactic': '戦術',
      'cp.title.smotheredMate': '逃げ場がない',
      'cp.title.backRankMate': 'いちばん奥の段',
      'cp.title.doubleCheck': '二方向から同時に',
      'cp.title.discoveredCheck': 'どけば王手',
      'cp.title.discoveredAttack': '開いた道',
      'cp.title.skewer': '前の駒をどかす',
      'cp.title.pin': 'ピンされた駒',
      'cp.title.deflection': '守りを引き離す',
      'cp.title.attraction': 'おびき寄せる',
      'cp.title.clearance': '道を空ける',
      'cp.title.interference': '間を断つ',
      'cp.title.intermezzo': 'その前に一手',
      'cp.title.capturingDefender': '守り駒を取る',
      'cp.title.xRayAttack': '駒を貫いて',
      'cp.title.trappedPiece': '行き場がない',
      'cp.title.zugzwang': '指す手がない',
      'cp.title.enPassant': '通り過ぎて取る',
      'cp.title.underPromotion': 'クイーンではない',
      'cp.title.advancedPawn': '最終段が近い',
      'cp.title.quietMove': '静かな一手',
      'cp.title.defensiveMove': '先に防ぐ',
      'cp.title.hangingPiece': 'ただ置かれている',
      'cp.title.mateLine': 'メイトへの道',
      'cp.title.promotionTitle': '最後まで行ったポーン',
      'cp.title.mateIn1': '{piece}が決める',
      'cp.title.sacrifice': '{piece}を捨てる',
      'cp.title.fork': '{piece}が二つを狙う',
      'cp.title.hanging': '{piece}が置かれている',
      'cp.title.undefended': '{piece}が守られていない',
      'cp.title.press': '{piece}が攻め立てる',
      'cp.hint.smotheredMate': 'キングの逃げ場を自分の駒がふさいでいます。',
      'cp.hint.backRankMate': 'キングがポーンの後ろに閉じ込められています。',
      'cp.hint.doubleCheck': '二つの駒が同時に王手をかけます。受けられません。',
      'cp.hint.discoveredCheck': '一つの駒がどけば、後ろの駒が王手をかけます。',
      'cp.hint.discoveredAttack': '一つの駒がどけば、後ろの駒が狙うものが現れます。',
      'cp.hint.skewer': '価値の高い駒を先に狙えば、後ろの駒が残ります。',
      'cp.hint.pin': '動くと後ろが露わになる駒があります。',
      'cp.hint.deflection': '何かを守っている駒を別の場所へ呼びましょう。',
      'cp.hint.attraction': '相手の駒を狙いのマスへ引き出してみましょう。',
      'cp.hint.clearance': '自分の駒が自分の道をふさいでいます。',
      'cp.hint.interference': '守る駒と守られる駒の間を遮ってみましょう。',
      'cp.hint.intermezzo': '取り返す前に挟める手があります。',
      'cp.hint.capturingDefender': '何かを守っている駒から消してみましょう。',
      'cp.hint.xRayAttack': '自分の駒の先まで伸びる筋を見てください。',
      'cp.hint.trappedPiece': '逃げるマスのない駒があります。',
      'cp.hint.zugzwang': '相手は何を指しても悪くなります。',
      'cp.hint.enPassant': '二歩進んだばかりのポーンをアンパッサンで取れます。',
      'cp.hint.underPromotion': 'クイーン以外の駒に昇格してみましょう。',
      'cp.hint.advancedPawn': '深く進んだポーンを見てください。',
      'cp.hint.quietMove': '取りも王手もしない手です。',
      'cp.hint.defensiveMove': '攻めより守りの手が要る局面です。',
      'cp.hint.hangingPiece': '誰も守っていない駒があります。',
      'cp.hint.mateIn1': '一手で決められます。',
      'cp.hint.mateLine': '逃げ場を狭めていくとメイトが見えます。',
      'cp.hint.sacrifice': '損に見える手を一度検討してみましょう。',
      'cp.hint.fork': '一手で二つを同時に狙えます。',
      'cp.hint.promotionHint': 'ポーンが最終段に届きます。',
      'cp.hint.capture': '守られていない駒があります。',
      'cp.hint.check': '王手をかけて相手を追い込みましょう。',
      'cp.why.mateNow': 'チェックメイトです。',
      'cp.why.mateLine': '手順を最後まで指せばチェックメイトです。',
      'cp.why.bigGain': '手順を最後まで指せば大きく駒得します（ポーン{gain}個分）。',
      'cp.why.gain': '手順を最後まで指せばポーン{gain}個分リードします。',
      'cp.why.gaveCrushing': '駒を渡しても局面は決定的に傾きます。',
      'cp.why.gaveBetter': '駒を渡しても位置が良くなります。',
      'cp.why.crushing': '取った駒はなくても局面は決定的に良くなります。',
      'cp.why.advantage': '取った駒はなくてもはっきり有利になります。',
      'cp.why.equality': '不利だった局面を互角に戻します。',
      'cp.why.better': '取った駒はなくても位置が良くなります。',
      'cp.piece.k': 'キング',
      'cp.piece.q': 'クイーン',
      'cp.piece.r': 'ルーク',
      'cp.piece.b': 'ビショップ',
      'cp.piece.n': 'ナイト',
      'cp.piece.p': 'ポーン'
    },
    'zh-CN': {
      'meta.desc': '找出一手扭转局面的国际象棋谜题',
      'cp.board': '棋盘',
      'cp.promotionTitle': '升变成什么？',
      'cp.replay': '看后续手顺',
      'cp.replayAgain': '再看一次',
      'cp.replaying': '走棋中…',
      'cp.next': '下一题',
      'cp.source': '谜题来源：Lichess Puzzle Database · CC0',
      'cp.count': '第 {index} / {total} 题',
      'cp.rating': '难度分 {rating}',
      'cp.sideWhite': '你执白',
      'cp.sideBlack': '你执黑',
      'cp.loading': '正在载入题目…',
      'cp.loadFailed': '题目载入失败，请检查网络后再点一次。',
      'cp.turnWhite': '轮到白方，找出最强的一手。',
      'cp.turnBlack': '轮到黑方，找出最强的一手。',
      'cp.illegal': '这一手不合规则。',
      'cp.notBest': '合规，但不是最强的一手，再看看。',
      'cp.reply': '对方以最佳应手回应…',
      'cp.keepGoing': '继续走最强的一手。',
      'cp.solvedMate': '将杀！解开了。',
      'cp.solved': '答对了！解开了。',
      'cp.hintShown': '{hint}已标出要走的子。',
      'cp.emptySquare': '{square} 空格',
      'cp.pieceAt': '{square} {color}{piece}',
      'cp.white': '白',
      'cp.black': '黑',
      'cp.rule1': '每道题都来自真实对局。<b>对手刚刚走错，你要做的是找出该局面下最强的一手。</b>',
      'cp.rule2': '<b>难度分三档，按难度分划分。</b>难度分来自成千上万人的实际成绩 —— 简单在 1200 以下，普通 1400~1900，困难 2000 以上。选定难度后只会出该档的题。',
      'cp.rule3': '<b>棋盘永远是自己这边在下方。</b>执黑时棋盘会翻过来。当前执哪一方写在上面。',
      'cp.rule4': '点一个子，<b>能走的格子会用圆点标出</b>。不合规则的走法根本走不了。',
      'cp.rule5': '合规还不够，<b>只有最强的一手才算对。</b>不过<b>如果局面有多种将杀，任何一种都算对。</b>',
      'cp.rule6': '走对以后<b>对方会以最佳应手回应</b>，一直走到手顺结束。',
      'cp.rule7': '<b>解完之后会告诉你那一手为什么赢。</b>它会数一数把手顺走完后你多赚了多少子力、会不会直接将杀 —— 特别是那些看起来在亏子的题，走完还看不出赚在哪时用得上。',
      'cp.rule8': '<b>提示</b>只告诉你该动哪个子。<b>重来</b>会把当前题目摆回开局。',
      'cp.rule9': '黄框是<b>刚走的那一手</b>，红框是<b>正被将军的王</b>。',
      'cp.rule10': '<b>题目按随机顺序出现。</b>但顺序一旦定下就不变，关掉窗口再打开会从上次的位置接着来。',
      'cp.theme.smotheredMate': '闷杀',
      'cp.theme.backRankMate': '底线杀',
      'cp.theme.doubleCheck': '双将',
      'cp.theme.discoveredCheck': '闪将',
      'cp.theme.discoveredAttack': '闪击',
      'cp.theme.skewer': '串击',
      'cp.theme.pin': '牵制',
      'cp.theme.fork': '双击',
      'cp.theme.deflection': '引离',
      'cp.theme.attraction': '引入',
      'cp.theme.clearance': '腾挪',
      'cp.theme.interference': '阻断',
      'cp.theme.intermezzo': '中间手',
      'cp.theme.capturingDefender': '消除防守',
      'cp.theme.xRayAttack': '透视攻击',
      'cp.theme.trappedPiece': '困子',
      'cp.theme.zugzwang': '逼着',
      'cp.theme.enPassant': '吃过路兵',
      'cp.theme.castling': '王车易位',
      'cp.theme.underPromotion': '低升变',
      'cp.theme.promotion': '升变',
      'cp.theme.advancedPawn': '推进兵',
      'cp.theme.sacrifice': '弃子',
      'cp.theme.mateIn1': '一步杀',
      'cp.theme.mateIn2': '两步杀',
      'cp.theme.mateIn3': '三步杀',
      'cp.theme.mateIn4': '多步杀',
      'cp.theme.mate': '将杀',
      'cp.theme.quietMove': '静棋',
      'cp.theme.defensiveMove': '防守手',
      'cp.theme.hangingPiece': '无保护子',
      'cp.theme.attackingF2F7': '弱点攻击',
      'cp.theme.exposedKing': '王暴露',
      'cp.theme.kingsideAttack': '王翼进攻',
      'cp.theme.queensideAttack': '后翼进攻',
      'cp.theme.pawnEndgame': '兵残局',
      'cp.theme.rookEndgame': '车残局',
      'cp.theme.bishopEndgame': '象残局',
      'cp.theme.knightEndgame': '马残局',
      'cp.theme.queenEndgame': '后残局',
      'cp.theme.opening': '开局',
      'cp.theme.middlegame': '中局',
      'cp.theme.endgame': '残局',
      'cp.theme.tactic': '战术',
      'cp.title.smotheredMate': '无处可逃',
      'cp.title.backRankMate': '最后一排',
      'cp.title.doubleCheck': '两处同时',
      'cp.title.discoveredCheck': '让开就是将军',
      'cp.title.discoveredAttack': '打开的线路',
      'cp.title.skewer': '逼走前面的子',
      'cp.title.pin': '被牵制的子',
      'cp.title.deflection': '把防守子引开',
      'cp.title.attraction': '引它过来',
      'cp.title.clearance': '腾开道路',
      'cp.title.interference': '切断中间',
      'cp.title.intermezzo': '先来一手',
      'cp.title.capturingDefender': '吃掉防守子',
      'cp.title.xRayAttack': '透过子力',
      'cp.title.trappedPiece': '无路可走',
      'cp.title.zugzwang': '无棋可走',
      'cp.title.enPassant': '吃过路兵',
      'cp.title.underPromotion': '不要升后',
      'cp.title.advancedPawn': '底线在望',
      'cp.title.quietMove': '安静的一手',
      'cp.title.defensiveMove': '先挡住',
      'cp.title.hangingPiece': '就那么放着',
      'cp.title.mateLine': '通向将杀',
      'cp.title.promotionTitle': '走到底的兵',
      'cp.title.mateIn1': '{piece}一击定胜',
      'cp.title.sacrifice': '弃掉{piece}',
      'cp.title.fork': '{piece}双击',
      'cp.title.hanging': '{piece}没人管',
      'cp.title.undefended': '{piece}没有保护',
      'cp.title.press': '{piece}紧逼',
      'cp.hint.smotheredMate': '王的逃格被自己的子挡住了。',
      'cp.hint.backRankMate': '王被自己的兵困在底线。',
      'cp.hint.doubleCheck': '两个子同时将军，挡不住。',
      'cp.hint.discoveredCheck': '一个子让开，后面的子就将军。',
      'cp.hint.discoveredAttack': '一个子让开，后面的子的目标就露出来了。',
      'cp.hint.skewer': '先瞄准贵重的子，后面的就留下了。',
      'cp.hint.pin': '有一个子一动，后面就暴露。',
      'cp.hint.deflection': '把正在防守的子引到别处去。',
      'cp.hint.attraction': '试着把对方的子引到你要的格子上。',
      'cp.hint.clearance': '你自己的子挡了自己的路。',
      'cp.hint.interference': '试着挡在防守子和被守子之间。',
      'cp.hint.intermezzo': '回吃之前还有一手可以插入。',
      'cp.hint.capturingDefender': '先把那个在防守的子吃掉。',
      'cp.hint.xRayAttack': '看看穿过自己子力继续延伸的那条线。',
      'cp.hint.trappedPiece': '有一个子没有格子可逃。',
      'cp.hint.zugzwang': '对方走什么都会变糟。',
      'cp.hint.enPassant': '刚走两格的兵可以吃过路兵。',
      'cp.hint.underPromotion': '试试升成后以外的子。',
      'cp.hint.advancedPawn': '看看那个推得很深的兵。',
      'cp.hint.quietMove': '这一手既不吃子也不将军。',
      'cp.hint.defensiveMove': '这个局面需要的是防守而不是进攻。',
      'cp.hint.hangingPiece': '有一个子没人保护。',
      'cp.hint.mateIn1': '一步就能结束。',
      'cp.hint.mateLine': '把逃格逐步收紧，杀棋就出来了。',
      'cp.hint.sacrifice': '算一算那个看起来亏的走法。',
      'cp.hint.fork': '一手可以同时打两个目标。',
      'cp.hint.promotionHint': '有兵能走到底线。',
      'cp.hint.capture': '有一个子没有保护。',
      'cp.hint.check': '将一将，把对方逼过去。',
      'cp.why.mateNow': '这就是将杀。',
      'cp.why.mateLine': '把这路棋走完就是将杀。',
      'cp.why.bigGain': '把这路棋走完能大赚子力（{gain} 个兵的价值）。',
      'cp.why.gain': '把这路棋走完能领先 {gain} 个兵的价值。',
      'cp.why.gaveCrushing': '即使弃子，局面也彻底倒向你这边。',
      'cp.why.gaveBetter': '即使弃子，位置也变好了。',
      'cp.why.crushing': '虽然没吃子，局面却彻底变好。',
      'cp.why.advantage': '虽然没吃子，却明显占优。',
      'cp.why.equality': '把原本吃亏的局面拉回均势。',
      'cp.why.better': '虽然没吃子，位置却变好了。',
      'cp.piece.k': '王',
      'cp.piece.q': '后',
      'cp.piece.r': '车',
      'cp.piece.b': '象',
      'cp.piece.n': '马',
      'cp.piece.p': '兵'
    },
    'zh-TW': {
      'meta.desc': '找出一手扭轉局面的西洋棋謎題',
      'cp.board': '棋盤',
      'cp.promotionTitle': '升變成什麼？',
      'cp.replay': '看後續手順',
      'cp.replayAgain': '再看一次',
      'cp.replaying': '走棋中…',
      'cp.next': '下一題',
      'cp.source': '謎題來源：Lichess Puzzle Database · CC0',
      'cp.count': '第 {index} / {total} 題',
      'cp.rating': '難度分 {rating}',
      'cp.sideWhite': '你執白',
      'cp.sideBlack': '你執黑',
      'cp.loading': '正在載入題目…',
      'cp.loadFailed': '題目載入失敗，請檢查網路後再點一次。',
      'cp.turnWhite': '輪到白方，找出最強的一手。',
      'cp.turnBlack': '輪到黑方，找出最強的一手。',
      'cp.illegal': '這一手不合規則。',
      'cp.notBest': '合規，但不是最強的一手，再看看。',
      'cp.reply': '對方以最佳應手回應…',
      'cp.keepGoing': '繼續走最強的一手。',
      'cp.solvedMate': '將殺！解開了。',
      'cp.solved': '答對了！解開了。',
      'cp.hintShown': '{hint}已標出要走的子。',
      'cp.emptySquare': '{square} 空格',
      'cp.pieceAt': '{square} {color}{piece}',
      'cp.white': '白',
      'cp.black': '黑',
      'cp.rule1': '每道題都來自真實對局。<b>對手剛剛走錯，你要做的是找出該局面下最強的一手。</b>',
      'cp.rule2': '<b>難度分三檔，按難度分劃分。</b>難度分來自成千上萬人的實際成績 —— 簡單在 1200 以下，普通 1400~1900，困難 2000 以上。選定難度後只會出該檔的題。',
      'cp.rule3': '<b>棋盤永遠是自己這邊在下方。</b>執黑時棋盤會翻過來。目前執哪一方寫在上面。',
      'cp.rule4': '點一個子，<b>能走的格子會用圓點標出</b>。不合規則的走法根本走不了。',
      'cp.rule5': '合規還不夠，<b>只有最強的一手才算對。</b>不過<b>如果局面有多種將殺，任何一種都算對。</b>',
      'cp.rule6': '走對以後<b>對方會以最佳應手回應</b>，一直走到手順結束。',
      'cp.rule7': '<b>解完之後會告訴你那一手為什麼贏。</b>它會數一數把手順走完後你多賺了多少子力、會不會直接將殺 —— 特別是那些看起來在虧子的題，走完還看不出賺在哪時用得上。',
      'cp.rule8': '<b>提示</b>只告訴你該動哪個子。<b>重來</b>會把目前題目擺回開局。',
      'cp.rule9': '黃框是<b>剛走的那一手</b>，紅框是<b>正被將軍的王</b>。',
      'cp.rule10': '<b>題目按隨機順序出現。</b>但順序一旦定下就不變，關掉視窗再打開會從上次的位置接著來。',
      'cp.theme.smotheredMate': '悶殺',
      'cp.theme.backRankMate': '底線殺',
      'cp.theme.doubleCheck': '雙將',
      'cp.theme.discoveredCheck': '閃將',
      'cp.theme.discoveredAttack': '閃擊',
      'cp.theme.skewer': '串擊',
      'cp.theme.pin': '牽制',
      'cp.theme.fork': '雙擊',
      'cp.theme.deflection': '引離',
      'cp.theme.attraction': '引入',
      'cp.theme.clearance': '騰挪',
      'cp.theme.interference': '阻斷',
      'cp.theme.intermezzo': '中間手',
      'cp.theme.capturingDefender': '消除防守',
      'cp.theme.xRayAttack': '透視攻擊',
      'cp.theme.trappedPiece': '困子',
      'cp.theme.zugzwang': '逼著',
      'cp.theme.enPassant': '吃過路兵',
      'cp.theme.castling': '王車易位',
      'cp.theme.underPromotion': '低升變',
      'cp.theme.promotion': '升變',
      'cp.theme.advancedPawn': '推進兵',
      'cp.theme.sacrifice': '棄子',
      'cp.theme.mateIn1': '一步殺',
      'cp.theme.mateIn2': '兩步殺',
      'cp.theme.mateIn3': '三步殺',
      'cp.theme.mateIn4': '多步殺',
      'cp.theme.mate': '將殺',
      'cp.theme.quietMove': '靜棋',
      'cp.theme.defensiveMove': '防守手',
      'cp.theme.hangingPiece': '無保護子',
      'cp.theme.attackingF2F7': '弱點攻擊',
      'cp.theme.exposedKing': '王暴露',
      'cp.theme.kingsideAttack': '王翼進攻',
      'cp.theme.queensideAttack': '后翼進攻',
      'cp.theme.pawnEndgame': '兵殘局',
      'cp.theme.rookEndgame': '車殘局',
      'cp.theme.bishopEndgame': '象殘局',
      'cp.theme.knightEndgame': '馬殘局',
      'cp.theme.queenEndgame': '后殘局',
      'cp.theme.opening': '開局',
      'cp.theme.middlegame': '中局',
      'cp.theme.endgame': '殘局',
      'cp.theme.tactic': '戰術',
      'cp.title.smotheredMate': '無處可逃',
      'cp.title.backRankMate': '最後一排',
      'cp.title.doubleCheck': '兩處同時',
      'cp.title.discoveredCheck': '讓開就是將軍',
      'cp.title.discoveredAttack': '打開的線路',
      'cp.title.skewer': '逼走前面的子',
      'cp.title.pin': '被牽制的子',
      'cp.title.deflection': '把防守子引開',
      'cp.title.attraction': '引它過來',
      'cp.title.clearance': '騰開道路',
      'cp.title.interference': '切斷中間',
      'cp.title.intermezzo': '先來一手',
      'cp.title.capturingDefender': '吃掉防守子',
      'cp.title.xRayAttack': '透過子力',
      'cp.title.trappedPiece': '無路可走',
      'cp.title.zugzwang': '無棋可走',
      'cp.title.enPassant': '吃過路兵',
      'cp.title.underPromotion': '不要升后',
      'cp.title.advancedPawn': '底線在望',
      'cp.title.quietMove': '安靜的一手',
      'cp.title.defensiveMove': '先擋住',
      'cp.title.hangingPiece': '就那麼放著',
      'cp.title.mateLine': '通向將殺',
      'cp.title.promotionTitle': '走到底的兵',
      'cp.title.mateIn1': '{piece}一擊定勝',
      'cp.title.sacrifice': '棄掉{piece}',
      'cp.title.fork': '{piece}雙擊',
      'cp.title.hanging': '{piece}沒人管',
      'cp.title.undefended': '{piece}沒有保護',
      'cp.title.press': '{piece}緊逼',
      'cp.hint.smotheredMate': '王的逃格被自己的子擋住了。',
      'cp.hint.backRankMate': '王被自己的兵困在底線。',
      'cp.hint.doubleCheck': '兩個子同時將軍，擋不住。',
      'cp.hint.discoveredCheck': '一個子讓開，後面的子就將軍。',
      'cp.hint.discoveredAttack': '一個子讓開，後面的子的目標就露出來了。',
      'cp.hint.skewer': '先瞄準貴重的子，後面的就留下了。',
      'cp.hint.pin': '有一個子一動，後面就暴露。',
      'cp.hint.deflection': '把正在防守的子引到別處去。',
      'cp.hint.attraction': '試著把對方的子引到你要的格子上。',
      'cp.hint.clearance': '你自己的子擋了自己的路。',
      'cp.hint.interference': '試著擋在防守子和被守子之間。',
      'cp.hint.intermezzo': '回吃之前還有一手可以插入。',
      'cp.hint.capturingDefender': '先把那個在防守的子吃掉。',
      'cp.hint.xRayAttack': '看看穿過自己子力繼續延伸的那條線。',
      'cp.hint.trappedPiece': '有一個子沒有格子可逃。',
      'cp.hint.zugzwang': '對方走什麼都會變糟。',
      'cp.hint.enPassant': '剛走兩格的兵可以吃過路兵。',
      'cp.hint.underPromotion': '試試升成后以外的子。',
      'cp.hint.advancedPawn': '看看那個推得很深的兵。',
      'cp.hint.quietMove': '這一手既不吃子也不將軍。',
      'cp.hint.defensiveMove': '這個局面需要的是防守而不是進攻。',
      'cp.hint.hangingPiece': '有一個子沒人保護。',
      'cp.hint.mateIn1': '一步就能結束。',
      'cp.hint.mateLine': '把逃格逐步收緊，殺棋就出來了。',
      'cp.hint.sacrifice': '算一算那個看起來虧的走法。',
      'cp.hint.fork': '一手可以同時打兩個目標。',
      'cp.hint.promotionHint': '有兵能走到底線。',
      'cp.hint.capture': '有一個子沒有保護。',
      'cp.hint.check': '將一將，把對方逼過去。',
      'cp.why.mateNow': '這就是將殺。',
      'cp.why.mateLine': '把這路棋走完就是將殺。',
      'cp.why.bigGain': '把這路棋走完能大賺子力（{gain} 個兵的價值）。',
      'cp.why.gain': '把這路棋走完能領先 {gain} 個兵的價值。',
      'cp.why.gaveCrushing': '即使棄子，局面也徹底倒向你這邊。',
      'cp.why.gaveBetter': '即使棄子，位置也變好了。',
      'cp.why.crushing': '雖然沒吃子，局面卻徹底變好。',
      'cp.why.advantage': '雖然沒吃子，卻明顯占優。',
      'cp.why.equality': '把原本吃虧的局面拉回均勢。',
      'cp.why.better': '雖然沒吃子，位置卻變好了。',
      'cp.piece.k': '王',
      'cp.piece.q': '后',
      'cp.piece.r': '車',
      'cp.piece.b': '象',
      'cp.piece.n': '馬',
      'cp.piece.p': '兵'
    },
    es: {
      'meta.desc': 'Problemas de ajedrez: encuentra la jugada que da la vuelta a la partida',
      'cp.board': 'Tablero',
      'cp.promotionTitle': '¿A qué promocionas?',
      'cp.replay': 'Ver el resto de la secuencia',
      'cp.replayAgain': 'Ver otra vez',
      'cp.replaying': 'Reproduciendo…',
      'cp.next': 'Siguiente problema',
      'cp.source': 'Problemas de la Lichess Puzzle Database · CC0',
      'cp.count': 'Problema {index} / {total}',
      'cp.rating': 'Elo {rating}',
      'cp.sideWhite': 'Juegas con blancas',
      'cp.sideBlack': 'Juegas con negras',
      'cp.loading': 'Cargando problemas…',
      'cp.loadFailed': 'No se pudieron cargar los problemas. Revisa la conexión y vuelve a tocar.',
      'cp.turnWhite': 'Juegan blancas. Busca la jugada más fuerte.',
      'cp.turnBlack': 'Juegan negras. Busca la jugada más fuerte.',
      'cp.illegal': 'Esa jugada no es legal.',
      'cp.notBest': 'Es legal, pero no es la jugada más fuerte. Míralo otra vez.',
      'cp.reply': 'El rival responde con lo mejor…',
      'cp.keepGoing': 'Sigue con la jugada más fuerte.',
      'cp.solvedMate': '¡Jaque mate! Resuelto.',
      'cp.solved': '¡Correcto! Resuelto.',
      'cp.hintShown': '{hint} Se ha marcado la pieza que mueve.',
      'cp.emptySquare': '{square} vacía',
      'cp.pieceAt': '{square} {piece} {color}',
      'cp.white': 'blanco',
      'cp.black': 'negro',
      'cp.rule1': 'Cada problema sale de una partida real. <b>El rival acaba de errar y tu tarea es encontrar la jugada más fuerte en esa posición.</b>',
      'cp.rule2': '<b>Hay tres dificultades, separadas por Elo.</b> El Elo sale del resultado real de miles de personas: fácil por debajo de 1200, media entre 1400 y 1900, difícil por encima de 2000. Al elegir dificultad solo salen problemas de esa franja.',
      'cp.rule3': '<b>Tu bando siempre queda abajo.</b> Si llevas negras, el tablero se ve girado. Arriba se indica con qué color juegas.',
      'cp.rule4': 'Toca una pieza y <b>sus casillas legales salen como puntos</b>. Una jugada ilegal no se puede hacer.',
      'cp.rule5': 'Que sea legal no basta: <b>solo cuenta la jugada más fuerte.</b> La excepción es una posición con varios mates: <b>ahí vale cualquiera.</b>',
      'cp.rule6': 'Si aciertas, <b>el rival responde con lo mejor</b> y así hasta que acaba la secuencia.',
      'cp.rule7': '<b>Al resolverlo te explica por qué ganaba esa jugada.</b> Cuenta cuánto material acabas ganando tras toda la secuencia y si termina en mate: sobre todo para los problemas donde la jugada parece una pérdida y aun después no ves qué ganaste.',
      'cp.rule8': 'La <b>Pista</b> solo te dice qué pieza mover. <b>Reiniciar</b> devuelve el problema al principio.',
      'cp.rule9': 'El borde amarillo marca <b>la última jugada</b> y el rojo, <b>un rey en jaque</b>.',
      'cp.rule10': '<b>Los problemas salen en orden aleatorio.</b> Ese orden se fija una vez, así que si cierras y vuelves, continúas donde lo dejaste.',
      'cp.theme.smotheredMate': 'Mate ahogado',
      'cp.theme.backRankMate': 'Mate del pasillo',
      'cp.theme.doubleCheck': 'Jaque doble',
      'cp.theme.discoveredCheck': 'Jaque a la descubierta',
      'cp.theme.discoveredAttack': 'Ataque a la descubierta',
      'cp.theme.skewer': 'Enfilada',
      'cp.theme.pin': 'Clavada',
      'cp.theme.fork': 'Horquilla',
      'cp.theme.deflection': 'Desviación',
      'cp.theme.attraction': 'Atracción',
      'cp.theme.clearance': 'Despeje',
      'cp.theme.interference': 'Interferencia',
      'cp.theme.intermezzo': 'Intermedia',
      'cp.theme.capturingDefender': 'Capturar al defensor',
      'cp.theme.xRayAttack': 'Ataque de rayos X',
      'cp.theme.trappedPiece': 'Pieza atrapada',
      'cp.theme.zugzwang': 'Zugzwang',
      'cp.theme.enPassant': 'Al paso',
      'cp.theme.castling': 'Enroque',
      'cp.theme.underPromotion': 'Subpromoción',
      'cp.theme.promotion': 'Promoción',
      'cp.theme.advancedPawn': 'Peón avanzado',
      'cp.theme.sacrifice': 'Sacrificio',
      'cp.theme.mateIn1': 'Mate en 1',
      'cp.theme.mateIn2': 'Mate en 2',
      'cp.theme.mateIn3': 'Mate en 3',
      'cp.theme.mateIn4': 'Mate largo',
      'cp.theme.mate': 'Mate',
      'cp.theme.quietMove': 'Jugada tranquila',
      'cp.theme.defensiveMove': 'Jugada defensiva',
      'cp.theme.hangingPiece': 'Pieza colgada',
      'cp.theme.attackingF2F7': 'Ataque a la casilla débil',
      'cp.theme.exposedKing': 'Rey expuesto',
      'cp.theme.kingsideAttack': 'Ataque en el flanco de rey',
      'cp.theme.queensideAttack': 'Ataque en el flanco de dama',
      'cp.theme.pawnEndgame': 'Final de peones',
      'cp.theme.rookEndgame': 'Final de torres',
      'cp.theme.bishopEndgame': 'Final de alfiles',
      'cp.theme.knightEndgame': 'Final de caballos',
      'cp.theme.queenEndgame': 'Final de damas',
      'cp.theme.opening': 'Apertura',
      'cp.theme.middlegame': 'Medio juego',
      'cp.theme.endgame': 'Final',
      'cp.theme.tactic': 'Táctica',
      'cp.title.smotheredMate': 'Sin escapatoria',
      'cp.title.backRankMate': 'La última fila',
      'cp.title.doubleCheck': 'Desde dos lados a la vez',
      'cp.title.discoveredCheck': 'Apártate y hay jaque',
      'cp.title.discoveredAttack': 'La línea se abre',
      'cp.title.skewer': 'Desplaza la pieza de delante',
      'cp.title.pin': 'Una pieza clavada',
      'cp.title.deflection': 'Aparta al defensor',
      'cp.title.attraction': 'Atráela',
      'cp.title.clearance': 'Despeja el camino',
      'cp.title.interference': 'Córtale el paso',
      'cp.title.intermezzo': 'Una jugada antes',
      'cp.title.capturingDefender': 'Captura al defensor',
      'cp.title.xRayAttack': 'A través de la pieza',
      'cp.title.trappedPiece': 'Sin sitio adonde ir',
      'cp.title.zugzwang': 'No hay jugada buena',
      'cp.title.enPassant': 'Captura al paso',
      'cp.title.underPromotion': 'No es una dama',
      'cp.title.advancedPawn': 'La coronación está cerca',
      'cp.title.quietMove': 'Una jugada tranquila',
      'cp.title.defensiveMove': 'Defiende primero',
      'cp.title.hangingPiece': 'Ahí, sin más',
      'cp.title.mateLine': 'El camino al mate',
      'cp.title.promotionTitle': 'Un peón hasta el final',
      'cp.title.mateIn1': 'El {piece} remata',
      'cp.title.sacrifice': 'Entrega el {piece}',
      'cp.title.fork': 'El {piece} ataca a dos',
      'cp.title.hanging': 'El {piece} está suelto',
      'cp.title.undefended': 'El {piece} quedó sin defensa',
      'cp.title.press': 'El {piece} aprieta',
      'cp.hint.smotheredMate': 'Las casillas de escape del rey las tapan sus propias piezas.',
      'cp.hint.backRankMate': 'El rey está encerrado tras sus peones.',
      'cp.hint.doubleCheck': 'Dos piezas dan jaque a la vez. No se puede tapar.',
      'cp.hint.discoveredCheck': 'Aparta una pieza y la de atrás da jaque.',
      'cp.hint.discoveredAttack': 'Aparta una pieza y aparece lo que ataca la de atrás.',
      'cp.hint.skewer': 'Apunta primero a la pieza valiosa y la de detrás queda a tiro.',
      'cp.hint.pin': 'Hay una pieza que al moverse deja expuesto lo que tiene detrás.',
      'cp.hint.deflection': 'Llama a otra parte a la pieza que defiende.',
      'cp.hint.attraction': 'Intenta atraer una pieza rival a la casilla que te interesa.',
      'cp.hint.clearance': 'Una pieza tuya te está tapando la línea.',
      'cp.hint.interference': 'Prueba a interponerte entre el defensor y lo que defiende.',
      'cp.hint.intermezzo': 'Hay una jugada que meter antes de recapturar.',
      'cp.hint.capturingDefender': 'Empieza quitando la pieza que defiende.',
      'cp.hint.xRayAttack': 'Mira la línea que sigue más allá de tu propia pieza.',
      'cp.hint.trappedPiece': 'Hay una pieza sin casillas a las que huir.',
      'cp.hint.zugzwang': 'Juegue lo que juegue el rival, empeora.',
      'cp.hint.enPassant': 'El peón que acaba de avanzar dos casillas se puede capturar al paso.',
      'cp.hint.underPromotion': 'Prueba a promocionar a algo que no sea dama.',
      'cp.hint.advancedPawn': 'Fíjate en el peón que ha avanzado mucho.',
      'cp.hint.quietMove': 'Es una jugada que ni captura ni da jaque.',
      'cp.hint.defensiveMove': 'Aquí hace falta defender más que atacar.',
      'cp.hint.hangingPiece': 'Hay una pieza que nadie defiende.',
      'cp.hint.mateIn1': 'Puedes rematarlo de una.',
      'cp.hint.mateLine': 'Estrecha las casillas de escape y aparece el mate.',
      'cp.hint.sacrifice': 'Calcula esa jugada que parece una pérdida.',
      'cp.hint.fork': 'Una jugada puede atacar dos cosas a la vez.',
      'cp.hint.promotionHint': 'Un peón llega a la última fila.',
      'cp.hint.capture': 'Hay una pieza sin defender.',
      'cp.hint.check': 'Da jaque y empuja al rival.',
      'cp.why.mateNow': 'Es jaque mate.',
      'cp.why.mateLine': 'Al completar la secuencia es jaque mate.',
      'cp.why.bigGain': 'Al completar la secuencia ganas mucho material ({gain} peones de valor).',
      'cp.why.gain': 'Al completar la secuencia vas por delante {gain} peones de valor.',
      'cp.why.gaveCrushing': 'Entregas material y aun así la posición se decanta del todo.',
      'cp.why.gaveBetter': 'Entregas material y aun así quedas mejor.',
      'cp.why.crushing': 'No capturas nada, pero la posición mejora de forma decisiva.',
      'cp.why.advantage': 'No capturas nada, pero quedas claramente mejor.',
      'cp.why.equality': 'Devuelve al equilibrio una posición peor.',
      'cp.why.better': 'No capturas nada, pero la posición mejora.',
      'cp.piece.k': 'rey',
      'cp.piece.q': 'dama',
      'cp.piece.r': 'torre',
      'cp.piece.b': 'alfil',
      'cp.piece.n': 'caballo',
      'cp.piece.p': 'peón'
    }
  });
})();
