// 이 게임에만 나오는 문구. 도구 이름과 게임 이름은 shared/strings.js에 있다.
//
// 힌트 이유(`lightup.why.*`)는 풀이기가 돌려주는 `why.code`와 이름이 같다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '전구를 놓아 모든 칸을 밝히는 퍼즐',
      'lightup.note': '{size}×{size} 판',
      'lightup.hintCleared': '어긋난 칸 {count}개를 걷어 냈습니다.',
      'lightup.why.numberFull': '벽의 <b>{clue}</b>에 맞는 전구가 이미 다 있으니 나머지 이웃에는 전구가 없습니다.',
      'lightup.why.numberNeed': '벽의 <b>{clue}</b>에 맞추려면 남은 이웃이 모두 전구여야 합니다.',
      'lightup.why.seen': '이미 빛을 받은 칸이라 전구를 두면 서로 비춥니다.',
      'lightup.why.onlyLight': '이 칸을 밝힐 수 있는 자리가 여기 하나뿐입니다.',
      'lightup.why.trialNone': '여기에 전구를 두면 어딘가에서 모순이 생기니 전구가 아닙니다.',
      'lightup.why.trialBulb': '여기를 비워 두면 어딘가에서 모순이 생기니 전구입니다.',
      'lightup.rule1': '흰 칸에 <b>전구</b>를 놓아 <b>모든 흰 칸을 밝힙니다.</b> 전구는 위아래·양옆으로 벽이나 판 끝에 닿을 때까지 빛을 뻗습니다.',
      'lightup.rule2': '<b>전구끼리 서로 비추면 안 됩니다.</b> 같은 줄에서 사이에 벽 없이 마주 보는 두 전구는 붉게 표시됩니다.',
      'lightup.rule3': '벽의 숫자는 그 벽에 <b>맞닿은(위아래·양옆) 전구의 수</b>입니다. 숫자 없는 벽 둘레에는 몇 개든 괜찮습니다.',
      'lightup.rule4': '칸을 누르면 <b>전구 → 점 → 빈칸</b> 순서로 바뀝니다. 점은 "여기는 전구가 아니다"라는 메모라 정답 판정에 쓰이지 않습니다. 점 위에서 끌면 지나간 칸에 점이 이어서 찍힙니다.',
      'lightup.rule5': '<b>모든 판은 답이 하나뿐이고 찍지 않고 풀립니다.</b> 쉬움과 보통은 숫자와 빛만 보고 풀리고, 어려움은 "여기에 전구를 두면 어떻게 되나"를 따져 봐야 하는 자리가 있습니다.',
      'lightup.rule6': '<b>힌트</b>는 어긋난 칸을 걷어 내고, 지금 알아낼 수 있는 칸을 채우며 그 까닭을 알려 줍니다. 힌트를 쓴 판은 최고 기록으로 남기지 않습니다.'
    },
    en: {
      'meta.desc': 'Place light bulbs until every cell is lit',
      'lightup.note': '{size}×{size} board',
      'lightup.hintCleared': 'Cleared {count} wrong cell(s).',
      'lightup.why.numberFull': 'The <b>{clue}</b> already has all its bulbs, so its other neighbours stay dark.',
      'lightup.why.numberNeed': 'The <b>{clue}</b> needs a bulb on every neighbour that is left.',
      'lightup.why.seen': 'This cell is already lit, so a bulb here would shine on another bulb.',
      'lightup.why.onlyLight': 'This is the only place that can light this cell.',
      'lightup.why.trialNone': 'A bulb here leads to a contradiction, so there is no bulb.',
      'lightup.why.trialBulb': 'Leaving this empty leads to a contradiction, so it is a bulb.',
      'lightup.rule1': 'Place <b>bulbs</b> on white cells until <b>every white cell is lit</b>. A bulb shines up, down, left and right until it hits a wall or the edge.',
      'lightup.rule2': '<b>Bulbs may not shine on each other.</b> Two bulbs facing each other in a line with no wall between turn red.',
      'lightup.rule3': 'A number on a wall is <b>how many bulbs touch it</b> (up, down, left, right). Walls without a number allow any count.',
      'lightup.rule4': 'Tap a cell to cycle <b>bulb → dot → empty</b>. A dot is just your note that there is no bulb — it is not checked. Drag from a dot to dot several cells.',
      'lightup.rule5': '<b>Every board has exactly one answer and needs no guessing.</b> Easy and Medium fall to the numbers and the light alone; Hard has spots where you must ask “what if a bulb went here?”',
      'lightup.rule6': 'A <b>Hint</b> clears wrong cells, fills in what you can work out right now, and tells you why. Boards solved with hints are not recorded.'
    },
    ja: {
      'meta.desc': '照明を置いてすべてのマスを照らすパズル',
      'lightup.note': '{size}×{size}の盤',
      'lightup.hintCleared': '間違ったマスを{count}個消しました。',
      'lightup.why.numberFull': '壁の<b>{clue}</b>の数だけ照明があるので、残りの隣は照明ではありません。',
      'lightup.why.numberNeed': '壁の<b>{clue}</b>を満たすには、残りの隣がすべて照明です。',
      'lightup.why.seen': 'すでに照らされたマスなので、照明を置くと照明どうしが照らし合います。',
      'lightup.why.onlyLight': 'このマスを照らせるのはここだけです。',
      'lightup.why.trialNone': 'ここに照明を置くとどこかで矛盾するので、照明ではありません。',
      'lightup.why.trialBulb': 'ここを空けるとどこかで矛盾するので、照明です。',
      'lightup.rule1': '白マスに<b>照明</b>を置いて、<b>すべての白マスを照らします。</b>照明は上下左右に、壁か盤の端まで光を伸ばします。',
      'lightup.rule2': '<b>照明どうしが照らし合ってはいけません。</b>壁をはさまずに同じ列で向き合う照明は赤く表示されます。',
      'lightup.rule3': '壁の数字は、その壁に<b>上下左右で接する照明の数</b>です。数字のない壁のまわりはいくつでもかまいません。',
      'lightup.rule4': 'マスを押すと<b>照明 → 点 → 空白</b>の順に変わります。点は「ここは照明ではない」というメモで、判定には使いません。点からなぞると通ったマスに点が続けて付きます。',
      'lightup.rule5': '<b>どの盤も答えはひとつで、当て推量なしで解けます。</b>やさしいとふつうは数字と光だけで解け、むずかしいには「ここに照明を置いたらどうなるか」を考える場所があります。',
      'lightup.rule6': '<b>ヒント</b>は間違ったマスを消し、今わかるマスを埋めて理由を教えます。ヒントを使った盤は記録に残りません。'
    },
    'zh-CN': {
      'meta.desc': '放置灯泡，照亮所有格子的谜题',
      'lightup.note': '{size}×{size} 盘',
      'lightup.hintCleared': '清除了 {count} 个错误的格子。',
      'lightup.why.numberFull': '墙上的 <b>{clue}</b> 已经有足够的灯泡，其余相邻格没有灯泡。',
      'lightup.why.numberNeed': '要满足墙上的 <b>{clue}</b>，剩下的相邻格都必须是灯泡。',
      'lightup.why.seen': '这一格已经被照亮，放灯泡会和别的灯泡互相照到。',
      'lightup.why.onlyLight': '能照亮这一格的位置只有这里。',
      'lightup.why.trialNone': '这里放灯泡会在某处产生矛盾，所以没有灯泡。',
      'lightup.why.trialBulb': '这里空着会在某处产生矛盾，所以是灯泡。',
      'lightup.rule1': '在白格上放<b>灯泡</b>，<b>照亮所有白格</b>。灯泡向上下左右发光，直到碰到墙或盘边。',
      'lightup.rule2': '<b>灯泡之间不能互相照到。</b>同一行或列中没有墙隔开、彼此相对的两个灯泡会显示为红色。',
      'lightup.rule3': '墙上的数字表示<b>与这面墙上下左右相邻的灯泡数</b>。没有数字的墙周围放几个都可以。',
      'lightup.rule4': '点击格子会按<b>灯泡 → 点 → 空白</b>循环。点只是“这里没有灯泡”的标记，不参与判定。从点上拖动可以连续打点。',
      'lightup.rule5': '<b>每一盘都只有一个答案，不用猜。</b>简单和普通只看数字和光就能解；困难里有需要想“如果这里放灯泡会怎样”的地方。',
      'lightup.rule6': '<b>提示</b>会清除错误的格子，补上现在能推出的格子，并说明理由。用过提示的盘不计入最佳纪录。'
    },
    'zh-TW': {
      'meta.desc': '放置燈泡，照亮所有格子的謎題',
      'lightup.note': '{size}×{size} 盤',
      'lightup.hintCleared': '清除了 {count} 個錯誤的格子。',
      'lightup.why.numberFull': '牆上的 <b>{clue}</b> 已經有足夠的燈泡，其餘相鄰格沒有燈泡。',
      'lightup.why.numberNeed': '要滿足牆上的 <b>{clue}</b>，剩下的相鄰格都必須是燈泡。',
      'lightup.why.seen': '這一格已經被照亮，放燈泡會和別的燈泡互相照到。',
      'lightup.why.onlyLight': '能照亮這一格的位置只有這裡。',
      'lightup.why.trialNone': '這裡放燈泡會在某處產生矛盾，所以沒有燈泡。',
      'lightup.why.trialBulb': '這裡空著會在某處產生矛盾，所以是燈泡。',
      'lightup.rule1': '在白格上放<b>燈泡</b>，<b>照亮所有白格</b>。燈泡向上下左右發光，直到碰到牆或盤邊。',
      'lightup.rule2': '<b>燈泡之間不能互相照到。</b>同一行或列中沒有牆隔開、彼此相對的兩個燈泡會顯示為紅色。',
      'lightup.rule3': '牆上的數字表示<b>與這面牆上下左右相鄰的燈泡數</b>。沒有數字的牆周圍放幾個都可以。',
      'lightup.rule4': '點擊格子會依<b>燈泡 → 點 → 空白</b>循環。點只是「這裡沒有燈泡」的標記，不參與判定。從點上拖曳可以連續打點。',
      'lightup.rule5': '<b>每一盤都只有一個答案，不用猜。</b>簡單和普通只看數字和光就能解；困難裡有需要想「如果這裡放燈泡會怎樣」的地方。',
      'lightup.rule6': '<b>提示</b>會清除錯誤的格子，補上現在能推出的格子，並說明理由。用過提示的盤不計入最佳紀錄。'
    },
    es: {
      'meta.desc': 'Coloca bombillas hasta iluminar todas las casillas',
      'lightup.note': 'Tablero {size}×{size}',
      'lightup.hintCleared': 'Se quitaron {count} casilla(s) incorrecta(s).',
      'lightup.why.numberFull': 'El <b>{clue}</b> ya tiene todas sus bombillas, así que sus otras vecinas quedan sin bombilla.',
      'lightup.why.numberNeed': 'El <b>{clue}</b> necesita una bombilla en cada vecina que queda.',
      'lightup.why.seen': 'Esta casilla ya está iluminada, así que una bombilla aquí alumbraría a otra.',
      'lightup.why.onlyLight': 'Es el único sitio que puede iluminar esta casilla.',
      'lightup.why.trialNone': 'Una bombilla aquí lleva a una contradicción, así que no hay bombilla.',
      'lightup.why.trialBulb': 'Dejar esto vacío lleva a una contradicción, así que es una bombilla.',
      'lightup.rule1': 'Coloca <b>bombillas</b> en las casillas blancas hasta que <b>todas estén iluminadas</b>. Una bombilla alumbra arriba, abajo, a izquierda y derecha hasta topar con un muro o el borde.',
      'lightup.rule2': '<b>Las bombillas no pueden alumbrarse entre sí.</b> Dos bombillas enfrentadas en una línea sin muro entre ellas se ponen rojas.',
      'lightup.rule3': 'El número de un muro es <b>cuántas bombillas lo tocan</b> (arriba, abajo, a los lados). Los muros sin número admiten cualquier cantidad.',
      'lightup.rule4': 'Toca una casilla para alternar <b>bombilla → punto → vacío</b>. El punto es solo tu nota de que ahí no hay bombilla; no se comprueba. Arrastra desde un punto para marcar varias casillas.',
      'lightup.rule5': '<b>Cada tablero tiene una sola solución y no hace falta adivinar.</b> Fácil y Normal salen solo con los números y la luz; Difícil tiene sitios donde hay que pensar «¿y si aquí hubiera una bombilla?».',
      'lightup.rule6': 'La <b>pista</b> quita las casillas incorrectas, completa lo que ya puedes deducir y te explica por qué. Los tableros resueltos con pistas no cuentan para el récord.'
    }
  });
})();
