// 이 게임에만 나오는 문구. 캐릭터·적·목표·아이템은 로직이 id만 들고 있고,
// 이름과 설명은 여기 있다 — 자료가 한 언어에 묶이지 않게 하기 위해서다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '길목에 사람을 세워 밀려오는 적을 막는다',
      'def.camp': '정비',
      'def.palette': '세울 사람',
      'def.items': '1회용 아이템',
      'def.dismiss': '해고',
      'def.up': '올리기',
      'def.rush': '바로 보내기',
      'def.stageLabel': '스테이지',
      'def.prevStage': '앞 스테이지',
      'def.teamLabel': '편성',
      'def.heroLabel': '영웅',
      'def.heroLabelNote': '저마다 한 판에 한 번. 붙여 세우면 서로의 스킬을 당긴다',
      'def.lockedLabel': '잠긴 사람',
      'def.lockedNote': '목표를 채우면 카드로 나오고, 보석으로 바로 열 수도 있다',
      'def.growLabel': '육성',
      'def.growNote': '부대 레벨 하나가 가진 사람 전부의 피해와 체력을 올린다',
      'def.otherLabel': '그 밖에',
      'def.unit.archer': '궁수',
      'def.unit.shield': '방패병',
      'def.unit.cannon': '포수',
      'def.unit.frost': '빙결술사',
      'def.unit.spear': '창병',
      'def.unit.healer': '힐러',
      'def.unit.blade': '검성',
      'def.unit.arch': '대마법사',
      'def.unit.warden': '사령관',
      'def.unit.saint': '성기사',
      'def.who.blade': '레안',
      'def.who.arch': '모르윈',
      'def.who.warden': '베린',
      'def.who.saint': '가론',
      'def.unit.archer.note': '멀리서 한 놈씩',
      'def.unit.shield.note': '앞을 막고 버틴다. 체력이 아주 높다',
      'def.unit.cannon.note': '코앞은 못 친다',
      'def.unit.frost.note': '오래 기다리는 대신 판을 바꾼다',
      'def.unit.spear.note': '',
      'def.unit.healer.note': '되살릴 이가 없으면 같이 싸운다. 언데드에 강하다',
      'def.unit.blade.note': '길목에 세워야 값이 나온다. 맞닿은 것만 벤다',
      'def.unit.arch.note': '판 끝에서 끝까지 닿는다. 코앞은 못 친다',
      'def.unit.warden.note': '곁에 누가 있을수록 세진다. 혼자서는 가장 약하다',
      'def.unit.saint.note': '되살리며 싸운다. 언데드에 아주 강하다',
      'def.skill.archer': '정조준',
      'def.skill.shield': '후려치기',
      'def.skill.cannon': '포격',
      'def.skill.frost': '얼음 지대',
      'def.skill.spear': '꿰뚫기',
      'def.skill.healer': '치유',
      'def.skill.blade': '회전베기',
      'def.skill.arch': '운석',
      'def.skill.warden': '호령',
      'def.skill.saint': '치유의 빛',
      'def.skill.archer.note': '두 배가 넘게 꽂는 한 발',
      'def.skill.shield.note': '때려서 멈춰 세운다',
      'def.skill.cannon.note': '한 발이 주변까지',
      'def.skill.frost.note': '바닥을 얼려 둔다. 밟는 동안 깎이고 느려진다',
      'def.skill.spear.note': '한 줄을 꿰고 출혈을 남긴다',
      'def.skill.healer.note': '가장 다친 아군을 되살리고 둘레의 언데드를 태운다',
      'def.skill.blade.note': '둘레를 통째로 벤다',
      'def.skill.arch.note': '떨어뜨려 태운다',
      'def.skill.warden.note': '둘레의 스킬을 한꺼번에 당긴다. 영웅은 두 배로',
      'def.skill.saint.note': '둘레의 아군을 한꺼번에 되살리고 언데드를 태운다',
      'def.foe.grunt': '보병',
      'def.foe.swarm': '무리',
      'def.foe.swift': '경보병',
      'def.foe.armored': '중장병',
      'def.foe.breaker': '공성병',
      'def.foe.mender': '치유병',
      'def.foe.bone': '해골병',
      'def.foe.wraith': '망령',
      'def.foe.boss': '우두머리',
      'def.map.plain': '들판',
      'def.map.rough': '벌판',
      'def.map.maze': '미로',
      'def.map.plain.note': '트여서 막을 데가 없다',
      'def.map.rough.note': '고루 트인 판',
      'def.map.maze.note': '좁은 목이 많다',
      'def.goal.flawless': '무결점',
      'def.goal.swift': '속공',
      'def.goal.thrifty': '검소',
      'def.goal.purist': '한 우물',
      'def.goal.saver': '알뜰',
      'def.goal.barehand': '맨손',
      'def.goal.behead': '참수',
      'def.goal.flawless.note': '목숨을 하나도 잃지 않는다',
      'def.goal.swift.note': '{arg}초 안에 끝낸다',
      'def.goal.thrifty.note': '{arg}명 이하로 막는다',
      'def.goal.purist.note': '한 종류만 쓴다',
      'def.goal.saver.note': '골드를 {arg} 이상 남긴다',
      'def.goal.barehand.note': '아무도 올리지 않는다',
      'def.goal.behead.note': '우두머리를 {arg}초 안에 잡는다',
      'def.item.bomb': '폭탄',
      'def.item.freeze': '얼림',
      'def.item.purse': '보급',
      'def.item.mend': '구호',
      'def.item.order': '명령서',
      'def.item.bomb.note': '모든 적의 체력을 35% 깎는다',
      'def.item.freeze.note': '3초 동안 모두 멈춘다',
      'def.item.purse.note': '골드 120',
      'def.item.mend.note': '목숨 하나를 되돌린다',
      'def.item.order.note': '한 사람을 빈 칸으로 옮긴다',
      'def.perk.lives': '목숨',
      'def.perk.slots': '편성 칸',
      'def.perk.purse': '시작 골드',
      'def.perk.hero': '영웅 칸',
      'def.perk.lives.note': '판을 시작할 때 목숨이 하나 는다',
      'def.perk.slots.note': '판에 데려가는 사람이 하나 는다',
      'def.perk.purse.note': '시작 골드가 10% 는다',
      'def.perk.hero.note': '판에 데려가는 영웅이 하나 는다',
      'def.stage': '스테이지 {n}',
      'def.lives': '목숨 {n}',
      'def.gold': '골드 {n}',
      'def.waiting': '대기',
      'def.startsIn': '곧 시작 {n}',
      'def.nextWave': '{wave}/{total} · 다음 {n}',
      'def.wave': '웨이브 {wave}/{total}',
      'def.mainFoe': '{map} · 주력은 <b>{foe}</b>',
      'def.mapLine': '<b>{name}</b> {note}',
      'def.goalLine': '목표 <b>{name}</b> · {note}',
      'def.called': '부름',
      'def.callNow': '지금',
      'def.callFrom': '{n}웨이브',
      'def.tier': '{who} {n}단계',
      'def.heal': '회복 <b>{n}</b>',
      'def.dps': '초당 <b>{n}</b>',
      'def.tagSplash': '(범위)',
      'def.tagRing': '(둘레)',
      'def.tagSmite': '(+회복)',
      'def.tagHoly': '(신성)',
      'def.basicSplash': '기본 공격이 범위',
      'def.basicRing': '기본 공격도 둘레를 벤다',
      'def.basicSmite': '기본 공격도 아군을 되살린다',
      'def.basicSingle': '기본 공격이 한 놈',
      'def.holyNote': '신성이라 언데드에 두 배',
      'def.stats': '체력 <b>{hp}/{maxHp}</b> · 공격 <b>{dmg}</b>{tag} · 사거리 <b>{min}-{max}</b>',
      'def.skillLine': '{skill} {power} · 쿨타임 <b>{cd}초</b>',
      'def.hold': '지속 <b>{n}초</b>',
      'def.waitLeft': '<b>{n}초 남음</b>',
      'def.ready': '<b>준비됨</b>',
      'def.maxed': '<b>끝까지 올렸다</b>',
      'def.upgrade': '<b>올리기 {cost}</b>',
      'def.upgradeStats': '공격 {a}→{b} · 체력 {c}→{d} · 사거리 +{e}칸',
      'def.upgradeCd': '쿨타임 {a}→{b}초',
      'def.upgradeHold': '지속 {a}→{b}초',
      'def.sell': '해고 +{n}',
      'def.fell': '{who}이(가) 무너졌다',
      'def.bossPassed': '우두머리가 지나갔다 · 목숨 −{n}',
      'def.foePassed': '적이 지나갔다',
      'def.waveStart': '웨이브 {n}',
      'def.waveBoss': '웨이브 {n} · 우두머리',
      'def.statDealt': '피해 {n}',
      'def.statKills': '처치 {n}',
      'def.statTaken': '버팀 {n}',
      'def.statHealed': '회복 {n}',
      'def.statSkills': '스킬 {n}',
      'def.statHired': '{n}명 고용',
      'def.cleared': '스테이지 {n} 돌파',
      'def.failed': '뚫렸다',
      'def.wonNote': '목숨 {lives} 남김 · {time}초',
      'def.lostNote': '웨이브 {n}까지 버텼다',
      'def.goalDone': '목표 달성 — {name}',
      'def.goalMissed': '목표 {name}은(는) 다음에',
      'def.gemsGot': '보석 +{n}',
      'def.nextStage': '다음 스테이지',
      'def.heroTip': '골드가 들지 않는다. 다른 영웅 곁에 서면 피해와 쿨타임이 한 명당 +{pct}%',
      'def.leadTip': '(사령관은 두 배)',
      'def.paletteTip': '{who} · 사거리 {min}-{max}{basic} · {skill}({cd}초) — {note} · 같은 종류는 {most}명까지, 겹칠수록 값이 오른다',
      'def.pickToMove': '옮길 사람을 누르세요',
      'def.pickTarget': '갈 자리를 누르세요',
      'def.cannotUse': '지금은 쓸 수 없다',
      'def.cannotGo': '그 자리에는 못 간다',
      'def.gems': '보석 {n}',
      'def.stageCleared': '클리어함',
      'def.stageNotYet': '아직',
      'def.stageLine': '{state} · 목표 {goal}',
      'def.slots': '{used}/{total}칸',
      'def.inTeam': '편성됨',
      'def.noEmptyTeam': '아무도 없이 갈 수는 없다',
      'def.teamFull': '편성 칸이 찼다',
      'def.noHeroes': '아직 없습니다. 스테이지 {n}부터 목표를 채우면 카드로 나옵니다.',
      'def.taken': '데려감',
      'def.hire': '고용 {n}',
      'def.heroFull': '영웅 칸이 찼다',
      'def.allUnlocked': '모두 열었습니다.',
      'def.heroPrefix': '영웅 {name}',
      'def.rangeSkill': '사거리 {min}-{max} · {skill} — {note}',
      'def.gemPrice': '보석 {n}',
      'def.levelRow': '부대 레벨 <b>{n}</b>',
      'def.levelNote': '가진 사람 전부의 공격과 체력이 같이 오른다',
      'def.levelDelta': '{name} {a}→{b}',
      'def.perkTop': '끝',
      'def.speed': '{n}배속',
      'def.cardGems': '보석 {n}',
      'def.cardGemsNote': '레벨을 올리는 데 쓴다',
      'def.cardItems': '{name} 2개',
      'def.cardItemsNote': '판 안에서 한 번씩 쓴다',
      'def.why.over': '판이 끝났다',
      'def.why.noSuchUnit': '없는 캐릭터',
      'def.why.notInTeam': '편성에 없다',
      'def.why.offBoard': '판 밖',
      'def.why.wall': '벽',
      'def.why.occupiedByUnit': '이미 서 있다',
      'def.why.foeThere': '적이 밟고 있다',
      'def.why.entry': '적이 나오는 자리',
      'def.why.heroUsed': '그 영웅은 이미 불렀다',
      'def.why.noGold': '골드가 모자라다',
      'def.help.r1': '아래에서 <b>사람을 고르고 빈 칸을 누르면</b> 그 자리에 섭니다. 누르고 있는 동안 <b>적이 갈 길이 어떻게 바뀌는지</b> 미리 보입니다.',
      'def.help.r2': '적은 <b>가장 빨리 출구에 닿는 길</b>로 옵니다. 돌아가는 것보다 사람을 부수는 것이 빠르면 <b>부수고 지나갑니다.</b>',
      'def.help.r3': '그래서 길을 <b>완전히 막아도 됩니다.</b> 대신 막은 사람은 부서지고, 부서진 사람은 돌아오지 않습니다.',
      'def.help.r4': '<b>공성병</b>은 조금만 돌아가야 해도 뚫고 들어옵니다. 막는 것만으로 짜면 여기서 무너집니다.',
      'def.help.r5': '적이 <b>출구에 닿으면 목숨이 줍니다.</b> 목숨이 다하면 그 판은 끝입니다.',
      'def.help.r6': '한 판은 <b>웨이브 열 개</b>이고 마지막은 <b>우두머리</b>입니다.',
      'def.help.r7': '세운 사람은 <b>골드로 올릴 수</b> 있고, <b>해고하면 일부를 돌려받습니다.</b> 사람을 누르면 지금 체력·공격과 함께 <b>올렸을 때 얼마나 오르는지</b>가 단추에 같이 적힙니다.',
      'def.help.r8': '<b>단계를 올리면 스킬이 더 자주, 더 오래 나갑니다.</b> 쿨타임이 줄고 지속(얼음·출혈·기절)이 늘어, <b>쿨타임이 긴 빙결술사와 대마법사가 가장 크게 좋아집니다</b> — 3단계 빙결술사는 얼음이 거의 끊기지 않습니다.',
      'def.help.r9': '판이 끝나면 <b>누가 얼마나 했는지</b>를 캐릭터별로 보여 줍니다 — 피해, 처치, 몸으로 버틴 피해, 회복, 스킬 횟수.',
      'def.help.r10': '<b>사거리는 사람마다 다르고 안쪽 한계가 있습니다.</b> 포수는 2~5칸이라 <b>코앞의 적은 못 칩니다</b> — 누르면 사거리가 도넛으로 보입니다.',
      'def.help.r11': '<b>적이 밟고 있는 칸과 적이 나오는 자리에는 세울 수 없습니다.</b> 길목은 미리 잡아 두세요.',
      'def.help.r12': '<b>입구를 둘러싸 막을 수도 있지만 남는 장사가 아닙니다.</b> 한 칸에 몰린 적이 <b>전부 같은 사람을 때려</b> 받는 피해가 마릿수만큼 곱해집니다 — 열 마리면 초당 120이라 방패병이 25초를 못 버팁니다. 길게 늘어놓고 나눠 받는 쪽이 오래 갑니다.',
      'def.help.r13': '<b>영웅</b>은 한 판에 <b>한 번만</b> 부를 수 있고, 편성에서 따로 한 칸을 씁니다. 값이 비싸 첫 웨이브에는 못 세우니 <b>어느 웨이브에 꺼낼지</b>가 판단입니다. 스테이지 4부터 카드로 나옵니다.',
      'def.help.r14': '스테이지마다 <b>목표</b>가 붙습니다. <b>못 채워도 클리어는 클리어</b>이고, 채우면 <b>카드를 한 장 고릅니다</b> — 새 사람, 보석, 1회용 아이템.',
      'def.help.r15': '<b>보석으로 레벨을 올립니다.</b> 판 안의 값은 그대로이고 스테이지마다 적만 세지므로, 멀리 가려면 키워야 합니다.',
      'def.help.r16': '<b>진 판도 보석을 줍니다.</b> 막혔을 때는 아이템을 모아 한 판에 몰아 쓰세요.',
      'def.help.r17': '<b>적마다 통하는 공격이 다릅니다.</b> 아래 표를 보고 편성하세요. 한 종류만 키우면 어느 판에선가 반드시 막힙니다.',
      'def.help.r18': '<b>같은 종류는 판에 넷까지</b>이고 <b>겹쳐 세울수록 값이 오릅니다.</b>',
      'def.help.r19': '<b>보석으로 올리는 것은 부대 레벨 하나</b>입니다. 가진 사람 전부의 공격과 체력이 같이 오르니, 새로 얻은 사람도 곧바로 제 몫을 합니다 — 누구를 데려갈지는 오직 <b>판과 적</b>의 문제입니다.',
      'def.help.r20': '정비에서 <b>보석으로 잠긴 사람을 바로 열 수</b> 있습니다. 목표를 못 채워도 막아 낼 종류를 못 얻는 일은 없습니다.',
      'def.help.mapTitle': '판과 적이 편성을 정한다',
      'def.help.mapNote': '판을 열기 전에 <b>판의 성격</b>과 <b>그 판의 주력 적</b>이 머리말과 정비에 적힙니다. 둘을 보고 데려갈 셋을 고르는 것이 이 게임입니다.',
      'def.help.m1': '<b>들판</b> — 트여서 막을 데가 없습니다. 화력으로 녹여야 합니다.',
      'def.help.m2': '<b>벌판</b> — 고루 트인 보통 판.',
      'def.help.m3': '<b>미로</b> — 좁은 목이 많습니다. <b>방패병·검성으로 막고</b> 뒤에서 때리는 것이 잘 듭니다.',
      'def.help.foeTitle': '적마다 듣는 공격이 다릅니다.',
      'def.help.f1': '<b>보병</b> — 약점이 없습니다. 값이 싼 <b>궁수</b>가 가장 낫습니다.',
      'def.help.f2': '<b>무리</b> — 한 놈씩 쏘면 반이 낭비됩니다. <b>범위</b>(포수·대마법사).',
      'def.help.f3': '<b>경보병</b> — 너무 빨라 사거리를 지나갑니다. <b>빙결술사로 발을 묶고</b> 한 놈씩 때리는 자를 같이 세우세요. 범위는 흩어져 달려 잘 안 걸립니다.',
      'def.help.f4': '<b>중장병</b> — 한 놈씩도 범위도 거의 안 통합니다. 방어를 무시하는 <b>지속 피해</b>(창병의 출혈, 얼음 지대)만 남습니다.',
      'def.help.f5': '<b>공성병</b> — 지속과 범위를 먹고 얼음도 잘 안 듣지만, <b>한 놈씩 꽂는 공격</b>에는 그대로 뚫립니다. 초당 60으로 부수며 오니 <b>방패병·힐러</b>로 시간을 벌어야 합니다.',
      'def.help.f6': '<b>치유병</b> — 어느 종류로 때려도 얼마쯤 깎이고 스스로 되살립니다. <b>한 번에 크게 넣는 스킬</b>로 끊으세요.',
      'def.help.f7': '<b>해골병·망령</b>(언데드) — 산 것을 잡는 수단이 <b>전부 반쯤만</b> 통합니다. 대신 <b>신성</b>에는 두 배로 탑니다 — 때리는 것이 신성인 <b>힐러</b>와 영웅 <b>성기사</b>가 여기서 딜러가 됩니다. 망령은 빠르고 얼음도 잘 안 듣습니다.',
      'def.help.sixTitle': '지키는 이 여섯',
      'def.help.sixNote': '모두 <b>기본 공격</b>과 <b>스킬</b>을 가집니다. 스킬은 제 쿨타임이 돌아올 때 나가고, <b>그 사이에는 기본 공격으로 한 놈씩 때립니다.</b> 사람을 누르면 남은 쿨타임이 보이고, 판에서는 오른쪽 위 점이 켜지면 준비된 것입니다.',
      'def.help.u1': '<b>궁수</b> 1~4칸 — <b>정조준</b>(5초): 배수가 붙은 한 발.',
      'def.help.u2': '<b>방패병</b> 1칸 — <b>후려치기</b>(3.5초): 1.2초 <b>기절</b>. 공격은 약하고 체력이 아주 높아 앞을 막는 자리입니다.',
      'def.help.u3': '<b>포수</b> 2~5칸 — <b>포격</b>(6초): 주변까지 한 번에. <b>코앞은 못 칩니다.</b>',
      'def.help.u4': '<b>빙결술사</b> 1~3칸 — <b>얼음 지대</b>(<b>9초</b>): 바닥을 얼려 밟는 동안 계속 깎고 느리게 만듭니다. 가장 오래 기다리는 대신 판을 바꿉니다.',
      'def.help.u5': '<b>창병</b> 1~2칸 — <b>꿰뚫기</b>(4초): 한 줄에 선 적을 모두 꿰뚫고 <b>출혈</b>을 남깁니다.',
      'def.help.u6': '<b>힐러</b> 1~3칸 — <b>치유</b>(3.5초): 가장 다친 아군을 되돌립니다. 되살릴 이가 없으면 같이 싸웁니다. 때리는 것이 <b>신성</b>이라 <b>언데드에게 두 배</b>로 들어가고, 치유가 둘레의 언데드를 태웁니다.',
      'def.help.heroTitle': '영웅 넷',
      'def.help.heroNote1': '<b>영웅은 골드가 들지 않습니다.</b> 대신 <b>웨이브마다 하나씩</b>만 부를 수 있습니다 — 2웨이브에 첫째, 3웨이브에 둘째, 4웨이브에 셋째입니다. 일반 편성이 골드 싸움이라면 영웅은 시간 싸움입니다.',
      'def.help.heroNote2': '<b>영웅끼리 붙여 세우면 서로 세집니다</b>(공명). 둘레 두 칸 안에 다른 영웅이 있으면 <b>피해와 스킬 쿨타임이 한 명당 +50%</b>이고 <b>사령관은 두 명분</b>으로 칩니다 — 둘이면 ×1.5, 셋이면 ×2, 사령관을 끼면 ×2.5입니다. 얽히면 점선으로 이어져 보입니다.',
      'def.help.h1': '<b>검성 레안</b> 1칸 — <b>가까운 소수</b>가 자리입니다. 기본도 <b>회전베기</b>(4.5초)도 자기를 가운데로 삼아 맞닿은 것을 통째로 벱니다. 체력이 아주 높으니 <b>길목에 세워야</b> 값이 나옵니다 — 멀리 두면 아무도 만나지 못합니다.',
      'def.help.h2': '<b>대마법사 모르윈</b> 2~6칸 — <b>멀리 있는 다수</b>가 자리입니다. 기본부터 넓은 범위이고 <b>운석</b>(9초)은 더 넓습니다. 판 끝에서 끝까지 닿지만 <b>코앞은 못 치고</b> 체력이 종잇장이라 앞에 세울 수 없습니다.',
      'def.help.h3': '<b>사령관 베린</b> 1~5칸 — <b>곁을 부리는</b> 자리입니다. <b>호령</b>(5초)이 둘레 아군의 스킬 쿨타임을 한꺼번에 당기고 영웅에게는 두 배로 당깁니다. 공명도 두 명분이라 <b>영웅 둘 사이에 끼워 세우는</b> 것이 가장 좋습니다. 혼자서는 영웅 중 가장 약합니다.',
      'def.help.h4': '<b>성기사 가론</b> 1~4칸 — <b>언데드</b>가 자리입니다. 때리는 것이 <b>신성</b>이라 해골병·망령에게 두 배로 들어가고, <b>치유의 빛</b>(6초)은 아군을 되살리면서 둘레의 언데드를 태웁니다. 산 것에게는 평범합니다.'
    },
    en: {
      'meta.desc': 'Post units on the path and hold back the advancing enemy',
      'def.camp': 'Camp',
      'def.palette': 'Units to place',
      'def.items': 'Single-use items',
      'def.dismiss': 'Dismiss',
      'def.up': 'Upgrade',
      'def.rush': 'Send now',
      'def.stageLabel': 'Stage',
      'def.prevStage': 'Previous stage',
      'def.teamLabel': 'Team',
      'def.heroLabel': 'Heroes',
      'def.heroLabelNote': 'One call each per run. Standing them together pulls each other’s skills forward',
      'def.lockedLabel': 'Locked units',
      'def.lockedNote': 'Meeting a goal offers them as a card, or you can unlock one outright with gems',
      'def.growLabel': 'Levelling',
      'def.growNote': 'A single army level raises damage and health for everyone you own',
      'def.otherLabel': 'Other',
      'def.unit.archer': 'Archer',
      'def.unit.shield': 'Shieldbearer',
      'def.unit.cannon': 'Gunner',
      'def.unit.frost': 'Frostmage',
      'def.unit.spear': 'Spearman',
      'def.unit.healer': 'Healer',
      'def.unit.blade': 'Blademaster',
      'def.unit.arch': 'Archmage',
      'def.unit.warden': 'Commander',
      'def.unit.saint': 'Paladin',
      'def.who.blade': 'Lean',
      'def.who.arch': 'Morwyn',
      'def.who.warden': 'Berin',
      'def.who.saint': 'Garon',
      'def.unit.archer.note': 'Picks them off from afar',
      'def.unit.shield.note': 'Blocks the front and holds. Very high health',
      'def.unit.cannon.note': 'Cannot hit what is right next to it',
      'def.unit.frost.note': 'A long wait, but it changes the board',
      'def.unit.spear.note': '',
      'def.unit.healer.note': 'Fights alongside when there is nobody to heal. Strong against undead',
      'def.unit.blade.note': 'Worth it on a chokepoint. Only cuts what it touches',
      'def.unit.arch.note': 'Reaches across the whole board. Cannot hit what is adjacent',
      'def.unit.warden.note': 'The more allies nearby, the stronger. Weakest alone',
      'def.unit.saint.note': 'Heals while fighting. Very strong against undead',
      'def.skill.archer': 'Careful Shot',
      'def.skill.shield': 'Bash',
      'def.skill.cannon': 'Bombardment',
      'def.skill.frost': 'Ice Field',
      'def.skill.spear': 'Impale',
      'def.skill.healer': 'Heal',
      'def.skill.blade': 'Whirlwind',
      'def.skill.arch': 'Meteor',
      'def.skill.warden': 'Rally Cry',
      'def.skill.saint': 'Light of Healing',
      'def.skill.archer.note': 'One shot for over double damage',
      'def.skill.shield.note': 'Hits and stops them in place',
      'def.skill.cannon.note': 'One shell catches the surroundings',
      'def.skill.frost.note': 'Freezes the ground: standing on it hurts and slows',
      'def.skill.spear.note': 'Runs a line through and leaves bleeding',
      'def.skill.healer.note': 'Heals the most hurt ally and burns nearby undead',
      'def.skill.blade.note': 'Cuts everything around at once',
      'def.skill.arch.note': 'Drops it and burns',
      'def.skill.warden.note': 'Pulls every nearby skill forward at once — double for heroes',
      'def.skill.saint.note': 'Heals every nearby ally at once and burns undead',
      'def.foe.grunt': 'Footsoldier',
      'def.foe.swarm': 'Swarm',
      'def.foe.swift': 'Skirmisher',
      'def.foe.armored': 'Heavy',
      'def.foe.breaker': 'Siegebreaker',
      'def.foe.mender': 'Field medic',
      'def.foe.bone': 'Skeleton',
      'def.foe.wraith': 'Wraith',
      'def.foe.boss': 'Boss',
      'def.map.plain': 'Open field',
      'def.map.rough': 'Rough ground',
      'def.map.maze': 'Maze',
      'def.map.plain.note': 'Wide open, nowhere to block',
      'def.map.rough.note': 'Evenly open ground',
      'def.map.maze.note': 'Plenty of narrow chokepoints',
      'def.goal.flawless': 'Flawless',
      'def.goal.swift': 'Speedrun',
      'def.goal.thrifty': 'Thrifty',
      'def.goal.purist': 'One kind',
      'def.goal.saver': 'Saver',
      'def.goal.barehand': 'Barehanded',
      'def.goal.behead': 'Beheading',
      'def.goal.flawless.note': 'Lose no lives at all',
      'def.goal.swift.note': 'Finish within {arg} seconds',
      'def.goal.thrifty.note': 'Hold with {arg} units or fewer',
      'def.goal.purist.note': 'Use only one kind',
      'def.goal.saver.note': 'Finish with {arg} gold or more left',
      'def.goal.barehand.note': 'Upgrade nobody',
      'def.goal.behead.note': 'Kill the boss within {arg} seconds',
      'def.item.bomb': 'Bomb',
      'def.item.freeze': 'Freeze',
      'def.item.purse': 'Supply',
      'def.item.mend': 'Aid',
      'def.item.order': 'Orders',
      'def.item.bomb.note': 'Cuts every enemy’s health by 35%',
      'def.item.freeze.note': 'Freezes everyone for 3 seconds',
      'def.item.purse.note': '120 gold',
      'def.item.mend.note': 'Gives back one life',
      'def.item.order.note': 'Moves one unit to an empty square',
      'def.perk.lives': 'Lives',
      'def.perk.slots': 'Team slots',
      'def.perk.purse': 'Starting gold',
      'def.perk.hero': 'Hero slots',
      'def.perk.lives.note': 'One more life at the start of a run',
      'def.perk.slots.note': 'One more unit to take into a run',
      'def.perk.purse.note': '10% more gold to start with',
      'def.perk.hero.note': 'One more hero to take into a run',
      'def.stage': 'Stage {n}',
      'def.lives': 'Lives {n}',
      'def.gold': 'Gold {n}',
      'def.waiting': 'Waiting',
      'def.startsIn': 'Starting in {n}',
      'def.nextWave': '{wave}/{total} · next in {n}',
      'def.wave': 'Wave {wave}/{total}',
      'def.mainFoe': '{map} · mostly <b>{foe}</b>',
      'def.mapLine': '<b>{name}</b> — {note}',
      'def.goalLine': 'Goal <b>{name}</b> · {note}',
      'def.called': 'Used',
      'def.callNow': 'Now',
      'def.callFrom': 'Wave {n}',
      'def.tier': '{who} · tier {n}',
      'def.heal': 'Heal <b>{n}</b>',
      'def.dps': '<b>{n}</b>/s',
      'def.tagSplash': '(area)',
      'def.tagRing': '(around)',
      'def.tagSmite': '(+heal)',
      'def.tagHoly': '(holy)',
      'def.basicSplash': 'Basic attack hits an area',
      'def.basicRing': 'Basic attack also cuts all around',
      'def.basicSmite': 'Basic attack also heals allies',
      'def.basicSingle': 'Basic attack hits one',
      'def.holyNote': 'Holy, so double against undead',
      'def.stats': 'HP <b>{hp}/{maxHp}</b> · ATK <b>{dmg}</b>{tag} · range <b>{min}-{max}</b>',
      'def.skillLine': '{skill} {power} · cooldown <b>{cd}s</b>',
      'def.hold': 'lasts <b>{n}s</b>',
      'def.waitLeft': '<b>{n}s left</b>',
      'def.ready': '<b>ready</b>',
      'def.maxed': '<b>Fully upgraded</b>',
      'def.upgrade': '<b>Upgrade {cost}</b>',
      'def.upgradeStats': 'ATK {a}→{b} · HP {c}→{d} · range +{e}',
      'def.upgradeCd': 'Cooldown {a}→{b}s',
      'def.upgradeHold': 'Duration {a}→{b}s',
      'def.sell': 'Dismiss +{n}',
      'def.fell': '{who} has fallen',
      'def.bossPassed': 'The boss got through · lives −{n}',
      'def.foePassed': 'An enemy got through',
      'def.waveStart': 'Wave {n}',
      'def.waveBoss': 'Wave {n} · boss',
      'def.statDealt': 'Damage {n}',
      'def.statKills': 'Kills {n}',
      'def.statTaken': 'Tanked {n}',
      'def.statHealed': 'Healed {n}',
      'def.statSkills': 'Skills {n}',
      'def.statHired': 'Hired {n}',
      'def.cleared': 'Stage {n} cleared',
      'def.failed': 'They broke through',
      'def.wonNote': '{lives} lives left · {time}s',
      'def.lostNote': 'Held to wave {n}',
      'def.goalDone': 'Goal met — {name}',
      'def.goalMissed': 'Goal {name}: next time',
      'def.gemsGot': 'Gems +{n}',
      'def.nextStage': 'Next stage',
      'def.heroTip': 'Costs no gold. Standing next to another hero adds +{pct}% damage and cooldown per hero',
      'def.leadTip': '(double for the Commander)',
      'def.paletteTip': '{who} · range {min}-{max}{basic} · {skill} ({cd}s) — {note} · up to {most} of a kind, and each extra costs more',
      'def.pickToMove': 'Tap the unit to move',
      'def.pickTarget': 'Tap where it should go',
      'def.cannotUse': 'Cannot use that now',
      'def.cannotGo': 'It cannot go there',
      'def.gems': 'Gems {n}',
      'def.stageCleared': 'Cleared',
      'def.stageNotYet': 'Not yet',
      'def.stageLine': '{state} · goal {goal}',
      'def.slots': '{used}/{total} slots',
      'def.inTeam': 'In the team',
      'def.noEmptyTeam': 'You cannot go in with nobody',
      'def.teamFull': 'The team is full',
      'def.noHeroes': 'None yet. From stage {n} on, meeting a goal offers them as a card.',
      'def.taken': 'Taking',
      'def.hire': 'Hire {n}',
      'def.heroFull': 'No hero slots left',
      'def.allUnlocked': 'Everything is unlocked.',
      'def.heroPrefix': 'Hero {name}',
      'def.rangeSkill': 'Range {min}-{max} · {skill} — {note}',
      'def.gemPrice': 'Gems {n}',
      'def.levelRow': 'Army level <b>{n}</b>',
      'def.levelNote': 'Raises attack and health for everyone you own',
      'def.levelDelta': '{name} {a}→{b}',
      'def.perkTop': 'Max',
      'def.speed': '{n}× speed',
      'def.cardGems': '{n} gems',
      'def.cardGemsNote': 'Spent on levelling up',
      'def.cardItems': '{name} ×2',
      'def.cardItemsNote': 'Single use, inside a run',
      'def.why.over': 'The run is over',
      'def.why.noSuchUnit': 'No such unit',
      'def.why.notInTeam': 'Not in your team',
      'def.why.offBoard': 'Off the board',
      'def.why.wall': 'A wall',
      'def.why.occupiedByUnit': 'Somebody is already there',
      'def.why.foeThere': 'An enemy is standing there',
      'def.why.entry': 'That is where enemies come out',
      'def.why.heroUsed': 'That hero has already been called',
      'def.why.noGold': 'Not enough gold',
      'def.help.r1': '<b>Pick a unit below and tap an empty square</b> to place it there. While you hold, you get a preview of <b>how the enemy path changes</b>.',
      'def.help.r2': 'Enemies take <b>the fastest route to the exit</b>. If smashing through a unit is quicker than going around, <b>they smash through.</b>',
      'def.help.r3': 'So <b>you may block the path completely.</b> The units doing the blocking get destroyed, and destroyed units do not come back.',
      'def.help.r4': 'A <b>siegebreaker</b> smashes through even for a short detour. A plan built on blocking alone collapses here.',
      'def.help.r5': '<b>Every enemy that reaches the exit costs a life.</b> Run out of lives and the run ends.',
      'def.help.r6': 'A run is <b>ten waves</b>, and the last one is the <b>boss</b>.',
      'def.help.r7': 'A placed unit can be <b>upgraded with gold</b>, and <b>dismissing one refunds part of the cost.</b> Tap a unit and the button shows its current health and attack alongside <b>how much the upgrade adds</b>.',
      'def.help.r8': '<b>Higher tiers make skills fire more often and last longer.</b> Cooldowns drop and durations (ice, bleed, stun) grow, so <b>the long-cooldown frostmage and archmage gain the most</b> — a tier-3 frostmage keeps the ice almost unbroken.',
      'def.help.r9': 'At the end of a run it shows <b>who did how much</b>, unit by unit — damage, kills, damage tanked, healing and skill uses.',
      'def.help.r10': '<b>Range differs per unit and has an inner limit.</b> The gunner covers 2–5 squares, so <b>it cannot hit what is right beside it</b> — tap it and the range shows as a ring.',
      'def.help.r11': '<b>You cannot build on a square an enemy is standing on, or on the spawn.</b> Claim the chokepoints early.',
      'def.help.r12': '<b>You can wall off the entrance, but it does not pay.</b> Enemies packed into one square <b>all hit the same unit</b>, so the damage multiplies by their number — ten of them is 120 a second, and a shieldbearer does not last 25 seconds. Spreading them out along a longer path holds far better.',
      'def.help.r13': 'A <b>hero</b> can be called <b>once per run</b> and takes its own team slot. They are expensive, so you cannot field one on wave one: <b>which wave to bring them out</b> is the decision. They start appearing as cards from stage 4.',
      'def.help.r14': 'Every stage carries a <b>goal</b>. <b>Missing it still counts as cleared</b>; meeting it lets you <b>pick a card</b> — a new unit, gems, or single-use items.',
      'def.help.r15': '<b>Gems raise your level.</b> The numbers inside a run stay the same while the enemies get stronger each stage, so going far means levelling up.',
      'def.help.r16': '<b>Even a lost run pays gems.</b> When you are stuck, save up items and spend them all in one run.',
      'def.help.r17': '<b>Different enemies answer to different attacks.</b> Build your team from the table below. Levelling only one kind will wall you somewhere.',
      'def.help.r18': '<b>Up to four of a kind per run</b>, and <b>each extra one costs more.</b>',
      'def.help.r19': '<b>Gems buy exactly one thing: army level.</b> It raises attack and health for everyone you own, so a unit you just unlocked pulls its weight at once — who to bring is purely a question of <b>the map and the enemy</b>.',
      'def.help.r20': 'In the camp you can <b>unlock a locked unit outright with gems</b>. Missing a goal never leaves you without the type you need.',
      'def.help.mapTitle': 'The map and the enemy decide your team',
      'def.help.mapNote': 'Before a run starts, the header and the camp tell you <b>what kind of map it is</b> and <b>which enemy dominates it</b>. Picking your three from those two facts is the game.',
      'def.help.m1': '<b>Open field</b> — wide open, nothing to block with. You have to melt them with firepower.',
      'def.help.m2': '<b>Rough ground</b> — evenly open, the standard map.',
      'def.help.m3': '<b>Maze</b> — plenty of narrow chokepoints. <b>Block with a shieldbearer or blademaster</b> and hit from behind.',
      'def.help.foeTitle': 'Different enemies answer to different attacks.',
      'def.help.f1': '<b>Footsoldier</b> — no weakness. The cheap <b>archer</b> is the best answer.',
      'def.help.f2': '<b>Swarm</b> — shooting one at a time wastes half your output. Go <b>area</b> (gunner, archmage).',
      'def.help.f3': '<b>Skirmisher</b> — so fast it runs past your range. <b>Pin them with a frostmage</b> and pair it with single-target damage. Area attacks miss because they run spread out.',
      'def.help.f4': '<b>Heavy</b> — barely takes single-target or area damage. Only <b>damage over time</b>, which ignores armour, gets through (spear bleed, ice field).',
      'def.help.f5': '<b>Siegebreaker</b> — eats damage-over-time and area, and shrugs off ice, but <b>single-target damage</b> goes straight through. It smashes at 60 a second, so buy time with a <b>shieldbearer and healer</b>.',
      'def.help.f6': '<b>Field medic</b> — every damage type is partly reduced and it heals itself. Break it with <b>a skill that lands big all at once</b>.',
      'def.help.f7': '<b>Skeleton and wraith</b> (undead) — everything that works on the living only lands <b>at about half</b>. But <b>holy</b> damage burns them double, so the <b>healer</b> and the hero <b>paladin</b>, whose attacks are holy, become your damage here. The wraith is fast and resists ice too.',
      'def.help.sixTitle': 'The six defenders',
      'def.help.sixNote': 'Everyone has a <b>basic attack</b> and a <b>skill</b>. The skill fires when its cooldown comes round, and <b>in between they hit one target with the basic attack.</b> Tap a unit to see the cooldown left; on the board, the dot at its top right lights up when it is ready.',
      'def.help.u1': '<b>Archer</b>, 1–4 squares — <b>Careful Shot</b> (5s): one shot with a damage multiplier.',
      'def.help.u2': '<b>Shieldbearer</b>, 1 square — <b>Bash</b> (3.5s): a 1.2-second <b>stun</b>. Weak attack, very high health: this is the unit that holds the front.',
      'def.help.u3': '<b>Gunner</b>, 2–5 squares — <b>Bombardment</b> (6s): catches the surroundings in one shot. <b>Cannot hit what is adjacent.</b>',
      'def.help.u4': '<b>Frostmage</b>, 1–3 squares — <b>Ice Field</b> (<b>9s</b>): freezes the ground so that standing on it keeps draining and slowing. The longest wait of all, but it changes the board.',
      'def.help.u5': '<b>Spearman</b>, 1–2 squares — <b>Impale</b> (4s): runs through every enemy in a line and leaves them <b>bleeding</b>.',
      'def.help.u6': '<b>Healer</b>, 1–3 squares — <b>Heal</b> (3.5s): restores the most wounded ally. With nobody to heal, it fights. Its attacks are <b>holy</b>, so they land <b>double on undead</b>, and the heal burns undead nearby.',
      'def.help.heroTitle': 'The four heroes',
      'def.help.heroNote1': '<b>Heroes cost no gold.</b> Instead you can call <b>only one per wave</b> — the first on wave 2, the second on wave 3, the third on wave 4. If the regular team is a fight over gold, heroes are a fight over time.',
      'def.help.heroNote2': '<b>Heroes standing together strengthen each other</b> (resonance). With another hero within two squares, <b>damage and skill cooldown improve by +50% per hero</b>, and <b>the Commander counts as two</b> — so two heroes is ×1.5, three is ×2, and with the Commander in the mix ×2.5. When they link up, a dotted line joins them.',
      'def.help.h1': '<b>Blademaster Lean</b>, 1 square — his place is <b>a few enemies up close</b>. Both the basic and <b>Whirlwind</b> (4.5s) cut everything touching him, with himself at the centre. His health is very high, so <b>put him on a chokepoint</b> — far back he never meets anyone.',
      'def.help.h2': '<b>Archmage Morwyn</b>, 2–6 squares — her place is <b>many enemies at a distance</b>. Even the basic is wide area, and <b>Meteor</b> (9s) is wider still. She reaches from one edge of the board to the other, but <b>cannot hit what is adjacent</b>, and her health is paper, so she cannot stand in front.',
      'def.help.h3': '<b>Commander Berin</b>, 1–5 squares — his place is <b>working the units around him</b>. <b>Rally Cry</b> (5s) pulls every nearby ally’s cooldown forward at once, and double for heroes. He also counts as two for resonance, so <b>wedging him between two heroes</b> is best. Alone he is the weakest of the heroes.',
      'def.help.h4': '<b>Paladin Garon</b>, 1–4 squares — his place is <b>against the undead</b>. His attacks are <b>holy</b>, so they land double on skeletons and wraiths, and <b>Light of Healing</b> (6s) restores allies while burning the undead around him. Against the living he is ordinary.'
    },
    ja: {
      'meta.desc': '通り道に人を置いて押し寄せる敵を止める',
      'def.camp': '整備',
      'def.palette': '置く人',
      'def.items': '使い切りアイテム',
      'def.dismiss': '解雇',
      'def.up': '強化',
      'def.rush': 'すぐ送る',
      'def.stageLabel': 'ステージ',
      'def.prevStage': '前のステージ',
      'def.teamLabel': '編成',
      'def.heroLabel': '英雄',
      'def.heroLabelNote': 'それぞれ一判に一度。並べて置くと互いのスキルを早める',
      'def.lockedLabel': '未開放の人',
      'def.lockedNote': '目標を達成するとカードで出て、ジェムですぐ開放もできる',
      'def.growLabel': '育成',
      'def.growNote': '部隊レベル一つが持っている全員の被害と体力を上げる',
      'def.otherLabel': 'その他',
      'def.unit.archer': '弓手',
      'def.unit.shield': '盾兵',
      'def.unit.cannon': '砲手',
      'def.unit.frost': '氷術士',
      'def.unit.spear': '槍兵',
      'def.unit.healer': 'ヒーラー',
      'def.unit.blade': '剣聖',
      'def.unit.arch': '大魔導士',
      'def.unit.warden': '司令官',
      'def.unit.saint': '聖騎士',
      'def.who.blade': 'レアン',
      'def.who.arch': 'モルウィン',
      'def.who.warden': 'ベリン',
      'def.who.saint': 'ガロン',
      'def.unit.archer.note': '遠くから一体ずつ',
      'def.unit.shield.note': '前を止めて耐える。体力がとても高い',
      'def.unit.cannon.note': '目の前は撃てない',
      'def.unit.frost.note': '待つ代わりに盤面を変える',
      'def.unit.spear.note': '',
      'def.unit.healer.note': '癒す相手がいなければ一緒に戦う。アンデッドに強い',
      'def.unit.blade.note': '要所に置いてこそ価値が出る。接した相手だけ斬る',
      'def.unit.arch.note': '盤の端から端まで届く。目の前は撃てない',
      'def.unit.warden.note': 'そばに誰かいるほど強くなる。単独では最弱',
      'def.unit.saint.note': '癒しながら戦う。アンデッドにとても強い',
      'def.skill.archer': '狙い撃ち',
      'def.skill.shield': '叩きつけ',
      'def.skill.cannon': '砲撃',
      'def.skill.frost': '氷結地帯',
      'def.skill.spear': '貫き',
      'def.skill.healer': '治癒',
      'def.skill.blade': '回転斬り',
      'def.skill.arch': '隕石',
      'def.skill.warden': '号令',
      'def.skill.saint': '癒しの光',
      'def.skill.archer.note': '二倍を超える一撃',
      'def.skill.shield.note': '叩いて足を止める',
      'def.skill.cannon.note': '一発が周囲まで及ぶ',
      'def.skill.frost.note': '地面を凍らせる。踏んでいる間は削られ遅くなる',
      'def.skill.spear.note': '一列を貫き出血を残す',
      'def.skill.healer.note': '最も傷ついた味方を癒し、周囲のアンデッドを焼く',
      'def.skill.blade.note': '周囲をまとめて斬る',
      'def.skill.arch.note': '落として焼く',
      'def.skill.warden.note': '周囲のスキルを一気に早める。英雄は二倍',
      'def.skill.saint.note': '周囲の味方を一度に癒し、アンデッドを焼く',
      'def.foe.grunt': '歩兵',
      'def.foe.swarm': '群れ',
      'def.foe.swift': '軽歩兵',
      'def.foe.armored': '重装兵',
      'def.foe.breaker': '攻城兵',
      'def.foe.mender': '衛生兵',
      'def.foe.bone': '骸骨兵',
      'def.foe.wraith': '亡霊',
      'def.foe.boss': 'ボス',
      'def.map.plain': '平原',
      'def.map.rough': '荒れ地',
      'def.map.maze': '迷路',
      'def.map.plain.note': '開けていて塞ぐ場所がない',
      'def.map.rough.note': 'ほどよく開けた盤',
      'def.map.maze.note': '狭い通り道が多い',
      'def.goal.flawless': '無失点',
      'def.goal.swift': '速攻',
      'def.goal.thrifty': '節約',
      'def.goal.purist': '一本槍',
      'def.goal.saver': '貯め',
      'def.goal.barehand': '素手',
      'def.goal.behead': '斬首',
      'def.goal.flawless.note': '命を一つも失わない',
      'def.goal.swift.note': '{arg}秒以内に終える',
      'def.goal.thrifty.note': '{arg}人以下で守り切る',
      'def.goal.purist.note': '一種類だけ使う',
      'def.goal.saver.note': 'ゴールドを{arg}以上残す',
      'def.goal.barehand.note': '誰も強化しない',
      'def.goal.behead.note': 'ボスを{arg}秒以内に倒す',
      'def.item.bomb': '爆弾',
      'def.item.freeze': '氷結',
      'def.item.purse': '補給',
      'def.item.mend': '救護',
      'def.item.order': '命令書',
      'def.item.bomb.note': 'すべての敵の体力を35%削る',
      'def.item.freeze.note': '3秒間すべてを止める',
      'def.item.purse.note': 'ゴールド120',
      'def.item.mend.note': '命を一つ戻す',
      'def.item.order.note': '一人を空きマスへ移す',
      'def.perk.lives': '命',
      'def.perk.slots': '編成枠',
      'def.perk.purse': '開始ゴールド',
      'def.perk.hero': '英雄枠',
      'def.perk.lives.note': '開始時の命が一つ増える',
      'def.perk.slots.note': '連れて行ける人が一人増える',
      'def.perk.purse.note': '開始ゴールドが10%増える',
      'def.perk.hero.note': '連れて行ける英雄が一人増える',
      'def.stage': 'ステージ {n}',
      'def.lives': '命 {n}',
      'def.gold': 'ゴールド {n}',
      'def.waiting': '待機',
      'def.startsIn': 'まもなく開始 {n}',
      'def.nextWave': '{wave}/{total} · 次 {n}',
      'def.wave': 'ウェーブ {wave}/{total}',
      'def.mainFoe': '{map} · 主力は<b>{foe}</b>',
      'def.mapLine': '<b>{name}</b> {note}',
      'def.goalLine': '目標 <b>{name}</b> · {note}',
      'def.called': '召喚済み',
      'def.callNow': 'いま',
      'def.callFrom': '{n}ウェーブ',
      'def.tier': '{who} {n}段階',
      'def.heal': '回復 <b>{n}</b>',
      'def.dps': '毎秒 <b>{n}</b>',
      'def.tagSplash': '(範囲)',
      'def.tagRing': '(周囲)',
      'def.tagSmite': '(+回復)',
      'def.tagHoly': '(神聖)',
      'def.basicSplash': '通常攻撃が範囲',
      'def.basicRing': '通常攻撃も周囲を斬る',
      'def.basicSmite': '通常攻撃も味方を癒す',
      'def.basicSingle': '通常攻撃は単体',
      'def.holyNote': '神聖なのでアンデッドに二倍',
      'def.stats': '体力 <b>{hp}/{maxHp}</b> · 攻撃 <b>{dmg}</b>{tag} · 射程 <b>{min}-{max}</b>',
      'def.skillLine': '{skill} {power} · クールタイム <b>{cd}秒</b>',
      'def.hold': '持続 <b>{n}秒</b>',
      'def.waitLeft': '<b>あと{n}秒</b>',
      'def.ready': '<b>準備完了</b>',
      'def.maxed': '<b>最後まで強化済み</b>',
      'def.upgrade': '<b>強化 {cost}</b>',
      'def.upgradeStats': '攻撃 {a}→{b} · 体力 {c}→{d} · 射程 +{e}マス',
      'def.upgradeCd': 'クールタイム {a}→{b}秒',
      'def.upgradeHold': '持続 {a}→{b}秒',
      'def.sell': '解雇 +{n}',
      'def.fell': '{who}が倒れた',
      'def.bossPassed': 'ボスが通り抜けた · 命 −{n}',
      'def.foePassed': '敵が通り抜けた',
      'def.waveStart': 'ウェーブ {n}',
      'def.waveBoss': 'ウェーブ {n} · ボス',
      'def.statDealt': '与ダメージ {n}',
      'def.statKills': '撃破 {n}',
      'def.statTaken': '受け {n}',
      'def.statHealed': '回復 {n}',
      'def.statSkills': 'スキル {n}',
      'def.statHired': '{n}人雇用',
      'def.cleared': 'ステージ {n} 突破',
      'def.failed': '抜かれた',
      'def.wonNote': '命 {lives} 残し · {time}秒',
      'def.lostNote': 'ウェーブ {n} まで耐えた',
      'def.goalDone': '目標達成 — {name}',
      'def.goalMissed': '目標 {name} は次回に',
      'def.gemsGot': 'ジェム +{n}',
      'def.nextStage': '次のステージ',
      'def.heroTip': 'ゴールドがかからない。他の英雄のそばに立つと一人につき被害とクールタイムが+{pct}%',
      'def.leadTip': '（司令官は二倍）',
      'def.paletteTip': '{who} · 射程 {min}-{max}{basic} · {skill}（{cd}秒）— {note} · 同じ種類は{most}人まで、重ねるほど値が上がる',
      'def.pickToMove': '動かす人を押してください',
      'def.pickTarget': '移る場所を押してください',
      'def.cannotUse': 'いまは使えない',
      'def.cannotGo': 'そこへは行けない',
      'def.gems': 'ジェム {n}',
      'def.stageCleared': 'クリア済み',
      'def.stageNotYet': 'まだ',
      'def.stageLine': '{state} · 目標 {goal}',
      'def.slots': '{used}/{total}枠',
      'def.inTeam': '編成済み',
      'def.noEmptyTeam': '誰もいないままでは行けない',
      'def.teamFull': '編成枠がいっぱいだ',
      'def.noHeroes': 'まだいません。ステージ {n} から目標を達成するとカードで出ます。',
      'def.taken': '連れて行く',
      'def.hire': '雇用 {n}',
      'def.heroFull': '英雄枠がいっぱいだ',
      'def.allUnlocked': 'すべて開放しました。',
      'def.heroPrefix': '英雄 {name}',
      'def.rangeSkill': '射程 {min}-{max} · {skill} — {note}',
      'def.gemPrice': 'ジェム {n}',
      'def.levelRow': '部隊レベル <b>{n}</b>',
      'def.levelNote': '持っている全員の攻撃と体力が一緒に上がる',
      'def.levelDelta': '{name} {a}→{b}',
      'def.perkTop': '最大',
      'def.speed': '{n}倍速',
      'def.cardGems': 'ジェム {n}',
      'def.cardGemsNote': 'レベルを上げるのに使う',
      'def.cardItems': '{name} 2個',
      'def.cardItemsNote': '一回の判で一度ずつ使う',
      'def.why.over': '判が終わった',
      'def.why.noSuchUnit': 'いない人',
      'def.why.notInTeam': '編成にいない',
      'def.why.offBoard': '盤の外',
      'def.why.wall': '壁',
      'def.why.occupiedByUnit': 'すでに立っている',
      'def.why.foeThere': '敵が踏んでいる',
      'def.why.entry': '敵が出てくる場所',
      'def.why.heroUsed': 'その英雄はもう呼んだ',
      'def.why.noGold': 'ゴールドが足りない',
      'def.help.r1': '下から<b>人を選んで空きマスを押すと</b>そこに立ちます。押している間は<b>敵の道がどう変わるか</b>が先に見えます。',
      'def.help.r2': '敵は<b>最も早く出口に着く道</b>を通ります。回り道より人を壊す方が速ければ<b>壊して通ります。</b>',
      'def.help.r3': 'だから道を<b>完全に塞いでも構いません。</b>ただし塞いだ人は壊れ、壊れた人は戻りません。',
      'def.help.r4': '<b>攻城兵</b>は少し回るだけでも突き破ってきます。塞ぐだけの構成はここで崩れます。',
      'def.help.r5': '敵が<b>出口に着くと命が減ります。</b>命が尽きるとその判は終わりです。',
      'def.help.r6': '一判は<b>ウェーブ十個</b>で、最後は<b>ボス</b>です。',
      'def.help.r7': '置いた人は<b>ゴールドで強化でき</b>、<b>解雇すれば一部が戻ります。</b>人を押すと今の体力・攻撃と一緒に<b>強化でどれだけ上がるか</b>がボタンに出ます。',
      'def.help.r8': '<b>段階を上げるとスキルがより頻繁に、より長く出ます。</b>クールタイムが縮み持続（氷・出血・気絶）が伸びるので、<b>クールタイムの長い氷術士と大魔導士が最も伸びます</b> — 3段階の氷術士は氷がほぼ切れません。',
      'def.help.r9': '判が終わると<b>誰がどれだけやったか</b>をキャラごとに見せます — ダメージ、撃破、身で受けたダメージ、回復、スキル回数。',
      'def.help.r10': '<b>射程は人ごとに違い、内側にも限界があります。</b>砲手は2〜5マスなので<b>目の前の敵は撃てません</b> — 押すと射程がドーナツ状に見えます。',
      'def.help.r11': '<b>敵が踏んでいるマスと敵が出てくる場所には置けません。</b>要所は先に押さえておきましょう。',
      'def.help.r12': '<b>入口を囲んで塞ぐこともできますが、割に合いません。</b>一マスに固まった敵は<b>全員が同じ人を叩く</b>ので、受けるダメージが数だけ掛け算になります — 十体なら毎秒120で、盾兵が25秒もちません。長く並べて分散させる方が長もちします。',
      'def.help.r13': '<b>英雄</b>は一判に<b>一度だけ</b>呼べ、編成で別枠を一つ使います。高いので最初のウェーブには出せず、<b>どのウェーブで出すか</b>が判断です。ステージ4からカードで出ます。',
      'def.help.r14': 'ステージごとに<b>目標</b>が付きます。<b>達成できなくてもクリアはクリア</b>で、達成すると<b>カードを一枚選べます</b> — 新しい人、ジェム、使い切りアイテム。',
      'def.help.r15': '<b>ジェムでレベルを上げます。</b>判の中の値はそのままで、ステージごとに敵だけ強くなるので、先へ進むには育てる必要があります。',
      'def.help.r16': '<b>負けた判でもジェムはもらえます。</b>詰まったときはアイテムを貯めて一判に集中して使いましょう。',
      'def.help.r17': '<b>敵ごとに通る攻撃が違います。</b>下の表を見て編成しましょう。一種類だけ育てるとどこかで必ず詰まります。',
      'def.help.r18': '<b>同じ種類は判に四人まで</b>で、<b>重ねるほど値が上がります。</b>',
      'def.help.r19': '<b>ジェムで上げるのは部隊レベル一つだけ</b>です。持っている全員の攻撃と体力が一緒に上がるので、手に入れたばかりの人もすぐ役に立ちます — 誰を連れて行くかは<b>盤と敵</b>だけの問題です。',
      'def.help.r20': '整備で<b>ジェムで鍵のかかった人をそのまま開放できます。</b>目標を逃しても、必要な種類が手に入らないことはありません。',
      'def.help.mapTitle': '盤と敵が編成を決める',
      'def.help.mapNote': '判を開く前に<b>盤の性格</b>と<b>その判の主力の敵</b>が見出しと整備に出ます。その二つを見て連れて行く三人を選ぶのがこのゲームです。',
      'def.help.m1': '<b>平原</b> — 開けていて塞ぐ場所がありません。火力で溶かすしかありません。',
      'def.help.m2': '<b>荒れ地</b> — ほどよく開けた普通の盤。',
      'def.help.m3': '<b>迷路</b> — 狭い通り道が多いです。<b>盾兵・剣聖で塞ぎ</b>、後ろから叩くのが効きます。',
      'def.help.foeTitle': '敵ごとに効く攻撃が違います。',
      'def.help.f1': '<b>歩兵</b> — 弱点がありません。安い<b>弓手</b>が最も良いです。',
      'def.help.f2': '<b>群れ</b> — 単体で撃つと半分が無駄になります。<b>範囲</b>（砲手・大魔導士）。',
      'def.help.f3': '<b>軽歩兵</b> — 速すぎて射程を通り過ぎます。<b>氷術士で足を止め</b>、単体で叩く人を並べましょう。範囲は散って走るので当たりにくいです。',
      'def.help.f4': '<b>重装兵</b> — 単体も範囲もほとんど通りません。防御を無視する<b>持続ダメージ</b>（槍兵の出血、氷結地帯）だけが残ります。',
      'def.help.f5': '<b>攻城兵</b> — 持続と範囲を食べ、氷も効きにくいですが、<b>単体で突き刺す攻撃</b>にはそのまま抜かれます。毎秒60で壊してくるので<b>盾兵・ヒーラー</b>で時間を稼ぎましょう。',
      'def.help.f6': '<b>衛生兵</b> — どの種類で叩いても幾らか削られ、自分を癒します。<b>一度に大きく入るスキル</b>で断ち切りましょう。',
      'def.help.f7': '<b>骸骨兵・亡霊</b>（アンデッド） — 生きた敵に効く手段が<b>すべて半分ほど</b>しか通りません。代わりに<b>神聖</b>には二倍で焼かれます — 攻撃が神聖な<b>ヒーラー</b>と英雄<b>聖騎士</b>がここでは主力です。亡霊は速く、氷も効きにくいです。',
      'def.help.sixTitle': '守る者たち六人',
      'def.help.sixNote': '全員が<b>通常攻撃</b>と<b>スキル</b>を持ちます。スキルはクールタイムが戻ったときに出て、<b>その間は通常攻撃で単体を叩きます。</b>人を押すと残りクールタイムが見え、盤では右上の点が点けば準備完了です。',
      'def.help.u1': '<b>弓手</b> 1〜4マス — <b>狙い撃ち</b>（5秒）：倍率の付いた一撃。',
      'def.help.u2': '<b>盾兵</b> 1マス — <b>叩きつけ</b>（3.5秒）：1.2秒の<b>気絶</b>。攻撃は弱く体力がとても高い、前を止める役です。',
      'def.help.u3': '<b>砲手</b> 2〜5マス — <b>砲撃</b>（6秒）：周囲までまとめて。<b>目の前は撃てません。</b>',
      'def.help.u4': '<b>氷術士</b> 1〜3マス — <b>氷結地帯</b>（<b>9秒</b>）：地面を凍らせ、踏んでいる間ずっと削り遅くします。最も長く待つ代わりに盤面を変えます。',
      'def.help.u5': '<b>槍兵</b> 1〜2マス — <b>貫き</b>（4秒）：一列に並んだ敵をすべて貫き<b>出血</b>を残します。',
      'def.help.u6': '<b>ヒーラー</b> 1〜3マス — <b>治癒</b>（3.5秒）：最も傷ついた味方を戻します。癒す相手がいなければ一緒に戦います。攻撃が<b>神聖</b>なので<b>アンデッドに二倍</b>で入り、治癒が周囲のアンデッドを焼きます。',
      'def.help.heroTitle': '英雄四人',
      'def.help.heroNote1': '<b>英雄はゴールドがかかりません。</b>代わりに<b>ウェーブごとに一人ずつ</b>しか呼べません — 2ウェーブで一人目、3ウェーブで二人目、4ウェーブで三人目です。通常編成がゴールドの戦いなら、英雄は時間の戦いです。',
      'def.help.heroNote2': '<b>英雄同士を近くに置くと互いに強くなります</b>（共鳴）。周囲二マス以内に他の英雄がいると<b>被害とスキルのクールタイムが一人につき+50%</b>で、<b>司令官は二人分</b>と数えます — 二人なら×1.5、三人なら×2、司令官が入れば×2.5です。つながると点線で結ばれて見えます。',
      'def.help.h1': '<b>剣聖レアン</b> 1マス — <b>近くの少数</b>が持ち場です。通常も<b>回転斬り</b>（4.5秒）も自分を中心に接した相手をまとめて斬ります。体力がとても高いので<b>要所に置いてこそ</b>価値が出ます — 遠くに置くと誰にも会えません。',
      'def.help.h2': '<b>大魔導士モルウィン</b> 2〜6マス — <b>遠くの多数</b>が持ち場です。通常から広い範囲で、<b>隕石</b>（9秒）はさらに広いです。盤の端から端まで届きますが<b>目の前は撃てず</b>、体力が紙なので前には置けません。',
      'def.help.h3': '<b>司令官ベリン</b> 1〜5マス — <b>周りを働かせる</b>持ち場です。<b>号令</b>（5秒）が周囲の味方のスキルクールタイムを一気に早め、英雄には二倍で早めます。共鳴も二人分なので<b>英雄二人の間に挟んで置く</b>のが最良です。単独では英雄中もっとも弱いです。',
      'def.help.h4': '<b>聖騎士ガロン</b> 1〜4マス — <b>アンデッド</b>が持ち場です。攻撃が<b>神聖</b>なので骸骨兵・亡霊に二倍で入り、<b>癒しの光</b>（6秒）は味方を戻しながら周囲のアンデッドを焼きます。生きた敵には普通です。'
    },
    'zh-CN': {
      'meta.desc': '在路口布防，挡住涌来的敌人',
      'def.camp': '整备',
      'def.palette': '可放置的人',
      'def.items': '一次性道具',
      'def.dismiss': '解雇',
      'def.up': '升级',
      'def.rush': '立刻开始',
      'def.stageLabel': '关卡',
      'def.prevStage': '上一关',
      'def.teamLabel': '编队',
      'def.heroLabel': '英雄',
      'def.heroLabelNote': '每局各能召唤一次。放在一起会互相加快技能',
      'def.lockedLabel': '未解锁的人',
      'def.lockedNote': '达成目标会作为卡片出现，也可以直接用宝石解锁',
      'def.growLabel': '培养',
      'def.growNote': '一个部队等级提升你拥有的所有人的伤害与生命',
      'def.otherLabel': '其他',
      'def.unit.archer': '弓手',
      'def.unit.shield': '盾兵',
      'def.unit.cannon': '炮手',
      'def.unit.frost': '冰术士',
      'def.unit.spear': '枪兵',
      'def.unit.healer': '治疗师',
      'def.unit.blade': '剑圣',
      'def.unit.arch': '大魔法师',
      'def.unit.warden': '指挥官',
      'def.unit.saint': '圣骑士',
      'def.who.blade': '雷安',
      'def.who.arch': '莫尔温',
      'def.who.warden': '贝林',
      'def.who.saint': '加隆',
      'def.unit.archer.note': '远远地一个个点掉',
      'def.unit.shield.note': '挡在前面硬抗，血量很高',
      'def.unit.cannon.note': '打不到贴脸的敌人',
      'def.unit.frost.note': '等得久，但能改变局面',
      'def.unit.spear.note': '',
      'def.unit.healer.note': '没人要治时就一起打，克制亡灵',
      'def.unit.blade.note': '摆在要道才划算，只砍贴身的',
      'def.unit.arch.note': '能打到棋盘另一头，但打不到贴脸的',
      'def.unit.warden.note': '旁边人越多越强，单独时最弱',
      'def.unit.saint.note': '边治边打，非常克制亡灵',
      'def.skill.archer': '瞄准射击',
      'def.skill.shield': '重击',
      'def.skill.cannon': '炮击',
      'def.skill.frost': '冰霜地带',
      'def.skill.spear': '穿刺',
      'def.skill.healer': '治疗',
      'def.skill.blade': '回旋斩',
      'def.skill.arch': '陨石',
      'def.skill.warden': '号令',
      'def.skill.saint': '治愈之光',
      'def.skill.archer.note': '一发打出两倍以上',
      'def.skill.shield.note': '一击把敌人打停',
      'def.skill.cannon.note': '一炮波及周围',
      'def.skill.frost.note': '冻住地面，踩上去会掉血变慢',
      'def.skill.spear.note': '贯穿一条线并留下流血',
      'def.skill.healer.note': '治疗伤得最重的队友，并灼烧周围亡灵',
      'def.skill.blade.note': '把周围一圈全砍',
      'def.skill.arch.note': '砸下去点燃',
      'def.skill.warden.note': '一次拉快周围所有技能，英雄加倍',
      'def.skill.saint.note': '一次治疗周围所有队友，并灼烧亡灵',
      'def.foe.grunt': '步兵',
      'def.foe.swarm': '虫群',
      'def.foe.swift': '轻步兵',
      'def.foe.armored': '重装兵',
      'def.foe.breaker': '攻城兵',
      'def.foe.mender': '医疗兵',
      'def.foe.bone': '骷髅兵',
      'def.foe.wraith': '幽魂',
      'def.foe.boss': '首领',
      'def.map.plain': '平原',
      'def.map.rough': '旷野',
      'def.map.maze': '迷宫',
      'def.map.plain.note': '太开阔，没地方拦',
      'def.map.rough.note': '开阔均匀的地形',
      'def.map.maze.note': '窄路口很多',
      'def.goal.flawless': '无失误',
      'def.goal.swift': '速攻',
      'def.goal.thrifty': '节俭',
      'def.goal.purist': '专一',
      'def.goal.saver': '省钱',
      'def.goal.barehand': '空手',
      'def.goal.behead': '斩首',
      'def.goal.flawless.note': '一条命都不丢',
      'def.goal.swift.note': '在 {arg} 秒内完成',
      'def.goal.thrifty.note': '用不超过 {arg} 人守住',
      'def.goal.purist.note': '只用一个种类',
      'def.goal.saver.note': '结束时剩下至少 {arg} 金',
      'def.goal.barehand.note': '谁都不升级',
      'def.goal.behead.note': '在 {arg} 秒内击杀首领',
      'def.item.bomb': '炸弹',
      'def.item.freeze': '冰冻',
      'def.item.purse': '补给',
      'def.item.mend': '救护',
      'def.item.order': '调令',
      'def.item.bomb.note': '全体敌人扣 35% 生命',
      'def.item.freeze.note': '全场静止 3 秒',
      'def.item.purse.note': '120 金',
      'def.item.mend.note': '回复一条命',
      'def.item.order.note': '把一个人移到空格',
      'def.perk.lives': '生命',
      'def.perk.slots': '编队位',
      'def.perk.purse': '初始金币',
      'def.perk.hero': '英雄位',
      'def.perk.lives.note': '开局多一条命',
      'def.perk.slots.note': '每局多带一个人',
      'def.perk.purse.note': '初始金币增加 10%',
      'def.perk.hero.note': '每局多带一名英雄',
      'def.stage': '第 {n} 关',
      'def.lives': '生命 {n}',
      'def.gold': '金币 {n}',
      'def.waiting': '待命',
      'def.startsIn': '{n} 秒后开始',
      'def.nextWave': '{wave}/{total} · 下一波 {n}',
      'def.wave': '第 {wave}/{total} 波',
      'def.mainFoe': '{map} · 主力是<b>{foe}</b>',
      'def.mapLine': '<b>{name}</b> {note}',
      'def.goalLine': '目标 <b>{name}</b> · {note}',
      'def.called': '已召唤',
      'def.callNow': '现在',
      'def.callFrom': '第 {n} 波',
      'def.tier': '{who} {n} 阶',
      'def.heal': '治疗 <b>{n}</b>',
      'def.dps': '每秒 <b>{n}</b>',
      'def.tagSplash': '（范围）',
      'def.tagRing': '（周围）',
      'def.tagSmite': '（+治疗）',
      'def.tagHoly': '（神圣）',
      'def.basicSplash': '普通攻击带范围',
      'def.basicRing': '普通攻击也会砍一圈',
      'def.basicSmite': '普通攻击也能治疗队友',
      'def.basicSingle': '普通攻击是单体',
      'def.holyNote': '神圣属性，对亡灵双倍',
      'def.stats': '生命 <b>{hp}/{maxHp}</b> · 攻击 <b>{dmg}</b>{tag} · 射程 <b>{min}-{max}</b>',
      'def.skillLine': '{skill} {power} · 冷却 <b>{cd} 秒</b>',
      'def.hold': '持续 <b>{n} 秒</b>',
      'def.waitLeft': '<b>还剩 {n} 秒</b>',
      'def.ready': '<b>就绪</b>',
      'def.maxed': '<b>已经满级</b>',
      'def.upgrade': '<b>升级 {cost}</b>',
      'def.upgradeStats': '攻击 {a}→{b} · 生命 {c}→{d} · 射程 +{e} 格',
      'def.upgradeCd': '冷却 {a}→{b} 秒',
      'def.upgradeHold': '持续 {a}→{b} 秒',
      'def.sell': '解雇 +{n}',
      'def.fell': '{who}倒下了',
      'def.bossPassed': '首领冲过去了 · 生命 −{n}',
      'def.foePassed': '有敌人冲过去了',
      'def.waveStart': '第 {n} 波',
      'def.waveBoss': '第 {n} 波 · 首领',
      'def.statDealt': '伤害 {n}',
      'def.statKills': '击杀 {n}',
      'def.statTaken': '承受 {n}',
      'def.statHealed': '治疗 {n}',
      'def.statSkills': '技能 {n}',
      'def.statHired': '雇了 {n} 人',
      'def.cleared': '通过第 {n} 关',
      'def.failed': '被攻破了',
      'def.wonNote': '剩 {lives} 条命 · {time} 秒',
      'def.lostNote': '撑到第 {n} 波',
      'def.goalDone': '达成目标 —— {name}',
      'def.goalMissed': '目标 {name} 留到下次',
      'def.gemsGot': '宝石 +{n}',
      'def.nextStage': '下一关',
      'def.heroTip': '不花金币。站在别的英雄旁边，每人加 {pct}% 伤害与冷却',
      'def.leadTip': '（指挥官加倍）',
      'def.paletteTip': '{who} · 射程 {min}-{max}{basic} · {skill}（{cd} 秒）—— {note} · 同种最多 {most} 人，越叠越贵',
      'def.pickToMove': '点一下要移动的人',
      'def.pickTarget': '点一下要去的位置',
      'def.cannotUse': '现在用不了',
      'def.cannotGo': '去不了那里',
      'def.gems': '宝石 {n}',
      'def.stageCleared': '已通关',
      'def.stageNotYet': '还没过',
      'def.stageLine': '{state} · 目标 {goal}',
      'def.slots': '{used}/{total} 位',
      'def.inTeam': '已编入',
      'def.noEmptyTeam': '不能一个人都不带',
      'def.teamFull': '编队位满了',
      'def.noHeroes': '还没有。从第 {n} 关起，达成目标就会作为卡片出现。',
      'def.taken': '已带上',
      'def.hire': '雇用 {n}',
      'def.heroFull': '英雄位满了',
      'def.allUnlocked': '已经全部解锁。',
      'def.heroPrefix': '英雄 {name}',
      'def.rangeSkill': '射程 {min}-{max} · {skill} —— {note}',
      'def.gemPrice': '宝石 {n}',
      'def.levelRow': '部队等级 <b>{n}</b>',
      'def.levelNote': '你拥有的所有人攻击与生命一起提升',
      'def.levelDelta': '{name} {a}→{b}',
      'def.perkTop': '已满',
      'def.speed': '{n} 倍速',
      'def.cardGems': '{n} 宝石',
      'def.cardGemsNote': '用来提升等级',
      'def.cardItems': '{name} ×2',
      'def.cardItemsNote': '每局各用一次',
      'def.why.over': '这一局结束了',
      'def.why.noSuchUnit': '没有这个人',
      'def.why.notInTeam': '不在编队里',
      'def.why.offBoard': '在棋盘外',
      'def.why.wall': '是墙',
      'def.why.occupiedByUnit': '已经有人了',
      'def.why.foeThere': '敌人正踩在上面',
      'def.why.entry': '那是敌人出生的位置',
      'def.why.heroUsed': '那个英雄已经召唤过了',
      'def.why.noGold': '金币不够',
      'def.help.r1': '在下面<b>选一个人再点空格</b>就把他放上去。按住时会先显示<b>敌人的路线会怎么变</b>。',
      'def.help.r2': '敌人走<b>最快到出口的路线</b>。如果拆人比绕路更快，他们就<b>拆了再过去。</b>',
      'def.help.r3': '所以<b>完全堵死也可以。</b>只是堵路的人会被拆掉，被拆掉就回不来了。',
      'def.help.r4': '<b>攻城兵</b>哪怕只需绕一点也会直接砸穿。只靠堵路的阵型会在这里崩掉。',
      'def.help.r5': '敌人<b>到达出口就扣一条命。</b>命没了这一局就结束。',
      'def.help.r6': '一局有<b>十波</b>，最后一波是<b>首领</b>。',
      'def.help.r7': '放下的人可以<b>用金币升级</b>，<b>解雇能退回一部分。</b>点一个人，按钮上会同时显示当前生命、攻击和<b>升级后会涨多少</b>。',
      'def.help.r8': '<b>提升阶数会让技能更频繁、持续更久。</b>冷却变短、持续（冰冻、流血、晕眩）变长，所以<b>冷却长的冰术士和大魔法师提升最大</b> —— 三阶冰术士的冰几乎不断。',
      'def.help.r9': '一局结束后会按角色显示<b>各自做了多少</b> —— 伤害、击杀、硬抗的伤害、治疗、技能次数。',
      'def.help.r10': '<b>射程因人而异，而且有内圈限制。</b>炮手是 2~5 格，所以<b>打不到贴脸的敌人</b> —— 点一下，射程会显示成一个圆环。',
      'def.help.r11': '<b>敌人踩着的格子和敌人出生的位置不能放人。</b>路口要提前占好。',
      'def.help.r12': '<b>可以把入口围死，但不划算。</b>挤在一格的敌人<b>会全打同一个人</b>，承受的伤害按数量翻倍 —— 十只就是每秒 120，盾兵撑不过 25 秒。拉长路线分散承伤才更持久。',
      'def.help.r13': '<b>英雄</b>每局<b>只能召唤一次</b>，并且单独占一个编队位。他们很贵，第一波放不出来，<b>在第几波放</b>就是判断。从第 4 关起会作为卡片出现。',
      'def.help.r14': '每一关都有<b>目标</b>。<b>没达成也照样算通关</b>，达成了就能<b>选一张卡</b> —— 新角色、宝石或一次性道具。',
      'def.help.r15': '<b>用宝石提升等级。</b>局内的数值不变，而敌人每关都更强，所以想走得远就得升级。',
      'def.help.r16': '<b>输掉的一局也会给宝石。</b>卡住时就攒道具，集中在一局里全用掉。',
      'def.help.r17': '<b>不同敌人吃的攻击不一样。</b>照下面的表来编队。只练一个种类，迟早会卡住。',
      'def.help.r18': '<b>同种每局最多四个</b>，而且<b>越叠越贵。</b>',
      'def.help.r19': '<b>宝石只用来提升一个东西：部队等级。</b>你拥有的所有人攻击与生命一起涨，所以刚解锁的人也能马上顶用 —— 带谁只取决于<b>地形和敌人</b>。',
      'def.help.r20': '在整备里可以<b>直接用宝石解锁角色</b>。就算没达成目标，也不会拿不到需要的种类。',
      'def.help.mapTitle': '地形和敌人决定编队',
      'def.help.mapNote': '开局前，标题栏和整备里会写出<b>这一关的地形</b>和<b>主力敌人</b>。照这两点挑出要带的三个人，就是这个游戏。',
      'def.help.m1': '<b>平原</b> —— 太开阔，没地方拦，只能靠火力硬融。',
      'def.help.m2': '<b>旷野</b> —— 开阔均匀的普通地形。',
      'def.help.m3': '<b>迷宫</b> —— 窄路口很多。<b>用盾兵或剑圣堵住</b>，在后面输出很有效。',
      'def.help.foeTitle': '不同敌人吃的攻击不一样。',
      'def.help.f1': '<b>步兵</b> —— 没有弱点。便宜的<b>弓手</b>最合适。',
      'def.help.f2': '<b>虫群</b> —— 单体输出会浪费一半。要用<b>范围</b>（炮手、大魔法师）。',
      'def.help.f3': '<b>轻步兵</b> —— 太快，会直接跑出射程。<b>用冰术士拖住</b>，再配单体输出。他们跑得分散，范围不好打中。',
      'def.help.f4': '<b>重装兵</b> —— 单体和范围几乎都打不动。只有无视防御的<b>持续伤害</b>（枪兵的流血、冰霜地带）有用。',
      'def.help.f5': '<b>攻城兵</b> —— 吃持续和范围，冰也不太管用，但<b>单体穿刺</b>能直接打穿。它每秒 60 的伤害拆过来，要用<b>盾兵和治疗师</b>拖时间。',
      'def.help.f6': '<b>医疗兵</b> —— 无论哪种伤害都会被削一部分，还会自愈。要用<b>一次打出大伤害的技能</b>打断。',
      'def.help.f7': '<b>骷髅兵与幽魂</b>（亡灵）—— 对活物有效的手段<b>全都只剩一半</b>。但<b>神圣</b>伤害对它们是双倍 —— 攻击带神圣的<b>治疗师</b>和英雄<b>圣骑士</b>在这里就是输出。幽魂很快，冰也不太管用。',
      'def.help.sixTitle': '六位守卫',
      'def.help.sixNote': '每个人都有<b>普通攻击</b>和<b>技能</b>。技能在冷却转好时释放，<b>其余时间用普通攻击单体输出。</b>点一个人能看到剩余冷却；在棋盘上，右上角的点亮起就代表就绪。',
      'def.help.u1': '<b>弓手</b> 1~4 格 —— <b>瞄准射击</b>（5 秒）：带倍率的一发。',
      'def.help.u2': '<b>盾兵</b> 1 格 —— <b>重击</b>（3.5 秒）：<b>晕眩</b> 1.2 秒。攻击弱、血量极高，是挡在前面的位置。',
      'def.help.u3': '<b>炮手</b> 2~5 格 —— <b>炮击</b>（6 秒）：一炮波及周围。<b>打不到贴脸的。</b>',
      'def.help.u4': '<b>冰术士</b> 1~3 格 —— <b>冰霜地带</b>（<b>9 秒</b>）：冻住地面，踩着就一直掉血变慢。等得最久，但能改变局面。',
      'def.help.u5': '<b>枪兵</b> 1~2 格 —— <b>穿刺</b>（4 秒）：贯穿一条线上的所有敌人并留下<b>流血</b>。',
      'def.help.u6': '<b>治疗师</b> 1~3 格 —— <b>治疗</b>（3.5 秒）：回复伤得最重的队友。没人要治时就一起打。攻击带<b>神圣</b>，<b>对亡灵双倍</b>，治疗还会灼烧周围亡灵。',
      'def.help.heroTitle': '四位英雄',
      'def.help.heroNote1': '<b>英雄不花金币。</b>但<b>每波只能召唤一个</b> —— 第 2 波第一个，第 3 波第二个，第 4 波第三个。普通编队拼的是金币，英雄拼的是时间。',
      'def.help.heroNote2': '<b>英雄站在一起会互相变强</b>（共鸣）。周围两格内有别的英雄，<b>伤害与技能冷却每人加 50%</b>，<b>指挥官算两人</b> —— 两人是 ×1.5，三人是 ×2，带上指挥官是 ×2.5。连上时会用虚线连起来。',
      'def.help.h1': '<b>剑圣雷安</b> 1 格 —— 他的位置是<b>贴身的少数敌人</b>。普通攻击和<b>回旋斩</b>（4.5 秒）都以自己为中心，把贴着的全砍。血量极高，所以<b>要摆在要道</b>才划算 —— 放得太远他谁也碰不到。',
      'def.help.h2': '<b>大魔法师莫尔温</b> 2~6 格 —— 她的位置是<b>远处的一大群</b>。普通攻击就是大范围，<b>陨石</b>（9 秒）范围更大。能打到棋盘另一头，但<b>打不到贴脸的</b>，而且血薄如纸，不能放在前面。',
      'def.help.h3': '<b>指挥官贝林</b> 1~5 格 —— 他的位置是<b>指挥周围的人</b>。<b>号令</b>（5 秒）一次拉快周围队友的技能冷却，对英雄加倍。共鸣也算两人，所以<b>夹在两名英雄之间</b>最好。单独时他是英雄里最弱的。',
      'def.help.h4': '<b>圣骑士加隆</b> 1~4 格 —— 他的位置是<b>对付亡灵</b>。攻击带<b>神圣</b>，对骷髅兵和幽魂双倍，<b>治愈之光</b>（6 秒）在回复队友的同时灼烧周围亡灵。对活物则很普通。'
    },
    'zh-TW': {
      'meta.desc': '在路口布防，擋住湧來的敵人',
      'def.camp': '整備',
      'def.palette': '可放置的人',
      'def.items': '一次性道具',
      'def.dismiss': '解雇',
      'def.up': '升級',
      'def.rush': '立刻開始',
      'def.stageLabel': '關卡',
      'def.prevStage': '上一關',
      'def.teamLabel': '編隊',
      'def.heroLabel': '英雄',
      'def.heroLabelNote': '每局各能召喚一次。放在一起會互相加快技能',
      'def.lockedLabel': '未解鎖的人',
      'def.lockedNote': '達成目標會作為卡片出現，也可以直接用寶石解鎖',
      'def.growLabel': '培養',
      'def.growNote': '一個部隊等級提升你擁有的所有人的傷害與生命',
      'def.otherLabel': '其他',
      'def.unit.archer': '弓手',
      'def.unit.shield': '盾兵',
      'def.unit.cannon': '砲手',
      'def.unit.frost': '冰術士',
      'def.unit.spear': '槍兵',
      'def.unit.healer': '治療師',
      'def.unit.blade': '劍聖',
      'def.unit.arch': '大魔法師',
      'def.unit.warden': '指揮官',
      'def.unit.saint': '聖騎士',
      'def.who.blade': '雷安',
      'def.who.arch': '莫爾溫',
      'def.who.warden': '貝林',
      'def.who.saint': '加隆',
      'def.unit.archer.note': '遠遠地一個個點掉',
      'def.unit.shield.note': '擋在前面硬扛，血量很高',
      'def.unit.cannon.note': '打不到貼臉的敵人',
      'def.unit.frost.note': '等得久，但能改變局面',
      'def.unit.spear.note': '',
      'def.unit.healer.note': '沒人要治時就一起打，剋制亡靈',
      'def.unit.blade.note': '擺在要道才划算，只砍貼身的',
      'def.unit.arch.note': '能打到棋盤另一頭，但打不到貼臉的',
      'def.unit.warden.note': '旁邊人越多越強，單獨時最弱',
      'def.unit.saint.note': '邊治邊打，非常剋制亡靈',
      'def.skill.archer': '瞄準射擊',
      'def.skill.shield': '重擊',
      'def.skill.cannon': '砲擊',
      'def.skill.frost': '冰霜地帶',
      'def.skill.spear': '穿刺',
      'def.skill.healer': '治療',
      'def.skill.blade': '迴旋斬',
      'def.skill.arch': '隕石',
      'def.skill.warden': '號令',
      'def.skill.saint': '治癒之光',
      'def.skill.archer.note': '一發打出兩倍以上',
      'def.skill.shield.note': '一擊把敵人打停',
      'def.skill.cannon.note': '一砲波及周圍',
      'def.skill.frost.note': '凍住地面，踩上去會掉血變慢',
      'def.skill.spear.note': '貫穿一條線並留下流血',
      'def.skill.healer.note': '治療傷得最重的隊友，並灼燒周圍亡靈',
      'def.skill.blade.note': '把周圍一圈全砍',
      'def.skill.arch.note': '砸下去點燃',
      'def.skill.warden.note': '一次拉快周圍所有技能，英雄加倍',
      'def.skill.saint.note': '一次治療周圍所有隊友，並灼燒亡靈',
      'def.foe.grunt': '步兵',
      'def.foe.swarm': '蟲群',
      'def.foe.swift': '輕步兵',
      'def.foe.armored': '重裝兵',
      'def.foe.breaker': '攻城兵',
      'def.foe.mender': '醫療兵',
      'def.foe.bone': '骷髏兵',
      'def.foe.wraith': '幽魂',
      'def.foe.boss': '首領',
      'def.map.plain': '平原',
      'def.map.rough': '曠野',
      'def.map.maze': '迷宮',
      'def.map.plain.note': '太開闊，沒地方攔',
      'def.map.rough.note': '開闊均勻的地形',
      'def.map.maze.note': '窄路口很多',
      'def.goal.flawless': '無失誤',
      'def.goal.swift': '速攻',
      'def.goal.thrifty': '節儉',
      'def.goal.purist': '專一',
      'def.goal.saver': '省錢',
      'def.goal.barehand': '空手',
      'def.goal.behead': '斬首',
      'def.goal.flawless.note': '一條命都不丟',
      'def.goal.swift.note': '在 {arg} 秒內完成',
      'def.goal.thrifty.note': '用不超過 {arg} 人守住',
      'def.goal.purist.note': '只用一個種類',
      'def.goal.saver.note': '結束時剩下至少 {arg} 金',
      'def.goal.barehand.note': '誰都不升級',
      'def.goal.behead.note': '在 {arg} 秒內擊殺首領',
      'def.item.bomb': '炸彈',
      'def.item.freeze': '冰凍',
      'def.item.purse': '補給',
      'def.item.mend': '救護',
      'def.item.order': '調令',
      'def.item.bomb.note': '全體敵人扣 35% 生命',
      'def.item.freeze.note': '全場靜止 3 秒',
      'def.item.purse.note': '120 金',
      'def.item.mend.note': '回復一條命',
      'def.item.order.note': '把一個人移到空格',
      'def.perk.lives': '生命',
      'def.perk.slots': '編隊位',
      'def.perk.purse': '初始金幣',
      'def.perk.hero': '英雄位',
      'def.perk.lives.note': '開局多一條命',
      'def.perk.slots.note': '每局多帶一個人',
      'def.perk.purse.note': '初始金幣增加 10%',
      'def.perk.hero.note': '每局多帶一名英雄',
      'def.stage': '第 {n} 關',
      'def.lives': '生命 {n}',
      'def.gold': '金幣 {n}',
      'def.waiting': '待命',
      'def.startsIn': '{n} 秒後開始',
      'def.nextWave': '{wave}/{total} · 下一波 {n}',
      'def.wave': '第 {wave}/{total} 波',
      'def.mainFoe': '{map} · 主力是<b>{foe}</b>',
      'def.mapLine': '<b>{name}</b> {note}',
      'def.goalLine': '目標 <b>{name}</b> · {note}',
      'def.called': '已召喚',
      'def.callNow': '現在',
      'def.callFrom': '第 {n} 波',
      'def.tier': '{who} {n} 階',
      'def.heal': '治療 <b>{n}</b>',
      'def.dps': '每秒 <b>{n}</b>',
      'def.tagSplash': '（範圍）',
      'def.tagRing': '（周圍）',
      'def.tagSmite': '（+治療）',
      'def.tagHoly': '（神聖）',
      'def.basicSplash': '普通攻擊帶範圍',
      'def.basicRing': '普通攻擊也會砍一圈',
      'def.basicSmite': '普通攻擊也能治療隊友',
      'def.basicSingle': '普通攻擊是單體',
      'def.holyNote': '神聖屬性，對亡靈雙倍',
      'def.stats': '生命 <b>{hp}/{maxHp}</b> · 攻擊 <b>{dmg}</b>{tag} · 射程 <b>{min}-{max}</b>',
      'def.skillLine': '{skill} {power} · 冷卻 <b>{cd} 秒</b>',
      'def.hold': '持續 <b>{n} 秒</b>',
      'def.waitLeft': '<b>還剩 {n} 秒</b>',
      'def.ready': '<b>就緒</b>',
      'def.maxed': '<b>已經滿級</b>',
      'def.upgrade': '<b>升級 {cost}</b>',
      'def.upgradeStats': '攻擊 {a}→{b} · 生命 {c}→{d} · 射程 +{e} 格',
      'def.upgradeCd': '冷卻 {a}→{b} 秒',
      'def.upgradeHold': '持續 {a}→{b} 秒',
      'def.sell': '解雇 +{n}',
      'def.fell': '{who}倒下了',
      'def.bossPassed': '首領衝過去了 · 生命 −{n}',
      'def.foePassed': '有敵人衝過去了',
      'def.waveStart': '第 {n} 波',
      'def.waveBoss': '第 {n} 波 · 首領',
      'def.statDealt': '傷害 {n}',
      'def.statKills': '擊殺 {n}',
      'def.statTaken': '承受 {n}',
      'def.statHealed': '治療 {n}',
      'def.statSkills': '技能 {n}',
      'def.statHired': '雇了 {n} 人',
      'def.cleared': '通過第 {n} 關',
      'def.failed': '被攻破了',
      'def.wonNote': '剩 {lives} 條命 · {time} 秒',
      'def.lostNote': '撐到第 {n} 波',
      'def.goalDone': '達成目標 —— {name}',
      'def.goalMissed': '目標 {name} 留到下次',
      'def.gemsGot': '寶石 +{n}',
      'def.nextStage': '下一關',
      'def.heroTip': '不花金幣。站在別的英雄旁邊，每人加 {pct}% 傷害與冷卻',
      'def.leadTip': '（指揮官加倍）',
      'def.paletteTip': '{who} · 射程 {min}-{max}{basic} · {skill}（{cd} 秒）—— {note} · 同種最多 {most} 人，越疊越貴',
      'def.pickToMove': '點一下要移動的人',
      'def.pickTarget': '點一下要去的位置',
      'def.cannotUse': '現在用不了',
      'def.cannotGo': '去不了那裡',
      'def.gems': '寶石 {n}',
      'def.stageCleared': '已通關',
      'def.stageNotYet': '還沒過',
      'def.stageLine': '{state} · 目標 {goal}',
      'def.slots': '{used}/{total} 位',
      'def.inTeam': '已編入',
      'def.noEmptyTeam': '不能一個人都不帶',
      'def.teamFull': '編隊位滿了',
      'def.noHeroes': '還沒有。從第 {n} 關起，達成目標就會作為卡片出現。',
      'def.taken': '已帶上',
      'def.hire': '雇用 {n}',
      'def.heroFull': '英雄位滿了',
      'def.allUnlocked': '已經全部解鎖。',
      'def.heroPrefix': '英雄 {name}',
      'def.rangeSkill': '射程 {min}-{max} · {skill} —— {note}',
      'def.gemPrice': '寶石 {n}',
      'def.levelRow': '部隊等級 <b>{n}</b>',
      'def.levelNote': '你擁有的所有人攻擊與生命一起提升',
      'def.levelDelta': '{name} {a}→{b}',
      'def.perkTop': '已滿',
      'def.speed': '{n} 倍速',
      'def.cardGems': '{n} 寶石',
      'def.cardGemsNote': '用來提升等級',
      'def.cardItems': '{name} ×2',
      'def.cardItemsNote': '每局各用一次',
      'def.why.over': '這一局結束了',
      'def.why.noSuchUnit': '沒有這個人',
      'def.why.notInTeam': '不在編隊裡',
      'def.why.offBoard': '在棋盤外',
      'def.why.wall': '是牆',
      'def.why.occupiedByUnit': '已經有人了',
      'def.why.foeThere': '敵人正踩在上面',
      'def.why.entry': '那是敵人出生的位置',
      'def.why.heroUsed': '那個英雄已經召喚過了',
      'def.why.noGold': '金幣不夠',
      'def.help.r1': '在下面<b>選一個人再點空格</b>就把他放上去。按住時會先顯示<b>敵人的路線會怎麼變</b>。',
      'def.help.r2': '敵人走<b>最快到出口的路線</b>。如果拆人比繞路更快，他們就<b>拆了再過去。</b>',
      'def.help.r3': '所以<b>完全堵死也可以。</b>只是堵路的人會被拆掉，被拆掉就回不來了。',
      'def.help.r4': '<b>攻城兵</b>哪怕只需繞一點也會直接砸穿。只靠堵路的陣型會在這裡崩掉。',
      'def.help.r5': '敵人<b>到達出口就扣一條命。</b>命沒了這一局就結束。',
      'def.help.r6': '一局有<b>十波</b>，最後一波是<b>首領</b>。',
      'def.help.r7': '放下的人可以<b>用金幣升級</b>，<b>解雇能退回一部分。</b>點一個人，按鈕上會同時顯示目前生命、攻擊和<b>升級後會漲多少</b>。',
      'def.help.r8': '<b>提升階數會讓技能更頻繁、持續更久。</b>冷卻變短、持續（冰凍、流血、暈眩）變長，所以<b>冷卻長的冰術士和大魔法師提升最大</b> —— 三階冰術士的冰幾乎不斷。',
      'def.help.r9': '一局結束後會按角色顯示<b>各自做了多少</b> —— 傷害、擊殺、硬扛的傷害、治療、技能次數。',
      'def.help.r10': '<b>射程因人而異，而且有內圈限制。</b>砲手是 2~5 格，所以<b>打不到貼臉的敵人</b> —— 點一下，射程會顯示成一個圓環。',
      'def.help.r11': '<b>敵人踩著的格子和敵人出生的位置不能放人。</b>路口要提前佔好。',
      'def.help.r12': '<b>可以把入口圍死，但不划算。</b>擠在一格的敵人<b>會全打同一個人</b>，承受的傷害按數量翻倍 —— 十隻就是每秒 120，盾兵撐不過 25 秒。拉長路線分散承傷才更持久。',
      'def.help.r13': '<b>英雄</b>每局<b>只能召喚一次</b>，並且單獨佔一個編隊位。他們很貴，第一波放不出來，<b>在第幾波放</b>就是判斷。從第 4 關起會作為卡片出現。',
      'def.help.r14': '每一關都有<b>目標</b>。<b>沒達成也照樣算通關</b>，達成了就能<b>選一張卡</b> —— 新角色、寶石或一次性道具。',
      'def.help.r15': '<b>用寶石提升等級。</b>局內的數值不變，而敵人每關都更強，所以想走得遠就得升級。',
      'def.help.r16': '<b>輸掉的一局也會給寶石。</b>卡住時就攢道具，集中在一局裡全用掉。',
      'def.help.r17': '<b>不同敵人吃的攻擊不一樣。</b>照下面的表來編隊。只練一個種類，遲早會卡住。',
      'def.help.r18': '<b>同種每局最多四個</b>，而且<b>越疊越貴。</b>',
      'def.help.r19': '<b>寶石只用來提升一個東西：部隊等級。</b>你擁有的所有人攻擊與生命一起漲，所以剛解鎖的人也能馬上頂用 —— 帶誰只取決於<b>地形和敵人</b>。',
      'def.help.r20': '在整備裡可以<b>直接用寶石解鎖角色</b>。就算沒達成目標，也不會拿不到需要的種類。',
      'def.help.mapTitle': '地形和敵人決定編隊',
      'def.help.mapNote': '開局前，標題欄和整備裡會寫出<b>這一關的地形</b>和<b>主力敵人</b>。照這兩點挑出要帶的三個人，就是這個遊戲。',
      'def.help.m1': '<b>平原</b> —— 太開闊，沒地方攔，只能靠火力硬融。',
      'def.help.m2': '<b>曠野</b> —— 開闊均勻的普通地形。',
      'def.help.m3': '<b>迷宮</b> —— 窄路口很多。<b>用盾兵或劍聖堵住</b>，在後面輸出很有效。',
      'def.help.foeTitle': '不同敵人吃的攻擊不一樣。',
      'def.help.f1': '<b>步兵</b> —— 沒有弱點。便宜的<b>弓手</b>最合適。',
      'def.help.f2': '<b>蟲群</b> —— 單體輸出會浪費一半。要用<b>範圍</b>（砲手、大魔法師）。',
      'def.help.f3': '<b>輕步兵</b> —— 太快，會直接跑出射程。<b>用冰術士拖住</b>，再配單體輸出。他們跑得分散，範圍不好打中。',
      'def.help.f4': '<b>重裝兵</b> —— 單體和範圍幾乎都打不動。只有無視防禦的<b>持續傷害</b>（槍兵的流血、冰霜地帶）有用。',
      'def.help.f5': '<b>攻城兵</b> —— 吃持續和範圍，冰也不太管用，但<b>單體穿刺</b>能直接打穿。它每秒 60 的傷害拆過來，要用<b>盾兵和治療師</b>拖時間。',
      'def.help.f6': '<b>醫療兵</b> —— 無論哪種傷害都會被削一部分，還會自癒。要用<b>一次打出大傷害的技能</b>打斷。',
      'def.help.f7': '<b>骷髏兵與幽魂</b>（亡靈）—— 對活物有效的手段<b>全都只剩一半</b>。但<b>神聖</b>傷害對牠們是雙倍 —— 攻擊帶神聖的<b>治療師</b>和英雄<b>聖騎士</b>在這裡就是輸出。幽魂很快，冰也不太管用。',
      'def.help.sixTitle': '六位守衛',
      'def.help.sixNote': '每個人都有<b>普通攻擊</b>和<b>技能</b>。技能在冷卻轉好時釋放，<b>其餘時間用普通攻擊單體輸出。</b>點一個人能看到剩餘冷卻；在棋盤上，右上角的點亮起就代表就緒。',
      'def.help.u1': '<b>弓手</b> 1~4 格 —— <b>瞄準射擊</b>（5 秒）：帶倍率的一發。',
      'def.help.u2': '<b>盾兵</b> 1 格 —— <b>重擊</b>（3.5 秒）：<b>暈眩</b> 1.2 秒。攻擊弱、血量極高，是擋在前面的位置。',
      'def.help.u3': '<b>砲手</b> 2~5 格 —— <b>砲擊</b>（6 秒）：一砲波及周圍。<b>打不到貼臉的。</b>',
      'def.help.u4': '<b>冰術士</b> 1~3 格 —— <b>冰霜地帶</b>（<b>9 秒</b>）：凍住地面，踩著就一直掉血變慢。等得最久，但能改變局面。',
      'def.help.u5': '<b>槍兵</b> 1~2 格 —— <b>穿刺</b>（4 秒）：貫穿一條線上的所有敵人並留下<b>流血</b>。',
      'def.help.u6': '<b>治療師</b> 1~3 格 —— <b>治療</b>（3.5 秒）：回復傷得最重的隊友。沒人要治時就一起打。攻擊帶<b>神聖</b>，<b>對亡靈雙倍</b>，治療還會灼燒周圍亡靈。',
      'def.help.heroTitle': '四位英雄',
      'def.help.heroNote1': '<b>英雄不花金幣。</b>但<b>每波只能召喚一個</b> —— 第 2 波第一個，第 3 波第二個，第 4 波第三個。普通編隊拼的是金幣，英雄拼的是時間。',
      'def.help.heroNote2': '<b>英雄站在一起會互相變強</b>（共鳴）。周圍兩格內有別的英雄，<b>傷害與技能冷卻每人加 50%</b>，<b>指揮官算兩人</b> —— 兩人是 ×1.5，三人是 ×2，帶上指揮官是 ×2.5。連上時會用虛線連起來。',
      'def.help.h1': '<b>劍聖雷安</b> 1 格 —— 他的位置是<b>貼身的少數敵人</b>。普通攻擊和<b>迴旋斬</b>（4.5 秒）都以自己為中心，把貼著的全砍。血量極高，所以<b>要擺在要道</b>才划算 —— 放得太遠他誰也碰不到。',
      'def.help.h2': '<b>大魔法師莫爾溫</b> 2~6 格 —— 她的位置是<b>遠處的一大群</b>。普通攻擊就是大範圍，<b>隕石</b>（9 秒）範圍更大。能打到棋盤另一頭，但<b>打不到貼臉的</b>，而且血薄如紙，不能放在前面。',
      'def.help.h3': '<b>指揮官貝林</b> 1~5 格 —— 他的位置是<b>指揮周圍的人</b>。<b>號令</b>（5 秒）一次拉快周圍隊友的技能冷卻，對英雄加倍。共鳴也算兩人，所以<b>夾在兩名英雄之間</b>最好。單獨時他是英雄裡最弱的。',
      'def.help.h4': '<b>聖騎士加隆</b> 1~4 格 —— 他的位置是<b>對付亡靈</b>。攻擊帶<b>神聖</b>，對骷髏兵和幽魂雙倍，<b>治癒之光</b>（6 秒）在回復隊友的同時灼燒周圍亡靈。對活物則很普通。'
    },
    es: {
      'meta.desc': 'Coloca unidades en el paso y frena el avance enemigo',
      'def.camp': 'Campamento',
      'def.palette': 'Unidades para colocar',
      'def.items': 'Objetos de un solo uso',
      'def.dismiss': 'Despedir',
      'def.up': 'Mejorar',
      'def.rush': 'Enviar ya',
      'def.stageLabel': 'Fase',
      'def.prevStage': 'Fase anterior',
      'def.teamLabel': 'Equipo',
      'def.heroLabel': 'Héroes',
      'def.heroLabelNote': 'Uno por partida cada uno. Juntos se adelantan las habilidades entre sí',
      'def.lockedLabel': 'Unidades bloqueadas',
      'def.lockedNote': 'Cumplir un objetivo los ofrece como carta, o los desbloqueas con gemas',
      'def.growLabel': 'Desarrollo',
      'def.growNote': 'Un solo nivel de tropa sube daño y vida de todos los que tienes',
      'def.otherLabel': 'Otros',
      'def.unit.archer': 'Arquera',
      'def.unit.shield': 'Escudero',
      'def.unit.cannon': 'Artillero',
      'def.unit.frost': 'Mago de hielo',
      'def.unit.spear': 'Lancero',
      'def.unit.healer': 'Sanadora',
      'def.unit.blade': 'Maestro de la espada',
      'def.unit.arch': 'Archimago',
      'def.unit.warden': 'Comandante',
      'def.unit.saint': 'Paladín',
      'def.who.blade': 'Lean',
      'def.who.arch': 'Morwyn',
      'def.who.warden': 'Berin',
      'def.who.saint': 'Garon',
      'def.unit.archer.note': 'Los va cazando de lejos',
      'def.unit.shield.note': 'Aguanta al frente. Muchísima vida',
      'def.unit.cannon.note': 'No alcanza lo que tiene pegado',
      'def.unit.frost.note': 'Tarda, pero cambia el tablero',
      'def.unit.spear.note': '',
      'def.unit.healer.note': 'Si no hay a quién curar, pelea. Fuerte contra no-muertos',
      'def.unit.blade.note': 'Rinde en un paso estrecho. Solo corta lo contiguo',
      'def.unit.arch.note': 'Llega de punta a punta. No alcanza lo pegado',
      'def.unit.warden.note': 'Cuanta más compañía, más fuerte. Solo, el más flojo',
      'def.unit.saint.note': 'Cura mientras pelea. Muy fuerte contra no-muertos',
      'def.skill.archer': 'Disparo certero',
      'def.skill.shield': 'Golpetazo',
      'def.skill.cannon': 'Bombardeo',
      'def.skill.frost': 'Campo de hielo',
      'def.skill.spear': 'Empalar',
      'def.skill.healer': 'Curación',
      'def.skill.blade': 'Torbellino',
      'def.skill.arch': 'Meteoro',
      'def.skill.warden': 'Grito de mando',
      'def.skill.saint': 'Luz sanadora',
      'def.skill.archer.note': 'Un disparo de más del doble',
      'def.skill.shield.note': 'Golpea y los detiene',
      'def.skill.cannon.note': 'Un disparo que alcanza el entorno',
      'def.skill.frost.note': 'Congela el suelo: pisarlo daña y ralentiza',
      'def.skill.spear.note': 'Atraviesa una línea y deja sangrado',
      'def.skill.healer.note': 'Cura al aliado más herido y quema a los no-muertos cercanos',
      'def.skill.blade.note': 'Corta todo lo que le rodea',
      'def.skill.arch.note': 'Lo deja caer y arde',
      'def.skill.warden.note': 'Adelanta de golpe las habilidades cercanas; el doble para héroes',
      'def.skill.saint.note': 'Cura de golpe a los aliados cercanos y quema no-muertos',
      'def.foe.grunt': 'Soldado',
      'def.foe.swarm': 'Enjambre',
      'def.foe.swift': 'Hostigador',
      'def.foe.armored': 'Acorazado',
      'def.foe.breaker': 'Rompemuros',
      'def.foe.mender': 'Sanador enemigo',
      'def.foe.bone': 'Esqueleto',
      'def.foe.wraith': 'Espectro',
      'def.foe.boss': 'Jefe',
      'def.map.plain': 'Campo abierto',
      'def.map.rough': 'Terreno irregular',
      'def.map.maze': 'Laberinto',
      'def.map.plain.note': 'Tan abierto que no hay dónde bloquear',
      'def.map.rough.note': 'Terreno abierto y parejo',
      'def.map.maze.note': 'Muchos pasos estrechos',
      'def.goal.flawless': 'Impecable',
      'def.goal.swift': 'Velocidad',
      'def.goal.thrifty': 'Austero',
      'def.goal.purist': 'De un solo tipo',
      'def.goal.saver': 'Ahorrador',
      'def.goal.barehand': 'A mano limpia',
      'def.goal.behead': 'Decapitación',
      'def.goal.flawless.note': 'No pierdas ninguna vida',
      'def.goal.swift.note': 'Termina en {arg} segundos',
      'def.goal.thrifty.note': 'Aguanta con {arg} unidades o menos',
      'def.goal.purist.note': 'Usa un solo tipo',
      'def.goal.saver.note': 'Acaba con {arg} de oro o más',
      'def.goal.barehand.note': 'No mejores a nadie',
      'def.goal.behead.note': 'Mata al jefe en {arg} segundos',
      'def.item.bomb': 'Bomba',
      'def.item.freeze': 'Congelar',
      'def.item.purse': 'Suministro',
      'def.item.mend': 'Auxilio',
      'def.item.order': 'Órdenes',
      'def.item.bomb.note': 'Quita el 35% de vida a todos los enemigos',
      'def.item.freeze.note': 'Detiene a todos 3 segundos',
      'def.item.purse.note': '120 de oro',
      'def.item.mend.note': 'Devuelve una vida',
      'def.item.order.note': 'Mueve una unidad a una casilla vacía',
      'def.perk.lives': 'Vidas',
      'def.perk.slots': 'Huecos de equipo',
      'def.perk.purse': 'Oro inicial',
      'def.perk.hero': 'Huecos de héroe',
      'def.perk.lives.note': 'Una vida más al empezar',
      'def.perk.slots.note': 'Una unidad más por partida',
      'def.perk.purse.note': 'Un 10% más de oro inicial',
      'def.perk.hero.note': 'Un héroe más por partida',
      'def.stage': 'Fase {n}',
      'def.lives': 'Vidas {n}',
      'def.gold': 'Oro {n}',
      'def.waiting': 'En espera',
      'def.startsIn': 'Empieza en {n}',
      'def.nextWave': '{wave}/{total} · siguiente en {n}',
      'def.wave': 'Oleada {wave}/{total}',
      'def.mainFoe': '{map} · sobre todo <b>{foe}</b>',
      'def.mapLine': '<b>{name}</b> — {note}',
      'def.goalLine': 'Objetivo <b>{name}</b> · {note}',
      'def.called': 'Usado',
      'def.callNow': 'Ahora',
      'def.callFrom': 'Oleada {n}',
      'def.tier': '{who} · nivel {n}',
      'def.heal': 'Cura <b>{n}</b>',
      'def.dps': '<b>{n}</b>/s',
      'def.tagSplash': '(área)',
      'def.tagRing': '(alrededor)',
      'def.tagSmite': '(+cura)',
      'def.tagHoly': '(sagrado)',
      'def.basicSplash': 'El ataque básico es en área',
      'def.basicRing': 'El ataque básico también corta alrededor',
      'def.basicSmite': 'El ataque básico también cura aliados',
      'def.basicSingle': 'El ataque básico es a uno',
      'def.holyNote': 'Sagrado: el doble contra no-muertos',
      'def.stats': 'Vida <b>{hp}/{maxHp}</b> · Ataque <b>{dmg}</b>{tag} · alcance <b>{min}-{max}</b>',
      'def.skillLine': '{skill} {power} · recarga <b>{cd}s</b>',
      'def.hold': 'dura <b>{n}s</b>',
      'def.waitLeft': '<b>faltan {n}s</b>',
      'def.ready': '<b>listo</b>',
      'def.maxed': '<b>Al máximo</b>',
      'def.upgrade': '<b>Mejorar {cost}</b>',
      'def.upgradeStats': 'Ataque {a}→{b} · Vida {c}→{d} · alcance +{e}',
      'def.upgradeCd': 'Recarga {a}→{b}s',
      'def.upgradeHold': 'Duración {a}→{b}s',
      'def.sell': 'Despedir +{n}',
      'def.fell': '{who} ha caído',
      'def.bossPassed': 'El jefe ha pasado · vidas −{n}',
      'def.foePassed': 'Un enemigo ha pasado',
      'def.waveStart': 'Oleada {n}',
      'def.waveBoss': 'Oleada {n} · jefe',
      'def.statDealt': 'Daño {n}',
      'def.statKills': 'Bajas {n}',
      'def.statTaken': 'Aguantado {n}',
      'def.statHealed': 'Curado {n}',
      'def.statSkills': 'Habilidades {n}',
      'def.statHired': 'Contratados {n}',
      'def.cleared': 'Fase {n} superada',
      'def.failed': 'Han roto la línea',
      'def.wonNote': '{lives} vidas · {time}s',
      'def.lostNote': 'Aguantaste hasta la oleada {n}',
      'def.goalDone': 'Objetivo cumplido — {name}',
      'def.goalMissed': 'Objetivo {name}: la próxima',
      'def.gemsGot': 'Gemas +{n}',
      'def.nextStage': 'Siguiente fase',
      'def.heroTip': 'No cuesta oro. Junto a otro héroe, +{pct}% de daño y recarga por héroe',
      'def.leadTip': '(el doble con el Comandante)',
      'def.paletteTip': '{who} · alcance {min}-{max}{basic} · {skill} ({cd}s) — {note} · hasta {most} del mismo tipo, y cada uno sube de precio',
      'def.pickToMove': 'Toca la unidad que quieras mover',
      'def.pickTarget': 'Toca adónde debe ir',
      'def.cannotUse': 'Ahora no se puede usar',
      'def.cannotGo': 'Ahí no puede ir',
      'def.gems': 'Gemas {n}',
      'def.stageCleared': 'Superada',
      'def.stageNotYet': 'Todavía no',
      'def.stageLine': '{state} · objetivo {goal}',
      'def.slots': '{used}/{total} huecos',
      'def.inTeam': 'En el equipo',
      'def.noEmptyTeam': 'No puedes ir sin nadie',
      'def.teamFull': 'El equipo está lleno',
      'def.noHeroes': 'Todavía ninguno. Desde la fase {n}, cumplir el objetivo los ofrece como carta.',
      'def.taken': 'Llevado',
      'def.hire': 'Contratar {n}',
      'def.heroFull': 'No quedan huecos de héroe',
      'def.allUnlocked': 'Ya está todo desbloqueado.',
      'def.heroPrefix': 'Héroe {name}',
      'def.rangeSkill': 'Alcance {min}-{max} · {skill} — {note}',
      'def.gemPrice': 'Gemas {n}',
      'def.levelRow': 'Nivel de tropa <b>{n}</b>',
      'def.levelNote': 'Sube ataque y vida de todos los que tienes',
      'def.levelDelta': '{name} {a}→{b}',
      'def.perkTop': 'Máx',
      'def.speed': '{n}× velocidad',
      'def.cardGems': '{n} gemas',
      'def.cardGemsNote': 'Se gasta en subir de nivel',
      'def.cardItems': '{name} ×2',
      'def.cardItemsNote': 'De un solo uso dentro de una partida',
      'def.why.over': 'La partida ha terminado',
      'def.why.noSuchUnit': 'No existe esa unidad',
      'def.why.notInTeam': 'No está en tu equipo',
      'def.why.offBoard': 'Fuera del tablero',
      'def.why.wall': 'Un muro',
      'def.why.occupiedByUnit': 'Ya hay alguien',
      'def.why.foeThere': 'Hay un enemigo encima',
      'def.why.entry': 'Ahí es por donde salen los enemigos',
      'def.why.heroUsed': 'Ese héroe ya ha sido llamado',
      'def.why.noGold': 'No hay oro suficiente',
      'def.help.r1': '<b>Elige una unidad abajo y toca una casilla vacía</b> para colocarla. Mientras mantienes pulsado ves <b>cómo cambia el camino enemigo</b>.',
      'def.help.r2': 'Los enemigos toman <b>la ruta más rápida a la salida</b>. Si romper una unidad es más rápido que rodear, <b>la rompen y pasan.</b>',
      'def.help.r3': 'Por eso <b>puedes bloquear el camino del todo.</b> Las unidades que bloquean se destruyen, y no vuelven.',
      'def.help.r4': 'El <b>rompemuros</b> atraviesa aunque el rodeo sea corto. Un plan basado solo en bloquear se cae aquí.',
      'def.help.r5': '<b>Cada enemigo que llega a la salida cuesta una vida.</b> Sin vidas, la partida acaba.',
      'def.help.r6': 'Una partida son <b>diez oleadas</b> y la última es el <b>jefe</b>.',
      'def.help.r7': 'Una unidad colocada se puede <b>mejorar con oro</b>, y <b>despedirla devuelve parte del coste.</b> Al tocarla, el botón muestra su vida y ataque actuales junto a <b>cuánto sube con la mejora</b>.',
      'def.help.r8': '<b>Subir de nivel hace que las habilidades salgan más a menudo y duren más.</b> Bajan las recargas y suben las duraciones (hielo, sangrado, aturdimiento), así que <b>el mago de hielo y el archimago, de recarga larga, son los que más ganan</b>: un mago de hielo de nivel 3 casi no deja huecos.',
      'def.help.r9': 'Al acabar muestra <b>quién hizo cuánto</b>, unidad por unidad: daño, bajas, daño aguantado, curación y habilidades usadas.',
      'def.help.r10': '<b>El alcance varía por unidad y tiene límite interior.</b> El artillero cubre de 2 a 5 casillas, así que <b>no alcanza lo que tiene pegado</b>: al tocarlo, el alcance se ve como un anillo.',
      'def.help.r11': '<b>No puedes construir donde hay un enemigo ni en la casilla de salida.</b> Ocupa los pasos clave con antelación.',
      'def.help.r12': '<b>Puedes cercar la entrada, pero no compensa.</b> Los enemigos amontonados en una casilla <b>golpean todos a la misma unidad</b>, así que el daño se multiplica por su número: diez son 120 por segundo y un escudero no aguanta 25 segundos. Repartirlos por un camino largo dura mucho más.',
      'def.help.r13': 'Un <b>héroe</b> se llama <b>una vez por partida</b> y ocupa su propio hueco. Son caros, así que no salen en la primera oleada: <b>en qué oleada sacarlos</b> es la decisión. Aparecen como carta a partir de la fase 4.',
      'def.help.r14': 'Cada fase trae un <b>objetivo</b>. <b>Fallarlo sigue contando como superada</b>; cumplirlo te deja <b>elegir una carta</b>: una unidad nueva, gemas o objetos de un solo uso.',
      'def.help.r15': '<b>Las gemas suben tu nivel.</b> Los números dentro de una partida no cambian y los enemigos sí se refuerzan cada fase, así que llegar lejos exige subir.',
      'def.help.r16': '<b>Incluso una partida perdida da gemas.</b> Si te atascas, acumula objetos y gástalos todos en una misma partida.',
      'def.help.r17': '<b>Cada enemigo responde a un tipo de ataque.</b> Arma el equipo con la tabla de abajo. Subir un solo tipo te bloqueará en algún momento.',
      'def.help.r18': '<b>Hasta cuatro del mismo tipo por partida</b>, y <b>cada uno de más sube de precio.</b>',
      'def.help.r19': '<b>Las gemas suben una sola cosa: el nivel de tropa.</b> Sube ataque y vida de todos los que tienes, así que una unidad recién desbloqueada rinde ya — a quién llevar depende solo <b>del mapa y del enemigo</b>.',
      'def.help.r20': 'En el campamento puedes <b>desbloquear una unidad directamente con gemas</b>. Fallar un objetivo nunca te deja sin el tipo que necesitas.',
      'def.help.mapTitle': 'El mapa y el enemigo deciden tu equipo',
      'def.help.mapNote': 'Antes de empezar, la cabecera y el campamento indican <b>qué clase de mapa es</b> y <b>qué enemigo domina</b>. Elegir tus tres a partir de eso es el juego.',
      'def.help.m1': '<b>Campo abierto</b> — sin nada con que bloquear. Hay que fundirlos a fuego.',
      'def.help.m2': '<b>Terreno irregular</b> — abierto y parejo, el mapa estándar.',
      'def.help.m3': '<b>Laberinto</b> — muchos pasos estrechos. <b>Bloquea con escudero o maestro de la espada</b> y pega desde atrás.',
      'def.help.foeTitle': 'Cada enemigo responde a un tipo de ataque.',
      'def.help.f1': '<b>Soldado</b> — sin puntos débiles. La <b>arquera</b>, barata, es lo mejor.',
      'def.help.f2': '<b>Enjambre</b> — disparar de uno en uno desperdicia la mitad. Usa <b>área</b> (artillero, archimago).',
      'def.help.f3': '<b>Hostigador</b> — tan rápido que se sale del alcance. <b>Frénalo con el mago de hielo</b> y acompáñalo de daño a un objetivo. El área falla porque corren dispersos.',
      'def.help.f4': '<b>Acorazado</b> — casi inmune a daño simple y de área. Solo pasa el <b>daño con el tiempo</b>, que ignora la armadura (sangrado del lancero, campo de hielo).',
      'def.help.f5': '<b>Rompemuros</b> — aguanta el daño con el tiempo y el área, y casi ignora el hielo, pero el <b>daño a un objetivo</b> lo atraviesa. Rompe a 60 por segundo: gana tiempo con <b>escudero y sanadora</b>.',
      'def.help.f6': '<b>Sanador enemigo</b> — todo tipo de daño se le reduce en parte y se cura solo. Rómpelo con <b>una habilidad que pegue fuerte de golpe</b>.',
      'def.help.f7': '<b>Esqueleto y espectro</b> (no-muertos) — todo lo que sirve contra los vivos entra <b>a la mitad</b>. En cambio el daño <b>sagrado</b> los quema al doble: la <b>sanadora</b> y el héroe <b>paladín</b>, cuyos ataques son sagrados, son aquí tu daño. El espectro es rápido y además resiste el hielo.',
      'def.help.sixTitle': 'Los seis defensores',
      'def.help.sixNote': 'Todos tienen <b>ataque básico</b> y <b>habilidad</b>. La habilidad sale cuando su recarga vuelve y <b>entre medias pegan a un objetivo con el básico.</b> Toca una unidad para ver la recarga restante; en el tablero, el punto de arriba a la derecha se enciende cuando está lista.',
      'def.help.u1': '<b>Arquera</b>, 1–4 casillas — <b>Disparo certero</b> (5 s): un disparo con multiplicador.',
      'def.help.u2': '<b>Escudero</b>, 1 casilla — <b>Golpetazo</b> (3,5 s): <b>aturde</b> 1,2 segundos. Poco ataque y muchísima vida: es quien aguanta el frente.',
      'def.help.u3': '<b>Artillero</b>, 2–5 casillas — <b>Bombardeo</b> (6 s): alcanza el entorno de una vez. <b>No llega a lo pegado.</b>',
      'def.help.u4': '<b>Mago de hielo</b>, 1–3 casillas — <b>Campo de hielo</b> (<b>9 s</b>): congela el suelo, y pisarlo desgasta y ralentiza sin parar. La espera más larga, pero cambia el tablero.',
      'def.help.u5': '<b>Lancero</b>, 1–2 casillas — <b>Empalar</b> (4 s): atraviesa a todos los enemigos de una línea y los deja <b>sangrando</b>.',
      'def.help.u6': '<b>Sanadora</b>, 1–3 casillas — <b>Curación</b> (3,5 s): recupera al aliado más herido. Si no hay a quién curar, pelea. Sus ataques son <b>sagrados</b>, así que hacen <b>el doble a los no-muertos</b>, y la cura quema a los que tiene cerca.',
      'def.help.heroTitle': 'Los cuatro héroes',
      'def.help.heroNote1': '<b>Los héroes no cuestan oro.</b> A cambio solo puedes llamar <b>uno por oleada</b>: el primero en la 2, el segundo en la 3, el tercero en la 4. Si el equipo normal es una pelea por oro, los héroes lo son por tiempo.',
      'def.help.heroNote2': '<b>Los héroes juntos se refuerzan entre sí</b> (resonancia). Con otro héroe a dos casillas, <b>daño y recarga mejoran un +50% por héroe</b>, y <b>el Comandante cuenta por dos</b>: dos héroes son ×1,5, tres son ×2 y con el Comandante ×2,5. Al enlazarse los une una línea de puntos.',
      'def.help.h1': '<b>Maestro de la espada Lean</b>, 1 casilla — su sitio es <b>pocos enemigos y de cerca</b>. Tanto el básico como <b>Torbellino</b> (4,5 s) cortan todo lo que le toca, con él en el centro. Tiene muchísima vida, así que <b>ponlo en un paso estrecho</b>: lejos no se cruza con nadie.',
      'def.help.h2': '<b>Archimaga Morwyn</b>, 2–6 casillas — su sitio son <b>muchos enemigos a distancia</b>. Ya el básico es de área amplia y <b>Meteoro</b> (9 s) lo es aún más. Llega de punta a punta del tablero, pero <b>no alcanza lo pegado</b> y su vida es de papel: no puede ir delante.',
      'def.help.h3': '<b>Comandante Berin</b>, 1–5 casillas — su sitio es <b>hacer rendir a los de alrededor</b>. <b>Grito de mando</b> (5 s) adelanta de golpe la recarga de los aliados cercanos, y el doble para héroes. Además cuenta por dos en la resonancia, así que <b>encajarlo entre dos héroes</b> es lo mejor. Solo, es el más flojo de los héroes.',
      'def.help.h4': '<b>Paladín Garon</b>, 1–4 casillas — su sitio es <b>contra los no-muertos</b>. Sus ataques son <b>sagrados</b>, así que hacen el doble a esqueletos y espectros, y <b>Luz sanadora</b> (6 s) recupera aliados mientras quema a los no-muertos cercanos. Contra los vivos es del montón.'
    }
  });
})();
