// 이 게임에만 나오는 문구. 힌트 해설은 solver.js가 자료로만 돌려주고 여기서 문장이 된다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '줄마다 검은 칸 두 개. 그 사이 숫자의 합을 맞히는 퍼즐',
      'doppel.gap': ' ',
      'doppel.row': '가로',
      'doppel.col': '세로',
      'doppel.line': '{dir} {index}줄(합 {clue})',
      'doppel.comboHead': '{dir} {index}줄 · 합 {clue}',
      'doppel.noCombos': '가능한 조합이 없습니다',
      'doppel.between': '사이 {n}칸',
      'doppel.emptySet': '없음',
      'doppel.block': '검은 칸',
      'doppel.solved': '다 풀었어요',
      'doppel.resultNote': '{size}×{size} {level} · {time}',
      'doppel.lineDone': '이미 끝난 줄이에요',
      'doppel.needBlocks': '검은 칸 두 개를 먼저 정해야 후보를 적을 수 있어요 (지금 {count}개)',
      'doppel.nothingToFill': '이 줄에 새로 적을 후보가 없어요',
      'doppel.filled': '{dir} {index}줄 {count}칸에 후보를 적었어요',
      'doppel.wrong': '여기 값이 정답과 달라요. 먼저 고쳐야 이어서 풀 수 있어요',
      'doppel.noStep': '더 짚어줄 것을 찾지 못했어요',
      'doppel.levelNote.easy': '배치 좁히기 없이 풀립니다',
      'doppel.levelNote.medium': '배치 좁히기가 필요합니다',
      'doppel.levelNote.hard': '맞물림까지 따지거나, 8×8을 상대합니다',
      'doppel.tech.eliminate': '같은 줄 소거',
      'doppel.tech.maxClue': '최대 단서',
      'doppel.tech.blockPairs': '검은 칸 자리 따지기',
      'doppel.tech.blocksPlaced': '검은 칸 확정',
      'doppel.tech.hiddenSingle': '숨은 단수',
      'doppel.tech.combinations': '조합 따지기',
      'doppel.tech.lineArrangements': '배치 좁히기',
      'doppel.tech.crossLines': '가로세로 맞물림',
      'doppel.why.eliminate': '{line}에 이미 {digit}이 있으니 같은 줄의 다른 칸에는 {digit}이 올 수 없습니다.',
      'doppel.why.noBlockRoom': '이 줄에는 검은 칸을 놓을 자리가 남아 있지 않습니다.',
      'doppel.why.onePair': '{line}에서 단서를 만족시킬 수 있는 검은 칸 자리는 한 쌍뿐입니다.',
      'doppel.why.gaps': '{line}에서 단서를 만들려면 검은 칸 사이가 {gaps}칸이어야 합니다.',
      'doppel.gapJoin': '칸 또는 ',
      'doppel.why.maxClue': '{line}의 단서는 그 줄의 숫자를 모두 더한 값이라, 검은 칸은 양 끝일 수밖에 없습니다.',
      'doppel.why.blocksPlaced': '{line}의 검은 칸 두 개가 이미 정해졌으니 나머지 칸은 모두 숫자입니다.',
      'doppel.why.hiddenSingle': '{line}에서 {digit}이 들어갈 수 있는 칸이 여기뿐입니다.',
      'doppel.why.noCombo': '이 줄은 단서를 만족시킬 수 없습니다.',
      'doppel.why.comboOne': '{line}은 검은 칸 사이 {inside}칸의 합이 {clue}이 되어야 하는데, 그런 조합은 하나뿐입니다.',
      'doppel.why.comboMany': '{line}은 검은 칸 사이 {inside}칸의 합이 {clue}이 되어야 하고, 그런 조합 {found}가지 어디에도 없는 숫자는 사이에 올 수 없습니다.',
      'doppel.why.noArrangement': '이 줄에 가능한 배치가 남아 있지 않습니다.',
      'doppel.why.arrangements': '{line}에서 단서를 만족시키는 배치는 {count}가지(검은 칸 자리로는 {spots}가지) 남았습니다. 그 배치 어디에도 나오지 않는 값은 놓을 수 없습니다.',
      'doppel.why.crossShort': '이 줄들에 그 값을 놓을 자리가 모자랍니다.',
      'doppel.why.cross': '{from} {lines}줄의 {value} 갈 수 있는 자리는 {to} {spots}줄 안에만 있습니다. 그 줄들이 내놓아야 할 {demand}개가 {to} {spots}줄에 남은 자리 수와 정확히 같으니, 그 자리는 전부 {from} {lines}줄 차지입니다.',
      'doppel.removal': '{spots}번 칸에서 {values} 빠집니다',
      'doppel.soThat': '그래서 {list}.',
      'doppel.thenOnly': '그래서 이 칸에 남는 것은 {value}뿐입니다.',
      'doppel.rule1': '모든 <b>가로줄과 세로줄에 검은 칸이 정확히 두 개</b>씩 들어갑니다.',
      'doppel.rule2': '나머지 칸에는 <b id="help-range">1~4</b>를 줄마다 한 번씩 채웁니다.',
      'doppel.rule3': '줄 끝의 숫자는 <b>검은 칸 두 개 사이에 있는 숫자들의 합</b>입니다. 바깥쪽 숫자는 세지 않습니다.',
      'doppel.rule4': '합이 <b>0</b>이면 두 검은 칸이 붙어 있다는 뜻이고, 합이 최대값이면 검은 칸이 양 끝에 있다는 뜻입니다.',
      'doppel.rule5': '<b>이 게임의 모든 판은 주어진 단서만으로 풀립니다.</b> 찍어야만 넘어가는 판은 나오지 않습니다.',
      'doppel.rule6': '<b>난이도는 판의 크기가 아니라 필요한 논리로 정합니다.</b> 쉬움은 한 줄만 봐도 풀리고, 보통은 한 줄의 가능한 배치를 모두 따져야 하며, 어려움은 가로줄과 세로줄을 맞물려 봐야 풀립니다. <b>판 크기는 난이도에 맞는 것 중에서 매번 무작위로 고릅니다.</b> 다만 <b>8×8은 필요한 논리가 보통과 같은데도 어려움에 넣었습니다</b> — 64칸에 줄마다 숫자가 여섯 개라, 따질 것의 양 자체가 벽이기 때문입니다.',
      'doppel.rule7': '칸을 고르면 그 줄의 합을 만들 수 있는 <b>숫자 조합</b>이 아래에 표시됩니다.',
      'doppel.rule8': '<b>연필 표시에는 검은 칸(■)도 넣을 수 있습니다.</b> 아직 숫자인지 검은 칸인지 모르는 자리를 그대로 적어 둘 수 있습니다.',
      'doppel.rule9': '<b>칸을 두 번 톡톡 두드리면</b> 가로·세로에 아직 안 쓰인 숫자가 연필로 적히고, 한 번 더 하면 검은 칸, 한 번 더 하면 빈 칸으로 돌아옵니다. 적을 숫자가 없으면 바로 검은 칸이 됩니다. 숫자를 확정한 칸은 실수로 지워지지 않도록 순환에서 빠집니다.',
      'doppel.rule10': '<b>그 줄의 검은 칸 두 개를 모두 정한 뒤 줄 끝의 단서 숫자를 누르면</b> 아직 비어 있는 칸에 후보가 한꺼번에 적힙니다. 두 번 두드리기를 칸마다 반복하는 것과 같고, <b>이미 연필로 적어 둔 칸은 건드리지 않습니다.</b>',
      'doppel.rule11': '<b>힌트</b>는 한 걸음씩만 알려 줍니다. 칸이 바로 확정되지 않는 단계에서는 "이 줄의 이 단서 때문에 여기서 이 값이 빠진다"까지만 짚고 그 결과를 연필로 적어 둡니다. 여러 번 누르면 근거가 쌓여 칸이 확정됩니다.',
      'doppel.rule12': '키보드: 방향키 이동, <b id="help-keys">1~4</b> 입력, <b>0</b> 또는 <b>B</b> 검은 칸, <b>Shift+숫자</b> 연필, <b>Shift+B</b> 검은 칸 연필, <b>Backspace</b> 지우기, <b>스페이스</b> 연필 전환.'
    },
    en: {
      'meta.desc': 'Two black cells per line — work out the sum of the digits between them',
      'doppel.gap': ' ',
      'doppel.row': 'Row',
      'doppel.col': 'Column',
      'doppel.line': '{dir} {index} (sum {clue})',
      'doppel.comboHead': '{dir} {index} · sum {clue}',
      'doppel.noCombos': 'No possible combination',
      'doppel.between': '{n} between',
      'doppel.emptySet': 'none',
      'doppel.block': 'a black cell',
      'doppel.solved': 'Solved',
      'doppel.resultNote': '{size}×{size} {level} · {time}',
      'doppel.lineDone': 'That line is already finished',
      'doppel.needBlocks': 'Settle both black cells first to pencil in candidates ({count} so far)',
      'doppel.nothingToFill': 'Nothing new to pencil in on this line',
      'doppel.filled': 'Pencilled candidates into {count} cells of {dir} {index}',
      'doppel.wrong': 'This value does not match the solution. Fix it before going on',
      'doppel.noStep': 'Nothing left that logic can point out',
      'doppel.levelNote.easy': 'Solvable without narrowing arrangements',
      'doppel.levelNote.medium': 'Needs narrowing of arrangements',
      'doppel.levelNote.hard': 'Needs cross-line reasoning, or an 8×8',
      'doppel.tech.eliminate': 'Same-line elimination',
      'doppel.tech.maxClue': 'Maximum clue',
      'doppel.tech.blockPairs': 'Black-cell pairs',
      'doppel.tech.blocksPlaced': 'Black cells settled',
      'doppel.tech.hiddenSingle': 'Hidden single',
      'doppel.tech.combinations': 'Combinations',
      'doppel.tech.lineArrangements': 'Narrowing arrangements',
      'doppel.tech.crossLines': 'Cross-line reasoning',
      'doppel.why.eliminate': '{line} already has a {digit}, so no other cell in that line can be {digit}.',
      'doppel.why.noBlockRoom': 'There is no room left for a black cell in this line.',
      'doppel.why.onePair': 'In {line} only one pair of positions for the black cells satisfies the clue.',
      'doppel.why.gaps': 'In {line} the clue only works if the gap between the black cells is {gaps}.',
      'doppel.gapJoin': ' or ',
      'doppel.why.maxClue': 'The clue on {line} is the sum of every digit in that line, so the black cells can only be at the two ends.',
      'doppel.why.blocksPlaced': 'Both black cells of {line} are already settled, so every other cell is a digit.',
      'doppel.why.hiddenSingle': 'This is the only cell in {line} where {digit} can go.',
      'doppel.why.noCombo': 'This line cannot satisfy its clue.',
      'doppel.why.comboOne': 'In {line} the {inside} cells between the black cells must add up to {clue}, and only one combination does that.',
      'doppel.why.comboMany': 'In {line} the {inside} cells between the black cells must add up to {clue}; a digit that appears in none of those {found} combinations cannot go between them.',
      'doppel.why.noArrangement': 'No possible arrangement is left for this line.',
      'doppel.why.arrangements': '{line} has {count} arrangements left that satisfy the clue ({spots} by black-cell positions). A value that appears in none of them cannot be placed.',
      'doppel.why.crossShort': 'These lines do not have enough room for that value.',
      'doppel.why.cross': 'The {value} of {from} {lines} can only go inside {to} {spots}. Those lines need {demand} of them, exactly as many places as {to} {spots} have left, so all of those places belong to {from} {lines}.',
      'doppel.removal': '{values} drop out of cell {spots}',
      'doppel.soThat': 'So {list}.',
      'doppel.thenOnly': 'So the only thing left for this cell is {value}.',
      'doppel.rule1': 'Every <b>row and column holds exactly two black cells</b>.',
      'doppel.rule2': 'The remaining cells take <b id="help-range">1–4</b>, each once per line.',
      'doppel.rule3': 'The number at the end of a line is the <b>sum of the digits between the two black cells</b>. Digits outside them do not count.',
      'doppel.rule4': 'A sum of <b>0</b> means the two black cells are side by side; the maximum sum means they sit at the two ends.',
      'doppel.rule5': '<b>Every board here is solvable from the given clues alone.</b> You will never have to guess.',
      'doppel.rule6': '<b>Difficulty comes from the logic a board needs, not from its size.</b> Easy falls to one line at a time, medium needs every possible arrangement of a line weighed up, and hard needs rows and columns played off each other. <b>The board size is drawn at random from the sizes that fit the difficulty.</b> One exception: <b>8×8 counts as hard even though it needs only medium logic</b> — 64 cells with six digits per line make the sheer volume the wall.',
      'doppel.rule7': 'Select a cell and the <b>digit combinations</b> that can make that line’s sum appear below.',
      'doppel.rule8': '<b>Pencil marks can include the black cell (■)</b>, so you can note a spot you are not yet sure about.',
      'doppel.rule9': '<b>Double-tap a cell</b> to pencil in the digits not yet used in its row and column; tap again for a black cell, once more for empty. With no digit left to write it goes straight to a black cell. Cells with a settled digit stay out of the cycle so they are not wiped by accident.',
      'doppel.rule10': '<b>Once both black cells of a line are settled, tap the clue number at the end of that line</b> and every empty cell gets its candidates at once. It is the same as double-tapping cell by cell, and <b>cells you already pencilled in are left alone</b>.',
      'doppel.rule11': 'A <b>Hint</b> moves one step at a time. When a cell is not settled yet it goes only as far as "this clue on this line rules that value out here" and pencils the result in. Press it a few times and the reasons stack up until the cell is settled.',
      'doppel.rule12': 'Keyboard: arrows to move, <b id="help-keys">1–4</b> to enter, <b>0</b> or <b>B</b> for a black cell, <b>Shift+number</b> for a pencil mark, <b>Shift+B</b> for a pencilled black cell, <b>Backspace</b> to erase, <b>Space</b> to toggle notes.'
    },
    ja: {
      'meta.desc': '各列に黒マス二つ。その間の数字の合計を当てるパズル',
      'doppel.gap': '',
      'doppel.row': '横',
      'doppel.col': '縦',
      'doppel.line': '{dir}{index}列（合計{clue}）',
      'doppel.comboHead': '{dir}{index}列 · 合計{clue}',
      'doppel.noCombos': '可能な組み合わせがありません',
      'doppel.between': '間{n}マス',
      'doppel.emptySet': 'なし',
      'doppel.block': '黒マス',
      'doppel.solved': '解けました',
      'doppel.resultNote': '{size}×{size} {level} · {time}',
      'doppel.lineDone': 'この列はもう終わっています',
      'doppel.needBlocks': '先に黒マス二つを決めないと候補を書けません（いま{count}個）',
      'doppel.nothingToFill': 'この列に新しく書ける候補がありません',
      'doppel.filled': '{dir}{index}列の{count}マスに候補を書きました',
      'doppel.wrong': 'ここの値が答えと違います。直さないと先へ進めません',
      'doppel.noStep': 'これ以上示せるものが見つかりません',
      'doppel.levelNote.easy': '配置の絞り込みなしで解けます',
      'doppel.levelNote.medium': '配置の絞り込みが必要です',
      'doppel.levelNote.hard': '縦横の噛み合わせまで見るか、8×8が相手です',
      'doppel.tech.eliminate': '同じ列の消去',
      'doppel.tech.maxClue': '最大の手がかり',
      'doppel.tech.blockPairs': '黒マスの位置しぼり',
      'doppel.tech.blocksPlaced': '黒マス確定',
      'doppel.tech.hiddenSingle': '隠れシングル',
      'doppel.tech.combinations': '組み合わせしぼり',
      'doppel.tech.lineArrangements': '配置の絞り込み',
      'doppel.tech.crossLines': '縦横の噛み合わせ',
      'doppel.why.eliminate': '{line}にはすでに{digit}があるので、同じ列の他のマスに{digit}は入りません。',
      'doppel.why.noBlockRoom': 'この列には黒マスを置く場所が残っていません。',
      'doppel.why.onePair': '{line}で手がかりを満たせる黒マスの位置は一組だけです。',
      'doppel.why.gaps': '{line}で手がかりを作るには、黒マスの間が{gaps}マスでなければなりません。',
      'doppel.gapJoin': 'マスまたは',
      'doppel.why.maxClue': '{line}の手がかりはその列の数字をすべて足した値なので、黒マスは両端しかありえません。',
      'doppel.why.blocksPlaced': '{line}の黒マス二つがすでに決まったので、残りのマスはすべて数字です。',
      'doppel.why.hiddenSingle': '{line}で{digit}が入れるマスはここだけです。',
      'doppel.why.noCombo': 'この列は手がかりを満たせません。',
      'doppel.why.comboOne': '{line}は黒マスの間{inside}マスの合計が{clue}にならねばならず、そんな組み合わせはひとつだけです。',
      'doppel.why.comboMany': '{line}は黒マスの間{inside}マスの合計が{clue}になる必要があり、その{found}通りのどれにも出ない数字は間に入れません。',
      'doppel.why.noArrangement': 'この列に可能な配置が残っていません。',
      'doppel.why.arrangements': '{line}で手がかりを満たす配置は{count}通り（黒マスの位置では{spots}通り）残っています。そのどれにも出ない値は置けません。',
      'doppel.why.crossShort': 'これらの列にはその値を置く場所が足りません。',
      'doppel.why.cross': '{from}{lines}列の{value}が入れる場所は{to}{spots}列の中だけです。その列が出すべき{demand}個が{to}{spots}列に残る場所の数とちょうど同じなので、その場所はすべて{from}{lines}列のものです。',
      'doppel.removal': '{spots}番のマスから{values}が外れます',
      'doppel.soThat': 'そのため{list}。',
      'doppel.thenOnly': 'そのため、このマスに残るのは{value}だけです。',
      'doppel.rule1': 'すべての<b>行と列に黒マスがちょうど二つ</b>入ります。',
      'doppel.rule2': '残りのマスには<b id="help-range">1〜4</b>を各列に一度ずつ埋めます。',
      'doppel.rule3': '列の端の数字は<b>黒マス二つの間にある数字の合計</b>です。外側の数字は数えません。',
      'doppel.rule4': '合計が<b>0</b>なら黒マス二つが隣り合っているということ、最大値なら両端にあるということです。',
      'doppel.rule5': '<b>この盤はすべて、与えられた手がかりだけで解けます。</b>当てずっぽうが要る盤は出ません。',
      'doppel.rule6': '<b>難易度は盤の大きさではなく必要な論理で決まります。</b>やさしいは一列見れば解け、ふつうは一列の可能な配置を全部数える必要があり、むずかしいは縦横を噛み合わせないと解けません。<b>盤の大きさは難易度に合うものから毎回無作為に選びます。</b>ただし<b>8×8は必要な論理がふつうと同じでもむずかしいに入れました</b> — 64マスに列ごと六つの数字では、数える量そのものが壁になるからです。',
      'doppel.rule7': 'マスを選ぶと、その列の合計を作れる<b>数字の組み合わせ</b>が下に出ます。',
      'doppel.rule8': '<b>メモには黒マス（■）も書けます。</b>数字か黒マスかまだ分からない場所をそのまま残せます。',
      'doppel.rule9': '<b>マスを二回叩く</b>と縦横でまだ使っていない数字がメモで入り、もう一度で黒マス、さらにもう一度で空に戻ります。書く数字がなければすぐ黒マスになります。数字を確定したマスは誤って消えないよう循環から外れます。',
      'doppel.rule10': '<b>その列の黒マス二つを決めたあと列の端の手がかり数字を押すと</b>、空いているマスにまとめて候補が入ります。マスごとに二回叩くのと同じで、<b>すでにメモしたマスには触れません。</b>',
      'doppel.rule11': '<b>ヒント</b>は一歩ずつだけ教えます。マスがすぐ確定しない段階では「この列のこの手がかりのせいでここからこの値が外れる」までを示し、その結果をメモに残します。何度か押すと根拠が積み上がってマスが確定します。',
      'doppel.rule12': 'キーボード：矢印キーで移動、<b id="help-keys">1〜4</b>で入力、<b>0</b>または<b>B</b>で黒マス、<b>Shift+数字</b>でメモ、<b>Shift+B</b>で黒マスのメモ、<b>Backspace</b>で消去、<b>スペース</b>でメモ切替。'
    },
    'zh-CN': {
      'meta.desc': '每行两个黑格，猜出它们之间数字的和',
      'doppel.gap': '',
      'doppel.row': '横',
      'doppel.col': '竖',
      'doppel.line': '{dir} {index} 行（和 {clue}）',
      'doppel.comboHead': '{dir} {index} 行 · 和 {clue}',
      'doppel.noCombos': '没有可行的组合',
      'doppel.between': '中间 {n} 格',
      'doppel.emptySet': '无',
      'doppel.block': '黑格',
      'doppel.solved': '全部解开',
      'doppel.resultNote': '{size}×{size} {level} · {time}',
      'doppel.lineDone': '这一行已经完成了',
      'doppel.needBlocks': '要先定下两个黑格才能写候选（现在 {count} 个）',
      'doppel.nothingToFill': '这一行没有新的候选可写',
      'doppel.filled': '在{dir} {index} 行的 {count} 格写了候选',
      'doppel.wrong': '这里的值和答案不一样，先改过来才能继续',
      'doppel.noStep': '暂时找不到可以指出的东西',
      'doppel.levelNote.easy': '不用缩小排列就能解开',
      'doppel.levelNote.medium': '需要缩小排列',
      'doppel.levelNote.hard': '要看横竖咬合，或者面对 8×8',
      'doppel.tech.eliminate': '同行消去',
      'doppel.tech.maxClue': '最大线索',
      'doppel.tech.blockPairs': '黑格位置推敲',
      'doppel.tech.blocksPlaced': '黑格确定',
      'doppel.tech.hiddenSingle': '隐性唯一',
      'doppel.tech.combinations': '组合推敲',
      'doppel.tech.lineArrangements': '缩小排列',
      'doppel.tech.crossLines': '横竖咬合',
      'doppel.why.eliminate': '{line}里已经有 {digit}，所以同一行别的格不能再是 {digit}。',
      'doppel.why.noBlockRoom': '这一行已经没有地方放黑格了。',
      'doppel.why.onePair': '在{line}里，能满足线索的黑格位置只有一对。',
      'doppel.why.gaps': '在{line}里，要凑出线索，两个黑格之间必须隔 {gaps} 格。',
      'doppel.gapJoin': ' 或 ',
      'doppel.why.maxClue': '{line}的线索正是那一行所有数字之和，所以黑格只能在两端。',
      'doppel.why.blocksPlaced': '{line}的两个黑格已经定下，剩下的格全是数字。',
      'doppel.why.hiddenSingle': '在{line}里，{digit} 只能放在这一格。',
      'doppel.why.noCombo': '这一行无法满足线索。',
      'doppel.why.comboOne': '{line}里两个黑格之间 {inside} 格的和必须是 {clue}，而这样的组合只有一种。',
      'doppel.why.comboMany': '{line}里两个黑格之间 {inside} 格的和必须是 {clue}，那 {found} 种组合里都没有的数字，不能放在中间。',
      'doppel.why.noArrangement': '这一行已经没有可行的排列了。',
      'doppel.why.arrangements': '{line}还剩 {count} 种满足线索的排列（按黑格位置算是 {spots} 种）。这些排列里都没出现的值就放不下。',
      'doppel.why.crossShort': '这几行放不下那个值。',
      'doppel.why.cross': '{from} {lines} 行的 {value} 只能落在{to} {spots} 行里。这些行要出的 {demand} 个，正好等于{to} {spots} 行剩下的位置数，所以那些位置全归{from} {lines} 行。',
      'doppel.removal': '第 {spots} 格去掉 {values}',
      'doppel.soThat': '于是{list}。',
      'doppel.thenOnly': '于是这一格只能是{value}。',
      'doppel.rule1': '每一<b>行、每一列都恰好有两个黑格</b>。',
      'doppel.rule2': '其余格子填 <b id="help-range">1~4</b>，每行每列各用一次。',
      'doppel.rule3': '行末的数字是<b>两个黑格之间数字的和</b>，外侧的数字不算。',
      'doppel.rule4': '和是 <b>0</b> 表示两个黑格挨在一起，和是最大值表示它们在两端。',
      'doppel.rule5': '<b>这里的每一盘都能只凭已给线索解开。</b>不会出现非猜不可的盘面。',
      'doppel.rule6': '<b>难度由需要的推理决定，不看盘面大小。</b>简单看一行就能推，普通要把一行所有可能的排列都算一遍，困难则要横竖咬合才行。<b>盘面大小从符合该难度的尺寸里随机选。</b>只有一个例外：<b>8×8 虽然只需要普通的推理，也算作困难</b> —— 64 格、每行六个数字，光是要算的量就是一道墙。',
      'doppel.rule7': '选中一格，下面会列出能凑出那一行之和的<b>数字组合</b>。',
      'doppel.rule8': '<b>笔记里也可以写黑格（■）</b>，还拿不准是数字还是黑格的位置可以先记下。',
      'doppel.rule9': '<b>连点两下一格</b>，会把横竖还没用过的数字写成笔记；再点一次变黑格，再点一次回到空白。没有数字可写时直接变黑格。已经确定数字的格不参与循环，免得误删。',
      'doppel.rule10': '<b>定下那一行的两个黑格后，点行末的线索数字</b>，所有空格会一次写满候选。效果和逐格连点两下一样，而且<b>已经写过笔记的格不会被动到</b>。',
      'doppel.rule11': '<b>提示</b>一次只走一步。格子还不能确定时，它只说到“因为这一行的这个线索，这里排除这个值”，并把结果写成笔记。多按几次，理由攒够了格子就定下来。',
      'doppel.rule12': '键盘：方向键移动，<b id="help-keys">1~4</b> 输入，<b>0</b> 或 <b>B</b> 黑格，<b>Shift+数字</b> 笔记，<b>Shift+B</b> 黑格笔记，<b>Backspace</b> 擦除，<b>空格</b> 切换笔记。'
    },
    'zh-TW': {
      'meta.desc': '每行兩個黑格，猜出它們之間數字的和',
      'doppel.gap': '',
      'doppel.row': '橫',
      'doppel.col': '直',
      'doppel.line': '{dir} {index} 行（和 {clue}）',
      'doppel.comboHead': '{dir} {index} 行 · 和 {clue}',
      'doppel.noCombos': '沒有可行的組合',
      'doppel.between': '中間 {n} 格',
      'doppel.emptySet': '無',
      'doppel.block': '黑格',
      'doppel.solved': '全部解開',
      'doppel.resultNote': '{size}×{size} {level} · {time}',
      'doppel.lineDone': '這一行已經完成了',
      'doppel.needBlocks': '要先定下兩個黑格才能寫候選（現在 {count} 個）',
      'doppel.nothingToFill': '這一行沒有新的候選可寫',
      'doppel.filled': '在{dir} {index} 行的 {count} 格寫了候選',
      'doppel.wrong': '這裡的值和答案不一樣，先改過來才能繼續',
      'doppel.noStep': '暫時找不到可以指出的東西',
      'doppel.levelNote.easy': '不用縮小排列就能解開',
      'doppel.levelNote.medium': '需要縮小排列',
      'doppel.levelNote.hard': '要看橫直咬合，或者面對 8×8',
      'doppel.tech.eliminate': '同行消去',
      'doppel.tech.maxClue': '最大線索',
      'doppel.tech.blockPairs': '黑格位置推敲',
      'doppel.tech.blocksPlaced': '黑格確定',
      'doppel.tech.hiddenSingle': '隱性唯一',
      'doppel.tech.combinations': '組合推敲',
      'doppel.tech.lineArrangements': '縮小排列',
      'doppel.tech.crossLines': '橫直咬合',
      'doppel.why.eliminate': '{line}裡已經有 {digit}，所以同一行別的格不能再是 {digit}。',
      'doppel.why.noBlockRoom': '這一行已經沒有地方放黑格了。',
      'doppel.why.onePair': '在{line}裡，能滿足線索的黑格位置只有一對。',
      'doppel.why.gaps': '在{line}裡，要湊出線索，兩個黑格之間必須隔 {gaps} 格。',
      'doppel.gapJoin': ' 或 ',
      'doppel.why.maxClue': '{line}的線索正是那一行所有數字之和，所以黑格只能在兩端。',
      'doppel.why.blocksPlaced': '{line}的兩個黑格已經定下，剩下的格全是數字。',
      'doppel.why.hiddenSingle': '在{line}裡，{digit} 只能放在這一格。',
      'doppel.why.noCombo': '這一行無法滿足線索。',
      'doppel.why.comboOne': '{line}裡兩個黑格之間 {inside} 格的和必須是 {clue}，而這樣的組合只有一種。',
      'doppel.why.comboMany': '{line}裡兩個黑格之間 {inside} 格的和必須是 {clue}，那 {found} 種組合裡都沒有的數字，不能放在中間。',
      'doppel.why.noArrangement': '這一行已經沒有可行的排列了。',
      'doppel.why.arrangements': '{line}還剩 {count} 種滿足線索的排列（按黑格位置算是 {spots} 種）。這些排列裡都沒出現的值就放不下。',
      'doppel.why.crossShort': '這幾行放不下那個值。',
      'doppel.why.cross': '{from} {lines} 行的 {value} 只能落在{to} {spots} 行裡。這些行要出的 {demand} 個，正好等於{to} {spots} 行剩下的位置數，所以那些位置全歸{from} {lines} 行。',
      'doppel.removal': '第 {spots} 格去掉 {values}',
      'doppel.soThat': '於是{list}。',
      'doppel.thenOnly': '於是這一格只能是{value}。',
      'doppel.rule1': '每一<b>行、每一列都恰好有兩個黑格</b>。',
      'doppel.rule2': '其餘格子填 <b id="help-range">1~4</b>，每行每列各用一次。',
      'doppel.rule3': '行末的數字是<b>兩個黑格之間數字的和</b>，外側的數字不算。',
      'doppel.rule4': '和是 <b>0</b> 表示兩個黑格挨在一起，和是最大值表示它們在兩端。',
      'doppel.rule5': '<b>這裡的每一盤都能只憑已給線索解開。</b>不會出現非猜不可的盤面。',
      'doppel.rule6': '<b>難度由需要的推理決定，不看盤面大小。</b>簡單看一行就能推，普通要把一行所有可能的排列都算一遍，困難則要橫直咬合才行。<b>盤面大小從符合該難度的尺寸裡隨機選。</b>只有一個例外：<b>8×8 雖然只需要普通的推理，也算作困難</b> —— 64 格、每行六個數字，光是要算的量就是一道牆。',
      'doppel.rule7': '選中一格，下面會列出能湊出那一行之和的<b>數字組合</b>。',
      'doppel.rule8': '<b>筆記裡也可以寫黑格（■）</b>，還拿不準是數字還是黑格的位置可以先記下。',
      'doppel.rule9': '<b>連點兩下一格</b>，會把橫直還沒用過的數字寫成筆記；再點一次變黑格，再點一次回到空白。沒有數字可寫時直接變黑格。已經確定數字的格不參與循環，免得誤刪。',
      'doppel.rule10': '<b>定下那一行的兩個黑格後，點行末的線索數字</b>，所有空格會一次寫滿候選。效果和逐格連點兩下一樣，而且<b>已經寫過筆記的格不會被動到</b>。',
      'doppel.rule11': '<b>提示</b>一次只走一步。格子還不能確定時，它只說到「因為這一行的這個線索，這裡排除這個值」，並把結果寫成筆記。多按幾次，理由攢夠了格子就定下來。',
      'doppel.rule12': '鍵盤：方向鍵移動，<b id="help-keys">1~4</b> 輸入，<b>0</b> 或 <b>B</b> 黑格，<b>Shift+數字</b> 筆記，<b>Shift+B</b> 黑格筆記，<b>Backspace</b> 擦除，<b>空白鍵</b> 切換筆記。'
    },
    es: {
      'meta.desc': 'Dos casillas negras por línea: acierta la suma de los dígitos entre ellas',
      'doppel.gap': ' ',
      'doppel.row': 'Fila',
      'doppel.col': 'Columna',
      'doppel.line': '{dir} {index} (suma {clue})',
      'doppel.comboHead': '{dir} {index} · suma {clue}',
      'doppel.noCombos': 'No hay ninguna combinación posible',
      'doppel.between': '{n} en medio',
      'doppel.emptySet': 'ninguno',
      'doppel.block': 'una casilla negra',
      'doppel.solved': 'Resuelto',
      'doppel.resultNote': '{size}×{size} {level} · {time}',
      'doppel.lineDone': 'Esa línea ya está terminada',
      'doppel.needBlocks': 'Fija primero las dos casillas negras para anotar candidatos (van {count})',
      'doppel.nothingToFill': 'No hay candidatos nuevos que anotar en esta línea',
      'doppel.filled': 'Candidatos anotados en {count} casillas de {dir} {index}',
      'doppel.wrong': 'Este valor no coincide con la solución. Corrígelo para seguir',
      'doppel.noStep': 'No queda nada que la lógica pueda señalar',
      'doppel.levelNote.easy': 'Se resuelve sin acotar disposiciones',
      'doppel.levelNote.medium': 'Hace falta acotar disposiciones',
      'doppel.levelNote.hard': 'Exige cruzar filas y columnas, o un 8×8',
      'doppel.tech.eliminate': 'Eliminación en la línea',
      'doppel.tech.maxClue': 'Pista máxima',
      'doppel.tech.blockPairs': 'Pares de casillas negras',
      'doppel.tech.blocksPlaced': 'Casillas negras fijadas',
      'doppel.tech.hiddenSingle': 'Único oculto',
      'doppel.tech.combinations': 'Combinaciones',
      'doppel.tech.lineArrangements': 'Acotar disposiciones',
      'doppel.tech.crossLines': 'Cruce de líneas',
      'doppel.why.eliminate': '{line} ya tiene un {digit}, así que ninguna otra casilla de esa línea puede ser {digit}.',
      'doppel.why.noBlockRoom': 'Ya no queda sitio para una casilla negra en esta línea.',
      'doppel.why.onePair': 'En {line} solo un par de posiciones para las casillas negras cumple la pista.',
      'doppel.why.gaps': 'En {line} la pista solo sale si entre las casillas negras hay {gaps} casillas.',
      'doppel.gapJoin': ' o ',
      'doppel.why.maxClue': 'La pista de {line} es la suma de todos los dígitos de esa línea, así que las casillas negras solo pueden ir en los extremos.',
      'doppel.why.blocksPlaced': 'Las dos casillas negras de {line} ya están fijadas, así que el resto son dígitos.',
      'doppel.why.hiddenSingle': 'Esta es la única casilla de {line} donde cabe el {digit}.',
      'doppel.why.noCombo': 'Esta línea no puede cumplir su pista.',
      'doppel.why.comboOne': 'En {line} las {inside} casillas entre las negras deben sumar {clue}, y solo una combinación lo consigue.',
      'doppel.why.comboMany': 'En {line} las {inside} casillas entre las negras deben sumar {clue}; un dígito que no aparece en ninguna de esas {found} combinaciones no cabe en medio.',
      'doppel.why.noArrangement': 'No queda ninguna disposición posible para esta línea.',
      'doppel.why.arrangements': 'A {line} le quedan {count} disposiciones que cumplen la pista ({spots} por posiciones de las negras). Un valor que no aparece en ninguna no se puede colocar.',
      'doppel.why.crossShort': 'Estas líneas no tienen sitio suficiente para ese valor.',
      'doppel.why.cross': 'El {value} de {from} {lines} solo cabe dentro de {to} {spots}. Esas líneas necesitan {demand}, exactamente los sitios que le quedan a {to} {spots}, así que todos esos sitios son de {from} {lines}.',
      'doppel.removal': '{values} se descartan en la casilla {spots}',
      'doppel.soThat': 'Así que {list}.',
      'doppel.thenOnly': 'Así que lo único que queda para esta casilla es {value}.',
      'doppel.rule1': 'Cada <b>fila y cada columna llevan exactamente dos casillas negras</b>.',
      'doppel.rule2': 'El resto de casillas se rellenan con <b id="help-range">1–4</b>, una vez por línea.',
      'doppel.rule3': 'El número al final de una línea es la <b>suma de los dígitos que hay entre las dos casillas negras</b>. Los de fuera no cuentan.',
      'doppel.rule4': 'Una suma de <b>0</b> significa que las dos negras están pegadas; la suma máxima, que están en los extremos.',
      'doppel.rule5': '<b>Todos los tableros se resuelven solo con las pistas dadas.</b> Nunca hará falta adivinar.',
      'doppel.rule6': '<b>La dificultad la marca la lógica que exige el tablero, no su tamaño.</b> Fácil sale mirando una línea, media exige pesar todas las disposiciones posibles de una línea, y difícil obliga a cruzar filas con columnas. <b>El tamaño se sortea entre los que encajan con esa dificultad.</b> Con una excepción: <b>el 8×8 cuenta como difícil aunque solo pida lógica media</b>: con 64 casillas y seis dígitos por línea, el muro es el propio volumen.',
      'doppel.rule7': 'Al elegir una casilla aparecen debajo las <b>combinaciones de dígitos</b> que pueden dar la suma de esa línea.',
      'doppel.rule8': '<b>Las notas admiten también la casilla negra (■)</b>, así puedes dejar apuntado un sitio del que aún no estás seguro.',
      'doppel.rule9': '<b>Toca dos veces una casilla</b> y se anotan los dígitos que aún no se han usado en su fila y columna; otra vez, casilla negra; otra más, vacía. Si no queda dígito que escribir, pasa directamente a negra. Las casillas con un dígito fijado salen del ciclo para no borrarlas sin querer.',
      'doppel.rule10': '<b>Cuando ya has fijado las dos negras de una línea, toca el número de la pista al final</b> y todas las casillas vacías reciben sus candidatos de golpe. Es lo mismo que ir tocando dos veces casilla a casilla, y <b>no toca las que ya tenían notas</b>.',
      'doppel.rule11': 'Una <b>Pista</b> avanza de paso en paso. Si la casilla aún no queda fijada, solo llega hasta «por esta pista de esta línea, aquí se descarta este valor» y lo anota. Púlsala varias veces y las razones se acumulan hasta fijar la casilla.',
      'doppel.rule12': 'Teclado: flechas para moverte, <b id="help-keys">1–4</b> para escribir, <b>0</b> o <b>B</b> para casilla negra, <b>Mayús+número</b> para notas, <b>Mayús+B</b> para negra en notas, <b>Retroceso</b> para borrar, <b>Espacio</b> para alternar notas.'
    }
  });
})();
