// 이 게임에만 나오는 문구. 자판과 단어는 한글 그대로다 — 옮길 대상이 아니다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '두 글자 한글 단어를 여섯 번 안에 맞히는 게임',
      'kkodle.subtitle': '두 글자 단어를 여섯 번 안에',
      'kkodle.daily': '오늘의 단어',
      'kkodle.practice': '연습',
      'kkodle.dailyNote': '오늘의 단어 · {date}',
      'kkodle.practiceNote': '연습 · 아무 때나 새 단어',
      'kkodle.enter': '입력',
      'kkodle.tooShort': '두 글자를 채워주세요',
      'kkodle.notAWord': '완성된 두 글자여야 해요',
      'kkodle.won': '{tries}번 만에 맞혔어요',
      'kkodle.lost': '아쉬워요',
      'kkodle.answer': '정답은 "{word}"',
      'kkodle.share': '결과 복사',
      'kkodle.againPractice': '연습 한 판 더',
      'kkodle.copied': '결과를 복사했어요',
      'kkodle.copyFailed': '복사할 수 없어 결과를 아래에 표시했어요',
      'kkodle.played': '판수',
      'kkodle.winRate': '승률',
      'kkodle.streak': '연속',
      'kkodle.bestStreak': '최고 연속',
      'kkodle.rule1': '두 글자 단어를 여섯 번 안에 맞힙니다.',
      'kkodle.rule2': '판정은 글자가 아니라 <b>자모 단위</b>입니다. 한 글자는 초성·중성·종성 세 칸으로 나뉘고, 칸마다 따로 색이 매겨집니다.',
      'kkodle.legendCorrect': '자리까지 맞음',
      'kkodle.legendPresent': '단어에 있지만 자리가 다름',
      'kkodle.legendAbsent': '없음',
      'kkodle.rule4': '받침이 없는 것도 하나의 답입니다. 받침 칸이 초록이면 그 자리에 받침이 없다는 뜻입니다.',
      'kkodle.rule5': '오늘의 단어는 매일 자정(KST)에 바뀌고, 모두에게 같습니다.'
    },
    en: {
      'meta.desc': 'Guess the two-syllable Korean word in six tries',
      'kkodle.subtitle': 'A two-syllable word in six tries',
      'kkodle.daily': 'Word of the day',
      'kkodle.practice': 'Practice',
      'kkodle.dailyNote': 'Word of the day · {date}',
      'kkodle.practiceNote': 'Practice · a new word any time',
      'kkodle.enter': 'Enter',
      'kkodle.tooShort': 'Fill in both syllables',
      'kkodle.notAWord': 'It has to be two complete syllables',
      'kkodle.won': 'Got it in {tries}',
      'kkodle.lost': 'So close',
      'kkodle.answer': 'The word was “{word}”',
      'kkodle.share': 'Copy result',
      'kkodle.againPractice': 'Another practice round',
      'kkodle.copied': 'Result copied',
      'kkodle.copyFailed': 'Could not copy, so the result is shown below',
      'kkodle.played': 'Played',
      'kkodle.winRate': 'Win rate',
      'kkodle.streak': 'Streak',
      'kkodle.bestStreak': 'Best streak',
      'kkodle.rule1': 'Guess the two-syllable word within six tries.',
      'kkodle.rule2': 'Marking works on <b>jamo, not syllables</b>. Each syllable splits into initial, vowel and final, and every slot is coloured on its own.',
      'kkodle.legendCorrect': 'right jamo, right place',
      'kkodle.legendPresent': 'in the word, wrong place',
      'kkodle.legendAbsent': 'not in the word',
      'kkodle.rule4': '“No final consonant” is an answer too. A green final slot means that syllable has none.',
      'kkodle.rule5': 'The word of the day changes at midnight KST and is the same for everyone.'
    },
    ja: {
      'meta.desc': '二文字のハングル単語を六回以内に当てるゲーム',
      'kkodle.subtitle': '二文字の単語を六回以内に',
      'kkodle.daily': '今日の単語',
      'kkodle.practice': '練習',
      'kkodle.dailyNote': '今日の単語 · {date}',
      'kkodle.practiceNote': '練習 · いつでも新しい単語',
      'kkodle.enter': '入力',
      'kkodle.tooShort': '二文字を埋めてください',
      'kkodle.notAWord': '完成した二文字でなければいけません',
      'kkodle.won': '{tries}回で当てました',
      'kkodle.lost': '惜しい',
      'kkodle.answer': '答えは「{word}」',
      'kkodle.share': '結果をコピー',
      'kkodle.againPractice': '練習をもう一局',
      'kkodle.copied': '結果をコピーしました',
      'kkodle.copyFailed': 'コピーできないので結果を下に表示しました',
      'kkodle.played': '回数',
      'kkodle.winRate': '勝率',
      'kkodle.streak': '連勝',
      'kkodle.bestStreak': '最高連勝',
      'kkodle.rule1': '二文字の単語を六回以内に当てます。',
      'kkodle.rule2': '判定は文字ではなく<b>字母単位</b>です。一文字は初声・中声・終声の三枠に分かれ、枠ごとに色が付きます。',
      'kkodle.legendCorrect': '位置まで合っている',
      'kkodle.legendPresent': '単語にはあるが位置が違う',
      'kkodle.legendAbsent': 'ない',
      'kkodle.rule4': '「パッチムなし」も答えのひとつです。終声の枠が緑なら、そこにパッチムがないという意味です。',
      'kkodle.rule5': '今日の単語は毎日0時（KST）に変わり、全員同じです。'
    },
    'zh-CN': {
      'meta.desc': '六次之内猜出两个字的韩语单词',
      'kkodle.subtitle': '六次之内猜出两个字的单词',
      'kkodle.daily': '每日单词',
      'kkodle.practice': '练习',
      'kkodle.dailyNote': '每日单词 · {date}',
      'kkodle.practiceNote': '练习 · 随时换新词',
      'kkodle.enter': '确认',
      'kkodle.tooShort': '请把两个字填满',
      'kkodle.notAWord': '必须是完整的两个字',
      'kkodle.won': '{tries} 次就猜中了',
      'kkodle.lost': '差一点',
      'kkodle.answer': '答案是“{word}”',
      'kkodle.share': '复制结果',
      'kkodle.againPractice': '再练一局',
      'kkodle.copied': '已复制结果',
      'kkodle.copyFailed': '无法复制，结果显示在下面',
      'kkodle.played': '局数',
      'kkodle.winRate': '胜率',
      'kkodle.streak': '连胜',
      'kkodle.bestStreak': '最高连胜',
      'kkodle.rule1': '在六次之内猜出两个字的单词。',
      'kkodle.rule2': '判定按<b>字母</b>而不是按字。一个字拆成初声、中声、终声三格，每格单独上色。',
      'kkodle.legendCorrect': '字母和位置都对',
      'kkodle.legendPresent': '词里有，但位置不对',
      'kkodle.legendAbsent': '词里没有',
      'kkodle.rule4': '“没有收音”也是一种答案。终声格变绿，就表示那个字没有收音。',
      'kkodle.rule5': '每日单词在韩国时间零点更换，所有人都一样。'
    },
    'zh-TW': {
      'meta.desc': '六次之內猜出兩個字的韓語單字',
      'kkodle.subtitle': '六次之內猜出兩個字的單字',
      'kkodle.daily': '每日單字',
      'kkodle.practice': '練習',
      'kkodle.dailyNote': '每日單字 · {date}',
      'kkodle.practiceNote': '練習 · 隨時換新字',
      'kkodle.enter': '確認',
      'kkodle.tooShort': '請把兩個字填滿',
      'kkodle.notAWord': '必須是完整的兩個字',
      'kkodle.won': '{tries} 次就猜中了',
      'kkodle.lost': '差一點',
      'kkodle.answer': '答案是「{word}」',
      'kkodle.share': '複製結果',
      'kkodle.againPractice': '再練一局',
      'kkodle.copied': '已複製結果',
      'kkodle.copyFailed': '無法複製，結果顯示在下面',
      'kkodle.played': '局數',
      'kkodle.winRate': '勝率',
      'kkodle.streak': '連勝',
      'kkodle.bestStreak': '最高連勝',
      'kkodle.rule1': '在六次之內猜出兩個字的單字。',
      'kkodle.rule2': '判定按<b>字母</b>而不是按字。一個字拆成初聲、中聲、終聲三格，每格單獨上色。',
      'kkodle.legendCorrect': '字母和位置都對',
      'kkodle.legendPresent': '字裡有，但位置不對',
      'kkodle.legendAbsent': '沒有',
      'kkodle.rule4': '「沒有收音」也是一種答案。終聲格變綠，就表示那個字沒有收音。',
      'kkodle.rule5': '每日單字在韓國時間零點更換，所有人都一樣。'
    },
    es: {
      'meta.desc': 'Adivina en seis intentos la palabra coreana de dos sílabas',
      'kkodle.subtitle': 'Una palabra de dos sílabas en seis intentos',
      'kkodle.daily': 'Palabra del día',
      'kkodle.practice': 'Práctica',
      'kkodle.dailyNote': 'Palabra del día · {date}',
      'kkodle.practiceNote': 'Práctica · palabra nueva cuando quieras',
      'kkodle.enter': 'Enviar',
      'kkodle.tooShort': 'Completa las dos sílabas',
      'kkodle.notAWord': 'Tienen que ser dos sílabas completas',
      'kkodle.won': 'Acertada en {tries}',
      'kkodle.lost': 'Por poco',
      'kkodle.answer': 'La palabra era «{word}»',
      'kkodle.share': 'Copiar resultado',
      'kkodle.againPractice': 'Otra ronda de práctica',
      'kkodle.copied': 'Resultado copiado',
      'kkodle.copyFailed': 'No se pudo copiar; el resultado aparece abajo',
      'kkodle.played': 'Partidas',
      'kkodle.winRate': 'Aciertos',
      'kkodle.streak': 'Racha',
      'kkodle.bestStreak': 'Mejor racha',
      'kkodle.rule1': 'Adivina la palabra de dos sílabas en seis intentos.',
      'kkodle.rule2': 'La corrección va por <b>jamo, no por sílaba</b>. Cada sílaba se parte en inicial, vocal y final, y cada hueco se colorea por su cuenta.',
      'kkodle.legendCorrect': 'jamo correcto en su sitio',
      'kkodle.legendPresent': 'está en la palabra, en otro sitio',
      'kkodle.legendAbsent': 'no está en la palabra',
      'kkodle.rule4': '«Sin consonante final» también es una respuesta. Un hueco final en verde significa que esa sílaba no lleva ninguna.',
      'kkodle.rule5': 'La palabra del día cambia a medianoche (hora de Corea) y es la misma para todos.'
    }
  });
})();
