// 이 게임에만 나오는 문구. 도구 이름과 게임 이름은 shared/strings.js에 있다.
//
// 힌트 이유(`slitherlink.why.*`)는 풀이기가 돌려주는 `why.code`와 이름이 같다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '숫자만큼 선을 둘러 고리 하나를 만드는 퍼즐',
      'slitherlink.note': '{size}×{size} 판',
      'slitherlink.hintCleared': '어긋난 선 {count}개를 걷어 냈습니다.',
      'slitherlink.why.cellFull': '숫자 <b>{clue}</b>의 선이 다 찼으니 나머지 변은 X입니다.',
      'slitherlink.why.cellNeed': '숫자 <b>{clue}</b>에 맞추려면 남은 변이 모두 선이어야 합니다.',
      'slitherlink.why.vertexFull': '이 점에는 선이 이미 둘 닿았으니 더 이을 수 없습니다.',
      'slitherlink.why.vertexContinue': '선은 점에서 끊기지 않으니 남은 한 길로 이어집니다.',
      'slitherlink.why.vertexDead': '길이 하나뿐인 점으로는 선이 들어올 수 없습니다.',
      'slitherlink.why.loopEarly': '여기를 이으면 고리가 일찍 닫힙니다.',
      'slitherlink.why.loopDone': '고리가 다 닫혔으니 나머지 변은 모두 X입니다.',
      'slitherlink.why.trialLine': '여기를 비워 두면 어딘가에서 모순이 생기니 선입니다.',
      'slitherlink.why.trialCross': '여기에 선을 그으면 어딘가에서 모순이 생기니 X입니다.',
      'slitherlink.rule1': '점과 점 사이에 선을 그어 <b>끊기지 않은 고리 하나</b>를 만듭니다. 고리는 스스로 겹치거나 갈라지지 않습니다.',
      'slitherlink.rule2': '칸의 숫자는 그 칸을 둘러싼 네 변 중 <b>선이 지나가는 변의 수</b>입니다. 숫자 없는 칸은 몇 개든 괜찮습니다.',
      'slitherlink.rule3': '변을 누르면 <b>선 → X → 빈칸</b> 순서로 바뀝니다. X는 "여기는 선이 아니다"라는 메모라 정답 판정에 쓰이지 않습니다.',
      'slitherlink.rule4': '점에서 <b>누른 채 끌면</b> 지나간 변에 선이 이어서 그어집니다. 선 위에서 시작해 끌면 반대로 지워집니다.',
      'slitherlink.rule5': '<b>모든 판은 답이 하나뿐이고 찍지 않고 풀립니다.</b> 쉬움과 보통은 칸과 점만 보고도 풀리고, 어려움은 "여기에 선을 그으면 어떻게 될까"를 따져 봐야 하는 자리가 있습니다.',
      'slitherlink.rule6': '<b>힌트</b>는 어긋난 선을 걷어 내고, 지금 알아낼 수 있는 변 하나를 채우며 그 까닭을 알려 줍니다. 힌트를 쓴 판은 최고 기록으로 남기지 않습니다.'
    },
    en: {
      'meta.desc': 'Draw a single loop that matches every number',
      'slitherlink.note': '{size}×{size} board',
      'slitherlink.hintCleared': 'Removed {count} wrong line(s).',
      'slitherlink.why.cellFull': 'The <b>{clue}</b> already has all its lines, so its other sides are X.',
      'slitherlink.why.cellNeed': 'The <b>{clue}</b> needs every side that is left.',
      'slitherlink.why.vertexFull': 'Two lines already meet at this dot, so nothing else can join it.',
      'slitherlink.why.vertexContinue': 'A line cannot stop at a dot, so it carries on the only way left.',
      'slitherlink.why.vertexDead': 'This dot has only one way in, so no line can use it.',
      'slitherlink.why.loopEarly': 'A line here would close the loop too early.',
      'slitherlink.why.loopDone': 'The loop is closed, so every other side is X.',
      'slitherlink.why.trialLine': 'Leaving this empty leads to a contradiction, so it is a line.',
      'slitherlink.why.trialCross': 'A line here leads to a contradiction, so it is X.',
      'slitherlink.rule1': 'Draw lines between the dots to make <b>one unbroken loop</b>. The loop never crosses or branches.',
      'slitherlink.rule2': 'A number tells <b>how many of the four sides around it</b> the loop uses. Cells without a number can have any count.',
      'slitherlink.rule3': 'Tap a side to cycle <b>line → X → empty</b>. An X is just your note that no line goes there — it is not checked.',
      'slitherlink.rule4': '<b>Drag</b> from a dot to draw along several sides at once. Start the drag on a line to erase instead.',
      'slitherlink.rule5': '<b>Every board has exactly one answer and needs no guessing.</b> Easy and Medium fall to the numbers and dots alone; Hard has spots where you must ask “what if a line went here?”',
      'slitherlink.rule6': 'A <b>Hint</b> removes wrong lines, fills in one side you can work out right now, and tells you why. Boards solved with hints are not recorded.'
    },
    ja: {
      'meta.desc': '数字に合わせて線を引き、ひとつながりの輪を作るパズル',
      'slitherlink.note': '{size}×{size}の盤',
      'slitherlink.hintCleared': '間違った線を{count}本消しました。',
      'slitherlink.why.cellFull': '<b>{clue}</b>の線はもう足りているので、残りの辺は×です。',
      'slitherlink.why.cellNeed': '<b>{clue}</b>を満たすには、残りの辺がすべて線です。',
      'slitherlink.why.vertexFull': 'この点にはもう線が2本来ているので、これ以上つなげません。',
      'slitherlink.why.vertexContinue': '線は点で途切れないので、残った一方へ続きます。',
      'slitherlink.why.vertexDead': '出入り口がひとつしかない点には線が来られません。',
      'slitherlink.why.loopEarly': 'ここをつなぐと輪が早く閉じてしまいます。',
      'slitherlink.why.loopDone': '輪が閉じたので、残りの辺はすべて×です。',
      'slitherlink.why.trialLine': 'ここを空けるとどこかで矛盾するので、線です。',
      'slitherlink.why.trialCross': 'ここに線を引くとどこかで矛盾するので、×です。',
      'slitherlink.rule1': '点と点の間に線を引いて、<b>途切れないひとつの輪</b>を作ります。輪は交差も枝分かれもしません。',
      'slitherlink.rule2': 'マスの数字は、そのマスの4辺のうち<b>線が通る辺の数</b>です。数字のないマスはいくつでもかまいません。',
      'slitherlink.rule3': '辺を押すと<b>線 → × → 空白</b>の順に変わります。×は「ここは線ではない」というメモで、判定には使いません。',
      'slitherlink.rule4': '点から<b>押したままなぞる</b>と、通った辺に続けて線が引けます。線の上から始めると消していきます。',
      'slitherlink.rule5': '<b>どの盤も答えはひとつで、当て推量なしで解けます。</b>やさしいとふつうは数字と点だけで解け、むずかしいには「ここに線を引いたらどうなるか」を考える場所があります。',
      'slitherlink.rule6': '<b>ヒント</b>は間違った線を消し、今わかる辺をひとつ埋めて理由を教えます。ヒントを使った盤は記録に残りません。'
    },
    'zh-CN': {
      'meta.desc': '按数字画线，连成一个完整回路的谜题',
      'slitherlink.note': '{size}×{size} 盘',
      'slitherlink.hintCleared': '清除了 {count} 条错误的线。',
      'slitherlink.why.cellFull': '<b>{clue}</b> 周围的线已经够了，其余的边都是 ×。',
      'slitherlink.why.cellNeed': '要满足 <b>{clue}</b>，剩下的边都必须是线。',
      'slitherlink.why.vertexFull': '这个点已经连了两条线，不能再连。',
      'slitherlink.why.vertexContinue': '线不能停在点上，只能沿剩下的唯一方向继续。',
      'slitherlink.why.vertexDead': '只剩一个出入口的点，线进不来。',
      'slitherlink.why.loopEarly': '连上这里，回路会提前闭合。',
      'slitherlink.why.loopDone': '回路已经闭合，其余的边都是 ×。',
      'slitherlink.why.trialLine': '这里空着会在某处产生矛盾，所以是线。',
      'slitherlink.why.trialCross': '这里画线会在某处产生矛盾，所以是 ×。',
      'slitherlink.rule1': '在点与点之间画线，连成<b>一个不间断的回路</b>。回路不能交叉，也不能分叉。',
      'slitherlink.rule2': '格子里的数字表示它四条边中<b>有几条是线</b>。没有数字的格子不限。',
      'slitherlink.rule3': '点击边会按<b>线 → × → 空白</b>循环。× 只是“这里不是线”的标记，不参与判定。',
      'slitherlink.rule4': '从点上<b>按住拖动</b>，经过的边会连续画线。从线上开始拖动则会擦除。',
      'slitherlink.rule5': '<b>每一盘都只有一个答案，不用猜。</b>简单和普通只看数字和点就能解；困难里有需要想“如果这里画线会怎样”的地方。',
      'slitherlink.rule6': '<b>提示</b>会清除错误的线，补上一条现在能推出的边，并说明理由。用过提示的盘不计入最佳纪录。'
    },
    'zh-TW': {
      'meta.desc': '依數字畫線，連成一個完整迴路的謎題',
      'slitherlink.note': '{size}×{size} 盤',
      'slitherlink.hintCleared': '清除了 {count} 條錯誤的線。',
      'slitherlink.why.cellFull': '<b>{clue}</b> 周圍的線已經夠了，其餘的邊都是 ×。',
      'slitherlink.why.cellNeed': '要滿足 <b>{clue}</b>，剩下的邊都必須是線。',
      'slitherlink.why.vertexFull': '這個點已經連了兩條線，不能再連。',
      'slitherlink.why.vertexContinue': '線不能停在點上，只能沿剩下的唯一方向繼續。',
      'slitherlink.why.vertexDead': '只剩一個出入口的點，線進不來。',
      'slitherlink.why.loopEarly': '連上這裡，迴路會提前閉合。',
      'slitherlink.why.loopDone': '迴路已經閉合，其餘的邊都是 ×。',
      'slitherlink.why.trialLine': '這裡空著會在某處產生矛盾，所以是線。',
      'slitherlink.why.trialCross': '這裡畫線會在某處產生矛盾，所以是 ×。',
      'slitherlink.rule1': '在點與點之間畫線，連成<b>一個不間斷的迴路</b>。迴路不能交叉，也不能分岔。',
      'slitherlink.rule2': '格子裡的數字表示它四條邊中<b>有幾條是線</b>。沒有數字的格子不限。',
      'slitherlink.rule3': '點擊邊會依<b>線 → × → 空白</b>循環。× 只是「這裡不是線」的標記，不參與判定。',
      'slitherlink.rule4': '從點上<b>按住拖曳</b>，經過的邊會連續畫線。從線上開始拖曳則會擦除。',
      'slitherlink.rule5': '<b>每一盤都只有一個答案，不用猜。</b>簡單和普通只看數字和點就能解；困難裡有需要想「如果這裡畫線會怎樣」的地方。',
      'slitherlink.rule6': '<b>提示</b>會清除錯誤的線，補上一條現在能推出的邊，並說明理由。用過提示的盤不計入最佳紀錄。'
    },
    es: {
      'meta.desc': 'Traza un único circuito que respete todos los números',
      'slitherlink.note': 'Tablero {size}×{size}',
      'slitherlink.hintCleared': 'Se quitaron {count} línea(s) incorrecta(s).',
      'slitherlink.why.cellFull': 'El <b>{clue}</b> ya tiene todas sus líneas, así que sus otros lados son X.',
      'slitherlink.why.cellNeed': 'El <b>{clue}</b> necesita todos los lados que le quedan.',
      'slitherlink.why.vertexFull': 'En este punto ya se juntan dos líneas; no cabe otra.',
      'slitherlink.why.vertexContinue': 'Una línea no puede terminar en un punto, así que sigue por el único camino libre.',
      'slitherlink.why.vertexDead': 'A este punto solo se llega por un lado, así que ninguna línea puede pasar.',
      'slitherlink.why.loopEarly': 'Una línea aquí cerraría el circuito antes de tiempo.',
      'slitherlink.why.loopDone': 'El circuito está cerrado, así que todos los demás lados son X.',
      'slitherlink.why.trialLine': 'Dejar esto vacío lleva a una contradicción, así que es línea.',
      'slitherlink.why.trialCross': 'Una línea aquí lleva a una contradicción, así que es X.',
      'slitherlink.rule1': 'Traza líneas entre los puntos para formar <b>un solo circuito cerrado</b>. El circuito nunca se cruza ni se ramifica.',
      'slitherlink.rule2': 'Cada número indica <b>cuántos de sus cuatro lados</b> usa el circuito. Las casillas sin número pueden tener cualquiera.',
      'slitherlink.rule3': 'Toca un lado para alternar <b>línea → X → vacío</b>. La X es solo una nota tuya de que ahí no hay línea; no se comprueba.',
      'slitherlink.rule4': '<b>Arrastra</b> desde un punto para trazar varios lados seguidos. Si empiezas sobre una línea, borras.',
      'slitherlink.rule5': '<b>Cada tablero tiene una sola solución y no hace falta adivinar.</b> Fácil y Normal salen solo con números y puntos; Difícil tiene sitios donde hay que pensar «¿y si aquí hubiera una línea?».',
      'slitherlink.rule6': 'La <b>pista</b> quita las líneas incorrectas, completa un lado que ya puedes deducir y te explica por qué. Los tableros resueltos con pistas no cuentan para el récord.'
    }
  });
})();
