// 이 게임에만 나오는 문구. 기록 안내와 도구 이름은 shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '섬에 적힌 숫자만큼 다리를 놓아 모든 섬을 하나로 잇는 퍼즐',
      'hashi.board': '섬과 다리',
      'hashi.howTo': '점선을 누르거나, 섬을 누르고 이어질 섬을 누르세요.',
      'hashi.done': '다 이었습니다',
      'hashi.noRoom': '여기에는 더 놓을 수 없습니다',
      'hashi.hintCleared': '어긋난 다리를 치웠습니다',
      'hashi.hintPlaced': '다리 하나를 놓았습니다',
      'hashi.rule1': '섬에 적힌 <b>숫자만큼</b> 그 섬에 다리가 닿아야 합니다.',
      'hashi.rule2': '다리는 <b>가로·세로</b>로만 놓고, 이웃한 두 섬을 곧게 잇습니다. 사이에 다른 섬이 있으면 건너뛸 수 없습니다.',
      'hashi.rule3': '같은 두 섬 사이에는 <b>최대 두 개</b>까지 놓습니다.',
      'hashi.rule4': '다리끼리 <b>교차할 수 없습니다.</b>',
      'hashi.rule5': '다 놓았을 때 <b>모든 섬이 하나로 이어져</b> 있어야 완성입니다. 숫자를 다 맞춰도 섬이 두 덩어리로 갈리면 완성이 아닙니다.',
      'hashi.rule6': '<b>점선이 다리를 놓을 수 있는 자리</b>입니다. 그 위를 누를 때마다 <b>없음 → 하나 → 둘 → 없음</b>으로 돕니다.',
      'hashi.rule7': '<b>섬을 누르고 이어질 섬을 눌러도</b> 같은 자리가 돕니다. 고른 섬에서 이을 수 있는 섬은 테두리로 알려 줍니다 — 다리가 교차하는 자리처럼 누르기 애매한 곳에 쓰세요.',
      'hashi.rule8': '<b>이 게임의 모든 판은 답이 하나뿐이고, 찍지 않고 논리로만 풀립니다.</b>',
      'hashi.rule9': '<b>힌트</b>는 어긋난 다리를 치우거나 다음 한 자리를 놓아 줍니다. 힌트를 쓴 판은 최고 기록에 넣지 않습니다.'
    },
    en: {
      'meta.desc': 'Draw bridges to match the number on each island and join them all into one',
      'hashi.board': 'Islands and bridges',
      'hashi.howTo': 'Tap a dashed line, or tap an island and then the one to link it to.',
      'hashi.done': 'All connected',
      'hashi.noRoom': 'No room for another bridge here',
      'hashi.hintCleared': 'Removed a wrong bridge',
      'hashi.hintPlaced': 'Placed one bridge',
      'hashi.rule1': 'Each island must touch <b>exactly as many bridges as its number</b>.',
      'hashi.rule2': 'Bridges run <b>horizontally or vertically</b> only, straight between two neighboring islands. They cannot jump over an island in between.',
      'hashi.rule3': 'At most <b>two bridges</b> between the same pair of islands.',
      'hashi.rule4': 'Bridges <b>may not cross</b> each other.',
      'hashi.rule5': 'When you are done, <b>every island must be connected into one group</b>. Matching all the numbers is not enough if the islands split into two clusters.',
      'hashi.rule6': 'A <b>dashed line marks a place a bridge can go</b>. Tapping it cycles <b>none → one → two → none</b>.',
      'hashi.rule7': '<b>Tapping an island and then another</b> cycles the same spot. Islands you can reach from the selected one are outlined — handy where bridges cross and tapping is fiddly.',
      'hashi.rule8': '<b>Every board here has exactly one solution and is solvable by logic alone.</b>',
      'hashi.rule9': 'A <b>Hint</b> clears a wrong bridge or places the next one. Boards solved with hints are not recorded.'
    },
    ja: {
      'meta.desc': '島に書かれた数だけ橋をかけ、すべての島をひとつにつなぐパズル',
      'hashi.board': '島と橋',
      'hashi.howTo': '点線を押すか、島を押してからつなぐ島を押してください。',
      'hashi.done': '全部つながりました',
      'hashi.noRoom': 'ここにはこれ以上かけられません',
      'hashi.hintCleared': 'ずれた橋を片づけました',
      'hashi.hintPlaced': '橋をひとつかけました',
      'hashi.rule1': '島に書かれた<b>数だけ</b>その島に橋が接します。',
      'hashi.rule2': '橋は<b>縦横</b>にだけかけ、隣り合う二つの島をまっすぐつなぎます。間に別の島があると飛び越えられません。',
      'hashi.rule3': '同じ二島の間は<b>最大二本</b>までです。',
      'hashi.rule4': '橋同士は<b>交差できません。</b>',
      'hashi.rule5': 'かけ終えたとき<b>すべての島がひとつにつながって</b>いなければ完成ではありません。数字が合っていても島が二つの塊に分かれていれば未完成です。',
      'hashi.rule6': '<b>点線が橋をかけられる場所</b>です。押すたびに<b>なし → 一本 → 二本 → なし</b>と変わります。',
      'hashi.rule7': '<b>島を押してからつなぐ島を押しても</b>同じ場所が変わります。選んだ島からつなげる島は縁取りで示します — 橋が交差して押しにくい所でどうぞ。',
      'hashi.rule8': '<b>この盤はすべて答えがひとつだけで、当てずっぽう抜きに論理だけで解けます。</b>',
      'hashi.rule9': '<b>ヒント</b>はずれた橋を片づけるか、次の一本をかけます。ヒントを使った盤はベスト記録に入れません。'
    },
    'zh-CN': {
      'meta.desc': '按岛上的数字架桥，把所有岛连成一片',
      'hashi.board': '岛与桥',
      'hashi.howTo': '点虚线，或先点一个岛再点要连的岛。',
      'hashi.done': '全部连通',
      'hashi.noRoom': '这里放不下更多的桥',
      'hashi.hintCleared': '清掉了一座架错的桥',
      'hashi.hintPlaced': '架好了一座桥',
      'hashi.rule1': '每座岛接到的桥数，要<b>等于岛上的数字</b>。',
      'hashi.rule2': '桥只能<b>横竖</b>架，笔直连接相邻的两座岛。中间隔着别的岛就不能跨过去。',
      'hashi.rule3': '同一对岛之间<b>最多两座</b>桥。',
      'hashi.rule4': '桥与桥<b>不能交叉。</b>',
      'hashi.rule5': '架完后<b>所有岛必须连成一片</b>才算完成。数字都对，但岛分成两块，也不算完成。',
      'hashi.rule6': '<b>虚线就是可以架桥的位置</b>。每点一次按<b>无 → 一座 → 两座 → 无</b>循环。',
      'hashi.rule7': '<b>先点一个岛再点另一个</b>，同样会切换那个位置。从选中的岛能连到的岛会有描边 —— 桥交叉、不好点的地方可以这样用。',
      'hashi.rule8': '<b>这里的每一盘都只有一个答案，而且只靠推理就能解开。</b>',
      'hashi.rule9': '<b>提示</b>会清掉架错的桥，或架好下一座。用过提示的盘面不计入最好成绩。'
    },
    'zh-TW': {
      'meta.desc': '按島上的數字架橋，把所有島連成一片',
      'hashi.board': '島與橋',
      'hashi.howTo': '點虛線，或先點一個島再點要連的島。',
      'hashi.done': '全部連通',
      'hashi.noRoom': '這裡放不下更多的橋',
      'hashi.hintCleared': '清掉了一座架錯的橋',
      'hashi.hintPlaced': '架好了一座橋',
      'hashi.rule1': '每座島接到的橋數，要<b>等於島上的數字</b>。',
      'hashi.rule2': '橋只能<b>橫豎</b>架，筆直連接相鄰的兩座島。中間隔著別的島就不能跨過去。',
      'hashi.rule3': '同一對島之間<b>最多兩座</b>橋。',
      'hashi.rule4': '橋與橋<b>不能交叉。</b>',
      'hashi.rule5': '架完後<b>所有島必須連成一片</b>才算完成。數字都對，但島分成兩塊，也不算完成。',
      'hashi.rule6': '<b>虛線就是可以架橋的位置</b>。每點一次按<b>無 → 一座 → 兩座 → 無</b>循環。',
      'hashi.rule7': '<b>先點一個島再點另一個</b>，同樣會切換那個位置。從選中的島能連到的島會有描邊 —— 橋交叉、不好點的地方可以這樣用。',
      'hashi.rule8': '<b>這裡的每一盤都只有一個答案，而且只靠推理就能解開。</b>',
      'hashi.rule9': '<b>提示</b>會清掉架錯的橋，或架好下一座。用過提示的盤面不計入最佳成績。'
    },
    es: {
      'meta.desc': 'Tiende puentes según el número de cada isla y únelas todas en una sola red',
      'hashi.board': 'Islas y puentes',
      'hashi.howTo': 'Toca una línea de puntos, o toca una isla y luego la isla a la que unirla.',
      'hashi.done': 'Todo conectado',
      'hashi.noRoom': 'Aquí no cabe otro puente',
      'hashi.hintCleared': 'Se retiró un puente mal puesto',
      'hashi.hintPlaced': 'Se tendió un puente',
      'hashi.rule1': 'Cada isla debe tocar <b>tantos puentes como indica su número</b>.',
      'hashi.rule2': 'Los puentes van solo <b>en horizontal o vertical</b>, rectos entre dos islas vecinas. No pueden saltarse una isla intermedia.',
      'hashi.rule3': 'Como mucho <b>dos puentes</b> entre el mismo par de islas.',
      'hashi.rule4': 'Los puentes <b>no pueden cruzarse</b>.',
      'hashi.rule5': 'Al terminar, <b>todas las islas deben quedar conectadas en una sola red</b>. Cuadrar los números no basta si las islas quedan en dos grupos.',
      'hashi.rule6': 'La <b>línea de puntos marca dónde cabe un puente</b>. Al tocarla alterna <b>ninguno → uno → dos → ninguno</b>.',
      'hashi.rule7': '<b>Tocar una isla y luego otra</b> alterna ese mismo sitio. Las islas alcanzables desde la seleccionada quedan resaltadas: útil donde los puentes se cruzan y cuesta acertar.',
      'hashi.rule8': '<b>Todos los tableros tienen una única solución y salen solo con lógica.</b>',
      'hashi.rule9': 'Una <b>Pista</b> retira un puente mal puesto o coloca el siguiente. Los tableros con pistas no cuentan para el récord.'
    }
  });
})();
