// 이 게임에만 나오는 문구. 도구 이름과 게임 이름은 shared/strings.js에 있다.
//
// 힌트 이유(`nurikabe.why.*`)는 풀이기가 돌려주는 `why.code`와 이름이 같다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '숫자만큼 섬을 남기고 나머지를 바다로 칠하는 퍼즐',
      'nurikabe.note': '{size}×{size} 판',
      'nurikabe.hintCleared': '어긋난 칸 {count}개를 걷어 냈습니다.',
      'nurikabe.why.islandDone': '숫자 <b>{clue}</b>의 섬이 다 찼으니 둘레는 바다입니다.',
      'nurikabe.why.twoIslands': '이 칸이 섬이면 숫자 있는 섬 둘이 붙어 버리니 바다입니다.',
      'nurikabe.why.pool': '여기까지 바다면 바다가 2×2로 뭉치니 섬입니다.',
      'nurikabe.why.unreachable': '어느 섬도 이 칸까지 뻗어 올 수 없으니 바다입니다.',
      'nurikabe.why.islandOneWay': '숫자 <b>{clue}</b>의 섬이 더 자랄 길이 여기 하나뿐입니다.',
      'nurikabe.why.strayLand': '숫자 없는 섬 조각이 숫자 있는 섬에 닿을 길이 여기 하나뿐입니다.',
      'nurikabe.why.seaOneWay': '바다가 끊기지 않고 이어질 길이 여기 하나뿐입니다.',
      'nurikabe.why.trialSea': '여기를 섬으로 두면 어딘가에서 모순이 생기니 바다입니다.',
      'nurikabe.why.trialLand': '여기를 바다로 두면 어딘가에서 모순이 생기니 섬입니다.',
      'nurikabe.rule1': '칸을 <b>바다</b>(검정)와 <b>섬</b>(흰 칸)으로 나눕니다. 숫자는 그 숫자가 든 <b>섬의 칸 수</b>이고, 섬 하나에는 숫자가 정확히 하나 있습니다.',
      'nurikabe.rule2': '<b>바다는 모두 이어져</b> 있어야 하고, 바다가 <b>2×2로 뭉친 자리</b>가 있으면 안 됩니다.',
      'nurikabe.rule3': '칸을 누르면 <b>바다 → 점 → 빈칸</b> 순서로 바뀝니다. 점은 "여기는 섬"이라는 메모라 정답 판정에 쓰이지 않습니다 — 바다만 제대로 칠하면 끝납니다.',
      'nurikabe.rule4': '누른 채 <b>끌면</b> 첫 칸에 찍힌 것이 지나간 칸에 이어서 찍힙니다.',
      'nurikabe.rule5': '<b>모든 판은 답이 하나뿐이고 찍지 않고 풀립니다.</b> 다만 "여기를 바다로 두면 어떻게 되나"를 따져 봐야 하는 자리가 있고, 큰 판일수록 많습니다.',
      'nurikabe.rule6': '<b>힌트</b>는 어긋난 칸을 걷어 내고, 지금 알아낼 수 있는 칸을 채우며 그 까닭을 알려 줍니다. 힌트를 쓴 판은 최고 기록으로 남기지 않습니다.'
    },
    en: {
      'meta.desc': 'Shade the sea so that each number becomes an island of that size',
      'nurikabe.note': '{size}×{size} board',
      'nurikabe.hintCleared': 'Cleared {count} wrong cell(s).',
      'nurikabe.why.islandDone': 'The island of <b>{clue}</b> is complete, so everything around it is sea.',
      'nurikabe.why.twoIslands': 'Land here would join two numbered islands, so it is sea.',
      'nurikabe.why.pool': 'Sea here would make a 2×2 block of sea, so it is land.',
      'nurikabe.why.unreachable': 'No island can reach this cell, so it is sea.',
      'nurikabe.why.islandOneWay': 'This is the only way the island of <b>{clue}</b> can grow.',
      'nurikabe.why.strayLand': 'This is the only way this stray bit of land can reach a numbered island.',
      'nurikabe.why.seaOneWay': 'This is the only way this sea can stay connected.',
      'nurikabe.why.trialSea': 'Land here leads to a contradiction, so it is sea.',
      'nurikabe.why.trialLand': 'Sea here leads to a contradiction, so it is land.',
      'nurikabe.rule1': 'Split the grid into <b>sea</b> (dark) and <b>islands</b> (light). Each number is <b>the size of its island</b>, and every island holds exactly one number.',
      'nurikabe.rule2': '<b>All the sea must be connected</b>, and the sea may never form a <b>2×2 block</b>.',
      'nurikabe.rule3': 'Tap a cell to cycle <b>sea → dot → empty</b>. A dot is just your note that the cell is land — it is not checked. Shading the sea correctly is enough to finish.',
      'nurikabe.rule4': '<b>Drag</b> to copy what the first cell got onto every cell you pass over.',
      'nurikabe.rule5': '<b>Every board has exactly one answer and needs no guessing.</b> Some spots do ask “what if this were sea?”, and bigger boards have more of them.',
      'nurikabe.rule6': 'A <b>Hint</b> clears wrong cells, fills in what you can work out right now, and tells you why. Boards solved with hints are not recorded.'
    },
    ja: {
      'meta.desc': '数字の数だけ島を残し、残りを海として塗るパズル',
      'nurikabe.note': '{size}×{size}の盤',
      'nurikabe.hintCleared': '間違ったマスを{count}個消しました。',
      'nurikabe.why.islandDone': '<b>{clue}</b>の島は完成したので、周りはすべて海です。',
      'nurikabe.why.twoIslands': 'ここが島だと数字のある島どうしがつながるので、海です。',
      'nurikabe.why.pool': 'ここまで海だと海が2×2に固まるので、島です。',
      'nurikabe.why.unreachable': 'どの島もこのマスまで届かないので、海です。',
      'nurikabe.why.islandOneWay': '<b>{clue}</b>の島が広がれるのはここだけです。',
      'nurikabe.why.strayLand': '数字のない島のかけらが数字のある島につながれるのはここだけです。',
      'nurikabe.why.seaOneWay': '海が途切れずにつながれるのはここだけです。',
      'nurikabe.why.trialSea': 'ここを島にするとどこかで矛盾するので、海です。',
      'nurikabe.why.trialLand': 'ここを海にするとどこかで矛盾するので、島です。',
      'nurikabe.rule1': 'マスを<b>海</b>(黒)と<b>島</b>(白)に分けます。数字はその数字が入った<b>島のマス数</b>で、どの島にも数字がちょうど1つあります。',
      'nurikabe.rule2': '<b>海はすべてつながっていて</b>、<b>2×2に固まった海</b>があってはいけません。',
      'nurikabe.rule3': 'マスを押すと<b>海 → 点 → 空白</b>の順に変わります。点は「ここは島」というメモで、判定には使いません。海を正しく塗れば完成です。',
      'nurikabe.rule4': '押したまま<b>なぞる</b>と、最初のマスと同じものが通ったマスに続けて付きます。',
      'nurikabe.rule5': '<b>どの盤も答えはひとつで、当て推量なしで解けます。</b>ただし「ここを海にしたらどうなるか」を考える場所があり、大きな盤ほど多くなります。',
      'nurikabe.rule6': '<b>ヒント</b>は間違ったマスを消し、今わかるマスを埋めて理由を教えます。ヒントを使った盤は記録に残りません。'
    },
    'zh-CN': {
      'meta.desc': '按数字留下岛屿，把其余部分涂成海的谜题',
      'nurikabe.note': '{size}×{size} 盘',
      'nurikabe.hintCleared': '清除了 {count} 个错误的格子。',
      'nurikabe.why.islandDone': '<b>{clue}</b> 的岛已经完整，周围都是海。',
      'nurikabe.why.twoIslands': '这里是岛的话，两个带数字的岛会连在一起，所以是海。',
      'nurikabe.why.pool': '这里也是海的话，海会形成 2×2 的块，所以是岛。',
      'nurikabe.why.unreachable': '没有任何岛能延伸到这一格，所以是海。',
      'nurikabe.why.islandOneWay': '<b>{clue}</b> 的岛只能从这里继续扩展。',
      'nurikabe.why.strayLand': '这块没有数字的陆地只能从这里连到带数字的岛。',
      'nurikabe.why.seaOneWay': '海只能从这里保持连通。',
      'nurikabe.why.trialSea': '这里是岛的话会在某处产生矛盾，所以是海。',
      'nurikabe.why.trialLand': '这里是海的话会在某处产生矛盾，所以是岛。',
      'nurikabe.rule1': '把格子分成<b>海</b>（黑）和<b>岛</b>（白）。数字表示它所在<b>岛的格数</b>，每个岛恰好有一个数字。',
      'nurikabe.rule2': '<b>所有的海必须连在一起</b>，而且不能有 <b>2×2 的海</b>。',
      'nurikabe.rule3': '点击格子会按<b>海 → 点 → 空白</b>循环。点只是“这里是岛”的标记，不参与判定——把海涂对就完成了。',
      'nurikabe.rule4': '按住<b>拖动</b>，会把第一格的标记连续涂到经过的格子上。',
      'nurikabe.rule5': '<b>每一盘都只有一个答案，不用猜。</b>不过有些地方需要想“如果这里是海会怎样”，盘越大越多。',
      'nurikabe.rule6': '<b>提示</b>会清除错误的格子，补上现在能推出的格子，并说明理由。用过提示的盘不计入最佳纪录。'
    },
    'zh-TW': {
      'meta.desc': '依數字留下島嶼，把其餘部分塗成海的謎題',
      'nurikabe.note': '{size}×{size} 盤',
      'nurikabe.hintCleared': '清除了 {count} 個錯誤的格子。',
      'nurikabe.why.islandDone': '<b>{clue}</b> 的島已經完整，周圍都是海。',
      'nurikabe.why.twoIslands': '這裡是島的話，兩個帶數字的島會連在一起，所以是海。',
      'nurikabe.why.pool': '這裡也是海的話，海會形成 2×2 的塊，所以是島。',
      'nurikabe.why.unreachable': '沒有任何島能延伸到這一格，所以是海。',
      'nurikabe.why.islandOneWay': '<b>{clue}</b> 的島只能從這裡繼續擴展。',
      'nurikabe.why.strayLand': '這塊沒有數字的陸地只能從這裡連到帶數字的島。',
      'nurikabe.why.seaOneWay': '海只能從這裡保持連通。',
      'nurikabe.why.trialSea': '這裡是島的話會在某處產生矛盾，所以是海。',
      'nurikabe.why.trialLand': '這裡是海的話會在某處產生矛盾，所以是島。',
      'nurikabe.rule1': '把格子分成<b>海</b>（黑）和<b>島</b>（白）。數字表示它所在<b>島的格數</b>，每個島恰好有一個數字。',
      'nurikabe.rule2': '<b>所有的海必須連在一起</b>，而且不能有 <b>2×2 的海</b>。',
      'nurikabe.rule3': '點擊格子會依<b>海 → 點 → 空白</b>循環。點只是「這裡是島」的標記，不參與判定——把海塗對就完成了。',
      'nurikabe.rule4': '按住<b>拖曳</b>，會把第一格的標記連續塗到經過的格子上。',
      'nurikabe.rule5': '<b>每一盤都只有一個答案，不用猜。</b>不過有些地方需要想「如果這裡是海會怎樣」，盤越大越多。',
      'nurikabe.rule6': '<b>提示</b>會清除錯誤的格子，補上現在能推出的格子，並說明理由。用過提示的盤不計入最佳紀錄。'
    },
    es: {
      'meta.desc': 'Sombrea el mar para que cada número sea una isla de ese tamaño',
      'nurikabe.note': 'Tablero {size}×{size}',
      'nurikabe.hintCleared': 'Se quitaron {count} casilla(s) incorrecta(s).',
      'nurikabe.why.islandDone': 'La isla del <b>{clue}</b> está completa, así que lo que la rodea es mar.',
      'nurikabe.why.twoIslands': 'Tierra aquí uniría dos islas con número, así que es mar.',
      'nurikabe.why.pool': 'Mar aquí formaría un bloque de mar de 2×2, así que es tierra.',
      'nurikabe.why.unreachable': 'Ninguna isla puede llegar a esta casilla, así que es mar.',
      'nurikabe.why.islandOneWay': 'Es el único camino por el que puede crecer la isla del <b>{clue}</b>.',
      'nurikabe.why.strayLand': 'Es el único camino por el que este trozo de tierra suelto puede llegar a una isla con número.',
      'nurikabe.why.seaOneWay': 'Es el único camino por el que este mar puede seguir conectado.',
      'nurikabe.why.trialSea': 'Tierra aquí lleva a una contradicción, así que es mar.',
      'nurikabe.why.trialLand': 'Mar aquí lleva a una contradicción, así que es tierra.',
      'nurikabe.rule1': 'Divide la cuadrícula en <b>mar</b> (oscuro) e <b>islas</b> (claro). Cada número es <b>el tamaño de su isla</b>, y cada isla tiene exactamente un número.',
      'nurikabe.rule2': '<b>Todo el mar debe estar conectado</b> y nunca puede formar un <b>bloque de 2×2</b>.',
      'nurikabe.rule3': 'Toca una casilla para alternar <b>mar → punto → vacío</b>. El punto es solo tu nota de que ahí hay tierra; no se comprueba. Basta con sombrear bien el mar.',
      'nurikabe.rule4': '<b>Arrastra</b> para copiar lo que recibió la primera casilla en todas las que recorras.',
      'nurikabe.rule5': '<b>Cada tablero tiene una sola solución y no hace falta adivinar.</b> Aun así, hay sitios donde hay que pensar «¿y si aquí fuera mar?», y los tableros grandes tienen más.',
      'nurikabe.rule6': 'La <b>pista</b> quita las casillas incorrectas, completa lo que ya puedes deducir y te explica por qué. Los tableros resueltos con pistas no cuentan para el récord.'
    }
  });
})();
