// 이 게임에만 나오는 문구. 기록 안내와 도구 이름은 shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '가장자리 숫자대로 칸을 칠해 그림을 찾는 논리 퍼즐',
      'nonogram.took': '{time} 걸렸습니다',
      'nonogram.solved': '다 풀었습니다',
      'nonogram.found': '{name}!',
      'nonogram.cleared': '잘못 칠한 칸 <b>{count}개</b>를 지웠습니다',
      'nonogram.hintFill': '이 칸은 <b>칠하는</b> 칸입니다',
      'nonogram.hintEmpty': '이 칸은 <b>비는</b> 칸입니다',
      'nonogram.rule1': '가장자리 숫자는 그 줄에서 <b>이어서 칠해진 칸의 길이</b>를 차례로 적은 것입니다. <b>3 1</b>이면 셋을 칠하고 한 칸 이상 띄운 뒤 하나를 칠합니다.',
      'nonogram.rule2': '칸을 누를 때마다 <b>빈칸 → 칠함 → 아님 → 빈칸</b>으로 돕니다.',
      'nonogram.rule3': '<b>아님</b>(가위표)은 비어 있는 것이 확실한 칸에 쳐 두는 <b>메모</b>입니다. 판정에는 들어가지 않지만, 이것을 쳐 두어야 다음 칸이 보입니다.',
      'nonogram.rule4': '<b>쓸면 여러 칸을 한 번에</b> 바꿉니다. 처음 누른 칸이 된 것과 같은 것으로 지나간 자리를 모두 바꿉니다 — 빈칸에서 시작하면 칠하고, 칠한 칸에서 시작하면 가위표를 칩니다.',
      'nonogram.rule5': '숫자를 다 맞춘 줄은 <b>숫자가 흐려집니다.</b>',
      'nonogram.rule6': '<b>모든 판은 찍지 않고 논리로만 풀립니다.</b> 막히면 한 줄만 다시 보세요 — 그 줄 안에서 반드시 정해지는 칸이 있습니다.',
      'nonogram.rule7': '작은 판과 보통 판에는 <b>그림</b>이 숨어 있습니다. 다 풀면 이름이 나옵니다.',
      'nonogram.rule8': '<b>힌트</b>는 다음 한 칸을 알려 줍니다. 힌트를 쓴 판은 최고 기록에 넣지 않습니다.',
      'nonogram.pic.heart': '하트', 'nonogram.pic.tree': '나무', 'nonogram.pic.fish': '물고기',
      'nonogram.pic.cup': '컵', 'nonogram.pic.house': '집', 'nonogram.pic.umbrella': '우산',
      'nonogram.pic.sailboat': '돛단배', 'nonogram.pic.key': '열쇠', 'nonogram.pic.cat': '고양이',
      'nonogram.pic.mushroom': '버섯', 'nonogram.pic.anchor': '닻', 'nonogram.pic.lock': '자물쇠',
      'nonogram.pic.cherry': '체리', 'nonogram.pic.coffee': '커피', 'nonogram.pic.butterfly': '나비',
      'nonogram.pic.snowman': '눈사람', 'nonogram.pic.star': '별', 'nonogram.pic.duck': '오리',
      'nonogram.pic.note': '음표', 'nonogram.pic.dice': '주사위'
    },
    en: {
      'meta.desc': 'Paint the cells to match the numbers along the edges and uncover the picture',
      'nonogram.took': 'Took {time}',
      'nonogram.solved': 'Solved',
      'nonogram.found': '{name}!',
      'nonogram.cleared': 'Cleared <b>{count} wrongly filled</b> cells',
      'nonogram.hintFill': 'This cell is <b>filled</b>',
      'nonogram.hintEmpty': 'This cell is <b>empty</b>',
      'nonogram.rule1': 'The numbers along an edge list the <b>lengths of the filled runs</b> in that line, in order. <b>3 1</b> means three filled, at least one gap, then one filled.',
      'nonogram.rule2': 'Tapping a cell cycles <b>empty → filled → crossed → empty</b>.',
      'nonogram.rule3': 'A <b>cross</b> is a <b>note</b> you put on cells you know stay empty. It never counts toward the solution, but marking them is what makes the next cell visible.',
      'nonogram.rule4': '<b>Swipe to change several cells at once.</b> The whole stroke becomes whatever the first cell turned into — start on an empty cell to fill, start on a filled one to cross out.',
      'nonogram.rule5': 'Once a line matches its numbers, <b>those numbers fade</b>.',
      'nonogram.rule6': '<b>Every board is solvable by logic alone.</b> If you are stuck, look at one single line again — there is always a cell that line alone decides.',
      'nonogram.rule7': 'Small and medium boards hide a <b>picture</b>. Solve it and its name appears.',
      'nonogram.rule8': 'A <b>Hint</b> reveals the next cell. Boards solved with hints are not recorded.',
      'nonogram.pic.heart': 'Heart', 'nonogram.pic.tree': 'Tree', 'nonogram.pic.fish': 'Fish',
      'nonogram.pic.cup': 'Cup', 'nonogram.pic.house': 'House', 'nonogram.pic.umbrella': 'Umbrella',
      'nonogram.pic.sailboat': 'Sailboat', 'nonogram.pic.key': 'Key', 'nonogram.pic.cat': 'Cat',
      'nonogram.pic.mushroom': 'Mushroom', 'nonogram.pic.anchor': 'Anchor', 'nonogram.pic.lock': 'Lock',
      'nonogram.pic.cherry': 'Cherry', 'nonogram.pic.coffee': 'Coffee', 'nonogram.pic.butterfly': 'Butterfly',
      'nonogram.pic.snowman': 'Snowman', 'nonogram.pic.star': 'Star', 'nonogram.pic.duck': 'Duck',
      'nonogram.pic.note': 'Music note', 'nonogram.pic.dice': 'Dice'
    },
    ja: {
      'meta.desc': '端の数字どおりにマスを塗って絵を見つける論理パズル',
      'nonogram.took': '{time} かかりました',
      'nonogram.solved': '解けました',
      'nonogram.found': '{name}！',
      'nonogram.cleared': '塗り間違えた<b>{count}マス</b>を消しました',
      'nonogram.hintFill': 'このマスは<b>塗る</b>マスです',
      'nonogram.hintEmpty': 'このマスは<b>空ける</b>マスです',
      'nonogram.rule1': '端の数字は、その列で<b>続けて塗るマスの長さ</b>を順に並べたものです。<b>3 1</b>なら三つ塗り、一マス以上あけて一つ塗ります。',
      'nonogram.rule2': 'マスを押すたびに<b>空 → 塗り → バツ → 空</b>と変わります。',
      'nonogram.rule3': '<b>バツ</b>は空くと確信したマスに付ける<b>メモ</b>です。判定には入りませんが、これを付けてこそ次のマスが見えます。',
      'nonogram.rule4': '<b>なぞると何マスもまとめて</b>変わります。最初に押したマスがなったものに、通った所がすべて揃います — 空マスから始めれば塗り、塗ったマスから始めればバツです。',
      'nonogram.rule5': '数字が揃った列は<b>数字が薄くなります。</b>',
      'nonogram.rule6': '<b>どの盤も当てずっぽう抜きに論理だけで解けます。</b>行き詰まったら一列だけ見直してください — その列だけで決まるマスが必ずあります。',
      'nonogram.rule7': '小さい盤とふつうの盤には<b>絵</b>が隠れています。解けると名前が出ます。',
      'nonogram.rule8': '<b>ヒント</b>は次の一マスを教えます。ヒントを使った盤はベスト記録に入れません。',
      'nonogram.pic.heart': 'ハート', 'nonogram.pic.tree': '木', 'nonogram.pic.fish': '魚',
      'nonogram.pic.cup': 'カップ', 'nonogram.pic.house': '家', 'nonogram.pic.umbrella': '傘',
      'nonogram.pic.sailboat': 'ヨット', 'nonogram.pic.key': '鍵', 'nonogram.pic.cat': 'ねこ',
      'nonogram.pic.mushroom': 'きのこ', 'nonogram.pic.anchor': 'いかり', 'nonogram.pic.lock': '南京錠',
      'nonogram.pic.cherry': 'さくらんぼ', 'nonogram.pic.coffee': 'コーヒー', 'nonogram.pic.butterfly': 'ちょう',
      'nonogram.pic.snowman': '雪だるま', 'nonogram.pic.star': '星', 'nonogram.pic.duck': 'あひる',
      'nonogram.pic.note': '音符', 'nonogram.pic.dice': 'サイコロ'
    },
    'zh-CN': {
      'meta.desc': '按边上的数字涂格子，把藏着的图案找出来',
      'nonogram.took': '用时 {time}',
      'nonogram.solved': '全部解开',
      'nonogram.found': '{name}！',
      'nonogram.cleared': '擦掉了<b>涂错的 {count} 格</b>',
      'nonogram.hintFill': '这一格是<b>要涂</b>的',
      'nonogram.hintEmpty': '这一格是<b>要空</b>的',
      'nonogram.rule1': '边上的数字，是那一行里<b>连续涂黑的长度</b>，按顺序排列。<b>3 1</b> 就是涂三格，空至少一格，再涂一格。',
      'nonogram.rule2': '每点一格，按<b>空 → 涂 → 打叉 → 空</b>循环。',
      'nonogram.rule3': '<b>叉</b>是给确定留空的格子做的<b>标记</b>。它不参与判定，但打上了才看得见下一格。',
      'nonogram.rule4': '<b>滑动可以一次改好几格。</b>整条路径都跟着第一格变成的样子走 —— 从空格起手就涂，从涂过的格起手就打叉。',
      'nonogram.rule5': '数字凑齐的那一行，<b>数字会变淡。</b>',
      'nonogram.rule6': '<b>所有盘面都只靠推理就能解开。</b>卡住时只盯着一行重看 —— 那一行里一定有能确定的格子。',
      'nonogram.rule7': '小盘和普通盘里藏着<b>图案</b>，解完会显示名字。',
      'nonogram.rule8': '<b>提示</b>会告诉你下一格。用过提示的盘面不计入最好成绩。',
      'nonogram.pic.heart': '心', 'nonogram.pic.tree': '树', 'nonogram.pic.fish': '鱼',
      'nonogram.pic.cup': '杯子', 'nonogram.pic.house': '房子', 'nonogram.pic.umbrella': '雨伞',
      'nonogram.pic.sailboat': '帆船', 'nonogram.pic.key': '钥匙', 'nonogram.pic.cat': '猫',
      'nonogram.pic.mushroom': '蘑菇', 'nonogram.pic.anchor': '锚', 'nonogram.pic.lock': '锁',
      'nonogram.pic.cherry': '樱桃', 'nonogram.pic.coffee': '咖啡', 'nonogram.pic.butterfly': '蝴蝶',
      'nonogram.pic.snowman': '雪人', 'nonogram.pic.star': '星星', 'nonogram.pic.duck': '鸭子',
      'nonogram.pic.note': '音符', 'nonogram.pic.dice': '骰子'
    },
    'zh-TW': {
      'meta.desc': '按邊上的數字塗格子，把藏著的圖案找出來',
      'nonogram.took': '用時 {time}',
      'nonogram.solved': '全部解開',
      'nonogram.found': '{name}！',
      'nonogram.cleared': '擦掉了<b>塗錯的 {count} 格</b>',
      'nonogram.hintFill': '這一格是<b>要塗</b>的',
      'nonogram.hintEmpty': '這一格是<b>要空</b>的',
      'nonogram.rule1': '邊上的數字，是那一行裡<b>連續塗黑的長度</b>，按順序排列。<b>3 1</b> 就是塗三格，空至少一格，再塗一格。',
      'nonogram.rule2': '每點一格，按<b>空 → 塗 → 打叉 → 空</b>循環。',
      'nonogram.rule3': '<b>叉</b>是給確定留空的格子做的<b>標記</b>。它不參與判定，但打上了才看得見下一格。',
      'nonogram.rule4': '<b>滑動可以一次改好幾格。</b>整條路徑都跟著第一格變成的樣子走 —— 從空格起手就塗，從塗過的格起手就打叉。',
      'nonogram.rule5': '數字湊齊的那一行，<b>數字會變淡。</b>',
      'nonogram.rule6': '<b>所有盤面都只靠推理就能解開。</b>卡住時只盯著一行重看 —— 那一行裡一定有能確定的格子。',
      'nonogram.rule7': '小盤和普通盤裡藏著<b>圖案</b>，解完會顯示名字。',
      'nonogram.rule8': '<b>提示</b>會告訴你下一格。用過提示的盤面不計入最佳成績。',
      'nonogram.pic.heart': '心', 'nonogram.pic.tree': '樹', 'nonogram.pic.fish': '魚',
      'nonogram.pic.cup': '杯子', 'nonogram.pic.house': '房子', 'nonogram.pic.umbrella': '雨傘',
      'nonogram.pic.sailboat': '帆船', 'nonogram.pic.key': '鑰匙', 'nonogram.pic.cat': '貓',
      'nonogram.pic.mushroom': '蘑菇', 'nonogram.pic.anchor': '錨', 'nonogram.pic.lock': '鎖',
      'nonogram.pic.cherry': '櫻桃', 'nonogram.pic.coffee': '咖啡', 'nonogram.pic.butterfly': '蝴蝶',
      'nonogram.pic.snowman': '雪人', 'nonogram.pic.star': '星星', 'nonogram.pic.duck': '鴨子',
      'nonogram.pic.note': '音符', 'nonogram.pic.dice': '骰子'
    },
    es: {
      'meta.desc': 'Pinta las casillas según los números del borde y descubre el dibujo',
      'nonogram.took': 'Tardaste {time}',
      'nonogram.solved': 'Resuelto',
      'nonogram.found': '¡{name}!',
      'nonogram.cleared': 'Se borraron <b>{count} casillas</b> mal pintadas',
      'nonogram.hintFill': 'Esta casilla va <b>pintada</b>',
      'nonogram.hintEmpty': 'Esta casilla va <b>vacía</b>',
      'nonogram.rule1': 'Los números del borde son las <b>longitudes de los tramos pintados</b> de esa línea, en orden. <b>3 1</b> significa tres pintadas, al menos un hueco, y luego una.',
      'nonogram.rule2': 'Al tocar una casilla alterna <b>vacía → pintada → tachada → vacía</b>.',
      'nonogram.rule3': 'La <b>tachadura</b> es una <b>nota</b> para las casillas que seguro quedan vacías. No cuenta para la solución, pero marcarlas es lo que te deja ver la siguiente.',
      'nonogram.rule4': '<b>Arrastra para cambiar varias casillas de una vez.</b> Todo el trazo toma lo que quedó la primera casilla: si empiezas en una vacía pintas, si empiezas en una pintada tachas.',
      'nonogram.rule5': 'Cuando una línea cuadra con sus números, <b>esos números se atenúan</b>.',
      'nonogram.rule6': '<b>Todos los tableros salen solo con lógica.</b> Si te atascas, vuelve a mirar una sola línea: siempre hay una casilla que esa línea decide por sí sola.',
      'nonogram.rule7': 'Los tableros pequeños y medianos esconden un <b>dibujo</b>. Al resolverlo aparece su nombre.',
      'nonogram.rule8': 'Una <b>Pista</b> descubre la siguiente casilla. Los tableros con pistas no cuentan para el récord.',
      'nonogram.pic.heart': 'Corazón', 'nonogram.pic.tree': 'Árbol', 'nonogram.pic.fish': 'Pez',
      'nonogram.pic.cup': 'Taza', 'nonogram.pic.house': 'Casa', 'nonogram.pic.umbrella': 'Paraguas',
      'nonogram.pic.sailboat': 'Velero', 'nonogram.pic.key': 'Llave', 'nonogram.pic.cat': 'Gato',
      'nonogram.pic.mushroom': 'Seta', 'nonogram.pic.anchor': 'Ancla', 'nonogram.pic.lock': 'Candado',
      'nonogram.pic.cherry': 'Cereza', 'nonogram.pic.coffee': 'Café', 'nonogram.pic.butterfly': 'Mariposa',
      'nonogram.pic.snowman': 'Muñeco de nieve', 'nonogram.pic.star': 'Estrella', 'nonogram.pic.duck': 'Pato',
      'nonogram.pic.note': 'Nota musical', 'nonogram.pic.dice': 'Dado'
    }
  });
})();
