// 이 게임에만 나오는 문구. 게임 이름과 헤더 공통 문구는 ../../shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '역을 놓고 그 사이로 노선을 그어 도시를 키운다. 건물 밑은 비싸고 강 밑은 더 비싸며, 급하게 굽으면 느려진다.',
      'metro.mapLabel': '도시',
      'metro.difficulty': '난이도',
      'metro.easy': '쉬움',
      'metro.normal': '보통',
      'metro.hard': '어려움',
      'metro.tool': '도구',
      'metro.modeStation': '역 놓기',
      'metro.modeLine': '노선 잇기',
      'metro.budget': '예산',
      'metro.newCity': '새 도시',
      'metro.cost': '건설비',
      'metro.time': '소요시간',
      'metro.length': '길이',
      'metro.curveLimit': '곡선 제한',
      'metro.underRoad': '도로 밑',
      'metro.underEmpty': '빈 땅',
      'metro.underBuilding': '건물 밑',
      'metro.underHill': '산 밑',
      'metro.underWater': '물 밑',
      'metro.confirm': '확정',
      'metro.cancel': '취소',
      'metro.unitMoney': '억',
      'metro.placeHint': '빈 자리를 눌러 역을 놓으세요',
      'metro.stationBuilt': '역을 놓았습니다',
      'metro.removed': '역을 철거했습니다',
      'metro.inUse': '노선이 붙은 역은 철거할 수 없습니다',
      'metro.noMoney': '예산이 모자랍니다',
      'metro.needStations': '역을 두 개 이상 놓으세요',
      'metro.bad.outside': '지도 밖입니다',
      'metro.bad.water': '물 위에는 놓을 수 없습니다',
      'metro.bad.hill': '산에는 놓을 수 없습니다',
      'metro.bad.building': '건물 위에는 놓을 수 없습니다',
      'metro.bad.close': '다른 역과 너무 가깝습니다',
      'metro.pickFirst': '역을 하나 고르세요',
      'metro.pickSecond': '이을 역을 고르세요',
      'metro.editHint': '선을 잡아 끌어 경로를 바꿔 보세요',
      'metro.maxMids': '중간점은 세 개까지입니다',
      'metro.sharp': '곡선이 너무 급해 지을 수 없습니다',
      'metro.built': '구간을 지었습니다',
      'metro.grew': '{n}곳이 자랐습니다',
      'metro.draftNote': '아직 만드는 중입니다. 승객 수요와 요금 수입은 들어오지 않았습니다.',
      'metro.ruleMap': '지도는 화면보다 넓습니다. <b>빈 곳을 끌면</b> 지도가 움직입니다. 고른 역이 화면 밖으로 나가면 가장자리에 점으로 남습니다.',
      'metro.ruleStation': '<b>역 놓기</b>에서 빈 자리를 누르면 역이 생깁니다. 물·산·건물 위에는 놓을 수 없습니다. 역을 다시 누르면 철거되고 절반을 돌려받습니다.',
      'metro.rule1': '<b>노선 잇기</b>로 바꾸고 역 두 개를 차례로 누르면 둘을 잇는 직선이 생깁니다.',
      'metro.rule2': '그 선을 <b>잡아 끌면</b> 그 자리에 중간점이 생기며 경로가 휩니다. 중간점은 <b>세 개</b>까지입니다.',
      'metro.rule3': '중간점을 <b>두 번 두드리면</b> 지워집니다. 끌 때 도로 가까이 가면 도로에 <b>달라붙습니다</b>.',
      'metro.rule4': '땅마다 값이 다릅니다. <b>도로 밑</b>이 가장 싸고, 빈 땅, 건물 밑, 산 밑 순으로 오르며 <b>물 밑</b>이 가장 비쌉니다.',
      'metro.rule5': '급하게 굽으면 그 구간의 <b>제한속도</b>가 걸려 느려집니다. 너무 급하면 아예 지을 수 없습니다.',
      'metro.rule6': '열차는 역에서 <b>서 있다가 출발해 다음 역에서 섭니다.</b> 그래서 역이 가까우면 최고 속도에 닿지 못합니다.',
      'metro.ruleGrow': '구간을 확정하면 <b>이어진 역 둘레의 동네가 자랍니다.</b> 빈 터에 건물이 들어서고 있던 건물은 높아지며, 자란 만큼 예산이 들어옵니다. <b>얼마나 높아질지는 건물의 종류가 정합니다.</b>',
      'metro.ruleDistrict': '<b>구시가지</b>는 골목이 좁고 굽은 데다 막다른 길과 삼거리가 많아 길을 따라가기 어렵습니다. <b>계획도시</b>는 그 반대입니다. 난이도는 둘의 배합을 바꿉니다.',
      'metro.rule7': '<b>확정</b>을 누르기 전에는 아무것도 지어지지 않습니다. 마음껏 끌어 보세요.'
    },
    en: {
      'meta.desc': 'Place stations and draw lines between them to grow the city. Tunnelling under buildings costs more, under water more still, and tight curves slow trains down.',
      'metro.mapLabel': 'City',
      'metro.difficulty': 'Difficulty',
      'metro.easy': 'Easy',
      'metro.normal': 'Normal',
      'metro.hard': 'Hard',
      'metro.tool': 'Tool',
      'metro.modeStation': 'Place stations',
      'metro.modeLine': 'Draw a line',
      'metro.budget': 'Budget',
      'metro.newCity': 'New city',
      'metro.cost': 'Cost',
      'metro.time': 'Travel time',
      'metro.length': 'Length',
      'metro.curveLimit': 'Curve limit',
      'metro.underRoad': 'Under road',
      'metro.underEmpty': 'Open land',
      'metro.underBuilding': 'Under buildings',
      'metro.underHill': 'Under hills',
      'metro.underWater': 'Under water',
      'metro.confirm': 'Build',
      'metro.cancel': 'Cancel',
      'metro.unitMoney': 'B',
      'metro.placeHint': 'Tap an empty spot to place a station',
      'metro.stationBuilt': 'Station placed',
      'metro.removed': 'Station removed',
      'metro.inUse': 'A station with a line attached cannot be removed',
      'metro.noMoney': 'Not enough budget',
      'metro.needStations': 'Place at least two stations',
      'metro.bad.outside': 'That is off the map',
      'metro.bad.water': 'Not on water',
      'metro.bad.hill': 'Not on a hill',
      'metro.bad.building': 'Not on a building',
      'metro.bad.close': 'Too close to another station',
      'metro.pickFirst': 'Pick a station',
      'metro.pickSecond': 'Pick the station to link',
      'metro.editHint': 'Drag the line to bend the route',
      'metro.maxMids': 'Up to three midpoints',
      'metro.sharp': 'That curve is too tight to build',
      'metro.built': 'Segment built',
      'metro.grew': '{n} plots grew',
      'metro.draftNote': 'Still being built — passenger demand and fare revenue are not in yet.',
      'metro.ruleMap': 'The map is wider than the screen. <b>Drag an empty spot</b> to move it. A station you picked leaves a dot at the edge once it scrolls off.',
      'metro.ruleStation': 'In <b>Place stations</b>, tap an empty spot to add one. Not on water, hills or buildings. Tap a station again to remove it and get half the cost back.',
      'metro.rule1': 'Switch to <b>Draw a line</b> and tap two stations; a straight line appears between them.',
      'metro.rule2': '<b>Drag that line</b> and a midpoint appears where you grabbed it, bending the route. You get <b>three</b> midpoints.',
      'metro.rule3': '<b>Double-tap</b> a midpoint to remove it. Drag one near a street and it <b>snaps</b> to the street.',
      'metro.rule4': 'Ground costs differ. <b>Under a street</b> is cheapest, then open land, buildings and hills — and <b>under water</b> is the dearest of all.',
      'metro.rule5': 'A tight bend puts a <b>speed limit</b> on that stretch. Too tight and it cannot be built at all.',
      'metro.rule6': 'Trains <b>start from a standstill and stop at the next station</b>, so close stations never reach top speed.',
      'metro.ruleGrow': 'Confirming a segment makes <b>the neighbourhoods around connected stations grow.</b> Empty plots get built on and existing buildings rise, and your budget grows with them. <b>How high they go is set by what kind of building it is.</b>',
      'metro.ruleDistrict': 'The <b>old town</b> has narrow winding lanes full of dead ends and forks, so following the streets is hard. A <b>planned district</b> is the opposite. Difficulty changes the mix.',
      'metro.rule7': 'Nothing is built until you press <b>Build</b>. Drag as much as you like.'
    },
    ja: {
      'meta.desc': '駅を置き、その間に路線を引いて街を育てる。建物の下は高くつき、水の下はもっと高く、急な曲線は速度を落とす。',
      'metro.mapLabel': '街',
      'metro.difficulty': '難易度',
      'metro.easy': 'やさしい',
      'metro.normal': 'ふつう',
      'metro.hard': 'むずかしい',
      'metro.tool': '道具',
      'metro.modeStation': '駅を置く',
      'metro.modeLine': '路線を引く',
      'metro.budget': '予算',
      'metro.newCity': '新しい街',
      'metro.cost': '建設費',
      'metro.time': '所要時間',
      'metro.length': '距離',
      'metro.curveLimit': '曲線制限',
      'metro.underRoad': '道路の下',
      'metro.underEmpty': '空き地',
      'metro.underBuilding': '建物の下',
      'metro.underHill': '山の下',
      'metro.underWater': '水の下',
      'metro.confirm': '確定',
      'metro.cancel': '取消',
      'metro.unitMoney': '億',
      'metro.placeHint': '空いている所を押すと駅ができます',
      'metro.stationBuilt': '駅を置きました',
      'metro.removed': '駅を撤去しました',
      'metro.inUse': '路線がつながった駅は撤去できません',
      'metro.noMoney': '予算が足りません',
      'metro.needStations': '駅を二つ以上置いてください',
      'metro.bad.outside': '地図の外です',
      'metro.bad.water': '水の上には置けません',
      'metro.bad.hill': '山には置けません',
      'metro.bad.building': '建物の上には置けません',
      'metro.bad.close': '他の駅に近すぎます',
      'metro.pickFirst': '駅を一つ選んでください',
      'metro.pickSecond': 'つなぐ駅を選んでください',
      'metro.editHint': '線をつかんで動かすと経路が曲がります',
      'metro.maxMids': '中間点は三つまでです',
      'metro.sharp': '曲線が急すぎて建設できません',
      'metro.built': '区間を建設しました',
      'metro.grew': '{n}か所が育ちました',
      'metro.draftNote': 'まだ作っている途中です。乗客の需要と運賃収入はまだありません。',
      'metro.ruleMap': '地図は画面より広いです。<b>何もない所をドラッグ</b>すると地図が動きます。選んだ駅が画面の外に出ると、端に点が残ります。',
      'metro.ruleStation': '<b>駅を置く</b>で空いている所を押すと駅ができます。水・山・建物の上には置けません。駅をもう一度押すと撤去され、半額が戻ります。',
      'metro.rule1': '<b>路線を引く</b>に切り替えて駅を二つ順に押すと、二つを結ぶ直線が現れます。',
      'metro.rule2': 'その線を<b>つかんで動かす</b>と、その場所に中間点ができて経路が曲がります。中間点は<b>三つ</b>までです。',
      'metro.rule3': '中間点を<b>二回たたく</b>と消えます。動かすとき道路に近づけると道路に<b>吸い付きます</b>。',
      'metro.rule4': '土地ごとに値段が違います。<b>道路の下</b>がいちばん安く、空き地・建物の下・山の下と上がり、<b>水の下</b>がいちばん高くつきます。',
      'metro.rule5': '急に曲がるとその区間に<b>制限速度</b>がかかって遅くなります。急すぎると建設そのものができません。',
      'metro.rule6': '列車は駅で<b>止まった状態から発車し、次の駅で止まります。</b>だから駅が近いと最高速度に届きません。',
      'metro.ruleGrow': '区間を確定すると<b>つながった駅の周りの街が育ちます。</b>空き地に建物が建ち、建っていた建物は高くなり、育った分だけ予算が入ります。<b>どこまで高くなるかは建物の種類が決めます。</b>',
      'metro.ruleDistrict': '<b>旧市街</b>は路地が狭く曲がっていて行き止まりや三叉路が多く、道に沿って進むのが難しいです。<b>計画都市</b>はその逆です。難易度はその配分を変えます。',
      'metro.rule7': '<b>確定</b>を押すまでは何も建ちません。思いきり動かしてみてください。'
    },
    'zh-CN': {
      'meta.desc': '设站并在站间铺线，把城市养大。建筑下造价高，水下更高，急弯会让列车变慢。',
      'metro.mapLabel': '城市',
      'metro.difficulty': '难度',
      'metro.easy': '简单',
      'metro.normal': '普通',
      'metro.hard': '困难',
      'metro.tool': '工具',
      'metro.modeStation': '设站',
      'metro.modeLine': '连线',
      'metro.budget': '预算',
      'metro.newCity': '新城市',
      'metro.cost': '造价',
      'metro.time': '运行时间',
      'metro.length': '长度',
      'metro.curveLimit': '弯道限速',
      'metro.underRoad': '道路下',
      'metro.underEmpty': '空地',
      'metro.underBuilding': '建筑下',
      'metro.underHill': '山下',
      'metro.underWater': '水下',
      'metro.confirm': '确定',
      'metro.cancel': '取消',
      'metro.unitMoney': '亿',
      'metro.placeHint': '点空地即可设站',
      'metro.stationBuilt': '已设站',
      'metro.removed': '已拆除车站',
      'metro.inUse': '已接线路的车站无法拆除',
      'metro.noMoney': '预算不足',
      'metro.needStations': '请先设两座以上车站',
      'metro.bad.outside': '超出地图',
      'metro.bad.water': '水上不能设站',
      'metro.bad.hill': '山上不能设站',
      'metro.bad.building': '建筑上不能设站',
      'metro.bad.close': '离其他车站太近',
      'metro.pickFirst': '先选一座车站',
      'metro.pickSecond': '再选要连接的车站',
      'metro.editHint': '拖动线路可以让它弯曲',
      'metro.maxMids': '中间点最多三个',
      'metro.sharp': '弯道太急，无法施工',
      'metro.built': '区间已建成',
      'metro.grew': '{n}处长大了',
      'metro.draftNote': '还在制作中，乘客需求和票价收入还没有加入。',
      'metro.ruleMap': '地图比屏幕更大。<b>拖动空白处</b>即可移动地图。已选的车站移出画面后，会在边缘留下一个点。',
      'metro.ruleStation': '在<b>设站</b>下点空地就能建站。水面、山地和建筑上不能建。再点一次车站即可拆除，退还一半费用。',
      'metro.rule1': '切换到<b>连线</b>，依次点两座车站，就会出现连接它们的直线。',
      'metro.rule2': '<b>拖动这条线</b>，会在拖的位置生成中间点，线路随之弯曲。中间点最多<b>三个</b>。',
      'metro.rule3': '<b>连点两下</b>中间点即可删除。拖动时靠近道路会<b>自动吸附</b>到道路上。',
      'metro.rule4': '地下造价各不相同。<b>道路下</b>最便宜，其次是空地、建筑下、山下，<b>水下</b>最贵。',
      'metro.rule5': '弯得太急，该区段会有<b>限速</b>而变慢。过急则根本无法施工。',
      'metro.rule6': '列车在车站<b>从静止起步，到下一站停车</b>，所以车站太近就到不了最高速度。',
      'metro.ruleGrow': '确定区间后，<b>已连通车站周围的街区会生长。</b>空地上会盖起房子，原有的房子会变高，长多少就进多少预算。<b>能长多高由建筑的类型决定。</b>',
      'metro.ruleDistrict': '<b>老城区</b>的巷子又窄又弯，死胡同和三岔路很多，顺着路走很难。<b>新城区</b>正相反。难度改变两者的比例。',
      'metro.rule7': '按下<b>确定</b>之前什么都不会建成，尽管拖动试试。'
    },
    'zh-TW': {
      'meta.desc': '設站並在站間鋪線，把城市養大。建築下造價高，水下更高，急彎會讓列車變慢。',
      'metro.mapLabel': '城市',
      'metro.difficulty': '難度',
      'metro.easy': '簡單',
      'metro.normal': '普通',
      'metro.hard': '困難',
      'metro.tool': '工具',
      'metro.modeStation': '設站',
      'metro.modeLine': '連線',
      'metro.budget': '預算',
      'metro.newCity': '新城市',
      'metro.cost': '造價',
      'metro.time': '運行時間',
      'metro.length': '長度',
      'metro.curveLimit': '彎道限速',
      'metro.underRoad': '道路下',
      'metro.underEmpty': '空地',
      'metro.underBuilding': '建築下',
      'metro.underHill': '山下',
      'metro.underWater': '水下',
      'metro.confirm': '確定',
      'metro.cancel': '取消',
      'metro.unitMoney': '億',
      'metro.placeHint': '點空地即可設站',
      'metro.stationBuilt': '已設站',
      'metro.removed': '已拆除車站',
      'metro.inUse': '已接線路的車站無法拆除',
      'metro.noMoney': '預算不足',
      'metro.needStations': '請先設兩座以上車站',
      'metro.bad.outside': '超出地圖',
      'metro.bad.water': '水上不能設站',
      'metro.bad.hill': '山上不能設站',
      'metro.bad.building': '建築上不能設站',
      'metro.bad.close': '離其他車站太近',
      'metro.pickFirst': '先選一座車站',
      'metro.pickSecond': '再選要連接的車站',
      'metro.editHint': '拖動線路可以讓它彎曲',
      'metro.maxMids': '中間點最多三個',
      'metro.sharp': '彎道太急，無法施工',
      'metro.built': '區間已建成',
      'metro.grew': '{n}處長大了',
      'metro.draftNote': '還在製作中，乘客需求和票價收入還沒有加入。',
      'metro.ruleMap': '地圖比螢幕更大。<b>拖動空白處</b>即可移動地圖。已選的車站移出畫面後，會在邊緣留下一個點。',
      'metro.ruleStation': '在<b>設站</b>下點空地就能建站。水面、山地和建築上不能建。再點一次車站即可拆除，退還一半費用。',
      'metro.rule1': '切換到<b>連線</b>，依序點兩座車站，就會出現連接它們的直線。',
      'metro.rule2': '<b>拖動這條線</b>，會在拖的位置生成中間點，線路隨之彎曲。中間點最多<b>三個</b>。',
      'metro.rule3': '<b>連點兩下</b>中間點即可刪除。拖動時靠近道路會<b>自動吸附</b>到道路上。',
      'metro.rule4': '地下造價各不相同。<b>道路下</b>最便宜，其次是空地、建築下、山下，<b>水下</b>最貴。',
      'metro.rule5': '彎得太急，該區段會有<b>限速</b>而變慢。過急則根本無法施工。',
      'metro.rule6': '列車在車站<b>從靜止起步，到下一站停車</b>，所以車站太近就到不了最高速度。',
      'metro.ruleGrow': '確定區間後，<b>已連通車站周圍的街區會生長。</b>空地上會蓋起房子，原有的房子會變高，長多少就進多少預算。<b>能長多高由建築的類型決定。</b>',
      'metro.ruleDistrict': '<b>老城區</b>的巷子又窄又彎，死胡同和三岔路很多，順著路走很難。<b>新城區</b>正相反。難度改變兩者的比例。',
      'metro.rule7': '按下<b>確定</b>之前什麼都不會建成，儘管拖動看看。'
    },
    es: {
      'meta.desc': 'Pon estaciones y traza líneas entre ellas para hacer crecer la ciudad. Excavar bajo edificios cuesta más, bajo el agua aún más, y las curvas cerradas frenan los trenes.',
      'metro.mapLabel': 'Ciudad',
      'metro.difficulty': 'Dificultad',
      'metro.easy': 'Fácil',
      'metro.normal': 'Normal',
      'metro.hard': 'Difícil',
      'metro.tool': 'Herramienta',
      'metro.modeStation': 'Poner estaciones',
      'metro.modeLine': 'Trazar línea',
      'metro.budget': 'Presupuesto',
      'metro.newCity': 'Nueva ciudad',
      'metro.cost': 'Coste',
      'metro.time': 'Tiempo',
      'metro.length': 'Longitud',
      'metro.curveLimit': 'Límite en curva',
      'metro.underRoad': 'Bajo la calle',
      'metro.underEmpty': 'Suelo libre',
      'metro.underBuilding': 'Bajo edificios',
      'metro.underHill': 'Bajo monte',
      'metro.underWater': 'Bajo el agua',
      'metro.confirm': 'Construir',
      'metro.cancel': 'Cancelar',
      'metro.unitMoney': 'B',
      'metro.placeHint': 'Toca un punto libre para poner una estación',
      'metro.stationBuilt': 'Estación construida',
      'metro.removed': 'Estación retirada',
      'metro.inUse': 'No se puede retirar una estación con línea conectada',
      'metro.noMoney': 'Presupuesto insuficiente',
      'metro.needStations': 'Pon al menos dos estaciones',
      'metro.bad.outside': 'Está fuera del mapa',
      'metro.bad.water': 'Sobre el agua no',
      'metro.bad.hill': 'Sobre la montaña no',
      'metro.bad.building': 'Sobre un edificio no',
      'metro.bad.close': 'Demasiado cerca de otra estación',
      'metro.pickFirst': 'Elige una estación',
      'metro.pickSecond': 'Elige la estación a enlazar',
      'metro.editHint': 'Arrastra la línea para curvar el trazado',
      'metro.maxMids': 'Hasta tres puntos intermedios',
      'metro.sharp': 'Esa curva es demasiado cerrada para construirla',
      'metro.built': 'Tramo construido',
      'metro.grew': '{n} solares crecieron',
      'metro.draftNote': 'Aún en construcción: todavía no hay demanda de pasajeros ni ingresos por billetes.',
      'metro.ruleMap': 'El mapa es más ancho que la pantalla. <b>Arrastra una zona vacía</b> para moverlo. La estación elegida deja un punto en el borde al salir de la vista.',
      'metro.ruleStation': 'En <b>Poner estaciones</b>, toca un punto libre para añadir una. No sobre agua, montaña ni edificios. Tócala de nuevo para retirarla y recuperar la mitad.',
      'metro.rule1': 'Cambia a <b>Trazar línea</b> y toca dos estaciones: aparecerá una recta que las une.',
      'metro.rule2': '<b>Arrastra esa línea</b> y surgirá un punto intermedio donde la agarraste, curvando el trazado. Tienes <b>tres</b> puntos.',
      'metro.rule3': '<b>Toca dos veces</b> un punto para borrarlo. Al arrastrarlo cerca de una calle, se <b>pega</b> a ella.',
      'metro.rule4': 'Cada terreno cuesta distinto. <b>Bajo la calle</b> es lo más barato, luego suelo libre, edificios y monte, y <b>bajo el agua</b> es lo más caro.',
      'metro.rule5': 'Una curva cerrada impone un <b>límite de velocidad</b> en ese tramo. Si es excesiva, no se puede construir.',
      'metro.rule6': 'Los trenes <b>arrancan parados y paran en la estación siguiente</b>, así que con estaciones juntas nunca alcanzan la velocidad máxima.',
      'metro.ruleGrow': 'Al confirmar un tramo, <b>crecen los barrios alrededor de las estaciones conectadas.</b> Los solares vacíos se edifican y los edificios suben, y el presupuesto crece con ellos. <b>Hasta dónde suben lo decide el tipo de edificio.</b>',
      'metro.ruleDistrict': 'El <b>casco antiguo</b> tiene callejones estrechos y sinuosos, llenos de fondos de saco y bifurcaciones, así que seguir las calles es difícil. Un <b>barrio planificado</b> es lo contrario. La dificultad cambia la mezcla.',
      'metro.rule7': 'No se construye nada hasta pulsar <b>Construir</b>. Arrastra cuanto quieras.'
    }
  });
})();
