// 이 게임에만 나오는 문구. 게임 이름과 헤더 공통 문구는 ../../shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '역을 놓고 그 사이로 노선을 그어 도시를 키운다. 건물 밑은 비싸고 강 밑은 더 비싸며, 급하게 굽으면 느려진다.',
      'metro.mapLabel': '도시',
      'metro.difficulty': '난이도',
      'metro.easy': '쉬움',
      'metro.normal': '보통',
      'metro.hard': '어려움',
      'metro.mode': '모드',
      'metro.modeRun': '기본',
      'metro.modeBuild': '건설',
      'metro.modeLines': '노선',
      'metro.tool': '도구',
      'metro.toolStation': '역',
      'metro.budget': '예산',
      'metro.newCity': '새 도시',
      'metro.speedStop': '멈춤',
      'metro.speedSlow': '보통',
      'metro.speedFast': '빠름',
      'metro.remove': '철거',
      'metro.removeHint': '철거를 누르면 없어집니다',
      'metro.caught': '이용',
      'metro.waiting': '대기',
      'metro.perMinute': '분당 수입',
      'metro.cost': '건설비',
      'metro.time': '소요시간',
      'metro.length': '길이',
      'metro.curveLimit': '곡선 제한',
      'metro.underRoad': '도로 밑',
      'metro.underEmpty': '빈 땅',
      'metro.underBuilding': '건물 밑',
      'metro.underHill': '산 밑',
      'metro.underWater': '물 밑',
      'metro.confirm': '확정',
      'metro.cancel': '취소',
      'metro.unitMoney': '억',
      'metro.placeHint': '빈 자리를 눌러 역을 놓으세요',
      'metro.ghostHint': '끌어서 자리를 잡고 확정하세요',
      'metro.stationBuilt': '역을 놓았습니다',
      'metro.removed': '역을 철거했습니다',
      'metro.inUse': '노선이 붙은 역은 철거할 수 없습니다',
      'metro.noMoney': '예산이 모자랍니다',
      'metro.needStations': '역을 두 개 이상 놓으세요',
      'metro.bad.outside': '지도 밖입니다',
      'metro.bad.water': '물 위에는 놓을 수 없습니다',
      'metro.bad.hill': '산에는 놓을 수 없습니다',
      'metro.bad.building': '건물 위에는 놓을 수 없습니다',
      'metro.bad.close': '다른 역과 너무 가깝습니다',
      'metro.bad.closed': '순환선은 더 이을 수 없습니다',
      'metro.bad.same': '같은 역입니다',
      'metro.bad.dup': '이미 이 노선에 있는 역입니다',
      'metro.bad.tooShort': '역이 셋은 되어야 순환선이 됩니다',
      'metro.bad.stationTurn': '역에서 너무 급하게 꺾입니다',
      'metro.bad.sharp': '곡선이 너무 급해 지을 수 없습니다',
      'metro.bad.doubled': '왔던 길로 되돌아갑니다',
      'metro.bad.short': '경로가 너무 짧습니다',
      'metro.bad.degenerate': '점이 겹쳐 있습니다',
      'metro.pickStation': '역을 눌러 노선을 잇습니다',
      'metro.pickTarget': '이을 역을 고르세요',
      'metro.newLine': '새 노선',
      'metro.extend': '{n}호선 연장',
      'metro.lineName': '{n}호선',
      'metro.loop': '순환',
      'metro.editHint': '선을 잡아 끌어 경로를 바꿔 보세요',
      'metro.maxMids': '중간점은 세 개까지입니다',
      'metro.built': '구간을 지었습니다',
      'metro.lineHint': '노선을 골라 정차역과 열차를 정합니다',
      'metro.noLines': '아직 노선이 없습니다',
      'metro.line': '노선',
      'metro.dropLine': '노선 삭제',
      'metro.lineGone': '노선을 없앴습니다',
      'metro.pattern': '운행 패턴',
      'metro.stops': '정차역',
      'metro.local': '완행',
      'metro.express': '급행',
      'metro.addExpress': '급행 추가',
      'metro.trains': '열차',
      'metro.trainMinus': '한 대 줄이기',
      'metro.trainPlus': '한 대 늘리기',
      'metro.cycle': '주기',
      'metro.crowd': '혼잡',
      'metro.headway': '배차',
      'metro.draftNote': '아직 만드는 중입니다. 균형(요금·건설비·열차값)은 아직 잡지 않았습니다.',
      'metro.ruleMap': '지도는 화면보다 넓습니다. <b>빈 곳을 끌면</b> 지도가 움직입니다. 고른 역이 화면 밖으로 나가면 가장자리에 점으로 남습니다.',
      'metro.ruleStation': '<b>건설</b> 모드에서 빈 자리를 누르면 임시 역이 생깁니다. <b>끌어서 자리를 잡고</b> 확정을 눌러야 지어집니다. 물·산·건물 위에는 놓을 수 없고, 역을 다시 누르면 철거되고 절반을 돌려받습니다.',
      'metro.rule1': '<b>기본</b> 모드에서 역을 누르면 <b>새 노선</b>이나 <b>연장</b>을 고를 수 있고, 이을 역을 누르면 둘을 잇는 직선이 생깁니다.',
      'metro.rule2': '그 선을 <b>잡아 끌면</b> 그 자리에 중간점이 생기며 경로가 휩니다. 중간점은 <b>세 개</b>까지입니다.',
      'metro.rule3': '중간점을 <b>두 번 두드리면</b> 지워집니다. 끌 때 도로 가까이 가면 도로에 <b>달라붙습니다</b>.',
      'metro.rule4': '땅마다 값이 다릅니다. <b>도로 밑</b>이 가장 싸고, 빈 땅, 건물 밑, 산 밑 순으로 오르며 <b>물 밑</b>이 가장 비쌉니다.',
      'metro.rule5': '급하게 굽으면 그 구간의 <b>제한속도</b>가 걸려 느려집니다. 너무 급하면 아예 지을 수 없습니다.',
      'metro.ruleExtend': '노선을 연장할 때 <b>역에서 꺾이는 각</b>이 허용 범위를 넘으면 잇지 못합니다. 마지막 역을 <b>첫 역으로 이으면 순환선</b>이 되어 한 방향으로만 돕니다.',
      'metro.rule6': '열차는 역에서 <b>서 있다가 출발해 다음 역에서 섭니다.</b> 그래서 역이 가까우면 최고 속도에 닿지 못합니다.',
      'metro.ruleTrains': '<b>노선</b> 모드에서 노선을 고르고 <b>정차역</b>과 <b>열차 수</b>를 정합니다. 열차는 노선 하나를 왕복하고, 순환선이면 한 방향으로 계속 돕니다. <b>급행</b>은 중간 역을 빼 둔 운행 패턴이라 정차 시간도 가감속도 덜 써서 훨씬 빠릅니다.',
      'metro.ruleDemand': '도시에 <b>수요</b>가 생깁니다. 지도의 굽은 선이 "여기서 저기로 가고 싶다"이고, <b>길수록 요금이 비싸고 두꺼울수록 사람이 많습니다.</b> 끝이 찬 동그라미면 그쪽은 이미 역이 가깝다는 뜻입니다.',
      'metro.ruleUse': '승객은 <b>가장 가까운 역이 아니라 목적지까지 가장 싼 길</b>을 고릅니다. 걷는 시간·기다리는 시간·타고 가는 시간을 다 더한 값이 지상 교통보다 나아야 탑니다. 그래서 <b>역을 가까이 놓고, 곧게 뚫고, 열차를 늘리는 것</b>이 모두 같은 숫자를 낮춥니다.',
      'metro.ruleTransfer': '두 노선이 <b>같은 역을 함께 쓰면 갈아탈 수 있습니다.</b> 갈아탈 때마다 번거로움과 기다리는 시간이 붙으므로, 직통으로 가는 운행이 있으면 승객은 그쪽을 고릅니다.',
      'metro.ruleBus': '역이 멀어도 <b>버스로 역까지 갈 수 있습니다.</b> 기다리는 몫이 붙어 사백 미터쯤부터는 걷는 것보다 버스가 낫고, 그보다 더 멀면 그냥 지상으로 갑니다. 수요 끝의 동그라미가 <b>점선이면 버스로만 닿는다</b>는 뜻입니다.',
      'metro.ruleCrowd': '열차에는 <b>실을 수 있는 양이 있습니다.</b> 가장 붐비는 구간이 정원을 넘으면 넘친 사람은 못 타고 지상으로 갑니다. 노선 모드의 <b>혼잡</b>이 100%를 넘으면 그만큼 놓치고 있다는 뜻이고, <b>열차를 늘리거나 급행으로 나누면</b> 내려갑니다.',
      'metro.ruleTrack': '<b>선로는 하나뿐입니다.</b> 열차를 아무리 사도 서로 붙어 갈 수는 없어서, 배차간격이 최소 간격 아래로는 내려가지 않고 그 위로는 다 같이 느려집니다. 그리고 <b>급행은 통과하는 역에서만 완행을 추월</b>할 수 있어, 완행이 잦으면 급행도 제 속도를 못 냅니다.',
      'metro.ruleGrow': '수요를 <b>실어 나른 만큼 도시가 자랍니다.</b> 빈 터에 건물이 들어서고 있던 건물은 높아지며, 자란 동네는 다시 더 큰 수요를 부릅니다. <b>얼마나 높아질지는 건물의 종류가 정합니다.</b>',
      'metro.ruleDistrict': '<b>구시가지</b>는 골목이 좁고 굽은 데다 막다른 길과 삼거리가 많아 길을 따라가기 어렵습니다. <b>계획도시</b>는 그 반대입니다. 난이도는 둘의 배합을 바꿉니다.',
      'metro.rule7': '<b>확정</b>을 누르기 전에는 아무것도 지어지지 않습니다. 마음껏 끌어 보세요.'
    },
    en: {
      'meta.desc': 'Place stations and draw lines between them to grow the city. Tunnelling under buildings costs more, under water more still, and tight curves slow trains down.',
      'metro.mapLabel': 'City',
      'metro.difficulty': 'Difficulty',
      'metro.easy': 'Easy',
      'metro.normal': 'Normal',
      'metro.hard': 'Hard',
      'metro.mode': 'Mode',
      'metro.modeRun': 'Run',
      'metro.modeBuild': 'Build',
      'metro.modeLines': 'Lines',
      'metro.tool': 'Tool',
      'metro.toolStation': 'Station',
      'metro.budget': 'Budget',
      'metro.newCity': 'New city',
      'metro.speedStop': 'Paused',
      'metro.speedSlow': 'Normal',
      'metro.speedFast': 'Fast',
      'metro.remove': 'Remove',
      'metro.removeHint': 'Press Remove to take it down',
      'metro.caught': 'Riding',
      'metro.waiting': 'Waiting',
      'metro.perMinute': 'Per minute',
      'metro.cost': 'Cost',
      'metro.time': 'Travel time',
      'metro.length': 'Length',
      'metro.curveLimit': 'Curve limit',
      'metro.underRoad': 'Under road',
      'metro.underEmpty': 'Open land',
      'metro.underBuilding': 'Under buildings',
      'metro.underHill': 'Under hills',
      'metro.underWater': 'Under water',
      'metro.confirm': 'Build',
      'metro.cancel': 'Cancel',
      'metro.unitMoney': 'B',
      'metro.placeHint': 'Tap an empty spot to place a station',
      'metro.ghostHint': 'Drag it into place, then confirm',
      'metro.stationBuilt': 'Station placed',
      'metro.removed': 'Station removed',
      'metro.inUse': 'A station with a line attached cannot be removed',
      'metro.noMoney': 'Not enough budget',
      'metro.needStations': 'Place at least two stations',
      'metro.bad.outside': 'That is off the map',
      'metro.bad.water': 'Not on water',
      'metro.bad.hill': 'Not on a hill',
      'metro.bad.building': 'Not on a building',
      'metro.bad.close': 'Too close to another station',
      'metro.bad.closed': 'A loop line cannot be extended',
      'metro.bad.same': 'That is the same station',
      'metro.bad.dup': 'That station is already on this line',
      'metro.bad.tooShort': 'A loop needs at least three stations',
      'metro.bad.stationTurn': 'That bends too sharply at the station',
      'metro.bad.sharp': 'That curve is too tight to build',
      'metro.bad.doubled': 'That doubles back on itself',
      'metro.bad.short': 'The route is too short',
      'metro.bad.degenerate': 'Those points overlap',
      'metro.pickStation': 'Tap a station to start or extend a line',
      'metro.pickTarget': 'Pick the station to link',
      'metro.newLine': 'New line',
      'metro.extend': 'Extend line {n}',
      'metro.lineName': 'Line {n}',
      'metro.loop': 'loop',
      'metro.editHint': 'Drag the line to bend the route',
      'metro.maxMids': 'Up to three midpoints',
      'metro.built': 'Segment built',
      'metro.lineHint': 'Pick a line to set its stops and trains',
      'metro.noLines': 'No lines yet',
      'metro.line': 'Line',
      'metro.dropLine': 'Delete line',
      'metro.lineGone': 'Line deleted',
      'metro.pattern': 'Service',
      'metro.stops': 'Stops',
      'metro.local': 'Local',
      'metro.express': 'Express',
      'metro.addExpress': 'Add express',
      'metro.trains': 'Trains',
      'metro.trainMinus': 'One fewer',
      'metro.trainPlus': 'One more',
      'metro.cycle': 'Cycle',
      'metro.crowd': 'Load',
      'metro.headway': 'Headway',
      'metro.draftNote': 'Still being built — the balance of fares, costs and train prices is not settled yet.',
      'metro.ruleMap': 'The map is wider than the screen. <b>Drag an empty spot</b> to move it. A station you picked leaves a dot at the edge once it scrolls off.',
      'metro.ruleStation': 'In <b>Build</b>, tap an empty spot and a station appears as a draft. <b>Drag it into place</b> and press Build to pay for it. Not on water, hills or buildings; tap a station again to remove it and get half back.',
      'metro.rule1': 'In <b>Run</b>, tap a station to choose <b>a new line</b> or <b>extending</b> one, then tap the station to link; a straight line appears between them.',
      'metro.rule2': '<b>Drag that line</b> and a midpoint appears where you grabbed it, bending the route. You get <b>three</b> midpoints.',
      'metro.rule3': '<b>Double-tap</b> a midpoint to remove it. Drag one near a street and it <b>snaps</b> to the street.',
      'metro.rule4': 'Ground costs differ. <b>Under a street</b> is cheapest, then open land, buildings and hills — and <b>under water</b> is the dearest of all.',
      'metro.rule5': 'A tight bend puts a <b>speed limit</b> on that stretch. Too tight and it cannot be built at all.',
      'metro.ruleExtend': 'When extending, the line cannot join if it <b>bends too sharply at the station</b>. Linking the last station back to the first makes a <b>loop line</b>, which runs one way round.',
      'metro.rule6': 'Trains <b>start from a standstill and stop at the next station</b>, so close stations never reach top speed.',
      'metro.ruleTrains': 'In <b>Lines</b>, pick a line and set its <b>stops</b> and <b>how many trains</b>. A train runs the line there and back; on a loop it keeps going one way. An <b>express</b> is a service with middle stops switched off — it skips the dwell and the braking, so it is much faster.',
      'metro.ruleDemand': '<b>Demand</b> appears in the city. Each curved line says "people here want to get there" — <b>the longer it is the higher the fare, the thicker it is the more people</b>. A filled dot means that end already has a station near it.',
      'metro.ruleUse': 'Passengers pick <b>the cheapest way to their destination, not the nearest station</b>. Walking, waiting and riding all add up, and the total has to beat going overground. So <b>putting stations close, cutting straight and adding trains</b> all push the same number down.',
      'metro.ruleTransfer': 'Two lines that <b>share a station let passengers change</b>. Every change adds the hassle and a fresh wait, so if a through service exists passengers take that instead.',
      'metro.ruleBus': 'When a station is far, <b>a bus can take people to it</b>. The wait makes walking better up to about 400m and the bus better beyond that; farther still and they just go overground. A <b>dashed circle</b> at a demand end means only a bus reaches it.',
      'metro.ruleCrowd': 'Trains <b>can only carry so many</b>. Where the busiest stretch goes over capacity, the overflow cannot board and goes overground instead. <b>Load</b> above 100% in Lines means you are turning that much away; <b>more trains, or splitting the flow onto an express</b>, brings it down.',
      'metro.ruleTrack': '<b>There is only one track.</b> However many trains you buy they cannot run nose to tail, so the headway never drops below a floor and past it everything just slows down. And an <b>express can only overtake a local at a station it skips</b>, so frequent locals hold the express back too.',
      'metro.ruleGrow': '<b>The city grows with the people you carry.</b> Empty plots get built on and buildings rise, and a grown neighbourhood then calls up bigger demand. <b>How high they go is set by what kind of building it is.</b>',
      'metro.ruleDistrict': 'The <b>old town</b> has narrow winding lanes full of dead ends and forks, so following the streets is hard. A <b>planned district</b> is the opposite. Difficulty changes the mix.',
      'metro.rule7': 'Nothing is built until you press <b>Build</b>. Drag as much as you like.'
    },
    ja: {
      'meta.desc': '駅を置き、その間に路線を引いて街を育てる。建物の下は高くつき、水の下はもっと高く、急な曲線は速度を落とす。',
      'metro.mapLabel': '街',
      'metro.difficulty': '難易度',
      'metro.easy': 'やさしい',
      'metro.normal': 'ふつう',
      'metro.hard': 'むずかしい',
      'metro.mode': 'モード',
      'metro.modeRun': '基本',
      'metro.modeBuild': '建設',
      'metro.modeLines': '路線',
      'metro.tool': '道具',
      'metro.toolStation': '駅',
      'metro.budget': '予算',
      'metro.newCity': '新しい街',
      'metro.speedStop': '停止',
      'metro.speedSlow': 'ふつう',
      'metro.speedFast': 'はやい',
      'metro.remove': '撤去',
      'metro.removeHint': '撤去を押すと無くなります',
      'metro.caught': '利用',
      'metro.waiting': '待ち',
      'metro.perMinute': '毎分収入',
      'metro.cost': '建設費',
      'metro.time': '所要時間',
      'metro.length': '距離',
      'metro.curveLimit': '曲線制限',
      'metro.underRoad': '道路の下',
      'metro.underEmpty': '空き地',
      'metro.underBuilding': '建物の下',
      'metro.underHill': '山の下',
      'metro.underWater': '水の下',
      'metro.confirm': '確定',
      'metro.cancel': '取消',
      'metro.unitMoney': '億',
      'metro.placeHint': '空いている所を押すと駅ができます',
      'metro.ghostHint': 'ドラッグで位置を決めて確定します',
      'metro.stationBuilt': '駅を置きました',
      'metro.removed': '駅を撤去しました',
      'metro.inUse': '路線がつながった駅は撤去できません',
      'metro.noMoney': '予算が足りません',
      'metro.needStations': '駅を二つ以上置いてください',
      'metro.bad.outside': '地図の外です',
      'metro.bad.water': '水の上には置けません',
      'metro.bad.hill': '山には置けません',
      'metro.bad.building': '建物の上には置けません',
      'metro.bad.close': '他の駅に近すぎます',
      'metro.bad.closed': '環状線はこれ以上つなげません',
      'metro.bad.same': '同じ駅です',
      'metro.bad.dup': 'すでにこの路線にある駅です',
      'metro.bad.tooShort': '環状線には駅が三つ要ります',
      'metro.bad.stationTurn': '駅での曲がりが急すぎます',
      'metro.bad.sharp': '曲線が急すぎて建設できません',
      'metro.bad.doubled': '来た道を戻っています',
      'metro.bad.short': '経路が短すぎます',
      'metro.bad.degenerate': '点が重なっています',
      'metro.pickStation': '駅を押すと路線をつなげます',
      'metro.pickTarget': 'つなぐ駅を選んでください',
      'metro.newLine': '新しい路線',
      'metro.extend': '{n}号線を延長',
      'metro.lineName': '{n}号線',
      'metro.loop': '環状',
      'metro.editHint': '線をつかんで動かすと経路が曲がります',
      'metro.maxMids': '中間点は三つまでです',
      'metro.built': '区間を建設しました',
      'metro.lineHint': '路線を選んで停車駅と列車を決めます',
      'metro.noLines': 'まだ路線がありません',
      'metro.line': '路線',
      'metro.dropLine': '路線を削除',
      'metro.lineGone': '路線を削除しました',
      'metro.pattern': '運行パターン',
      'metro.stops': '停車駅',
      'metro.local': '各駅',
      'metro.express': '急行',
      'metro.addExpress': '急行を追加',
      'metro.trains': '列車',
      'metro.trainMinus': '一台減らす',
      'metro.trainPlus': '一台増やす',
      'metro.cycle': '一周',
      'metro.crowd': '混雑',
      'metro.headway': '間隔',
      'metro.draftNote': 'まだ作っている途中です。運賃・建設費・列車の値段の釣り合いはまだ取れていません。',
      'metro.ruleMap': '地図は画面より広いです。<b>何もない所をドラッグ</b>すると地図が動きます。選んだ駅が画面の外に出ると、端に点が残ります。',
      'metro.ruleStation': '<b>建設</b>モードで空いている所を押すと仮の駅ができます。<b>ドラッグで位置を決めて</b>確定を押すと建ちます。水・山・建物の上には置けず、駅をもう一度押すと撤去され半額が戻ります。',
      'metro.rule1': '<b>基本</b>モードで駅を押すと<b>新しい路線</b>か<b>延長</b>を選べます。つなぐ駅を押すと二つを結ぶ直線が現れます。',
      'metro.rule2': 'その線を<b>つかんで動かす</b>と、その場所に中間点ができて経路が曲がります。中間点は<b>三つ</b>までです。',
      'metro.rule3': '中間点を<b>二回たたく</b>と消えます。動かすとき道路に近づけると道路に<b>吸い付きます</b>。',
      'metro.rule4': '土地ごとに値段が違います。<b>道路の下</b>がいちばん安く、空き地・建物の下・山の下と上がり、<b>水の下</b>がいちばん高くつきます。',
      'metro.rule5': '急に曲がるとその区間に<b>制限速度</b>がかかって遅くなります。急すぎると建設そのものができません。',
      'metro.ruleExtend': '延長するとき<b>駅での曲がり</b>が許容を超えるとつなげません。最後の駅を<b>最初の駅につなぐと環状線</b>になり、一方向に回り続けます。',
      'metro.rule6': '列車は駅で<b>止まった状態から発車し、次の駅で止まります。</b>だから駅が近いと最高速度に届きません。',
      'metro.ruleTrains': '<b>路線</b>モードで路線を選び、<b>停車駅</b>と<b>列車の数</b>を決めます。列車は路線を往復し、環状線なら一方向に回り続けます。<b>急行</b>は途中の駅を外した運行パターンで、停車時間も加減速も減るぶん速くなります。',
      'metro.ruleDemand': '街に<b>需要</b>が生まれます。地図の曲がった線が「ここからあそこへ行きたい」で、<b>長いほど運賃が高く、太いほど人が多い</b>という意味です。端が塗りつぶされていれば、そちらはもう駅が近いということです。',
      'metro.ruleUse': '乗客は<b>いちばん近い駅ではなく、目的地までいちばん安い道</b>を選びます。歩く時間・待つ時間・乗る時間の合計が地上の交通より良くないと乗りません。だから<b>駅を近くに置き、まっすぐ抜き、列車を増やす</b>ことがすべて同じ数字を下げます。',
      'metro.ruleTransfer': '二つの路線が<b>同じ駅を使っていれば乗り換えられます。</b>乗り換えるたびに手間と待ち時間が加わるので、直通の運行があれば乗客はそちらを選びます。',
      'metro.ruleBus': '駅が遠くても<b>バスで駅まで行けます。</b>待ち時間が付くので四百メートルあたりまでは歩くほうが、それより遠ければバスのほうが良く、さらに遠ければ地上のまま行きます。需要の端の丸が<b>点線ならバスでしか届かない</b>という意味です。',
      'metro.ruleCrowd': '列車には<b>積める量があります。</b>いちばん混む区間が定員を超えると、あふれた人は乗れずに地上へ回ります。路線モードの<b>混雑</b>が100%を超えていれば、そのぶん逃していることで、<b>列車を増やすか急行に分ければ</b>下がります。',
      'metro.ruleTrack': '<b>線路は一本だけです。</b>列車をいくら買っても数珠つなぎには走れないので、運転間隔は最小間隔より下がらず、それを超えると全部いっしょに遅くなります。そして<b>急行は通過する駅でしか各駅を追い越せない</b>ので、各駅が多いと急行も速度を出せません。',
      'metro.ruleGrow': '<b>運んだぶんだけ街が育ちます。</b>空き地に建物が建ち、建っていた建物は高くなり、育った街はさらに大きな需要を呼びます。<b>どこまで高くなるかは建物の種類が決めます。</b>',
      'metro.ruleDistrict': '<b>旧市街</b>は路地が狭く曲がっていて行き止まりや三叉路が多く、道に沿って進むのが難しいです。<b>計画都市</b>はその逆です。難易度はその配分を変えます。',
      'metro.rule7': '<b>確定</b>を押すまでは何も建ちません。思いきり動かしてみてください。'
    },
    'zh-CN': {
      'meta.desc': '设站并在站间铺线，把城市养大。建筑下造价高，水下更高，急弯会让列车变慢。',
      'metro.mapLabel': '城市',
      'metro.difficulty': '难度',
      'metro.easy': '简单',
      'metro.normal': '普通',
      'metro.hard': '困难',
      'metro.mode': '模式',
      'metro.modeRun': '基本',
      'metro.modeBuild': '建设',
      'metro.modeLines': '线路',
      'metro.tool': '工具',
      'metro.toolStation': '车站',
      'metro.budget': '预算',
      'metro.newCity': '新城市',
      'metro.speedStop': '暂停',
      'metro.speedSlow': '正常',
      'metro.speedFast': '快进',
      'metro.remove': '拆除',
      'metro.removeHint': '按拆除即可移除',
      'metro.caught': '乘车',
      'metro.waiting': '等待',
      'metro.perMinute': '每分收入',
      'metro.cost': '造价',
      'metro.time': '运行时间',
      'metro.length': '长度',
      'metro.curveLimit': '弯道限速',
      'metro.underRoad': '道路下',
      'metro.underEmpty': '空地',
      'metro.underBuilding': '建筑下',
      'metro.underHill': '山下',
      'metro.underWater': '水下',
      'metro.confirm': '确定',
      'metro.cancel': '取消',
      'metro.unitMoney': '亿',
      'metro.placeHint': '点空地即可设站',
      'metro.ghostHint': '拖动调整位置后确定',
      'metro.stationBuilt': '已设站',
      'metro.removed': '已拆除车站',
      'metro.inUse': '已接线路的车站无法拆除',
      'metro.noMoney': '预算不足',
      'metro.needStations': '请先设两座以上车站',
      'metro.bad.outside': '超出地图',
      'metro.bad.water': '水上不能设站',
      'metro.bad.hill': '山上不能设站',
      'metro.bad.building': '建筑上不能设站',
      'metro.bad.close': '离其他车站太近',
      'metro.bad.closed': '环线无法再延长',
      'metro.bad.same': '是同一座车站',
      'metro.bad.dup': '该站已在这条线路上',
      'metro.bad.tooShort': '环线至少需要三座车站',
      'metro.bad.stationTurn': '在车站转弯太急',
      'metro.bad.sharp': '弯道太急，无法施工',
      'metro.bad.doubled': '原路折返了',
      'metro.bad.short': '线路太短',
      'metro.bad.degenerate': '点重合了',
      'metro.pickStation': '点车站来连接线路',
      'metro.pickTarget': '再选要连接的车站',
      'metro.newLine': '新线路',
      'metro.extend': '延长{n}号线',
      'metro.lineName': '{n}号线',
      'metro.loop': '环线',
      'metro.editHint': '拖动线路可以让它弯曲',
      'metro.maxMids': '中间点最多三个',
      'metro.built': '区间已建成',
      'metro.lineHint': '选线路来设停车站和列车',
      'metro.noLines': '还没有线路',
      'metro.line': '线路',
      'metro.dropLine': '删除线路',
      'metro.lineGone': '已删除线路',
      'metro.pattern': '运行模式',
      'metro.stops': '停车站',
      'metro.local': '普通',
      'metro.express': '快车',
      'metro.addExpress': '加快车',
      'metro.trains': '列车',
      'metro.trainMinus': '减少一列',
      'metro.trainPlus': '增加一列',
      'metro.cycle': '周期',
      'metro.crowd': '拥挤',
      'metro.headway': '间隔',
      'metro.draftNote': '还在制作中。票价、造价和列车价格的平衡还没有调好。',
      'metro.ruleMap': '地图比屏幕更大。<b>拖动空白处</b>即可移动地图。已选的车站移出画面后，会在边缘留下一个点。',
      'metro.ruleStation': '在<b>建设</b>模式下点空地会出现临时车站。<b>拖动调整位置</b>后按确定才会建成。水面、山地和建筑上不能建；再点一次车站即可拆除，退还一半。',
      'metro.rule1': '在<b>基本</b>模式下点车站可以选择<b>新线路</b>或<b>延长</b>，再点要连接的车站，就会出现连接它们的直线。',
      'metro.rule2': '<b>拖动这条线</b>，会在拖的位置生成中间点，线路随之弯曲。中间点最多<b>三个</b>。',
      'metro.rule3': '<b>连点两下</b>中间点即可删除。拖动时靠近道路会<b>自动吸附</b>到道路上。',
      'metro.rule4': '地下造价各不相同。<b>道路下</b>最便宜，其次是空地、建筑下、山下，<b>水下</b>最贵。',
      'metro.rule5': '弯得太急，该区段会有<b>限速</b>而变慢。过急则根本无法施工。',
      'metro.ruleExtend': '延长时如果<b>在车站转弯太急</b>就接不上。把最后一站接回第一站就成了<b>环线</b>，只朝一个方向绕行。',
      'metro.rule6': '列车在车站<b>从静止起步，到下一站停车</b>，所以车站太近就到不了最高速度。',
      'metro.ruleTrains': '在<b>线路</b>模式下选一条线路，设定<b>停车站</b>和<b>列车数量</b>。列车在线路上往返，环线则一直朝一个方向绕。<b>快车</b>是关掉中间停站的运行模式，省下停站时间和加减速，所以快得多。',
      'metro.ruleDemand': '城市里会出现<b>需求</b>。地图上的弧线表示"想从这里去那里"，<b>越长票价越高，越粗人越多</b>。端点是实心的，表示那一头已经有车站在附近。',
      'metro.ruleUse': '乘客选的是<b>到目的地最省的路，而不是最近的车站</b>。步行、等待和乘车的时间加起来要比地面交通更划算才会乘坐。所以<b>把站设近、线路挖直、增加列车</b>都是在压低同一个数字。',
      'metro.ruleTransfer': '两条线路<b>共用同一座车站就可以换乘</b>。每换乘一次都会加上麻烦和重新等待的时间，所以有直达运行时乘客会选直达。',
      'metro.ruleBus': '车站远也可以<b>坐公交到车站</b>。因为要等车，四百米左右以内走路更好，再远就是公交更好；更远的话干脆走地面。需求端点是<b>虚线就表示只有公交能到</b>。',
      'metro.ruleCrowd': '列车<b>能装的人是有限的</b>。最挤的区间超过定员时，多出来的人上不了车，只能走地面。线路模式里的<b>拥挤</b>超过100%就是在漏掉那么多人，<b>增加列车或用快车分流</b>就会降下来。',
      'metro.ruleTrack': '<b>轨道只有一条。</b>再买列车也不能首尾相接，所以发车间隔降不到最小间隔以下，超过之后大家一起变慢。而且<b>快车只能在它通过的车站超越普通车</b>，普通车太密的话快车也快不起来。',
      'metro.ruleGrow': '<b>运了多少人，城市就长多少。</b>空地上会盖起房子，原有的房子会变高，长大的街区又会带来更大的需求。<b>能长多高由建筑的类型决定。</b>',
      'metro.ruleDistrict': '<b>老城区</b>的巷子又窄又弯，死胡同和三岔路很多，顺着路走很难。<b>新城区</b>正相反。难度改变两者的比例。',
      'metro.rule7': '按下<b>确定</b>之前什么都不会建成，尽管拖动试试。'
    },
    'zh-TW': {
      'meta.desc': '設站並在站間鋪線，把城市養大。建築下造價高，水下更高，急彎會讓列車變慢。',
      'metro.mapLabel': '城市',
      'metro.difficulty': '難度',
      'metro.easy': '簡單',
      'metro.normal': '普通',
      'metro.hard': '困難',
      'metro.mode': '模式',
      'metro.modeRun': '基本',
      'metro.modeBuild': '建設',
      'metro.modeLines': '路線',
      'metro.tool': '工具',
      'metro.toolStation': '車站',
      'metro.budget': '預算',
      'metro.newCity': '新城市',
      'metro.speedStop': '暫停',
      'metro.speedSlow': '正常',
      'metro.speedFast': '快進',
      'metro.remove': '拆除',
      'metro.removeHint': '按拆除即可移除',
      'metro.caught': '乘車',
      'metro.waiting': '等待',
      'metro.perMinute': '每分收入',
      'metro.cost': '造價',
      'metro.time': '運行時間',
      'metro.length': '長度',
      'metro.curveLimit': '彎道限速',
      'metro.underRoad': '道路下',
      'metro.underEmpty': '空地',
      'metro.underBuilding': '建築下',
      'metro.underHill': '山下',
      'metro.underWater': '水下',
      'metro.confirm': '確定',
      'metro.cancel': '取消',
      'metro.unitMoney': '億',
      'metro.placeHint': '點空地即可設站',
      'metro.ghostHint': '拖動調整位置後確定',
      'metro.stationBuilt': '已設站',
      'metro.removed': '已拆除車站',
      'metro.inUse': '已接線路的車站無法拆除',
      'metro.noMoney': '預算不足',
      'metro.needStations': '請先設兩座以上車站',
      'metro.bad.outside': '超出地圖',
      'metro.bad.water': '水上不能設站',
      'metro.bad.hill': '山上不能設站',
      'metro.bad.building': '建築上不能設站',
      'metro.bad.close': '離其他車站太近',
      'metro.bad.closed': '環線無法再延長',
      'metro.bad.same': '是同一座車站',
      'metro.bad.dup': '該站已在這條線路上',
      'metro.bad.tooShort': '環線至少需要三座車站',
      'metro.bad.stationTurn': '在車站轉彎太急',
      'metro.bad.sharp': '彎道太急，無法施工',
      'metro.bad.doubled': '原路折返了',
      'metro.bad.short': '線路太短',
      'metro.bad.degenerate': '點重合了',
      'metro.pickStation': '點車站來連接線路',
      'metro.pickTarget': '再選要連接的車站',
      'metro.newLine': '新線路',
      'metro.extend': '延長{n}號線',
      'metro.lineName': '{n}號線',
      'metro.loop': '環線',
      'metro.editHint': '拖動線路可以讓它彎曲',
      'metro.maxMids': '中間點最多三個',
      'metro.built': '區間已建成',
      'metro.lineHint': '選線路來設停車站和列車',
      'metro.noLines': '還沒有線路',
      'metro.line': '路線',
      'metro.dropLine': '刪除線路',
      'metro.lineGone': '已刪除線路',
      'metro.pattern': '運行模式',
      'metro.stops': '停車站',
      'metro.local': '普通',
      'metro.express': '快車',
      'metro.addExpress': '加快車',
      'metro.trains': '列車',
      'metro.trainMinus': '減少一列',
      'metro.trainPlus': '增加一列',
      'metro.cycle': '週期',
      'metro.crowd': '擁擠',
      'metro.headway': '間隔',
      'metro.draftNote': '還在製作中。票價、造價和列車價格的平衡還沒有調好。',
      'metro.ruleMap': '地圖比螢幕更大。<b>拖動空白處</b>即可移動地圖。已選的車站移出畫面後，會在邊緣留下一個點。',
      'metro.ruleStation': '在<b>建設</b>模式下點空地會出現臨時車站。<b>拖動調整位置</b>後按確定才會建成。水面、山地和建築上不能建；再點一次車站即可拆除，退還一半。',
      'metro.rule1': '在<b>基本</b>模式下點車站可以選擇<b>新線路</b>或<b>延長</b>，再點要連接的車站，就會出現連接它們的直線。',
      'metro.rule2': '<b>拖動這條線</b>，會在拖的位置生成中間點，線路隨之彎曲。中間點最多<b>三個</b>。',
      'metro.rule3': '<b>連點兩下</b>中間點即可刪除。拖動時靠近道路會<b>自動吸附</b>到道路上。',
      'metro.rule4': '地下造價各不相同。<b>道路下</b>最便宜，其次是空地、建築下、山下，<b>水下</b>最貴。',
      'metro.rule5': '彎得太急，該區段會有<b>限速</b>而變慢。過急則根本無法施工。',
      'metro.ruleExtend': '延長時如果<b>在車站轉彎太急</b>就接不上。把最後一站接回第一站就成了<b>環線</b>，只朝一個方向繞行。',
      'metro.rule6': '列車在車站<b>從靜止起步，到下一站停車</b>，所以車站太近就到不了最高速度。',
      'metro.ruleTrains': '在<b>線路</b>模式下選一條線路，設定<b>停車站</b>和<b>列車數量</b>。列車在線路上往返，環線則一直朝一個方向繞。<b>快車</b>是關掉中間停站的運行模式，省下停站時間和加減速，所以快得多。',
      'metro.ruleDemand': '城市裡會出現<b>需求</b>。地圖上的弧線表示「想從這裡去那裡」，<b>越長票價越高，越粗人越多</b>。端點是實心的，表示那一頭已經有車站在附近。',
      'metro.ruleUse': '乘客選的是<b>到目的地最省的路，而不是最近的車站</b>。步行、等待和乘車的時間加起來要比地面交通更划算才會乘坐。所以<b>把站設近、線路挖直、增加列車</b>都是在壓低同一個數字。',
      'metro.ruleTransfer': '兩條線路<b>共用同一座車站就可以換乘</b>。每換乘一次都會加上麻煩和重新等待的時間，所以有直達運行時乘客會選直達。',
      'metro.ruleBus': '車站遠也可以<b>坐公車到車站</b>。因為要等車，四百公尺左右以內走路更好，再遠就是公車更好；更遠的話乾脆走地面。需求端點是<b>虛線就表示只有公車能到</b>。',
      'metro.ruleCrowd': '列車<b>能裝的人是有限的</b>。最擠的區間超過定員時，多出來的人上不了車，只能走地面。線路模式裡的<b>擁擠</b>超過100%就是在漏掉那麼多人，<b>增加列車或用快車分流</b>就會降下來。',
      'metro.ruleTrack': '<b>軌道只有一條。</b>再買列車也不能首尾相接，所以發車間隔降不到最小間隔以下，超過之後大家一起變慢。而且<b>快車只能在它通過的車站超越普通車</b>，普通車太密的話快車也快不起來。',
      'metro.ruleGrow': '<b>運了多少人，城市就長多少。</b>空地上會蓋起房子，原有的房子會變高，長大的街區又會帶來更大的需求。<b>能長多高由建築的類型決定。</b>',
      'metro.ruleDistrict': '<b>老城區</b>的巷子又窄又彎，死胡同和三岔路很多，順著路走很難。<b>新城區</b>正相反。難度改變兩者的比例。',
      'metro.rule7': '按下<b>確定</b>之前什麼都不會建成，儘管拖動看看。'
    },
    es: {
      'meta.desc': 'Pon estaciones y traza líneas entre ellas para hacer crecer la ciudad. Excavar bajo edificios cuesta más, bajo el agua aún más, y las curvas cerradas frenan los trenes.',
      'metro.mapLabel': 'Ciudad',
      'metro.difficulty': 'Dificultad',
      'metro.easy': 'Fácil',
      'metro.normal': 'Normal',
      'metro.hard': 'Difícil',
      'metro.mode': 'Modo',
      'metro.modeRun': 'Básico',
      'metro.modeBuild': 'Construir',
      'metro.modeLines': 'Líneas',
      'metro.tool': 'Herramienta',
      'metro.toolStation': 'Estación',
      'metro.budget': 'Presupuesto',
      'metro.newCity': 'Nueva ciudad',
      'metro.speedStop': 'Pausa',
      'metro.speedSlow': 'Normal',
      'metro.speedFast': 'Rápido',
      'metro.remove': 'Retirar',
      'metro.removeHint': 'Pulsa Retirar para quitarla',
      'metro.caught': 'Viajan',
      'metro.waiting': 'Esperan',
      'metro.perMinute': 'Por minuto',
      'metro.cost': 'Coste',
      'metro.time': 'Tiempo',
      'metro.length': 'Longitud',
      'metro.curveLimit': 'Límite en curva',
      'metro.underRoad': 'Bajo la calle',
      'metro.underEmpty': 'Suelo libre',
      'metro.underBuilding': 'Bajo edificios',
      'metro.underHill': 'Bajo monte',
      'metro.underWater': 'Bajo el agua',
      'metro.confirm': 'Construir',
      'metro.cancel': 'Cancelar',
      'metro.unitMoney': 'B',
      'metro.placeHint': 'Toca un punto libre para poner una estación',
      'metro.ghostHint': 'Arrástrala a su sitio y confirma',
      'metro.stationBuilt': 'Estación construida',
      'metro.removed': 'Estación retirada',
      'metro.inUse': 'No se puede retirar una estación con línea conectada',
      'metro.noMoney': 'Presupuesto insuficiente',
      'metro.needStations': 'Pon al menos dos estaciones',
      'metro.bad.outside': 'Está fuera del mapa',
      'metro.bad.water': 'Sobre el agua no',
      'metro.bad.hill': 'Sobre la montaña no',
      'metro.bad.building': 'Sobre un edificio no',
      'metro.bad.close': 'Demasiado cerca de otra estación',
      'metro.bad.closed': 'Una línea circular no se puede ampliar',
      'metro.bad.same': 'Es la misma estación',
      'metro.bad.dup': 'Esa estación ya está en la línea',
      'metro.bad.tooShort': 'Un circular necesita tres estaciones',
      'metro.bad.stationTurn': 'Gira demasiado en la estación',
      'metro.bad.sharp': 'Esa curva es demasiado cerrada para construirla',
      'metro.bad.doubled': 'Vuelve sobre sí misma',
      'metro.bad.short': 'El trazado es demasiado corto',
      'metro.bad.degenerate': 'Esos puntos coinciden',
      'metro.pickStation': 'Toca una estación para enlazar',
      'metro.pickTarget': 'Elige la estación a enlazar',
      'metro.newLine': 'Línea nueva',
      'metro.extend': 'Ampliar línea {n}',
      'metro.lineName': 'Línea {n}',
      'metro.loop': 'circular',
      'metro.editHint': 'Arrastra la línea para curvar el trazado',
      'metro.maxMids': 'Hasta tres puntos intermedios',
      'metro.built': 'Tramo construido',
      'metro.lineHint': 'Elige una línea para sus paradas y trenes',
      'metro.noLines': 'Aún no hay líneas',
      'metro.line': 'Línea',
      'metro.dropLine': 'Borrar línea',
      'metro.lineGone': 'Línea borrada',
      'metro.pattern': 'Servicio',
      'metro.stops': 'Paradas',
      'metro.local': 'Local',
      'metro.express': 'Exprés',
      'metro.addExpress': 'Añadir exprés',
      'metro.trains': 'Trenes',
      'metro.trainMinus': 'Uno menos',
      'metro.trainPlus': 'Uno más',
      'metro.cycle': 'Ciclo',
      'metro.crowd': 'Carga',
      'metro.headway': 'Intervalo',
      'metro.draftNote': 'Aún en construcción: el equilibrio de tarifas, costes y precio de los trenes no está ajustado.',
      'metro.ruleMap': 'El mapa es más ancho que la pantalla. <b>Arrastra una zona vacía</b> para moverlo. La estación elegida deja un punto en el borde al salir de la vista.',
      'metro.ruleStation': 'En <b>Construir</b>, toca un punto libre y aparece una estación provisional. <b>Arrástrala a su sitio</b> y pulsa Construir para pagarla. No sobre agua, montaña ni edificios; tócala de nuevo para retirarla y recuperar la mitad.',
      'metro.rule1': 'En <b>Básico</b>, toca una estación para elegir <b>línea nueva</b> o <b>ampliar</b>, y luego la estación a enlazar: aparecerá una recta entre ambas.',
      'metro.rule2': '<b>Arrastra esa línea</b> y surgirá un punto intermedio donde la agarraste, curvando el trazado. Tienes <b>tres</b> puntos.',
      'metro.rule3': '<b>Toca dos veces</b> un punto para borrarlo. Al arrastrarlo cerca de una calle, se <b>pega</b> a ella.',
      'metro.rule4': 'Cada terreno cuesta distinto. <b>Bajo la calle</b> es lo más barato, luego suelo libre, edificios y monte, y <b>bajo el agua</b> es lo más caro.',
      'metro.rule5': 'Una curva cerrada impone un <b>límite de velocidad</b> en ese tramo. Si es excesiva, no se puede construir.',
      'metro.ruleExtend': 'Al ampliar, no se puede unir si <b>gira demasiado en la estación</b>. Unir la última estación con la primera crea una <b>línea circular</b>, que gira en un solo sentido.',
      'metro.rule6': 'Los trenes <b>arrancan parados y paran en la estación siguiente</b>, así que con estaciones juntas nunca alcanzan la velocidad máxima.',
      'metro.ruleTrains': 'En <b>Líneas</b>, elige una línea y ajusta sus <b>paradas</b> y <b>cuántos trenes</b>. Un tren la recorre de ida y vuelta; en una circular sigue en un solo sentido. Un <b>exprés</b> es un servicio con las paradas intermedias desactivadas: se ahorra la parada y los frenazos, así que es mucho más rápido.',
      'metro.ruleDemand': 'Aparece <b>demanda</b> en la ciudad. Cada arco dice «aquí quieren ir allí»: <b>cuanto más largo, mayor la tarifa; cuanto más grueso, más gente</b>. Un punto relleno significa que ese extremo ya tiene una estación cerca.',
      'metro.ruleUse': 'Los pasajeros eligen <b>el camino más barato hasta su destino, no la estación más cercana</b>. Caminar, esperar y viajar suman, y el total debe ganarle al transporte de superficie. Por eso <b>acercar estaciones, excavar recto y añadir trenes</b> bajan todos el mismo número.',
      'metro.ruleTransfer': 'Dos líneas que <b>comparten estación permiten transbordo</b>. Cada cambio añade la molestia y una espera nueva, así que si hay un servicio directo los pasajeros lo prefieren.',
      'metro.ruleBus': 'Si la estación queda lejos, <b>un autobús puede llevar a la gente hasta ella</b>. La espera hace que caminar gane hasta unos 400 m y el autobús más allá; aún más lejos van por superficie. Un <b>círculo punteado</b> en un extremo indica que solo llega el autobús.',
      'metro.ruleCrowd': 'Los trenes <b>solo pueden llevar a tanta gente</b>. Donde el tramo más cargado supera la capacidad, el excedente no puede subir y se va por superficie. Una <b>carga</b> por encima del 100% en Líneas significa que estás dejando fuera a esa gente; <b>más trenes, o repartir el flujo en un exprés</b>, la baja.',
      'metro.ruleTrack': '<b>Solo hay una vía.</b> Por muchos trenes que compres no pueden ir pegados, así que el intervalo nunca baja de un mínimo y pasado ese punto todo se ralentiza. Y un <b>exprés solo adelanta al local en las estaciones que se salta</b>, así que muchos locales también frenan al exprés.',
      'metro.ruleGrow': '<b>La ciudad crece con la gente que transportas.</b> Los solares se edifican y los edificios suben, y un barrio crecido pide después más demanda. <b>Hasta dónde suben lo decide el tipo de edificio.</b>',
      'metro.ruleDistrict': 'El <b>casco antiguo</b> tiene callejones estrechos y sinuosos, llenos de fondos de saco y bifurcaciones, así que seguir las calles es difícil. Un <b>barrio planificado</b> es lo contrario. La dificultad cambia la mezcla.',
      'metro.rule7': 'No se construye nada hasta pulsar <b>Construir</b>. Arrastra cuanto quieras.'
    }
  });
})();
