// 이 게임에만 나오는 문구. 기록 안내와 도구 이름은 shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '해와 달을 반씩, 셋 연달아 오지 않게 놓는 퍼즐',
      'tango.autoCheck': '자동 체크',
      'tango.note': '{size}×{size}, 놓인 칸 {given}개와 표 {links}개.',
      'tango.locked': '처음부터 놓여 있는 칸은 바꿀 수 없습니다.',
      'tango.hintCleared': '어긋난 칸 {count}개를 걷어 냈습니다.',
      'tango.hintPlaced': '지금 알아낼 수 있는 칸을 채웠습니다.',
      'tango.why.scan.col': '이 열에 들어갈 수 있는 배치를 모두 따져 보면, 채운 칸은 어느 배치에서나 같습니다.',
      'tango.why.scan.row': '이 행에 들어갈 수 있는 배치를 모두 따져 보면, 채운 칸은 어느 배치에서나 같습니다.',
      'tango.why.half.col': '이 열은 한쪽이 벌써 절반을 채웠으니 남은 칸은 모두 반대입니다.',
      'tango.why.half.row': '이 행은 한쪽이 벌써 절반을 채웠으니 남은 칸은 모두 반대입니다.',
      'tango.why.gap.col': '이 열에서 같은 것 둘 사이에 낀 칸은 반대입니다. 셋 연달아 올 수 없습니다.',
      'tango.why.gap.row': '이 행에서 같은 것 둘 사이에 낀 칸은 반대입니다. 셋 연달아 올 수 없습니다.',
      'tango.why.pair.col': '이 열에 같은 것 둘이 붙어 있습니다. 셋 연달아 올 수 없으니 그 옆은 반대입니다.',
      'tango.why.pair.row': '이 행에 같은 것 둘이 붙어 있습니다. 셋 연달아 올 수 없으니 그 옆은 반대입니다.',
      'tango.why.diff': '×로 묶인 두 칸은 다릅니다. 한쪽이 놓여 있으니 다른 쪽은 반대입니다.',
      'tango.why.same': '=로 묶인 두 칸은 같습니다. 한쪽이 놓여 있으니 다른 쪽도 같은 것입니다.',
      'tango.rule1': '모든 칸을 <b>해</b>나 <b>달</b>로 채웁니다.',
      'tango.rule2': '<b>줄마다 해와 달이 반씩</b>입니다. 6×6이면 한 줄에 해 셋, 달 셋입니다. 행도 열도 마찬가지입니다.',
      'tango.rule3': '<b>같은 것이 셋 연달아 올 수 없습니다.</b> 가로로도 세로로도 둘까지입니다.',
      'tango.rule4': '두 칸 사이의 <b>=</b>는 둘이 <b>같다</b>는 뜻이고, <b>×</b>는 둘이 <b>다르다</b>는 뜻입니다.',
      'tango.rule5': '처음부터 놓여 있는 칸은 <b>바뀌지 않습니다</b>.',
      'tango.rule6': '칸을 누르면 <b>빈칸 → 해 → 달 → 빈칸</b> 순서로 바뀝니다.',
      'tango.rule7': '<b>자동 체크</b>를 켜 두면 규칙을 어긴 칸이 곧바로 붉게 표시됩니다. 스스로 찾고 싶으면 꺼 두세요.',
      'tango.rule8': '<b>이 게임의 모든 판은 답이 하나뿐이고, 찍지 않고 논리만으로 풀립니다.</b> 마지막에 두 자리를 놓고 고민하게 되는 판은 나오지 않습니다.',
      'tango.rule9': '<b>힌트</b>는 어긋난 칸이 있으면 먼저 걷어 내고, 없으면 지금 판에서 규칙 하나로 알아낼 수 있는 칸을 채우며 그 까닭을 알려 줍니다. 힌트를 쓴 판은 최고 기록으로 남기지 않습니다.',
      'tango.rule10': '키보드: <b>방향키</b>로 칸을 옮기고, <b>스페이스</b>로 바꾸고, <b>Backspace</b>로 되돌립니다.'
    },
    en: {
      'meta.desc': 'Fill the grid with half suns and half moons, never three alike in a row',
      'tango.autoCheck': 'Auto-check',
      'tango.note': '{size}×{size}, {given} given cells and {links} signs.',
      'tango.locked': 'Cells given at the start cannot be changed.',
      'tango.hintCleared': 'Removed {count} wrong cells.',
      'tango.hintPlaced': 'Filled a cell logic can settle now.',
      'tango.why.scan.col': 'Try every arrangement that fits this column: the filled cells come out the same in all of them.',
      'tango.why.scan.row': 'Try every arrangement that fits this row: the filled cells come out the same in all of them.',
      'tango.why.half.col': 'One symbol already fills half of this column, so every remaining cell is the other.',
      'tango.why.half.row': 'One symbol already fills half of this row, so every remaining cell is the other.',
      'tango.why.gap.col': 'In this column, a cell between two alike must be the opposite, or there would be three in a row.',
      'tango.why.gap.row': 'In this row, a cell between two alike must be the opposite, or there would be three in a row.',
      'tango.why.pair.col': 'Two alike sit one above the other in this column. Three in a row is not allowed, so the cell next to them is the opposite.',
      'tango.why.pair.row': 'Two alike sit side by side in this row. Three in a row is not allowed, so the cell next to them is the opposite.',
      'tango.why.diff': 'Cells joined by × are different. One is filled, so the other is the opposite.',
      'tango.why.same': 'Cells joined by = are the same. One is filled, so the other matches it.',
      'tango.rule1': 'Fill every cell with a <b>sun</b> or a <b>moon</b>.',
      'tango.rule2': '<b>Every line holds half of each.</b> On a 6×6 that is three suns and three moons per line — rows and columns alike.',
      'tango.rule3': '<b>No three alike in a row.</b> Two in a row is the limit, horizontally and vertically.',
      'tango.rule4': 'An <b>=</b> between two cells means they are <b>the same</b>; an <b>×</b> means they are <b>different</b>.',
      'tango.rule5': 'Cells that are filled in from the start <b>never change</b>.',
      'tango.rule6': 'Tapping a cell cycles <b>empty → sun → moon → empty</b>.',
      'tango.rule7': 'With <b>Auto-check</b> on, any cell that breaks a rule turns red at once. Turn it off to find them yourself.',
      'tango.rule8': '<b>Every board here has exactly one solution and is solvable by logic alone.</b> You will never be left choosing between two spots at the end.',
      'tango.rule9': 'A <b>Hint</b> first removes any wrong cells; otherwise it fills what a single rule settles on the current board and tells you why. Boards solved with hints are not recorded.',
      'tango.rule10': 'Keyboard: <b>arrow keys</b> to move, <b>Space</b> to cycle, <b>Backspace</b> to undo.'
    },
    ja: {
      'meta.desc': '太陽と月を半分ずつ、同じものが三つ続かないように置くパズル',
      'tango.autoCheck': '自動チェック',
      'tango.note': '{size}×{size}、最初から置かれたマス {given} 個と記号 {links} 個。',
      'tango.locked': '最初から置かれているマスは変えられません。',
      'tango.hintCleared': 'ずれたマス{count}個を取り除きました。',
      'tango.hintPlaced': 'いま確定できるマスを埋めました。',
      'tango.why.scan.col': 'この列に入りうる並びをすべて試すと、埋めたマスはどの並びでも同じになります。',
      'tango.why.scan.row': 'この行に入りうる並びをすべて試すと、埋めたマスはどの並びでも同じになります。',
      'tango.why.half.col': 'この列は片方がもう半分に達しているので、残りのマスはすべて反対です。',
      'tango.why.half.row': 'この行は片方がもう半分に達しているので、残りのマスはすべて反対です。',
      'tango.why.gap.col': 'この列で同じもの二つに挟まれたマスは反対です。三つ続けられません。',
      'tango.why.gap.row': 'この行で同じもの二つに挟まれたマスは反対です。三つ続けられません。',
      'tango.why.pair.col': 'この列に同じものが二つ並んでいます。三つ続けられないので、その隣は反対です。',
      'tango.why.pair.row': 'この行に同じものが二つ並んでいます。三つ続けられないので、その隣は反対です。',
      'tango.why.diff': '×で結ばれた二マスは違います。片方が置かれているので、もう片方は反対です。',
      'tango.why.same': '=で結ばれた二マスは同じです。片方が置かれているので、もう片方も同じものです。',
      'tango.rule1': 'すべてのマスを<b>太陽</b>か<b>月</b>で埋めます。',
      'tango.rule2': '<b>どの列も太陽と月が半分ずつ</b>です。6×6なら一列に太陽三つ、月三つ。行も列も同じです。',
      'tango.rule3': '<b>同じものが三つ続いてはいけません。</b>縦も横も二つまでです。',
      'tango.rule4': 'マスの間の<b>=</b>は二つが<b>同じ</b>、<b>×</b>は二つが<b>違う</b>という意味です。',
      'tango.rule5': '最初から置かれているマスは<b>変わりません</b>。',
      'tango.rule6': 'マスを押すと<b>空 → 太陽 → 月 → 空</b>の順に変わります。',
      'tango.rule7': '<b>自動チェック</b>を入れておくと、ルール違反のマスがすぐ赤くなります。自分で探したいときは切ってください。',
      'tango.rule8': '<b>この盤はすべて答えがひとつだけで、当てずっぽう抜きに論理だけで解けます。</b>最後に二択で悩む盤は出ません。',
      'tango.rule9': '<b>ヒント</b>はずれたマスがあればまず取り除き、なければいまの盤からルールひとつで確定できるマスを埋めて、その理由を知らせます。ヒントを使った盤はベスト記録に残しません。',
      'tango.rule10': 'キーボード：<b>矢印キー</b>で移動、<b>スペース</b>で切替、<b>Backspace</b>で戻します。'
    },
    'zh-CN': {
      'meta.desc': '把太阳和月亮各放一半，不让同样的连成三个',
      'tango.autoCheck': '自动检查',
      'tango.note': '{size}×{size}，已给出 {given} 格，记号 {links} 个。',
      'tango.locked': '一开始就给出的格子不能改。',
      'tango.hintCleared': '清掉了 {count} 个放错的格子。',
      'tango.hintPlaced': '填好了现在能推出的一格。',
      'tango.why.scan.col': '把这一列能放的排法都试一遍，填好的格子在每种排法里都一样。',
      'tango.why.scan.row': '把这一行能放的排法都试一遍，填好的格子在每种排法里都一样。',
      'tango.why.half.col': '这一列有一种已经占满一半，剩下的格子都是另一种。',
      'tango.why.half.row': '这一行有一种已经占满一半，剩下的格子都是另一种。',
      'tango.why.gap.col': '这一列里夹在两个同样的中间的格子是相反的，否则会连成三个。',
      'tango.why.gap.row': '这一行里夹在两个同样的中间的格子是相反的，否则会连成三个。',
      'tango.why.pair.col': '这一列有两个同样的挨在一起。不能连成三个，所以旁边那格是相反的。',
      'tango.why.pair.row': '这一行有两个同样的挨在一起。不能连成三个，所以旁边那格是相反的。',
      'tango.why.diff': '用 × 连着的两格不同。一格已经填好，另一格就是相反的。',
      'tango.why.same': '用 = 连着的两格相同。一格已经填好，另一格也一样。',
      'tango.rule1': '把每一格填上<b>太阳</b>或<b>月亮</b>。',
      'tango.rule2': '<b>每行每列各占一半。</b>6×6 就是每行三个太阳、三个月亮，列也一样。',
      'tango.rule3': '<b>同样的不能连成三个。</b>横竖都最多两个。',
      'tango.rule4': '两格之间的 <b>=</b> 表示两格<b>相同</b>，<b>×</b> 表示两格<b>不同</b>。',
      'tango.rule5': '一开始就填好的格子<b>不会变</b>。',
      'tango.rule6': '点一格会按<b>空 → 太阳 → 月亮 → 空</b>轮换。',
      'tango.rule7': '开着<b>自动检查</b>时，违反规则的格子会立刻变红。想自己找就关掉。',
      'tango.rule8': '<b>这里的每个盘面都只有一个答案，不用猜，只靠推理就能解开。</b>不会出现最后在两处之间犹豫的盘面。',
      'tango.rule9': '<b>提示</b>会先清掉放错的格子；没有放错的，就填上现在的盘面靠一条规则能推出的格子，并说明原因。用过提示的盘面不计入最好成绩。',
      'tango.rule10': '键盘：<b>方向键</b>移动，<b>空格</b>切换，<b>Backspace</b> 撤销。'
    },
    'zh-TW': {
      'meta.desc': '把太陽和月亮各放一半，不讓同樣的連成三個',
      'tango.autoCheck': '自動檢查',
      'tango.note': '{size}×{size}，已給出 {given} 格，記號 {links} 個。',
      'tango.locked': '一開始就給出的格子不能改。',
      'tango.hintCleared': '清掉了 {count} 個放錯的格子。',
      'tango.hintPlaced': '填好了現在能推出的一格。',
      'tango.why.scan.col': '把這一列能放的排法都試一遍，填好的格子在每種排法裡都一樣。',
      'tango.why.scan.row': '把這一行能放的排法都試一遍，填好的格子在每種排法裡都一樣。',
      'tango.why.half.col': '這一列有一種已經占滿一半，剩下的格子都是另一種。',
      'tango.why.half.row': '這一行有一種已經占滿一半，剩下的格子都是另一種。',
      'tango.why.gap.col': '這一列裡夾在兩個同樣的中間的格子是相反的，否則會連成三個。',
      'tango.why.gap.row': '這一行裡夾在兩個同樣的中間的格子是相反的，否則會連成三個。',
      'tango.why.pair.col': '這一列有兩個同樣的挨在一起。不能連成三個，所以旁邊那格是相反的。',
      'tango.why.pair.row': '這一行有兩個同樣的挨在一起。不能連成三個，所以旁邊那格是相反的。',
      'tango.why.diff': '用 × 連著的兩格不同。一格已經填好，另一格就是相反的。',
      'tango.why.same': '用 = 連著的兩格相同。一格已經填好，另一格也一樣。',
      'tango.rule1': '把每一格填上<b>太陽</b>或<b>月亮</b>。',
      'tango.rule2': '<b>每行每列各占一半。</b>6×6 就是每行三個太陽、三個月亮，列也一樣。',
      'tango.rule3': '<b>同樣的不能連成三個。</b>橫豎都最多兩個。',
      'tango.rule4': '兩格之間的 <b>=</b> 表示兩格<b>相同</b>，<b>×</b> 表示兩格<b>不同</b>。',
      'tango.rule5': '一開始就填好的格子<b>不會變</b>。',
      'tango.rule6': '點一格會按<b>空 → 太陽 → 月亮 → 空</b>輪換。',
      'tango.rule7': '開著<b>自動檢查</b>時，違反規則的格子會立刻變紅。想自己找就關掉。',
      'tango.rule8': '<b>這裡的每個盤面都只有一個答案，不用猜，只靠推理就能解開。</b>不會出現最後在兩處之間猶豫的盤面。',
      'tango.rule9': '<b>提示</b>會先清掉放錯的格子；沒有放錯的，就填上現在的盤面靠一條規則能推出的格子，並說明原因。用過提示的盤面不計入最好成績。',
      'tango.rule10': '鍵盤：<b>方向鍵</b>移動，<b>空白鍵</b>切換，<b>Backspace</b> 還原。'
    },
    es: {
      'meta.desc': 'Llena la cuadrícula con mitad soles y mitad lunas, sin tres iguales seguidos',
      'tango.autoCheck': 'Comprobación automática',
      'tango.note': '{size}×{size}, {given} casillas dadas y {links} signos.',
      'tango.locked': 'Las casillas dadas al principio no se pueden cambiar.',
      'tango.hintCleared': 'Quitó {count} casillas mal puestas.',
      'tango.hintPlaced': 'Llenó una casilla que la lógica ya resuelve.',
      'tango.why.scan.col': 'Si pruebas todas las formas que caben en esta columna, las casillas llenadas salen iguales en todas.',
      'tango.why.scan.row': 'Si pruebas todas las formas que caben en esta fila, las casillas llenadas salen iguales en todas.',
      'tango.why.half.col': 'Un símbolo ya ocupa la mitad de esta columna, así que las casillas que quedan son del otro.',
      'tango.why.half.row': 'Un símbolo ya ocupa la mitad de esta fila, así que las casillas que quedan son del otro.',
      'tango.why.gap.col': 'En esta columna, la casilla entre dos iguales es la contraria; si no, habría tres seguidas.',
      'tango.why.gap.row': 'En esta fila, la casilla entre dos iguales es la contraria; si no, habría tres seguidas.',
      'tango.why.pair.col': 'En esta columna hay dos iguales juntas. No puede haber tres seguidas, así que la de al lado es la contraria.',
      'tango.why.pair.row': 'En esta fila hay dos iguales juntas. No puede haber tres seguidas, así que la de al lado es la contraria.',
      'tango.why.diff': 'Las casillas unidas por × son distintas. Una ya está puesta, así que la otra es la contraria.',
      'tango.why.same': 'Las casillas unidas por = son iguales. Una ya está puesta, así que la otra es igual.',
      'tango.rule1': 'Llena cada casilla con un <b>sol</b> o una <b>luna</b>.',
      'tango.rule2': '<b>Cada línea lleva la mitad de cada uno.</b> En un 6×6 son tres soles y tres lunas por línea, tanto en filas como en columnas.',
      'tango.rule3': '<b>Nunca tres iguales seguidos.</b> El límite son dos, en horizontal y en vertical.',
      'tango.rule4': 'Un <b>=</b> entre dos casillas significa que son <b>iguales</b>; una <b>×</b>, que son <b>distintas</b>.',
      'tango.rule5': 'Las casillas que vienen puestas desde el principio <b>no cambian</b>.',
      'tango.rule6': 'Al tocar una casilla pasa por <b>vacía → sol → luna → vacía</b>.',
      'tango.rule7': 'Con la <b>comprobación automática</b> activada, cualquier casilla que rompa una regla se pone roja al momento. Desactívala si prefieres buscarlas tú.',
      'tango.rule8': '<b>Todos los tableros aquí tienen una sola solución y se resuelven solo con lógica.</b> Nunca te quedarás eligiendo entre dos casillas al final.',
      'tango.rule9': 'Una <b>pista</b> quita primero las casillas mal puestas; si no hay, llena lo que una sola regla resuelve en el tablero actual y te dice por qué. Los tableros resueltos con pistas no se registran.',
      'tango.rule10': 'Teclado: <b>flechas</b> para moverte, <b>Espacio</b> para cambiar, <b>Retroceso</b> para deshacer.'
    }
  });
})();
