// 여러 페이지가 함께 쓰는 문구만 둔다. 게임 이름은 목록 카드와 그 게임의 헤더·문서
// 제목에 같이 나오므로 여기 한 곳에서 관리하고, 게임 하나에만 나오는 문구는 그 게임
// 폴더의 strings.js에 둔다.
(function () {
  SharedI18n.add({
    ko: {
      'game.2048': '2048',
      'game.kkodle': '꼬들',
      'game.sudoku': '스도쿠',
      'game.doppelblock': '더블블록',
      'game.chess-puzzle': '체스 퍼즐',
      'game.zip': '한붓그리기',
      'game.queens': '왕관 놓기',
      'game.patches': 'Patches',
      'game.conquest': '점령전',
      'game.hashi': '다리 잇기',
      'game.dicewars': '주사위 영토전',
      'game.yacht': '야추',
      'game.nonogram': '노노그램',
      'game.rushhour': '차 빼기',
      'game.healer': '힐러',
      'game.defense': '길목 지키기',

      'ui.back': '← 목록',
      'ui.bgm': 'BGM',
      'ui.sfx': '효과음',
      'ui.help': '도움말',
      'ui.close': '닫기',
      'ui.score': '점수',
      'ui.best': '최고',
      'ui.rules': '규칙',
      'ui.hint': '힌트',
      'ui.undo': '되돌리기',
      'ui.erase': '지우기',
      'ui.pencil': '연필',
      'ui.newGame': '새 게임',
      'ui.newBoard': '새 판',
      'ui.again': '한 판 더',
      'ui.retry': '다시 하기',
      'ui.restart': '다시',
      'ui.next': '다음',
      'ui.difficulty': '난이도',
      'ui.making': '만드는 중…'
    },
    en: {
      'game.2048': '2048',
      'game.kkodle': 'Kkodle',
      'game.sudoku': 'Sudoku',
      'game.doppelblock': 'Doppelblock',
      'game.chess-puzzle': 'Chess Puzzles',
      'game.zip': 'One Line',
      'game.queens': 'Queens',
      'game.patches': 'Patches',
      'game.conquest': 'Conquest',
      'game.hashi': 'Bridges',
      'game.dicewars': 'Dice Wars',
      'game.yacht': 'Yacht',
      'game.nonogram': 'Nonogram',
      'game.rushhour': 'Rush Hour',
      'game.healer': 'Healer',
      'game.defense': 'Hold the Line',

      'ui.back': '← All games',
      'ui.bgm': 'Music',
      'ui.sfx': 'Sound',
      'ui.help': 'Help',
      'ui.close': 'Close',
      'ui.score': 'Score',
      'ui.best': 'Best',
      'ui.rules': 'Rules',
      'ui.hint': 'Hint',
      'ui.undo': 'Undo',
      'ui.erase': 'Erase',
      'ui.pencil': 'Notes',
      'ui.newGame': 'New game',
      'ui.newBoard': 'New board',
      'ui.again': 'Play again',
      'ui.retry': 'Try again',
      'ui.restart': 'Restart',
      'ui.next': 'Next',
      'ui.difficulty': 'Difficulty',
      'ui.making': 'Generating…'
    },
    ja: {
      'game.2048': '2048',
      'game.kkodle': 'コドゥル',
      'game.sudoku': '数独',
      'game.doppelblock': 'ドッペルブロック',
      'game.chess-puzzle': 'チェスパズル',
      'game.zip': '一筆書き',
      'game.queens': 'クイーン置き',
      'game.patches': 'Patches',
      'game.conquest': '陣取り',
      'game.hashi': '橋渡し',
      'game.dicewars': 'ダイスウォーズ',
      'game.yacht': 'ヨット',
      'game.nonogram': 'お絵かきロジック',
      'game.rushhour': 'ラッシュアワー',
      'game.healer': 'ヒーラー',
      'game.defense': '進路防衛',

      'ui.back': '← 一覧',
      'ui.bgm': 'BGM',
      'ui.sfx': '効果音',
      'ui.help': 'ヘルプ',
      'ui.close': '閉じる',
      'ui.score': 'スコア',
      'ui.best': 'ベスト',
      'ui.rules': 'ルール',
      'ui.hint': 'ヒント',
      'ui.undo': '戻す',
      'ui.erase': '消す',
      'ui.pencil': 'メモ',
      'ui.newGame': '新しいゲーム',
      'ui.newBoard': '新しい盤',
      'ui.again': 'もう一局',
      'ui.retry': 'もう一度',
      'ui.restart': 'やり直す',
      'ui.next': '次へ',
      'ui.difficulty': '難易度',
      'ui.making': '生成中…'
    },
    'zh-CN': {
      'game.2048': '2048',
      'game.kkodle': '韩语猜词',
      'game.sudoku': '数独',
      'game.doppelblock': '双块',
      'game.chess-puzzle': '国际象棋谜题',
      'game.zip': '一笔画',
      'game.queens': '放皇后',
      'game.patches': 'Patches',
      'game.conquest': '占领战',
      'game.hashi': '数桥',
      'game.dicewars': '骰子领土战',
      'game.yacht': '快艇骰子',
      'game.nonogram': '数织',
      'game.rushhour': '停车难题',
      'game.healer': '治疗师',
      'game.defense': '守路口',

      'ui.back': '← 列表',
      'ui.bgm': '音乐',
      'ui.sfx': '音效',
      'ui.help': '帮助',
      'ui.close': '关闭',
      'ui.score': '分数',
      'ui.best': '最高',
      'ui.rules': '规则',
      'ui.hint': '提示',
      'ui.undo': '撤销',
      'ui.erase': '擦除',
      'ui.pencil': '笔记',
      'ui.newGame': '新游戏',
      'ui.newBoard': '新一局',
      'ui.again': '再来一局',
      'ui.retry': '再试一次',
      'ui.restart': '重来',
      'ui.next': '下一个',
      'ui.difficulty': '难度',
      'ui.making': '生成中…'
    },
    'zh-TW': {
      'game.2048': '2048',
      'game.kkodle': '韓語猜詞',
      'game.sudoku': '數獨',
      'game.doppelblock': '雙塊',
      'game.chess-puzzle': '西洋棋謎題',
      'game.zip': '一筆畫',
      'game.queens': '放皇后',
      'game.patches': 'Patches',
      'game.conquest': '佔領戰',
      'game.hashi': '數橋',
      'game.dicewars': '骰子領土戰',
      'game.yacht': '快艇骰子',
      'game.nonogram': '數織',
      'game.rushhour': '停車難題',
      'game.healer': '治療師',
      'game.defense': '守路口',

      'ui.back': '← 列表',
      'ui.bgm': '音樂',
      'ui.sfx': '音效',
      'ui.help': '說明',
      'ui.close': '關閉',
      'ui.score': '分數',
      'ui.best': '最高',
      'ui.rules': '規則',
      'ui.hint': '提示',
      'ui.undo': '復原',
      'ui.erase': '擦除',
      'ui.pencil': '筆記',
      'ui.newGame': '新遊戲',
      'ui.newBoard': '新一局',
      'ui.again': '再來一局',
      'ui.retry': '再試一次',
      'ui.restart': '重來',
      'ui.next': '下一個',
      'ui.difficulty': '難度',
      'ui.making': '生成中…'
    },
    es: {
      'game.2048': '2048',
      'game.kkodle': 'Kkodle',
      'game.sudoku': 'Sudoku',
      'game.doppelblock': 'Doppelblock',
      'game.chess-puzzle': 'Ajedrez',
      'game.zip': 'Un solo trazo',
      'game.queens': 'Reinas',
      'game.patches': 'Patches',
      'game.conquest': 'Conquista',
      'game.hashi': 'Puentes',
      'game.dicewars': 'Guerra de dados',
      'game.yacht': 'Yacht',
      'game.nonogram': 'Nonograma',
      'game.rushhour': 'Atasco',
      'game.healer': 'Sanador',
      'game.defense': 'Defensa',

      'ui.back': '← Lista',
      'ui.bgm': 'Música',
      'ui.sfx': 'Efectos',
      'ui.help': 'Ayuda',
      'ui.close': 'Cerrar',
      'ui.score': 'Puntos',
      'ui.best': 'Mejor',
      'ui.rules': 'Reglas',
      'ui.hint': 'Pista',
      'ui.undo': 'Deshacer',
      'ui.erase': 'Borrar',
      'ui.pencil': 'Notas',
      'ui.newGame': 'Nueva partida',
      'ui.newBoard': 'Nuevo tablero',
      'ui.again': 'Otra partida',
      'ui.retry': 'Reintentar',
      'ui.restart': 'Reiniciar',
      'ui.next': 'Siguiente',
      'ui.difficulty': 'Dificultad',
      'ui.making': 'Generando…'
    }
  });
})();
