// 여러 페이지가 함께 쓰는 문구만 둔다. 게임 이름은 목록 카드와 그 게임의 헤더·문서
// 제목에 같이 나오므로 여기 한 곳에서 관리하고, 게임 하나에만 나오는 문구는 그 게임
// 폴더의 strings.js에 둔다.
(function () {
  SharedI18n.add({
    ko: {
      'game.2048': '2048',
      'game.kkodle': '꼬들',
      'game.sudoku': '스도쿠',
      'game.doppelblock': '도펠블록',
      'game.chess-puzzle': '체스 퍼즐',
      'game.zip': 'Zip',
      'game.queens': 'Queens',
      'game.patches': 'Patches',
      'game.tango': 'Tango',
      'game.idioms': '사자성어 찾기',
      'game.conquest': '점령전',
      'game.hashi': '하시',
      'game.dicewars': '다이스 워즈',
      'game.yacht': '야추',
      'game.nonogram': '노노그램',
      'game.rushhour': '러시아워',
      'game.healer': '힐러',
      'game.defense': '길목 지키기',
      'game.metro': '지하철 노선',
      'game.roadworks': '도로공사',
      'game.sokoban': '소코반',
      'game.slitherlink': '슬리더링크',

      'ui.back': '← 목록',
      'ui.bgm': 'BGM',
      'ui.sfx': '효과음',
      'ui.help': '도움말',
      'ui.close': '닫기',
      'ui.score': '점수',
      'ui.best': '최고',
      'ui.rules': '규칙',
      'ui.hint': '힌트',
      'ui.undo': '되돌리기',
      'ui.erase': '지우기',
      'ui.pencil': '연필',
      'ui.newGame': '새 게임',
      'ui.newBoard': '새 판',
      'ui.again': '한 판 더',
      'ui.retry': '다시 하기',
      'ui.restart': '다시',
      'ui.next': '다음',
      'ui.difficulty': '난이도',
      'ui.making': '만드는 중…',
      'ui.easy': '쉬움',
      'ui.medium': '보통',
      'ui.hard': '어려움',
      'ui.small': '작게',
      'ui.large': '크게',
      'ui.boardSize': '판 크기',
      'record.best': '최고 {time}',
      'record.done': '완성! {time}',
      'record.hinted': '힌트를 {count}번 썼으니 기록은 남기지 않습니다.',
      'record.improved': '최고 기록을 {time}에서 줄였습니다.',
      'record.first': '첫 기록입니다.',
      'record.bestIs': '최고 기록은 {time}입니다.',
      'record.genFail': '판을 만들지 못했습니다. 새 판을 눌러 다시 시도해 주세요.',
      'record.hintedShort': '힌트를 써서 기록에는 넣지 않습니다',
      'record.bestMark': '최고 기록',
      'ui.toStart': '처음으로',
      'ui.nextBoard': '다음 판',
      'ui.players': '인원',
      'ui.playerCount': '{n}인',

      'daily.toast': '오늘의 도전 {done}/{total}',
      'daily.toastAll': '오늘의 도전 완료!',
      'daily.any': '한 판 풀기',
      'daily.size': '{size}×{size} 판 풀기',
      'daily.sizeUp': '{size}×{size} 이상 풀기',
      'daily.clean': '힌트 없이 풀기',
      'daily.sizeClean': '{size}×{size} 판을 힌트 없이 풀기',
      'daily.sizeUpClean': '{size}×{size} 이상을 힌트 없이 풀기',
      'daily.sizeFast': '{size}×{size} 판을 힌트 없이 {min}분 안에 풀기',
      'daily.sizeUpFast': '{size}×{size} 이상을 힌트 없이 {min}분 안에 풀기',
      'daily.anyLevel': '아무 난이도나 한 판 풀기',
      'daily.medium': '보통 이상 난이도 풀기',
      'daily.hard': '어려움 난이도 풀기',
      'daily.fast': '{min}분 안에 풀기',
      'daily.tile': '{tile} 타일 만들기',
      'daily.kkodle.win': '단어 맞히기',
      'daily.kkodle.tries': '{n}번 안에 맞히기',
      'daily.flawless': '틀리지 않고 힌트 없이 풀기',
      'daily.hardFlawless': '어려움 문제를 틀리지 않고 힌트 없이 풀기',
      'daily.win': '한 판 이기기',
      'daily.winMedium': '보통 이상 난이도에서 이기기',
      'daily.winHard': '어려움 난이도에서 이기기',
      'daily.winPlayers': '{n}인 판에서 이기기',
      'daily.yacht.finish': '한 판 끝까지 두기',
      'daily.score': '{score}점 이상 내기',
      'daily.optimal': '힌트 없이 최소 이동으로 풀기',
      'daily.hardOptimal': '어려움을 힌트 없이 최소 이동으로 풀기',
      'daily.newStage': '처음 푸는 단계 풀기',
      'daily.improve': '푼 단계를 더 적은 이동으로 다시 풀기'
    },
    en: {
      'game.2048': '2048',
      'game.kkodle': 'Kkodle',
      'game.sudoku': 'Sudoku',
      'game.doppelblock': 'Doppelblock',
      'game.chess-puzzle': 'Chess Puzzles',
      'game.zip': 'Zip',
      'game.queens': 'Queens',
      'game.patches': 'Patches',
      'game.tango': 'Tango',
      'game.idioms': 'Idiom Trails',
      'game.conquest': 'Conquest',
      'game.hashi': 'Hashi',
      'game.dicewars': 'Dice Wars',
      'game.yacht': 'Yacht',
      'game.nonogram': 'Nonogram',
      'game.rushhour': 'Rush Hour',
      'game.healer': 'Healer',
      'game.defense': 'Hold the Line',
      'game.metro': 'Metro Lines',
      'game.roadworks': 'Roadworks',
      'game.sokoban': 'Sokoban',
      'game.slitherlink': 'Slitherlink',

      'ui.back': '← All games',
      'ui.bgm': 'Music',
      'ui.sfx': 'Sound',
      'ui.help': 'Help',
      'ui.close': 'Close',
      'ui.score': 'Score',
      'ui.best': 'Best',
      'ui.rules': 'Rules',
      'ui.hint': 'Hint',
      'ui.undo': 'Undo',
      'ui.erase': 'Erase',
      'ui.pencil': 'Notes',
      'ui.newGame': 'New game',
      'ui.newBoard': 'New board',
      'ui.again': 'Play again',
      'ui.retry': 'Try again',
      'ui.restart': 'Restart',
      'ui.next': 'Next',
      'ui.difficulty': 'Difficulty',
      'ui.making': 'Generating…',
      'ui.easy': 'Easy',
      'ui.medium': 'Medium',
      'ui.hard': 'Hard',
      'ui.small': 'Small',
      'ui.large': 'Large',
      'ui.boardSize': 'Board size',
      'record.best': 'Best {time}',
      'record.done': 'Done! {time}',
      'record.hinted': 'You used {count} hints, so this one is not recorded.',
      'record.improved': 'Your best time is down from {time}.',
      'record.first': 'Your first record.',
      'record.bestIs': 'Your best time is {time}.',
      'record.genFail': 'Could not build a board. Tap New board to try again.',
      'record.hintedShort': 'hints used, so this one is not recorded',
      'record.bestMark': 'best time',
      'ui.toStart': 'Restart',
      'ui.nextBoard': 'Next board',
      'ui.players': 'Players',
      'ui.playerCount': '{n} players',

      'daily.toast': 'Daily challenge {done}/{total}',
      'daily.toastAll': 'Daily challenge complete!',
      'daily.any': 'Solve a puzzle',
      'daily.size': 'Solve a {size}×{size} puzzle',
      'daily.sizeUp': 'Solve {size}×{size} or larger',
      'daily.clean': 'Solve without hints',
      'daily.sizeClean': 'Solve {size}×{size} without hints',
      'daily.sizeUpClean': 'Solve {size}×{size} or larger without hints',
      'daily.sizeFast': 'Solve {size}×{size} without hints in under {min} min',
      'daily.sizeUpFast': 'Solve {size}×{size} or larger without hints in under {min} min',
      'daily.anyLevel': 'Solve a puzzle on any level',
      'daily.medium': 'Solve on Medium or harder',
      'daily.hard': 'Solve on Hard',
      'daily.fast': 'Solve in under {min} minutes',
      'daily.tile': 'Make a {tile} tile',
      'daily.kkodle.win': 'Guess the word',
      'daily.kkodle.tries': 'Guess it in {n} tries or fewer',
      'daily.flawless': 'Solve with no mistakes or hints',
      'daily.hardFlawless': 'Solve a Hard puzzle with no mistakes or hints',
      'daily.win': 'Win a game',
      'daily.winMedium': 'Win on Medium or harder',
      'daily.winHard': 'Win on Hard',
      'daily.winPlayers': 'Win a {n}-player game',
      'daily.yacht.finish': 'Play a game to the end',
      'daily.score': 'Score {score} or more',
      'daily.optimal': 'Solve in the fewest moves without hints',
      'daily.hardOptimal': 'Solve a Hard puzzle in the fewest moves without hints',
      'daily.newStage': 'Clear a new stage',
      'daily.improve': 'Beat your move record on a cleared stage'
    },
    ja: {
      'game.2048': '2048',
      'game.kkodle': 'コドゥル',
      'game.sudoku': '数独',
      'game.doppelblock': 'ドッペルブロック',
      'game.chess-puzzle': 'チェスパズル',
      'game.zip': 'Zip',
      'game.queens': 'Queens',
      'game.patches': 'Patches',
      'game.tango': 'Tango',
      'game.idioms': '四字熟語さがし',
      'game.conquest': '陣取り',
      'game.hashi': '橋をかけろ',
      'game.dicewars': 'ダイスウォーズ',
      'game.yacht': 'ヨット',
      'game.nonogram': 'お絵かきロジック',
      'game.rushhour': 'ラッシュアワー',
      'game.healer': 'ヒーラー',
      'game.defense': '進路防衛',
      'game.metro': '地下鉄路線',
      'game.roadworks': '道路工事',
      'game.sokoban': '倉庫番',
      'game.slitherlink': 'スリザーリンク',

      'ui.back': '← 一覧',
      'ui.bgm': 'BGM',
      'ui.sfx': '効果音',
      'ui.help': 'ヘルプ',
      'ui.close': '閉じる',
      'ui.score': 'スコア',
      'ui.best': 'ベスト',
      'ui.rules': 'ルール',
      'ui.hint': 'ヒント',
      'ui.undo': '戻す',
      'ui.erase': '消す',
      'ui.pencil': 'メモ',
      'ui.newGame': '新しいゲーム',
      'ui.newBoard': '新しい盤',
      'ui.again': 'もう一局',
      'ui.retry': 'もう一度',
      'ui.restart': 'やり直す',
      'ui.next': '次へ',
      'ui.difficulty': '難易度',
      'ui.making': '生成中…',
      'ui.easy': 'やさしい',
      'ui.medium': 'ふつう',
      'ui.hard': 'むずかしい',
      'ui.small': '小さめ',
      'ui.large': '大きめ',
      'ui.boardSize': '盤の大きさ',
      'record.best': 'ベスト {time}',
      'record.done': '完成！{time}',
      'record.hinted': 'ヒントを{count}回使ったので記録には残しません。',
      'record.improved': 'ベスト記録を {time} から縮めました。',
      'record.first': '初めての記録です。',
      'record.bestIs': 'ベスト記録は {time} です。',
      'record.genFail': '盤を作れませんでした。「新しい盤」を押してもう一度お試しください。',
      'record.hintedShort': 'ヒントを使ったので記録には残しません',
      'record.bestMark': 'ベスト記録',
      'ui.toStart': '最初から',
      'ui.nextBoard': '次の盤',
      'ui.players': '人数',
      'ui.playerCount': '{n}人',

      'daily.toast': '今日のチャレンジ {done}/{total}',
      'daily.toastAll': '今日のチャレンジ達成!',
      'daily.any': '1問解く',
      'daily.size': '{size}×{size}を解く',
      'daily.sizeUp': '{size}×{size}以上を解く',
      'daily.clean': 'ヒントなしで解く',
      'daily.sizeClean': '{size}×{size}をヒントなしで解く',
      'daily.sizeUpClean': '{size}×{size}以上をヒントなしで解く',
      'daily.sizeFast': '{size}×{size}をヒントなしで{min}分以内に解く',
      'daily.sizeUpFast': '{size}×{size}以上をヒントなしで{min}分以内に解く',
      'daily.anyLevel': 'どの難易度でも1問解く',
      'daily.medium': 'ふつう以上の難易度で解く',
      'daily.hard': 'むずかしいで解く',
      'daily.fast': '{min}分以内に解く',
      'daily.tile': '{tile}のタイルを作る',
      'daily.kkodle.win': '単語を当てる',
      'daily.kkodle.tries': '{n}回以内に当てる',
      'daily.flawless': 'ミスもヒントもなしで解く',
      'daily.hardFlawless': 'むずかしいをミスもヒントもなしで解く',
      'daily.win': '1回勝つ',
      'daily.winMedium': 'ふつう以上の難易度で勝つ',
      'daily.winHard': 'むずかしいで勝つ',
      'daily.winPlayers': '{n}人戦で勝つ',
      'daily.yacht.finish': '1ゲーム最後まで遊ぶ',
      'daily.score': '{score}点以上を取る',
      'daily.optimal': 'ヒントなしで最少手数で解く',
      'daily.hardOptimal': 'むずかしいをヒントなしで最少手数で解く',
      'daily.newStage': '初めてのステージをクリアする',
      'daily.improve': 'クリア済みのステージを少ない手数で解き直す'
    },
    'zh-CN': {
      'game.2048': '2048',
      'game.kkodle': '韩语猜词',
      'game.sudoku': '数独',
      'game.doppelblock': 'Doppelblock',
      'game.chess-puzzle': '国际象棋谜题',
      'game.zip': 'Zip',
      'game.queens': 'Queens',
      'game.patches': 'Patches',
      'game.tango': 'Tango',
      'game.idioms': '找四字成语',
      'game.conquest': '占领战',
      'game.hashi': '数桥',
      'game.dicewars': 'Dice Wars',
      'game.yacht': '快艇骰子',
      'game.nonogram': '数织',
      'game.rushhour': 'Rush Hour',
      'game.healer': '治疗师',
      'game.defense': '守路口',
      'game.metro': '地铁线路',
      'game.roadworks': '道路改造',
      'game.sokoban': '推箱子',
      'game.slitherlink': '数回',

      'ui.back': '← 列表',
      'ui.bgm': '音乐',
      'ui.sfx': '音效',
      'ui.help': '帮助',
      'ui.close': '关闭',
      'ui.score': '分数',
      'ui.best': '最高',
      'ui.rules': '规则',
      'ui.hint': '提示',
      'ui.undo': '撤销',
      'ui.erase': '擦除',
      'ui.pencil': '笔记',
      'ui.newGame': '新游戏',
      'ui.newBoard': '新一局',
      'ui.again': '再来一局',
      'ui.retry': '再试一次',
      'ui.restart': '重来',
      'ui.next': '下一个',
      'ui.difficulty': '难度',
      'ui.making': '生成中…',
      'ui.easy': '简单',
      'ui.medium': '普通',
      'ui.hard': '困难',
      'ui.small': '小',
      'ui.large': '大',
      'ui.boardSize': '盘面大小',
      'record.best': '最高 {time}',
      'record.done': '完成！{time}',
      'record.hinted': '用了 {count} 次提示，这一局不计入记录。',
      'record.improved': '最好成绩从 {time} 提升了。',
      'record.first': '这是第一条记录。',
      'record.bestIs': '最好成绩是 {time}。',
      'record.genFail': '没能生成盘面。点“新一局”再试一次。',
      'record.hintedShort': '用了提示，不计入记录',
      'record.bestMark': '最好成绩',
      'ui.toStart': '从头开始',
      'ui.nextBoard': '下一局',
      'ui.players': '人数',
      'ui.playerCount': '{n} 人',

      'daily.toast': '今日挑战 {done}/{total}',
      'daily.toastAll': '今日挑战完成!',
      'daily.any': '完成一局',
      'daily.size': '完成一局{size}×{size}',
      'daily.sizeUp': '完成一局{size}×{size}以上',
      'daily.clean': '不用提示完成',
      'daily.sizeClean': '{size}×{size}不用提示完成',
      'daily.sizeUpClean': '{size}×{size}以上不用提示完成',
      'daily.sizeFast': '{size}×{size}不用提示{min}分钟内完成',
      'daily.sizeUpFast': '{size}×{size}以上不用提示{min}分钟内完成',
      'daily.anyLevel': '任意难度完成一局',
      'daily.medium': '以普通或更高难度完成',
      'daily.hard': '以困难难度完成',
      'daily.fast': '{min}分钟内完成',
      'daily.tile': '合成{tile}方块',
      'daily.kkodle.win': '猜中单词',
      'daily.kkodle.tries': '{n}次以内猜中',
      'daily.flawless': '不出错、不用提示完成',
      'daily.hardFlawless': '不出错、不用提示完成一道困难题',
      'daily.win': '赢一局',
      'daily.winMedium': '在普通或更高难度获胜',
      'daily.winHard': '在困难难度获胜',
      'daily.winPlayers': '赢一局{n}人对战',
      'daily.yacht.finish': '完整玩完一局',
      'daily.score': '得到{score}分以上',
      'daily.optimal': '不用提示以最少步数完成',
      'daily.hardOptimal': '不用提示以最少步数完成一道困难题',
      'daily.newStage': '通过一个新关卡',
      'daily.improve': '以更少步数重玩已通过的关卡'
    },
    'zh-TW': {
      'game.2048': '2048',
      'game.kkodle': '韓語猜詞',
      'game.sudoku': '數獨',
      'game.doppelblock': 'Doppelblock',
      'game.chess-puzzle': '西洋棋謎題',
      'game.zip': 'Zip',
      'game.queens': 'Queens',
      'game.patches': 'Patches',
      'game.tango': 'Tango',
      'game.idioms': '找四字成語',
      'game.conquest': '佔領戰',
      'game.hashi': '數橋',
      'game.dicewars': 'Dice Wars',
      'game.yacht': '快艇骰子',
      'game.nonogram': '數織',
      'game.rushhour': 'Rush Hour',
      'game.healer': '治療師',
      'game.defense': '守路口',
      'game.metro': '地鐵路線',
      'game.roadworks': '道路改造',
      'game.sokoban': '倉庫番',
      'game.slitherlink': '數迴',

      'ui.back': '← 列表',
      'ui.bgm': '音樂',
      'ui.sfx': '音效',
      'ui.help': '說明',
      'ui.close': '關閉',
      'ui.score': '分數',
      'ui.best': '最高',
      'ui.rules': '規則',
      'ui.hint': '提示',
      'ui.undo': '復原',
      'ui.erase': '擦除',
      'ui.pencil': '筆記',
      'ui.newGame': '新遊戲',
      'ui.newBoard': '新一局',
      'ui.again': '再來一局',
      'ui.retry': '再試一次',
      'ui.restart': '重來',
      'ui.next': '下一個',
      'ui.difficulty': '難度',
      'ui.making': '生成中…',
      'ui.easy': '簡單',
      'ui.medium': '普通',
      'ui.hard': '困難',
      'ui.small': '小',
      'ui.large': '大',
      'ui.boardSize': '盤面大小',
      'record.best': '最高 {time}',
      'record.done': '完成！{time}',
      'record.hinted': '用了 {count} 次提示，這一局不計入紀錄。',
      'record.improved': '最佳成績從 {time} 提升了。',
      'record.first': '這是第一筆紀錄。',
      'record.bestIs': '最佳成績是 {time}。',
      'record.genFail': '沒能產生盤面。點「新一局」再試一次。',
      'record.hintedShort': '用了提示，不計入紀錄',
      'record.bestMark': '最佳成績',
      'ui.toStart': '從頭開始',
      'ui.nextBoard': '下一局',
      'ui.players': '人數',
      'ui.playerCount': '{n} 人',

      'daily.toast': '今日挑戰 {done}/{total}',
      'daily.toastAll': '今日挑戰完成!',
      'daily.any': '完成一局',
      'daily.size': '完成一局{size}×{size}',
      'daily.sizeUp': '完成一局{size}×{size}以上',
      'daily.clean': '不用提示完成',
      'daily.sizeClean': '{size}×{size}不用提示完成',
      'daily.sizeUpClean': '{size}×{size}以上不用提示完成',
      'daily.sizeFast': '{size}×{size}不用提示{min}分鐘內完成',
      'daily.sizeUpFast': '{size}×{size}以上不用提示{min}分鐘內完成',
      'daily.anyLevel': '任意難度完成一局',
      'daily.medium': '以普通或更高難度完成',
      'daily.hard': '以困難難度完成',
      'daily.fast': '{min}分鐘內完成',
      'daily.tile': '合成{tile}方塊',
      'daily.kkodle.win': '猜中單字',
      'daily.kkodle.tries': '{n}次以內猜中',
      'daily.flawless': '不出錯、不用提示完成',
      'daily.hardFlawless': '不出錯、不用提示完成一道困難題',
      'daily.win': '贏一局',
      'daily.winMedium': '在普通或更高難度獲勝',
      'daily.winHard': '在困難難度獲勝',
      'daily.winPlayers': '贏一局{n}人對戰',
      'daily.yacht.finish': '完整玩完一局',
      'daily.score': '得到{score}分以上',
      'daily.optimal': '不用提示以最少步數完成',
      'daily.hardOptimal': '不用提示以最少步數完成一道困難題',
      'daily.newStage': '通過一個新關卡',
      'daily.improve': '以更少步數重玩已通過的關卡'
    },
    es: {
      'game.2048': '2048',
      'game.kkodle': 'Kkodle',
      'game.sudoku': 'Sudoku',
      'game.doppelblock': 'Doppelblock',
      'game.chess-puzzle': 'Problemas de ajedrez',
      'game.zip': 'Zip',
      'game.queens': 'Queens',
      'game.patches': 'Patches',
      'game.tango': 'Tango',
      'game.idioms': 'Rastros de modismos',
      'game.conquest': 'Conquista',
      'game.hashi': 'Hashi',
      'game.dicewars': 'Dice Wars',
      'game.yacht': 'Yacht',
      'game.nonogram': 'Nonograma',
      'game.rushhour': 'Rush Hour',
      'game.healer': 'Sanador',
      'game.defense': 'Defensa',
      'game.metro': 'Líneas de Metro',
      'game.roadworks': 'Obras Viales',
      'game.sokoban': 'Sokoban',
      'game.slitherlink': 'Slitherlink',

      'ui.back': '← Lista',
      'ui.bgm': 'Música',
      'ui.sfx': 'Efectos',
      'ui.help': 'Ayuda',
      'ui.close': 'Cerrar',
      'ui.score': 'Puntos',
      'ui.best': 'Mejor',
      'ui.rules': 'Reglas',
      'ui.hint': 'Pista',
      'ui.undo': 'Deshacer',
      'ui.erase': 'Borrar',
      'ui.pencil': 'Notas',
      'ui.newGame': 'Nueva partida',
      'ui.newBoard': 'Nuevo tablero',
      'ui.again': 'Otra partida',
      'ui.retry': 'Reintentar',
      'ui.restart': 'Reiniciar',
      'ui.next': 'Siguiente',
      'ui.difficulty': 'Dificultad',
      'ui.making': 'Generando…',
      'ui.easy': 'Fácil',
      'ui.medium': 'Media',
      'ui.hard': 'Difícil',
      'ui.small': 'Pequeño',
      'ui.large': 'Grande',
      'ui.boardSize': 'Tamaño del tablero',
      'record.best': 'Mejor {time}',
      'record.done': '¡Completado! {time}',
      'record.hinted': 'Usaste {count} pistas, así que no cuenta para el récord.',
      'record.improved': 'Has bajado tu mejor marca de {time}.',
      'record.first': 'Tu primera marca.',
      'record.bestIs': 'Tu mejor marca es {time}.',
      'record.genFail': 'No se pudo generar el tablero. Pulsa Nuevo tablero para reintentar.',
      'record.hintedShort': 'con pistas, no cuenta para el récord',
      'record.bestMark': 'mejor marca',
      'ui.toStart': 'Desde el principio',
      'ui.nextBoard': 'Siguiente tablero',
      'ui.players': 'Jugadores',
      'ui.playerCount': '{n} jugadores',

      'daily.toast': 'Reto diario {done}/{total}',
      'daily.toastAll': '¡Reto diario completado!',
      'daily.any': 'Resuelve un tablero',
      'daily.size': 'Resuelve uno de {size}×{size}',
      'daily.sizeUp': 'Resuelve uno de {size}×{size} o mayor',
      'daily.clean': 'Resuelve sin pistas',
      'daily.sizeClean': 'Resuelve {size}×{size} sin pistas',
      'daily.sizeUpClean': 'Resuelve {size}×{size} o mayor sin pistas',
      'daily.sizeFast': 'Resuelve {size}×{size} sin pistas en menos de {min} min',
      'daily.sizeUpFast': 'Resuelve {size}×{size} o mayor sin pistas en menos de {min} min',
      'daily.anyLevel': 'Resuelve uno en cualquier nivel',
      'daily.medium': 'Resuelve en dificultad Media o superior',
      'daily.hard': 'Resuelve en Difícil',
      'daily.fast': 'Resuelve en menos de {min} minutos',
      'daily.tile': 'Consigue la ficha {tile}',
      'daily.kkodle.win': 'Adivina la palabra',
      'daily.kkodle.tries': 'Adivínala en {n} intentos o menos',
      'daily.flawless': 'Resuelve sin errores ni pistas',
      'daily.hardFlawless': 'Resuelve uno Difícil sin errores ni pistas',
      'daily.win': 'Gana una partida',
      'daily.winMedium': 'Gana en dificultad Media o superior',
      'daily.winHard': 'Gana en Difícil',
      'daily.winPlayers': 'Gana una partida de {n} jugadores',
      'daily.yacht.finish': 'Juega una partida completa',
      'daily.score': 'Consigue {score} puntos o más',
      'daily.optimal': 'Resuelve con el mínimo de movimientos sin pistas',
      'daily.hardOptimal': 'Resuelve uno Difícil con el mínimo de movimientos sin pistas',
      'daily.newStage': 'Supera un nivel nuevo',
      'daily.improve': 'Mejora tu récord de movimientos en un nivel superado'
    }
  });
})();
