// 이 게임에만 나오는 문구. 기록 안내와 도구 이름은 shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '행·열·색 영역마다 왕관을 하나씩, 서로 닿지 않게 놓는 퍼즐',
      'queens.autoCheck': '자동 체크',
      'queens.note': '{size}×{size}, 영역 {count}개.',
      'queens.hintCleared': '어긋난 왕관 {count}개를 걷어 내고 다음 자리를 짚었습니다.',
      'queens.hintPlaced': '지금 알아낼 수 있는 영역에 왕관을 놓았습니다.',
      'queens.rule1': '<b>행마다, 열마다, 색 영역마다 왕관을 정확히 하나씩</b> 놓습니다. 판이 8칸이면 왕관도 8개입니다.',
      'queens.rule2': '왕관끼리 <b>서로 닿을 수 없습니다</b>. 위아래·양옆은 물론 <b>대각으로도</b> 붙으면 안 됩니다.',
      'queens.rule3': '대각은 <b>바로 옆 한 칸만</b> 막힙니다. 한 칸 건너 비스듬한 자리는 괜찮습니다 — 체스의 퀸과 다른 점입니다.',
      'queens.rule4': '칸을 누르면 <b>빈칸 → X → 왕관</b> 순서로 바뀝니다. X는 스스로 남기는 메모라 정답 판정에 쓰이지 않습니다.',
      'queens.rule5': '빈칸에서 <b>누른 채 끌면</b> 지나간 칸에 X가 이어서 찍힙니다. 왕관 위에서 시작해 끌면 반대로 지워집니다.',
      'queens.rule6': '<b>자동 체크</b>를 켜 두면 규칙을 어긴 왕관이 곧바로 붉게 표시됩니다. 스스로 찾고 싶으면 꺼 두세요.',
      'queens.rule7': '<b>이 게임의 모든 판은 답이 하나뿐이고, 찍지 않고 논리만으로 풀립니다.</b> 마지막에 두 자리를 놓고 고민하게 되는 판은 나오지 않습니다.',
      'queens.rule8': '<b>힌트</b>는 어긋난 왕관을 걷어 내고, 지금 알아낼 수 있는 영역 하나에 왕관을 놓아 줍니다. 힌트를 쓴 판은 최고 기록으로 남기지 않습니다.',
      'queens.rule9': '키보드: <b>방향키</b>로 칸을 옮기고, <b>스페이스</b>로 바꾸고, <b>Backspace</b>로 되돌립니다.'
    },
    en: {
      'meta.desc': 'Place one crown in every row, column and colored region, none of them touching',
      'queens.autoCheck': 'Auto-check',
      'queens.note': '{size}×{size}, {count} regions.',
      'queens.hintCleared': 'Removed {count} misplaced crowns and pointed at the next spot.',
      'queens.hintPlaced': 'Placed a crown in a region logic can settle now.',
      'queens.rule1': 'Place <b>exactly one crown per row, per column and per colored region</b>. An 8-wide board takes 8 crowns.',
      'queens.rule2': 'Crowns <b>may not touch</b>. Not side by side, not above or below, and <b>not diagonally</b> either.',
      'queens.rule3': 'Only the <b>immediately adjacent</b> diagonal is blocked. A diagonal one cell further away is fine — unlike a chess queen.',
      'queens.rule4': 'Tapping a cell cycles <b>empty → X → crown</b>. The X is your own note and never counts toward the solution.',
      'queens.rule5': '<b>Press and drag</b> from an empty cell to stamp X along the way. Start on a crown and drag to erase instead.',
      'queens.rule6': 'With <b>Auto-check</b> on, any crown that breaks a rule turns red at once. Turn it off to find them yourself.',
      'queens.rule7': '<b>Every board here has exactly one solution and is solvable by logic alone.</b> You will never be left choosing between two spots at the end.',
      'queens.rule8': 'A <b>Hint</b> removes misplaced crowns and places one in a region logic can settle. Boards solved with hints are not recorded.',
      'queens.rule9': 'Keyboard: <b>arrow keys</b> to move, <b>Space</b> to cycle, <b>Backspace</b> to undo.'
    },
    ja: {
      'meta.desc': '行・列・色の領域ごとにクイーンをひとつずつ、互いに触れないように置くパズル',
      'queens.autoCheck': '自動チェック',
      'queens.note': '{size}×{size}、領域 {count} 個。',
      'queens.hintCleared': 'ずれたクイーン{count}個を取り除き、次の場所を示しました。',
      'queens.hintPlaced': 'いま確定できる領域にクイーンを置きました。',
      'queens.rule1': '<b>行ごと・列ごと・色の領域ごとにクイーンをちょうどひとつずつ</b>置きます。8マスの盤ならクイーンも8個です。',
      'queens.rule2': 'クイーン同士は<b>触れられません</b>。上下左右はもちろん、<b>斜めでも</b>隣り合ってはいけません。',
      'queens.rule3': '斜めは<b>すぐ隣の一マスだけ</b>が禁止です。一マス離れた斜めなら構いません — チェスのクイーンとの違いです。',
      'queens.rule4': 'マスを押すと<b>空 → X → クイーン</b>の順に変わります。Xは自分用のメモで、正解の判定には使いません。',
      'queens.rule5': '空マスから<b>押したまま引く</b>と、通ったマスに続けてXが付きます。クイーンの上から引くと逆に消えます。',
      'queens.rule6': '<b>自動チェック</b>を入れておくと、ルール違反のクイーンがすぐ赤くなります。自分で探したいときは切ってください。',
      'queens.rule7': '<b>この盤はすべて答えがひとつだけで、当てずっぽう抜きに論理だけで解けます。</b>最後に二択で悩む盤は出ません。',
      'queens.rule8': '<b>ヒント</b>はずれたクイーンを取り除き、いま確定できる領域にひとつ置きます。ヒントを使った盤はベスト記録に残しません。',
      'queens.rule9': 'キーボード：<b>矢印キー</b>で移動、<b>スペース</b>で切替、<b>Backspace</b>で戻します。'
    },
    'zh-CN': {
      'meta.desc': '每行、每列、每个颜色区域各放一个皇冠，且彼此不相邻',
      'queens.autoCheck': '自动检查',
      'queens.note': '{size}×{size}，区域 {count} 个。',
      'queens.hintCleared': '移走了 {count} 个放错的皇冠，并指出了下一个位置。',
      'queens.hintPlaced': '在当前可以确定的区域放好了皇冠。',
      'queens.rule1': '<b>每行、每列、每个颜色区域各放一个皇冠</b>。8 格的盘面就放 8 个。',
      'queens.rule2': '皇冠之间<b>不能相邻</b>。上下左右不行，<b>斜着挨着</b>也不行。',
      'queens.rule3': '只有<b>紧挨着的</b>斜角受限。隔一格的斜向位置没问题 —— 这和国际象棋的皇后不同。',
      'queens.rule4': '点一格会按<b>空 → X → 皇冠</b>循环。X 只是自己的标记，不参与判定。',
      'queens.rule5': '从空格<b>按住拖动</b>会一路打上 X。从皇冠上开始拖则相反，是擦掉。',
      'queens.rule6': '打开<b>自动检查</b>，违规的皇冠会立刻变红。想自己找就关掉它。',
      'queens.rule7': '<b>这里的每一盘都只有一个答案，而且只靠推理就能解开。</b>不会出现最后在两个位置之间犹豫的盘面。',
      'queens.rule8': '<b>提示</b>会移走放错的皇冠，并在当前可确定的区域放上一个。用过提示的盘面不计入最好成绩。',
      'queens.rule9': '键盘：<b>方向键</b>移动，<b>空格</b>切换，<b>Backspace</b> 撤销。'
    },
    'zh-TW': {
      'meta.desc': '每行、每列、每個顏色區域各放一個皇冠，且彼此不相鄰',
      'queens.autoCheck': '自動檢查',
      'queens.note': '{size}×{size}，區域 {count} 個。',
      'queens.hintCleared': '移走了 {count} 個放錯的皇冠，並指出了下一個位置。',
      'queens.hintPlaced': '在目前可以確定的區域放好了皇冠。',
      'queens.rule1': '<b>每行、每列、每個顏色區域各放一個皇冠</b>。8 格的盤面就放 8 個。',
      'queens.rule2': '皇冠之間<b>不能相鄰</b>。上下左右不行，<b>斜著挨著</b>也不行。',
      'queens.rule3': '只有<b>緊鄰的</b>斜角受限。隔一格的斜向位置沒問題 —— 這和西洋棋的皇后不同。',
      'queens.rule4': '點一格會按<b>空 → X → 皇冠</b>循環。X 只是自己的標記，不參與判定。',
      'queens.rule5': '從空格<b>按住拖曳</b>會一路打上 X。從皇冠上開始拖則相反，是擦掉。',
      'queens.rule6': '打開<b>自動檢查</b>，違規的皇冠會立刻變紅。想自己找就關掉它。',
      'queens.rule7': '<b>這裡的每一盤都只有一個答案，而且只靠推理就能解開。</b>不會出現最後在兩個位置之間猶豫的盤面。',
      'queens.rule8': '<b>提示</b>會移走放錯的皇冠，並在目前可確定的區域放上一個。用過提示的盤面不計入最佳成績。',
      'queens.rule9': '鍵盤：<b>方向鍵</b>移動，<b>空白鍵</b>切換，<b>Backspace</b> 復原。'
    },
    es: {
      'meta.desc': 'Coloca una corona en cada fila, columna y región de color, sin que se toquen',
      'queens.autoCheck': 'Comprobación automática',
      'queens.note': '{size}×{size}, {count} regiones.',
      'queens.hintCleared': 'Se quitaron {count} coronas mal puestas y se señaló el siguiente sitio.',
      'queens.hintPlaced': 'Se colocó una corona en una región que la lógica ya fija.',
      'queens.rule1': 'Coloca <b>exactamente una corona por fila, por columna y por región de color</b>. Un tablero de 8 lleva 8 coronas.',
      'queens.rule2': 'Las coronas <b>no pueden tocarse</b>. Ni en horizontal, ni en vertical, ni <b>en diagonal</b>.',
      'queens.rule3': 'Solo se bloquea la diagonal <b>inmediatamente contigua</b>. Una diagonal a dos casillas vale — aquí está la diferencia con la dama del ajedrez.',
      'queens.rule4': 'Al tocar una casilla alterna <b>vacía → X → corona</b>. La X es una nota tuya y no cuenta para la solución.',
      'queens.rule5': '<b>Mantén pulsado y arrastra</b> desde una casilla vacía para marcar X por el camino. Si empiezas sobre una corona, borras.',
      'queens.rule6': 'Con la <b>comprobación automática</b> activada, cualquier corona que rompa una regla se pone roja al instante. Apágala si prefieres buscarlas tú.',
      'queens.rule7': '<b>Todos los tableros tienen una única solución y salen solo con lógica.</b> Nunca acabarás dudando entre dos casillas.',
      'queens.rule8': 'Una <b>Pista</b> retira las coronas mal puestas y coloca una en una región que la lógica ya fija. Los tableros con pistas no cuentan para el récord.',
      'queens.rule9': 'Teclado: <b>flechas</b> para moverte, <b>Espacio</b> para alternar, <b>Retroceso</b> para deshacer.'
    }
  });
})();
