// 이 게임에만 나오는 문구. 난이도·도구 이름 같은 공통 문구는 shared/strings.js에 있다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '힌트만으로 풀 수 있는 스도쿠. 찍어야 하는 판은 나오지 않는다',
      'sudoku.helpTitle': '규칙과 조작',
      'sudoku.rule1': '가로줄·세로줄·3×3 상자마다 1~9가 한 번씩 들어갑니다.',
      'sudoku.rule2': '<b>이 게임의 모든 판은 주어진 숫자만으로 풀립니다.</b> 찍어야만 넘어가는 판은 나오지 않습니다 — 만들 때 논리로 끝까지 풀리는지 확인하고 내보냅니다.',
      'sudoku.rule3': '<b>연필</b>을 켜면 후보 숫자를 작게 적어둘 수 있습니다. 숫자를 확정하면 같은 줄·상자의 연필 표시에서 그 숫자가 자동으로 지워집니다.',
      'sudoku.rule4': '<b>힌트</b>는 정답을 보여주는 대신, 지금 논리로 확정할 수 있는 칸 하나와 그 근거가 된 기법을 알려줍니다.',
      'sudoku.rule5': '키보드: 방향키로 이동, <b>1~9</b> 입력, <b>Shift+숫자</b>는 연필, <b>Backspace</b> 지우기, <b>스페이스</b> 연필 전환, <b>Ctrl+Z</b> 되돌리기.',
      'sudoku.solved': '다 풀었어요',
      'sudoku.wrong': '여기 숫자가 정답과 달라요. 먼저 고쳐야 이어서 풀 수 있어요',
      'sudoku.noStep': '더 짚어줄 칸을 찾지 못했어요',
      'sudoku.nakedSingle': '이 칸에 들어갈 수 있는 숫자가 하나뿐',
      'sudoku.hiddenSingle': '이 줄에서 그 숫자가 들어갈 칸이 여기뿐',
      'sudoku.pointing': '상자 안에서 그 숫자의 자리가 한 줄에 몰려 있음',
      'sudoku.claiming': '줄에서 그 숫자의 자리가 한 상자에 몰려 있음',
      'sudoku.nakedPair': '두 칸이 같은 두 숫자를 나눠 가짐',
      'sudoku.hiddenPair': '두 숫자가 두 칸에만 들어갈 수 있음',
      'sudoku.nakedTriple': '세 칸이 같은 세 숫자를 나눠 가짐',
      'sudoku.hiddenTriple': '세 숫자가 세 칸에만 들어갈 수 있음'
    },
    en: {
      'meta.desc': 'Sudoku you can always solve by logic — never by guessing',
      'sudoku.helpTitle': 'Rules and controls',
      'sudoku.rule1': 'Every row, every column and every 3×3 box holds 1 to 9 exactly once.',
      'sudoku.rule2': '<b>Every board here is solvable from the given numbers alone.</b> You will never have to guess — each board is checked to the end by logic before it ships.',
      'sudoku.rule3': 'Turn on <b>Notes</b> to pencil in candidates. Once you place a number, it is cleared from the notes in the same row, column and box.',
      'sudoku.rule4': 'A <b>Hint</b> does not reveal the answer. It points at one cell logic can settle right now, and names the technique behind it.',
      'sudoku.rule5': 'Keyboard: arrow keys to move, <b>1–9</b> to enter, <b>Shift+number</b> for notes, <b>Backspace</b> to erase, <b>Space</b> to toggle notes, <b>Ctrl+Z</b> to undo.',
      'sudoku.solved': 'Solved',
      'sudoku.wrong': 'This number does not match the solution. Fix it before going on',
      'sudoku.noStep': 'No cell left that logic can settle right now',
      'sudoku.nakedSingle': 'Only one number fits this cell',
      'sudoku.hiddenSingle': 'This is the only cell in the line for that number',
      'sudoku.pointing': 'Inside the box, that number is confined to one line',
      'sudoku.claiming': 'Along the line, that number is confined to one box',
      'sudoku.nakedPair': 'Two cells share the same two numbers',
      'sudoku.hiddenPair': 'Two numbers fit in only two cells',
      'sudoku.nakedTriple': 'Three cells share the same three numbers',
      'sudoku.hiddenTriple': 'Three numbers fit in only three cells'
    },
    ja: {
      'meta.desc': '論理だけで解ける数独。当てずっぽうが要る盤は出ません',
      'sudoku.helpTitle': 'ルールと操作',
      'sudoku.rule1': '各行・各列・各3×3ブロックに1〜9が一度ずつ入ります。',
      'sudoku.rule2': '<b>この盤はすべて、与えられた数字だけで解けます。</b>当てずっぽうが要る盤は出ません — 作るときに論理で最後まで解けるか確かめています。',
      'sudoku.rule3': '<b>メモ</b>をオンにすると候補を小さく書けます。数字を確定すると、同じ行・列・ブロックのメモから自動で消えます。',
      'sudoku.rule4': '<b>ヒント</b>は答えを見せる代わりに、いま論理で確定できるマスと、その根拠になった手筋を教えます。',
      'sudoku.rule5': 'キーボード：矢印キーで移動、<b>1〜9</b>で入力、<b>Shift+数字</b>でメモ、<b>Backspace</b>で消去、<b>スペース</b>でメモ切替、<b>Ctrl+Z</b>で戻す。',
      'sudoku.solved': '解けました',
      'sudoku.wrong': 'この数字が答えと違います。直さないと先へ進めません',
      'sudoku.noStep': 'いま確定できるマスが見つかりません',
      'sudoku.nakedSingle': 'このマスに入る数字はひとつだけ',
      'sudoku.hiddenSingle': 'この列でその数字が入るのはここだけ',
      'sudoku.pointing': 'ブロック内でその数字の位置が一列に寄っている',
      'sudoku.claiming': '列でその数字の位置が一ブロックに寄っている',
      'sudoku.nakedPair': '二つのマスが同じ二つの数字を分け合っている',
      'sudoku.hiddenPair': '二つの数字が二つのマスにしか入らない',
      'sudoku.nakedTriple': '三つのマスが同じ三つの数字を分け合っている',
      'sudoku.hiddenTriple': '三つの数字が三つのマスにしか入らない'
    },
    'zh-CN': {
      'meta.desc': '只靠推理就能解开的数独，不会出现需要猜的盘面',
      'sudoku.helpTitle': '规则与操作',
      'sudoku.rule1': '每一行、每一列、每个 3×3 宫里，1~9 各出现一次。',
      'sudoku.rule2': '<b>这里的每一盘都能只凭已给数字解开。</b>不会出现非猜不可的盘面 —— 生成时会用逻辑推到底再放出来。',
      'sudoku.rule3': '打开<b>笔记</b>可以把候选数字写小。确定一个数字后，同一行、列、宫的笔记里会自动去掉它。',
      'sudoku.rule4': '<b>提示</b>不直接给答案，而是指出当前逻辑可以确定的一格，并说明用到的技巧。',
      'sudoku.rule5': '键盘：方向键移动，<b>1~9</b> 输入，<b>Shift+数字</b>写笔记，<b>Backspace</b> 擦除，<b>空格</b>切换笔记，<b>Ctrl+Z</b> 撤销。',
      'sudoku.solved': '全部解开',
      'sudoku.wrong': '这个数字和答案不一样，先改过来才能继续',
      'sudoku.noStep': '暂时找不到可以确定的格子',
      'sudoku.nakedSingle': '这一格只能填一个数字',
      'sudoku.hiddenSingle': '这条线上只有这一格能放那个数字',
      'sudoku.pointing': '宫内那个数字的位置集中在一条线上',
      'sudoku.claiming': '线上那个数字的位置集中在一个宫里',
      'sudoku.nakedPair': '两格分享同样的两个数字',
      'sudoku.hiddenPair': '两个数字只能放进两格',
      'sudoku.nakedTriple': '三格分享同样的三个数字',
      'sudoku.hiddenTriple': '三个数字只能放进三格'
    },
    'zh-TW': {
      'meta.desc': '只靠推理就能解開的數獨，不會出現需要猜的盤面',
      'sudoku.helpTitle': '規則與操作',
      'sudoku.rule1': '每一行、每一列、每個 3×3 宮裡，1~9 各出現一次。',
      'sudoku.rule2': '<b>這裡的每一盤都能只憑已給數字解開。</b>不會出現非猜不可的盤面 —— 產生時會用邏輯推到底再放出來。',
      'sudoku.rule3': '打開<b>筆記</b>可以把候選數字寫小。確定一個數字後，同一行、列、宮的筆記裡會自動去掉它。',
      'sudoku.rule4': '<b>提示</b>不直接給答案，而是指出目前邏輯可以確定的一格，並說明用到的技巧。',
      'sudoku.rule5': '鍵盤：方向鍵移動，<b>1~9</b> 輸入，<b>Shift+數字</b>寫筆記，<b>Backspace</b> 擦除，<b>空白鍵</b>切換筆記，<b>Ctrl+Z</b> 復原。',
      'sudoku.solved': '全部解開',
      'sudoku.wrong': '這個數字和答案不一樣，先改過來才能繼續',
      'sudoku.noStep': '暫時找不到可以確定的格子',
      'sudoku.nakedSingle': '這一格只能填一個數字',
      'sudoku.hiddenSingle': '這條線上只有這一格能放那個數字',
      'sudoku.pointing': '宮內那個數字的位置集中在一條線上',
      'sudoku.claiming': '線上那個數字的位置集中在一個宮裡',
      'sudoku.nakedPair': '兩格分享同樣的兩個數字',
      'sudoku.hiddenPair': '兩個數字只能放進兩格',
      'sudoku.nakedTriple': '三格分享同樣的三個數字',
      'sudoku.hiddenTriple': '三個數字只能放進三格'
    },
    es: {
      'meta.desc': 'Sudokus que siempre salen con lógica: nunca hay que adivinar',
      'sudoku.helpTitle': 'Reglas y controles',
      'sudoku.rule1': 'Cada fila, cada columna y cada caja de 3×3 lleva el 1 al 9 una sola vez.',
      'sudoku.rule2': '<b>Todos los tableros se resuelven solo con los números dados.</b> Nunca hará falta adivinar: cada tablero se comprueba hasta el final con lógica antes de publicarse.',
      'sudoku.rule3': 'Activa las <b>Notas</b> para apuntar candidatos. Al fijar un número, se borra de las notas de su fila, columna y caja.',
      'sudoku.rule4': 'Una <b>Pista</b> no da la solución: señala una casilla que la lógica ya puede fijar y nombra la técnica que lo permite.',
      'sudoku.rule5': 'Teclado: flechas para moverte, <b>1–9</b> para escribir, <b>Mayús+número</b> para notas, <b>Retroceso</b> para borrar, <b>Espacio</b> para alternar notas, <b>Ctrl+Z</b> para deshacer.',
      'sudoku.solved': 'Resuelto',
      'sudoku.wrong': 'Este número no coincide con la solución. Corrígelo para seguir',
      'sudoku.noStep': 'No queda ninguna casilla que la lógica pueda fijar ahora',
      'sudoku.nakedSingle': 'Solo cabe un número en esta casilla',
      'sudoku.hiddenSingle': 'Es la única casilla de la línea para ese número',
      'sudoku.pointing': 'Dentro de la caja, ese número queda en una sola línea',
      'sudoku.claiming': 'En la línea, ese número queda en una sola caja',
      'sudoku.nakedPair': 'Dos casillas comparten los mismos dos números',
      'sudoku.hiddenPair': 'Dos números solo caben en dos casillas',
      'sudoku.nakedTriple': 'Tres casillas comparten los mismos tres números',
      'sudoku.hiddenTriple': 'Tres números solo caben en tres casillas'
    }
  });
})();
