// 이 게임에만 나오는 문구. 도구 이름과 게임 이름은 shared/strings.js에 있다.
//
// 힌트 이유(`pips.why.*`)는 풀이기가 돌려주는 `why.code`와 이름이 같다.
(function () {
  SharedI18n.add({
    ko: {
      'meta.desc': '도미노를 빠짐없이 놓아 구역마다 조건을 맞추는 퍼즐',
      'pips.tray': '도미노',
      'pips.pickFirst': '먼저 아래에서 도미노를 고르세요.',
      'pips.noRoom': '여기에는 놓을 자리가 없습니다.',
      'pips.wrong': '자리가 틀린 도미노가 있습니다. 표시한 도미노를 다시 보세요.',
      'pips.wrongWay': '방향이 틀린 도미노가 있습니다. 표시한 도미노를 다시 보세요.',
      'pips.noStep': '지금은 더 정할 수 있는 자리가 없습니다.',
      'pips.why.cell': '표시한 칸을 덮을 수 있는 놓기가 이것 하나뿐입니다.',
      'pips.why.tile': '이 도미노가 들어갈 자리가 여기뿐입니다.',
      'pips.why.trial': '다른 자리에 두면 어딘가에서 모순이 생겨 여기입니다.',
      'pips.rule1': '판의 모든 칸을 <b>아래의 도미노로 빠짐없이</b> 덮습니다. 도미노는 하나도 남기지 않고 다 씁니다.',
      'pips.rule2': '색칠한 <b>구역</b>에는 조건이 있습니다. 숫자는 구역의 눈을 더한 <b>합</b>, <b>&lt;</b>와 <b>&gt;</b>는 합이 그보다 작거나 큼, <b>=</b>는 눈이 모두 같음, <b>≠</b>는 눈이 모두 다름입니다. 색이 없는 칸에는 아무 눈이나 와도 됩니다.',
      'pips.rule3': '도미노 하나가 두 구역에 걸쳐도 됩니다.',
      'pips.rule4': '아래에서 도미노를 고르고 판의 칸을 누르면 그 칸을 덮도록 놓입니다. <b>끌어다 놓아도 됩니다.</b> 고른 도미노를 한 번 더 누르면 돌아가고, 판에 놓은 도미노를 누르거나 판 밖으로 끌어내면 다시 아래로 돌아옵니다.',
      'pips.rule5': '<b>모든 판은 도미노가 가는 자리가 하나뿐입니다.</b> 한 구역 안에 통째로 든 도미노는 뒤집어도 맞을 수 있는데, 규칙에 맞게 다 덮었으면 어느 쪽이든 정답입니다.',
      'pips.rule6': '<b>힌트</b>는 틀린 도미노를 짚어 주고, 틀린 것이 없으면 지금 판에서 새로 정할 수 있는 도미노 하나를 까닭과 함께 놓아 줍니다.',
      'pips.rule7': '키보드: <b>R</b> 돌리기, <b>Ctrl+Z</b> 되돌리기.'
    },
    en: {
      'meta.desc': 'Place every domino so each region meets its condition',
      'pips.tray': 'Dominoes',
      'pips.pickFirst': 'Pick a domino below first.',
      'pips.noRoom': 'There’s no room for it here.',
      'pips.wrong': 'A domino is in the wrong place. Check the highlighted one.',
      'pips.wrongWay': 'A domino is facing the wrong way. Check the highlighted one.',
      'pips.noStep': 'Nothing else can be settled right now.',
      'pips.why.cell': 'This is the only way to cover the highlighted cell.',
      'pips.why.tile': 'This is the only place this domino fits.',
      'pips.why.trial': 'Anywhere else leads to a contradiction, so it goes here.',
      'pips.rule1': 'Cover every cell of the board <b>with all the dominoes below</b>. Every domino gets used.',
      'pips.rule2': 'Each colored <b>region</b> has a condition. A number is the <b>sum</b> of its pips, <b>&lt;</b> and <b>&gt;</b> mean the sum is less or more than that, <b>=</b> means all pips are equal, and <b>≠</b> means all are different. Uncolored cells can hold anything.',
      'pips.rule3': 'A domino may straddle two regions.',
      'pips.rule4': 'Pick a domino below, then tap a cell on the board to place it over that cell — <b>or just drag it there.</b> Tap the picked domino again to rotate it. Tap a placed domino, or drag it off the board, to send it back.',
      'pips.rule5': '<b>On every board, each domino has only one place it can go.</b> A domino lying entirely inside one region may work either way round — if every rule holds, either way is correct.',
      'pips.rule6': 'The <b>hint</b> points out a misplaced domino; if there is none, it places one domino that can now be settled and tells you why.',
      'pips.rule7': 'Keyboard: <b>R</b> to rotate, <b>Ctrl+Z</b> to undo.'
    },
    ja: {
      'meta.desc': 'ドミノをすべて置いて、領域ごとの条件を満たすパズル',
      'pips.tray': 'ドミノ',
      'pips.pickFirst': '先に下のドミノを選んでください。',
      'pips.noRoom': 'ここには置く場所がありません。',
      'pips.wrong': '場所が違うドミノがあります。示したドミノを見直してください。',
      'pips.wrongWay': '向きが違うドミノがあります。示したドミノを見直してください。',
      'pips.noStep': 'いまはこれ以上決められる場所がありません。',
      'pips.why.cell': '示したマスを覆える置き方はこれしかありません。',
      'pips.why.tile': 'このドミノが入る場所はここだけです。',
      'pips.why.trial': 'ほかに置くとどこかで矛盾するので、ここです。',
      'pips.rule1': '盤のすべてのマスを<b>下のドミノで残らず</b>覆います。ドミノはすべて使います。',
      'pips.rule2': '色の付いた<b>領域</b>には条件があります。数字は目の<b>合計</b>、<b>&lt;</b>と<b>&gt;</b>は合計がそれより小さい・大きい、<b>=</b>は目がすべて同じ、<b>≠</b>はすべて違うことです。色のないマスは何の目でもかまいません。',
      'pips.rule3': 'ひとつのドミノが二つの領域にまたがってもかまいません。',
      'pips.rule4': '下のドミノを選んで盤のマスを押すと、そのマスを覆うように置かれます。<b>ドラッグして置いてもかまいません。</b>選んだドミノをもう一度押すと回転し、盤に置いたドミノを押すか盤の外へドラッグすると下に戻ります。',
      'pips.rule5': '<b>どの盤もドミノの置き場所はひとつに決まります。</b>ひとつの領域にすっぽり入ったドミノは裏返しても合うことがあり、ルールどおりに覆えていればどちらでも正解です。',
      'pips.rule6': '<b>ヒント</b>は間違ったドミノを示し、なければいまの盤から新しく決められるドミノをひとつ、理由と一緒に置きます。',
      'pips.rule7': 'キーボード: <b>R</b>で回転、<b>Ctrl+Z</b>で元に戻す。'
    },
    'zh-CN': {
      'meta.desc': '放下所有骨牌，让每个区域满足条件的谜题',
      'pips.tray': '骨牌',
      'pips.pickFirst': '请先在下面选一张骨牌。',
      'pips.noRoom': '这里放不下。',
      'pips.wrong': '有骨牌放错了位置，请看看标出的骨牌。',
      'pips.wrongWay': '有骨牌方向放反了，请看看标出的骨牌。',
      'pips.noStep': '现在没有能确定的位置了。',
      'pips.why.cell': '能盖住标出格子的放法只有这一种。',
      'pips.why.tile': '这张骨牌只能放在这里。',
      'pips.why.trial': '放在别处都会出现矛盾，所以是这里。',
      'pips.rule1': '用<b>下面的全部骨牌</b>盖满棋盘上的每一格，每张骨牌都要用上。',
      'pips.rule2': '有颜色的<b>区域</b>带有条件：数字是区域内点数的<b>和</b>，<b>&lt;</b> 和 <b>&gt;</b> 表示和小于或大于该数，<b>=</b> 表示点数全部相同，<b>≠</b> 表示全部不同。没有颜色的格子放什么点数都可以。',
      'pips.rule3': '一张骨牌可以跨两个区域。',
      'pips.rule4': '在下面选一张骨牌，再点棋盘上的格子，骨牌就会盖住那一格，<b>也可以直接拖过去。</b>再点一次选中的骨牌可以旋转；点棋盘上的骨牌或把它拖出棋盘，会把它放回下面。',
      'pips.rule5': '<b>每个棋盘上每张骨牌的位置都是唯一的。</b>整张落在同一区域内的骨牌翻过来也可能成立，只要满足所有规则，哪个方向都算对。',
      'pips.rule6': '<b>提示</b>会指出放错的骨牌；没有放错的话，会根据当前棋盘放下一张能确定的骨牌，并说明理由。',
      'pips.rule7': '键盘：<b>R</b> 旋转，<b>Ctrl+Z</b> 撤销。'
    },
    'zh-TW': {
      'meta.desc': '放下所有骨牌，讓每個區域滿足條件的謎題',
      'pips.tray': '骨牌',
      'pips.pickFirst': '請先在下面選一張骨牌。',
      'pips.noRoom': '這裡放不下。',
      'pips.wrong': '有骨牌放錯了位置，請看看標出的骨牌。',
      'pips.wrongWay': '有骨牌方向放反了，請看看標出的骨牌。',
      'pips.noStep': '現在沒有能確定的位置了。',
      'pips.why.cell': '能蓋住標出格子的放法只有這一種。',
      'pips.why.tile': '這張骨牌只能放在這裡。',
      'pips.why.trial': '放在別處都會出現矛盾，所以是這裡。',
      'pips.rule1': '用<b>下面的全部骨牌</b>蓋滿棋盤上的每一格，每張骨牌都要用上。',
      'pips.rule2': '有顏色的<b>區域</b>帶有條件：數字是區域內點數的<b>和</b>，<b>&lt;</b> 和 <b>&gt;</b> 表示和小於或大於該數，<b>=</b> 表示點數全部相同，<b>≠</b> 表示全部不同。沒有顏色的格子放什麼點數都可以。',
      'pips.rule3': '一張骨牌可以跨兩個區域。',
      'pips.rule4': '在下面選一張骨牌，再點棋盤上的格子，骨牌就會蓋住那一格，<b>也可以直接拖過去。</b>再點一次選中的骨牌可以旋轉；點棋盤上的骨牌或把它拖出棋盤，會把它放回下面。',
      'pips.rule5': '<b>每個棋盤上每張骨牌的位置都是唯一的。</b>整張落在同一區域內的骨牌翻過來也可能成立，只要滿足所有規則，哪個方向都算對。',
      'pips.rule6': '<b>提示</b>會指出放錯的骨牌；沒有放錯的話，會根據目前棋盤放下一張能確定的骨牌，並說明理由。',
      'pips.rule7': '鍵盤：<b>R</b> 旋轉，<b>Ctrl+Z</b> 復原。'
    },
    es: {
      'meta.desc': 'Coloca todas las fichas de dominó para que cada región cumpla su condición',
      'pips.tray': 'Fichas',
      'pips.pickFirst': 'Primero elige una ficha de abajo.',
      'pips.noRoom': 'Aquí no cabe.',
      'pips.wrong': 'Hay una ficha mal colocada. Revisa la marcada.',
      'pips.wrongWay': 'Hay una ficha al revés. Revisa la marcada.',
      'pips.noStep': 'Ahora mismo no se puede decidir nada más.',
      'pips.why.cell': 'Es la única forma de cubrir la casilla marcada.',
      'pips.why.tile': 'Es el único sitio donde cabe esta ficha.',
      'pips.why.trial': 'En cualquier otro sitio se llega a una contradicción, así que va aquí.',
      'pips.rule1': 'Cubre todas las casillas del tablero <b>con todas las fichas de abajo</b>. Se usan todas.',
      'pips.rule2': 'Cada <b>región</b> de color tiene una condición. Un número es la <b>suma</b> de sus puntos, <b>&lt;</b> y <b>&gt;</b> indican que la suma es menor o mayor, <b>=</b> que todos los puntos son iguales y <b>≠</b> que todos son distintos. Las casillas sin color admiten cualquier valor.',
      'pips.rule3': 'Una ficha puede ocupar dos regiones.',
      'pips.rule4': 'Elige una ficha abajo y toca una casilla del tablero para colocarla cubriéndola, <b>o simplemente arrástrala.</b> Toca otra vez la ficha elegida para girarla. Toca una ficha colocada, o sácala del tablero arrastrando, para devolverla.',
      'pips.rule5': '<b>En cada tablero, cada ficha tiene un único sitio.</b> Una ficha que queda entera dentro de una región puede valer en los dos sentidos: si se cumplen todas las reglas, cualquiera es correcto.',
      'pips.rule6': 'La <b>pista</b> señala una ficha mal colocada; si no hay ninguna, coloca una ficha que ya se puede decidir y te dice por qué.',
      'pips.rule7': 'Teclado: <b>R</b> para girar, <b>Ctrl+Z</b> para deshacer.'
    }
  });
})();
